manwar/perlweeklychallenge-club

- challenge-002/lars-balker/perl5/ch-1.pl
- challenge-002/lars-balker/perl5/ch-2.pl
- challenge-002/lars-balker/perl6/ch-1.pl6
- challenge-002/lars-balker/perl6/ch-2.pl6
> lars balker solutions, week 2

- challenge-004/andrezgz/perl5/ch-1.pl
- challenge-004/andrezgz/perl5/ch-2.pl
Hi @manwar , my proposed solutions for this week challenge
> challenge-004 andrezgz solution

- challenge-005/doug-schrag/perl6/ch-1.p6
- challenge-005/doug-schrag/perl6/ch-2.p6
Challenge #1 results
```
doug$ time perl6 challenge-005/doug-schrag/perl6/ch-1.p6 --word-file=words.txt listen
listen
inlets
silent
tinsel
enlist
real 0m2.700s
user 0m2.757s
sys 0m0.100s
```
This algorithm is too slow for large words.
Challenge #2 results
```
doug$ time perl6 challenge-005/doug-schrag/perl6/ch-2.p6 --word-file=words.txt
aelrst
alerts
alters
artels
estral
laster
ratels
salter
slater
staler
stelar
talers
aeprs
apers
asper
pares
parse
pears
prase
presa
rapes
reaps
spare
spear
real 0m7.725s
user 0m7.746s
sys  0m0.152s
```
> Doug Schrag challenge 5

- challenge-006/joelle-maslak/perl5/ch-2.pl
- challenge-006/joelle-maslak/perl6/ch-2.p6
Perl 5 & 6 solutions attached.
You linked to https://en.wikipedia.org/wiki/Landau%E2%80%93Ramanujan_constant which is the Landau-Ramanujan Constant.
That's not the same thing as the Ramanujan's Constant, which you can find here:
https://en.wikipedia.org/wiki/Heegner_number#Almost_integers_and_Ramanujan's_constant
Since the Ramanujan's constant is fairly easy to calculate to 33 digits of precision, I solved for that.  The Landau-Ramanujan Constant is not easy to calculate to 33 digits of precision!  Please let me know if I solved for the wrong constant.
> Jmaslak week 6, problem 2

- challenge-009/andrezgz/ch2-data.csv
- challenge-009/andrezgz/perl5/ch-1.pl
- challenge-009/andrezgz/perl5/ch-2.pl
Hi @manwar, as always my solution to this week challenge
> challenge-009 andrezgz solution

- challenge-010/kian-meng-ang/perl5/ch-1.pl
> Challenge #010 C1 answer

- challenge-012/dave-jacoby/c2.pl
Part 1 of 2. Or maybe 3; I'll have to think about the API.
> Annotated Challenge #2

- challenge-012/kian-meng-ang/perl5/ch-2.pl
- challenge-012/kian-meng-ang/perl5/ch-3.pl
> Add C2 & C3 answers for challenge #012

- challenge-017/dave-jacoby/perl5/ch-1b.pl
I benchmarked Ackerman w/ and without memoization.
It's better with memoization.
> Benchmarking and Memoization! Oh My!

- challenge-022/e-choroba/perl5/ch-1.pl
- challenge-022/e-choroba/perl5/ch-2.pl
Sexy Prime Pairs uses the prime module I've already used in two
previous challenges, 012 and 015.
LZW works according to the example in the Wikipedia page, i.e. only
works for capital letters. It can be easily extended to handle any
other characters, though.
> Add solution to 022 by E. Choroba

- challenge-026/simon-proctor/perl6/ch-2.p6
Note the degrees version rounds to 0.01deg as deg -> rad -> deg conversion tends to add some float errors.
> Think this does the job.

- .gitignore
Ignore any .precomp directories created for Raku modules.
> Add .precomp to .gitignore

- challenge-043/andrezgz/perl/ch-1.pl
Hi @manwar I've removed an unnecessary line noted by Ryan Thompson in his review. As he said:
"Andrezgz defines, but does not even need, a hash of the available numbers, 1, 2, 3, 4, and 6."
> challenge-043 task-1 fix

- challenge-049/e-choroba/perl/ch-2.pl
- challenge-049/e-choroba/perl/ch-2b.pl
Also, remove an unused subroutine from the original solution. For
larger caches, the linked list solution is much faster (benchmark will
be shown in a blog).
> Add alternative solution to LRU Cache using a linked list

- challenge-053/ryan-thompson/perl/ch-2.pl
Found this during my review. When I was blogging, I wanted to rename a variable `%next` to `%edges`. Search/replace without testing was obviously not smart.
> edges -> next (fix silly search/replace error)

- challenge-054/e-choroba/perl5/ch-1.pl
- challenge-054/e-choroba/perl5/ch-2.pl
- challenge-054/e-choroba/perl5/ch-2b.pl
Permutation is solved recursively character by character.
To solve the Extra Credit task of the Collatz Conjencture, I first
used a heap, but in the end solving it with a pure array was much
simpler and even faster (and not terribly memory hungry either).
> Add 054 by E. Choroba (K-th Permutation and Collatz Conjencture)

- challenge-056/jaredor/perl/ch-1.pl
Thank you Mohammad, for catching the warning for null comparison against the user option for -k. I've implemented your suggestion, but I hope you don't mind that I recast it using my style: I like "die ... unless ..." for going through validation checks. Cheers, --Jared
> Add necessary check for required option -k

- .gitignore
Would be nice to exclude .*.swp files.
> ignore vim swap files

- challenge-065/e-choroba/perl/ch-1.pl
- challenge-065/e-choroba/perl/ch-1b.pl
- challenge-065/e-choroba/perl/ch-2.pl
There are two solutions for 065/1 Digits Sum. The first one is the
naive one which uses the brute force. The second solution generates
only the possible numbers and seems to be much faster: on my machine,
it runs 3 times faster for length 7 and sum 42.
The Palindrome Partition adds one more solution to the "aabaab" case:
["aa", "aa"]. It's not clear why this solution is invalid (Must the
solutions be adjacent? Should each solution be never part of another
solution?) Fixing the algorithm might not be straight forward, as
additional constraints might need information that's not available in
the current implementation.
> Add solutions to 065 by E. Choroba

- challenge-071/dave-jacoby/perl/ch-2b.pl
When i wrote this at first, I used an existing list implementation hat was doubly-linked. 
I blame/credit Walt Mankowski for bringing this to my attention and forcing me to recode.
> Task 2: this time with a SINGLY-linked list

- challenge-072/e-choroba/perl5/ch-1.pl
- challenge-072/e-choroba/perl5/ch-2.pl
In 072/1, ignore the N <= 10 condition. We can solve it fast for much
larger Ns, also, it's N == 25 where it starts to get tricky and
interesting.
In 072/2, specify the input filename as the last argument to make it
optional. $. is needed in the range operator as only literal numbers
are interpreted as line numbers directly.
> Solve 072 (Trailing Zeros and Lines Range) by E. Choroba

- challenge-072/yary-h/range.raku
My arg handling in Raku needed improvement, the "where" clause should say what is wrong when rejecting input. Fixed by adding "die" statements.
> Better messages on bad inputs

- challenge-072/jeongoon/raku/ch-1.raku
Sorry. I pushed wrong version one on raku
> ch-072/jeongoon bug fixed in both perl and raku when matching "/0+$/" has no result

- challenge-074/duncan-c-white/README
- challenge-074/duncan-c-white/perl/ch-1.pl
- challenge-074/duncan-c-white/perl/ch-2.pl
sorry for missing last year's 100-submission challenge, once again I was busy last week (with actual Perl programming, gasp).  I'm not quite sure why "First" Non-repeating character in eg 1, pass 2 "ab" is b not a, seems to me that b is the "last" non-repeating char in ab.  but anyway, I get your output..
> wrote my solutions to challenge 74, 2 quite easy questions

- .gitignore
Thought I'd add the output directory of the Rust compiler to the .gitignore
> Add Rust language target directory to .gitignore

- challenge-080/andinus/README
- challenge-080/andinus/perl/ch-1.pl
It didn't check for =1=, I might have assumed that it was accounted
for in this line:
print "1\n" and exit 0 if $sorted[$#sorted] < 1;
This was pointed out by <https://octodon.social/@polettix>
<https://tilde.zone/web/statuses/104981669595493301#>
I also discovered that it'll fail if the inputs are not unique, this
can be fixed by using hash & map somehow. Maybe I'll fix it later
someday.
> challenge-080 ch-1.pl: Fix logical error

- challenge-093/gustavo-chaves/ch-1.pl
The max-points function now uses Math::BigRat objects in order to avoid
rounding errors as much as possible.
> Improve gustavo-chaves's challenge 093

- challenge-097/athanasius/perl/ch-1.pl
- challenge-097/athanasius/perl/ch-2.pl
- challenge-097/athanasius/raku/ch-1.raku
- challenge-097/athanasius/raku/ch-2.raku
On branch branch-for-challenge-097
new file:   challenge-097/athanasius/perl/ch-1.pl
new file:   challenge-097/athanasius/perl/ch-2.pl
new file:   challenge-097/athanasius/raku/ch-1.raku
new file:   challenge-097/athanasius/raku/ch-2.raku
> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #097

- challenge-090/wlmb/perl/ch-1.pl
- challenge-090/wlmb/perl/ch-2.pl
- challenge-091/wlmb/perl/ch-1.pl
- challenge-091/wlmb/perl/ch-2.pl
- challenge-092/wlmb/perl/ch-1.pl
- challenge-092/wlmb/perl/ch-2.pl
- challenge-093/wlmb/perl/ch-1.pl
- challenge-093/wlmb/perl/ch-2.pl
- challenge-094/wlmb/perl/ch-1.pl
- challenge-094/wlmb/perl/ch-2.pl
- challenge-094/wlmb/perl/ch-2a.pl
- challenge-095/wlmb/perl/ch-1.pl
- challenge-095/wlmb/perl/ch-1a.pl
- challenge-095/wlmb/perl/ch-2.pl
- challenge-096/wlmb/perl/ch-1.pl
- challenge-096/wlmb/perl/ch-2.pl
- challenge-097/wlmb/perl/ch-1.pl
- challenge-097/wlmb/perl/ch-2.pl
- challenge-098/wlmb/perl/ch-1.pl
- challenge-098/wlmb/perl/ch-2.pl
I just noticed I haven't been using double slashes in the comments that link to the corresponding blog pages. Fixed that.
Regards
> Fix wrong links in comments for all programs

- challenge-099/e-choroba/perl/ch-1a.pl
- challenge-099/e-choroba/perl/ch-1b.pl
- challenge-099/e-choroba/perl/ch-2.pl
Two different solutions are given for the Pattern Match: One
transforms the pattern into a regex, while the other really implements
the searching for the pattern character by character.
Similarly, there are two subroutines in the Unique Subsequence: One
just returns the final count of solutions, the other one enumarates
all the valid positions in the string.
> Add solution to 099 Pattern Match & Unique Subsequence by E. Choroba

- challenge-117/abigail/blog.txt
- challenge-117/abigail/blog1.txt
- challenge-117/abigail/perl/ch-1.pl
- challenge-117/abigail/perl/ch-2.pl
The links existed in the README file, but not yet in the blog?.txt files.
> Links to blogs.

- challenge-118/lance-wicks/perl/ch-2.pl
- challenge-118/lance-wicks/perl/lib/Knight.pm
A relatively short path is found with 99999 repetitions, more required to get to my best-shortest route so far of 11 moves: (7,0) (6,2) (5,4) (4,2) (2,1) (0,2) (1,0) (2,2) (0,1) (1,3) (3,2) (1,1).
I might do a parallel processing experiment as this is single threaded, and I don't like that I have lost the A-H column names, as it goes against my original intent to make this express the problem without optimisations. :)
> Add a script to be run on CLI, repeats 99999 times 

- challenge-122/andinus/README
- challenge-122/andinus/README.org
- challenge-122/andinus/raku/ch-2.raku
``.comb.grep(* !== "").join'' can be replaced with ``.join''.
And we don't have to convert it back to Int since we're just printing
it.
> Challenge 122: Remove unnecessary method calls

- challenge-131/ben-davies/raku/ch-1.raku
Because it needs to be sorted, but the error given otherwise is useless.
> Document the @xs parameter of challenge 131 task 1

- challenge-132/james-raspass/README
- challenge-132/james-raspass/raku/ch-1.raku
```
$ raku challenge-132/james-raspass/raku/ch-1.raku 2021-09-18 2021-09-22
On the date you were born, someone who was your current age, would have been born on 2021-09-14.
Someone born today will be your current age on 2021-09-26.
```
Uses a slightly different date format but shows off coercion beautifully, the errors are very readable for other date formats:
```
$ raku challenge-132/james-raspass/raku/ch-1.raku 2021/09/18
Invalid Date string '2021/09/18'; use yyyy-mm-dd instead
```
> 132: Mirror Dates in Raku by James Raspass

- challenge-133/ben-davies/raku/ch-2.raku
`&prime-factors` is eager to invoke `Int.is-prime`; cache an infinite sequence of primes so it gets called once per prime max.
> Optimize Ben Davies' challenge 133 task 2 solution

- challenge-138/ash/raku/ch-1.raku
BTW, @manwar, the output for 2021 should be 261, not 260.
> Task 1 of Challenge 138

- challenge-141/simon-proctor/raku/ch-1.raku
- challenge-141/simon-proctor/raku/ch-2.raku
Hi, sorry been a bit bleh but back on the challenge. 
I've done a general find N integers with X divisors version which defaults to N=10 and X=8 because... why not? :)
> Challenge 1

- .vscode/settings.json
This folder is in our .gitignore and should not be checked into this
repository. Having this in the repo will affect everyone using vs code
which might be annoying for contributors who don't like the settings.
Me for example ;) I don't like those rulers. :man_shrugging:
> Remove vscode settings from repo

- challenge-148/perlboy1967/perl/ch-1.pl
- challenge-148/perlboy1967/perl/ch-2.pl
It appears to be Eban <= 100.
Oh well, both are delivered and first 100 is more fun to do efficiently.
> Task 1 - Oops, I thought the challenge was the first 100 Eban numbers... 

- challenge-159/duncan-c-white/README
- challenge-159/duncan-c-white/perl/MakePrimes.pm
- challenge-159/duncan-c-white/perl/PrimeFactors.pm
- challenge-159/duncan-c-white/perl/ch-1.pl
- challenge-159/duncan-c-white/perl/ch-2.pl
bonus feature was (in task 2) a "--tabulate" mode which makes it display the first N Moebius numbers in tabular form. ./ch-2 -t 50 generates the same table as the Wikipedia page contains..
> 2 nice tasks this week, took 1h15m for both basic solutions - then another 10 minutes to add a bonus feature..

- challenge-183/2colours/raku/ch-1.raku
- challenge-183/2colours/raku/ch-2.raku
Hi,
thank you for the challenges. I personally like that they are often a bit vague because this leaves some design decisions for the solver. In this case, I spent more time deciding on the input and the output, also trying to conform with the given examples:
- ch-1: accepting JSON-compatible content, inside parentheses for the containing list. The output is also provided as JSON arrays inside a list (utilizing two Raku modules that can be installed via zef)
- ch-2: reverse dates produce negative result, 0 is not shown - TODO handle matching dates - there is no conversion between days and years so that leap-years don't cause problems, instead, the year is offset to the closest date within the interval
Please take my solution (after a little modification on my side, noticed the matching …
> Branch for challenge 183

- challenge-191/massa/raku/ch-1.raku
Hello, @manwar -- please consider merging.
This makes no difference in the test case, but it just run in O(n log n) instead of O(n²) or worse that the other solution did...
> forgot about transitivity

- challenge-191/simon-proctor/raku/ch-1.raku
Adds a second way of working out the answer and benchmarking for the two.
Turns out, about the same speed. 
Also adds tests for the single and empty list cases.
> Adding a second way of doing it and benchmarking code

- challenge-206/robbie-hatley/blog.txt
- challenge-206/robbie-hatley/perl/ch-1.pl
- challenge-206/robbie-hatley/perl/ch-2.pl
An interesting pair of challenges, especially #2!
> Robbie Hatley's Perl solutions for PWCC 206

- challenge-216/robbie-hatley/blog.txt
- challenge-216/robbie-hatley/perl/ch-1.pl
- challenge-216/robbie-hatley/perl/ch-2.pl
Nifty challenge. #1 was easy, but #2 was quite challenging, especially to make it fast. I got the run time  down to 100ms. I see ways I could get it down to about 100µs if I spent more hours on it, but I've spent all the time I'm willing to spend this afternoon; I've other things to do. I'm sure others will have faster solutions; will be interesting to see what people come up with.
> Robbie Hatley's Perl solutions to The Weekly Challenge 216

- challenge-219/robbie-hatley/blog.txt
- challenge-219/robbie-hatley/perl/ch-1.pl
I only had time for #1 this week, alas. (Very hectic week for me.)
> Robbie Hatley's Perl solution to The Weekly Challenge 219-1.

- challenge-250/robbie-hatley/perl/ch-2.pl
One too many brackets: "[[[:alnum:]]". Oopsie! I changed it to "[a-zA-Z0-9]" which is much more clear.
> Fixed error in 250-2.

- challenge-257/robbie-hatley/perl/ch-1.pl
I may not find time to do task #2 this week, but here's my solution to task #1.
> Robbie Hatley's Perl solution to The Weekly Challenge 257-1.

- challenge-286/ppentchev/README
- challenge-286/ppentchev/blog.txt
- challenge-286/ppentchev/docs/index.md
- challenge-286/ppentchev/python/README.md
- challenge-286/ppentchev/python/pyproject.toml
- challenge-286/ppentchev/python/requirements/ruff.txt
- challenge-286/ppentchev/python/ruff-base.toml
- challenge-286/ppentchev/python/scripts/ch-1.py
- challenge-286/ppentchev/python/scripts/ch-2.py
- challenge-286/ppentchev/python/tox.ini
- challenge-286/ppentchev/tests/01-perl-ch-1.t
- challenge-286/ppentchev/tests/03-python-ch-1.t
- challenge-286/ppentchev/tests/04-python-ch-2.t
- challenge-286/ppentchev/tests/lib/PWCTest/Ch286.pm
Also fix a couple of things in the other files:
- make the TAP test functions accept an arrayref for the command to run instead of a single string, since we want to run the Python solution using `python3 -B -u /path/to/the/program`
- fix the use of Test::More::skip() in the Self Spammer test function
- fix a shadowed variable in the Order Game test function
- correct the indentation in the documentation's "Implementation details" section
- make the README file a copy of docs/index.md instead of a wrong copy of a completely different project's README file
- point blog.txt to the Ringlet copy of this challenge's documentation
> Add Peter Pentchev's Python solutions to 286

- challenge-203/jaldhar-h-vyas/perl/ch-1.pl
- challenge-203/jaldhar-h-vyas/perl/ch-2.pl
- challenge-203/jaldhar-h-vyas/raku/ch-1.raku
- challenge-203/jaldhar-h-vyas/raku/ch-2.raku
> Challenge 203 by Jaldhar H. Vyas.
