manwar/perlweeklychallenge-club

challenge-078/athanasius/perl/ch-1.pl, challenge-078/athanasius/perl/ch-2.pl, challenge-078/athanasius/raku/ch-1.raku, challenge-078/athanasius/raku/ch-2.raku
On branch branch-for-challenge-078
new file:   challenge-078/athanasius/perl/ch-1.pl
new file:   challenge-078/athanasius/perl/ch-2.pl
new file:   challenge-078/athanasius/raku/ch-1.raku
new file:   challenge-078/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #078

challenge-077/cheok-yin-fung/perl/ch-2.pl, challenge-078/cheok-yin-fung/ch-1.pl, challenge-078/cheok-yin-fung/ch-2.pl
submission for the latest challenge: 2 Perl scripts
=> submission for Challenge 078 and update 077

challenge-078/jaldhar-h-vyas/blog.txt, challenge-078/jaldhar-h-vyas/perl/ch-1.pl, challenge-078/jaldhar-h-vyas/perl/ch-2.pl, challenge-078/jaldhar-h-vyas/raku/ch-1.sh, challenge-078/jaldhar-h-vyas/raku/ch-2.p6
Late I know, but I want to get back on track after another forced hiatus.
=> Challenge 78 by Jaldhar H. Vyas

challenge-079/nunovieira220/js/ch-1.js, challenge-079/nunovieira220/js/ch-2.js, challenge-079/nunovieira220/perl/ch-1.pl, challenge-079/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 079.
=> Add solution to challenge 079

challenge-079/polettix/blog.txt, challenge-079/polettix/blog1.txt, challenge-079/polettix/perl/ch-1.pl, challenge-079/polettix/perl/ch-2.pl
... this is pretty much it, thanks!
=> Add PWC079 for polettix

challenge-079/jeongoon/perl/blog1.txt, challenge-079/jeongoon/perl/ch-1.pl, challenge-079/jeongoon/perl/ch-2.pl, challenge-079/jeongoon/raku/ch-1.raku, challenge-079/jeongoon/raku/ch-1.short.raku, challenge-079/jeongoon/raku/ch-2.raku
=> [ch-079/jeongoon] Perl and Raku solution added.

challenge-079/daniel-mantovani/blog.txt, challenge-079/daniel-mantovani/blog1.txt, challenge-079/daniel-mantovani/perl/ch-1.pl, challenge-079/daniel-mantovani/perl/ch-2.pl
=> Branch for challenge 079

challenge-079/rakulius/README, challenge-079/rakulius/raku/ch-1.p6
=> My solution for Challenge 079 - Task #1.

challenge-079/athanasius/perl/ch-1.pl, challenge-079/athanasius/perl/ch-2.pl, challenge-079/athanasius/raku/ch-1.raku, challenge-079/athanasius/raku/ch-2.raku
On branch branch-for-challenge-079
new file:   challenge-079/athanasius/perl/ch-1.pl
new file:   challenge-079/athanasius/perl/ch-2.pl
new file:   challenge-079/athanasius/raku/ch-1.raku
new file:   challenge-079/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #079

challenge-079/juliodcs/perl/ch-1.pl
Updated ch-1 perl solution to work with bigints
=> Juliodcs week79

challenge-079/alexander-pankoff/README, challenge-079/alexander-pankoff/perl/ch-1.pl, challenge-079/alexander-pankoff/perl/ch-2.pl
My solutions for the current week
=> add solutions for challenge-079

challenge-079/cheok-yin-fung/perl/ch-1.pl
=> say "laziness" for a week

challenge-080/gugod/kotlin/ch-1.kts, challenge-080/gugod/kotlin/ch-2.kts, challenge-080/gugod/perl/ch-1.pl, challenge-080/gugod/perl/ch-2.pl, challenge-080/gugod/raku/ch-1.raku, challenge-080/gugod/raku/ch-2.raku
I also wrote a blog about this:
https://gugod.org/2020/09/solutions-of-pwc-080/
=> solutions of PWC 080 from gugod in Perl, Raku, and Kotlin.

challenge-080/walt-mankowski/blog.txt, challenge-080/walt-mankowski/perl/ch-1.pl, challenge-080/walt-mankowski/perl/ch-2.pl, challenge-080/walt-mankowski/python/ch-1.py, challenge-080/walt-mankowski/python/ch-2.py
Perl and Python code for challenge 80
=> Branch for challenge 080

challenge-080/shawn-wagner/perl/ch1.pl, challenge-080/shawn-wagner/perl/ch2.pl, challenge-080/shawn-wagner/tcl/ch1.tcl, challenge-080/shawn-wagner/tcl/ch2.tcl
=> Challenge 080 solution

challenge-080/nunovieira220/js/ch-1.js, challenge-080/nunovieira220/js/ch-2.js, challenge-080/nunovieira220/perl/ch-1.pl, challenge-080/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 079.
=> Add solution to challenge 080

challenge-080/juliodcs/perl/ch-1.pl, challenge-080/juliodcs/perl/ch-2.pl, challenge-080/juliodcs/raku/ch-1.raku, challenge-080/juliodcs/raku/ch-2.raku
=> Add solution for Week 80

challenge-080/ted-leahy/perl/ch-1.pl, challenge-080/ted-leahy/perl/ch-2.pl
This is the second week I've done this challenge, and I just want to say thanks a lot, it's great! I'm fairly new to perl (been working with it for just under 2 months) so these are a lot of fun and really useful for improving my new perl skills.
Let me know if you notice any noob mistakes, I'm still not 100% sure about Perl best practices :)
-Ted
=> Add solutions for week 80

challenge-080/jeongoon/haskell/ch-1.hs, challenge-080/jeongoon/haskell/ch-2.hs, challenge-080/jeongoon/perl/ch-1.pl, challenge-080/jeongoon/perl/ch-2.pl, challenge-080/jeongoon/raku/ch-1.raku, challenge-080/jeongoon/raku/ch-2.raku
=> [ch-080/jeongoon] Perl, Raku, Haskell Solution added.

challenge-080/polettix/blog.txt, challenge-080/polettix/blog1.txt, challenge-080/polettix/perl/ch-1.pl, challenge-080/polettix/perl/ch-2.pl
Blog entry for count candies is still not out... but will be soon ;-)
=> Add polettix's solution to PWC080

challenge-080/athanasius/perl/ch-1.pl, challenge-080/athanasius/perl/ch-2.pl, challenge-080/athanasius/raku/ch-1.raku, challenge-080/athanasius/raku/ch-2.raku
On branch branch-for-challenge-080
new file:   challenge-080/athanasius/perl/ch-1.pl
new file:   challenge-080/athanasius/perl/ch-2.pl
new file:   challenge-080/athanasius/raku/ch-1.raku
new file:   challenge-080/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #080

challenge-080/alexander-pankoff/README, challenge-080/alexander-pankoff/haskell/ch-1.hs, challenge-080/alexander-pankoff/perl/ch-1.pl, challenge-080/alexander-pankoff/perl/ch-2.pl
My solutions for the current week
=> Challenge 080

challenge-081/jeongoon/blog.txt
Thank you for kind words, and giving me a champion ^^
=> [ch-081/jeongoon] a Blog added

challenge-081/jeongoon/blog1.txt
=> [ch-081/jeongoon] another blog added

challenge-080/andinus/README, challenge-080/andinus/perl/ch-1.pl, challenge-081/andinus/perl/ch-2.pl
This fixes the bug in challenge-080 ch-1 where repeated elements would
break the code & removes a useless line in challenge-081 ch-2.
=> Fix bug on challenge-080 ch-1, compact challenge-081 ch-2

challenge-081/polettix/blog.txt, challenge-081/polettix/blog1.txt, challenge-081/polettix/perl/ch-1.pl, challenge-081/polettix/perl/ch-2.pl
My solutions for this week's challenges. As usual, the blog posts are on their way. Thanks!
=> Add polettix's solution for PWC081

challenge-081/tyler-wardhaugh/clojure/src/tw/weekly/c81/t2.clj
We just need a count of the words, which can be achieved by summing (via
x/reduce +) 1 for every instance we find.
Add comments to clarify what the algorithm is doing at each step.
=> Ch81/Task 2: optimize and add comments

challenge-081/alexander-pankoff/README, challenge-081/alexander-pankoff/perl/ch-1.pl, challenge-081/alexander-pankoff/perl/ch-2.pl
My solutions for the current challenge. 
Thanks :+1:
=> Challenge 081

challenge-081/duncan-c-white/README, challenge-081/duncan-c-white/perl/WestSideStory, challenge-081/duncan-c-white/perl/ch-1.pl, challenge-081/duncan-c-white/perl/ch-2.pl
…enjoyed both, especially the frequency sort
=> imported my solutions to this week's questions..

challenge-082/gugod/raku/ch-1.raku, challenge-082/gugod/raku/ch-2.raku
I blogged about this too: https://gugod.org/2020/10/pwc-082-raku/
=> gugod's solution for PWC 082

challenge-082/polettix/blog.txt, challenge-082/polettix/blog1.txt, challenge-082/polettix/perl/ch-1.pl, challenge-082/polettix/perl/ch-2.pl
Blog entry for task #2 is on its way for being published. Thanks for all the energy you put!
=> Add entries for 082/polettix

challenge-082/alexander-pankoff/perl/ch-1.pl, challenge-082/alexander-pankoff/perl/ch-2.pl
Hey Mohammad,
please merge my perl solutions for the current week.
Thanks!
=> Challenge 082

challenge-082/gugod/raku/ch-1.raku
Hi,
I updated my solution and also wrote about them here
- https://gugod.org/2020/10/pwc-082-raku-en/
- https://gugod.org/2020/10/common-factors-and-gcd-en/
=> [gugod] an imprement of 082.1

challenge-082/abigail/perl/ch-1.pl
Improved the running time of the algorithm from O (sqrt (gcd ($M, $N)))
to O (sqrt (p) + |f| log |f|) where p is the largest prime factor
of gcd ($M, $N), and |f| is total number of factors.
This is not an improvement if the gcd is a prime, but a dramatic
improvement if the gcd contains lots of prime factors.
=> Improve the performance of week 082/part 1.

challenge-082/jluis/perl/ch-1.pl, challenge-082/jluis/perl/ch-2.pl
This week  I cannot thick of a fancy solution so I push this as WIP solution
=> my aproach to challenge 082

challenge-082/nunovieira220/js/ch-1.js, challenge-082/nunovieira220/js/ch-2.js, challenge-082/nunovieira220/perl/ch-1.pl, challenge-082/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 082.
=> Add solution to challenge 082

challenge-082/walt-mankowski/blog.txt, challenge-082/walt-mankowski/perl/ch-1.pl, challenge-082/walt-mankowski/perl/ch-2.pl, challenge-082/walt-mankowski/python/ch-1.py, challenge-082/walt-mankowski/python/ch-2.py
Perl and Python code for challenge 82
=> Branch for challenge 082

challenge-082/polettix/blog2.txt, challenge-082/polettix/perl/ch-2.pl
Ehr... sorry for all the noise, but I solved a different problem in challenge 2, and I had to change it. I also added another blog post about this... I hope it can be useful.
Sorry again for the trouble and thanks for all that you do!
=> Adjust solution to examples :)

challenge-082/athanasius/perl/ch-1.pl, challenge-082/athanasius/perl/ch-2.pl, challenge-082/athanasius/raku/ch-1.raku, challenge-082/athanasius/raku/ch-2.raku
On branch branch-for-challenge-082
new file:   challenge-082/athanasius/perl/ch-1.pl
new file:   challenge-082/athanasius/perl/ch-2.pl
new file:   challenge-082/athanasius/raku/ch-1.raku
new file:   challenge-082/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #082

challenge-082/jeongoon/go/ch-2.go, challenge-082/jeongoon/perl/Ch2PlanA.pm
Sorry, I know it is late. but this version is more accurate.
=> [ch-082/jeongoon] I think this is correct one {ch-2.go, Ch2PlanA.pm}

challenge-083/james-smith/perl/ch-1.pl, challenge-083/james-smith/perl/ch-2.pl
Pushed code to solve this weeks problems in Perl
=> solutions to challenge 83

challenge-083/jluis/perl/ch-1.pl, challenge-083/jluis/perl/ch-2.pl
I would like to put the fist as a one-liner but I didn't find a reference of how it can be better integrated on the repo:
=> This week solutions 

challenge-083/walt-mankowski/blog.txt, challenge-083/walt-mankowski/perl/ch-1.pl, challenge-083/walt-mankowski/perl/ch-2.pl
Here are my solutions to this week's challenge. Just Perl code this week.
=> Branch for challenge 083

challenge-083/shawn-wagner/ocaml/Makefile, challenge-083/shawn-wagner/ocaml/ch1.ml, challenge-083/shawn-wagner/ocaml/ch2.ml, challenge-083/shawn-wagner/perl/ch-1.pl, challenge-083/shawn-wagner/perl/ch-2.pl, challenge-083/shawn-wagner/tcl/ch-1.tcl, challenge-083/shawn-wagner/tcl/ch-2.tcl
Solutions in perl, tcl and ocaml.
=> Challenge 083 solution

challenge-083/gugod/README, challenge-083/gugod/python/ch-1.py, challenge-083/gugod/python/ch-2.py, challenge-083/gugod/raku/ch-1.raku, challenge-083/gugod/raku/ch-2.raku
my blog entry https://gugod.org/2020/10/pwc-083/
=> gugod's solution to pwc 083

challenge-083/polettix/blog.txt, challenge-083/polettix/blog1.txt, challenge-083/polettix/perl/ch-1.pl, challenge-083/polettix/perl/ch-2.pl
Hi! My contribution for this week, blog entries on their way to publication in the coming days. Thank you!
=> Add polettix's solution to challenge 083

challenge-083/alexander-pankoff/perl/ch-1.pl, challenge-083/alexander-pankoff/perl/ch-2.pl
My perl solutions for the current week. 
As always, thanks for the challenge.
=> add solutions for challenge-083

challenge-083/nunovieira220/js/ch-1.js, challenge-083/nunovieira220/js/ch-2.js, challenge-083/nunovieira220/perl/ch-1.pl, challenge-083/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 083.
=> Add solution to challenge 083

challenge-083/athanasius/perl/ch-1.pl, challenge-083/athanasius/perl/ch-2.pl, challenge-083/athanasius/raku/ch-1.raku, challenge-083/athanasius/raku/ch-2.raku
On branch branch-for-challenge-083
new file:   challenge-083/athanasius/perl/ch-1.pl
new file:   challenge-083/athanasius/perl/ch-2.pl
new file:   challenge-083/athanasius/raku/ch-1.raku
new file:   challenge-083/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #083

challenge-083/duncan-c-white/README, challenge-083/duncan-c-white/perl/ch-1.pl, challenge-083/duncan-c-white/perl/ch-2.pl
I didn't have much time to think about the second one, so my solution is not very elegant; solid, does the job, no inspiration, no cleverness, probably not very efficient
=> imported my solutions, slightly late, only started at 11:40pm:-)

challenge-084/simon-proctor/raku/ch-1.raku
Need to have a think about challenge 2.
=> Flipping integers

challenge-084/frankivo/ReverseInteger.scala
=> ReverseInteger

challenge-083/daniel-mita/perl/ch-2.pl
I might come back and refactor this, but in the meantime this fixes my previously incorrect handling of possible combinations.
=> Fix incorrect implementation of combinations for challenge-083-2-perl

challenge-084/james-smith/perl/ch-1.pl, challenge-084/james-smith/perl/ch-2.pl
This weeks were quite easy - and so the coding is a bit naive - and I can't see any real "optimizations" in this code..
=> challenge solutions

challenge-084/polettix/blog.txt, challenge-084/polettix/blog1.txt, challenge-084/polettix/perl/ch-1.pl, challenge-084/polettix/perl/ch-2.pl
Blog posts already available.
Thanks for your huge work, Flavio.
=> Add poletti'x solution to challenge 084

challenge-084/shawn-wagner/perl/ch-1.pl, challenge-084/shawn-wagner/perl/ch-2.pl
Just perl this week, I'm afraid.
=> Challenge 084, both parts in perl

challenge-084/nunovieira220/js/ch-1.js, challenge-084/nunovieira220/js/ch-2.js, challenge-084/nunovieira220/perl/ch-1.pl, challenge-084/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 084.
=> Add solution to challenge 084

challenge-001/samir-parikh/perl/README, challenge-001/samir-parikh/perl/ch-1.pl, challenge-002/samir-parikh/perl/README, challenge-002/samir-parikh/perl/ch-1.pl, challenge-084/samir-parikh/README, challenge-084/samir-parikh/perl/ch-1.pl, challenge-084/samir-parikh/perl/ch-2.pl
Hi Mohammad -- I am new to Perl and thought I could use your site to practice and learn.  I'm not experienced with Github so I hope I did this right!
=> add solutions to Challenge 084

challenge-084/athanasius/perl/ch-1.pl, challenge-084/athanasius/perl/ch-2.pl, challenge-084/athanasius/raku/ch-1.raku, challenge-084/athanasius/raku/ch-2.raku
On branch branch-for-challenge-084
new file:   challenge-084/athanasius/perl/ch-1.pl
new file:   challenge-084/athanasius/perl/ch-2.pl
new file:   challenge-084/athanasius/raku/ch-1.raku
new file:   challenge-084/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #084

challenge-084/adam-russell/blog.txt, challenge-084/adam-russell/perl/ch-1.pl
only able to get to part 1 this week!
=> solution for challenge 084

challenge-084/duncan-c-white/README, challenge-084/duncan-c-white/perl/ch-1.pl, challenge-084/duncan-c-white/perl/ch-2-firstattempt.pl, challenge-084/duncan-c-white/perl/ch-2.pl
2 relatively easy questions this week, including 2 versions of the task 2 solutions (see README for details)
=> committed my solutions for this week's exercises

challenge-083/alexander-pankoff/perl/ch-2.pl, challenge-083/alexander-pankoff/perl/lib/Combinations.pm, challenge-084/alexander-pankoff/perl/ch-1.pl, challenge-084/alexander-pankoff/perl/ch-2.pl, challenge-084/alexander-pankoff/perl/lib/MatrixParser.pm, challenge-084/alexander-pankoff/perl/lib/MatrixParser/Lexer.pm, challenge-084/alexander-pankoff/perl/lib/MatrixParser/Token.pm
My solutions for the current challenge. 
There are also minor tweaks to last weeks solution so that i could easier reuse the `combinations` sub.
=> Challenge 084

challenge-084/kai-burgdorf/perl/ch-1.pl, challenge-084/kai-burgdorf/perl/ch-2.pl
I found a bug in ch-1 and improved my solution for ch-2. 
a little late, i hope you don't mind merging anyways
=> Revise challenge 84

challenge-085/simon-proctor/raku/ch-1.raku, challenge-085/simon-proctor/raku/ch-2.raku
There's probably a super maths way of doing the second challenge.
I am so tired I couldn't even read it correctly though.
I hope you're OK. :)
=> Challenge 85

challenge-085/nunovieira220/js/ch-1.js, challenge-085/nunovieira220/js/ch-2.js, challenge-085/nunovieira220/perl/ch-1.pl, challenge-085/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 085.
=> Add solution to challenge 085

challenge-085/walt-mankowski/perl/ch-1.pl, challenge-085/walt-mankowski/perl/ch-2.pl
=> Branch for challenge 085

challenge-085/e-choroba/perl/ch-1.pl, challenge-085/e-choroba/perl/ch-2.pl
The Triplet Sum solution is the fastest I could find.
=> Add solution to 085 Triplet Sum & Power of Two Integers (E. Choroba)

challenge-085/shawn-wagner/ocaml/ch1.ml, challenge-085/shawn-wagner/ocaml/dune, challenge-085/shawn-wagner/perl/ch-1.pl, challenge-085/shawn-wagner/perl/ch-2.pl
Both parts in perl, and first in ocaml.
=> Challenge 085 solution

challenge-085/athanasius/perl/ch-1.pl, challenge-085/athanasius/perl/ch-2.pl, challenge-085/athanasius/raku/ch-1.raku, challenge-085/athanasius/raku/ch-2.raku
On branch branch-for-challenge-085
new file:   challenge-085/athanasius/perl/ch-1.pl
new file:   challenge-085/athanasius/perl/ch-2.pl
new file:   challenge-085/athanasius/raku/ch-1.raku
new file:   challenge-085/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #085

challenge-085/kai-burgdorf/perl/ch-1.pl
This time only challenge one ;(
=> solution for week 085 ch-1

challenge-085/abigail/blog.txt, challenge-085/abigail/blog1.txt
=> Links to blogs.

challenge-085/adam-russell/blog1.txt, challenge-085/adam-russell/prolog/ch-2.p
added a second blog link which discusses the Prolog solutions
=> Challenge 085

challenge-085/duncan-c-white/README, challenge-085/duncan-c-white/perl/ch-1.pl, challenge-085/duncan-c-white/perl/ch-2.pl
I couldn't think of a very interesting approach, I'm afraid
=> committed my solutions to this week's questions

challenge-085/e-choroba/perl/ch-2.pl
=> Fixed error in 085/2

challenge-086/polettix/blog.txt, challenge-086/polettix/blog1.txt, challenge-086/polettix/perl/ch-1.pl, challenge-086/polettix/perl/ch-2.pl
Hi! Thanks for all the hard work!
Please find my contribution for this week's challenge. The second blog post will be published tomorrow in the morning (European time).
Cheers!
=> Add polettix's solution to PWC086

challenge-086/nunovieira220/js/ch-1.js, challenge-086/nunovieira220/js/ch-2.js, challenge-086/nunovieira220/perl/ch-1.pl, challenge-086/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 086.
=> Add solution to challenge 086

challenge-086/tyler-wardhaugh/clojure/src/tw/weekly/c86/t1.clj, challenge-086/tyler-wardhaugh/lua/README.md, challenge-086/tyler-wardhaugh/lua/ch-1.lua, challenge-086/tyler-wardhaugh/lua/ch-2.lua, challenge-086/tyler-wardhaugh/lua/run.lua, challenge-086/tyler-wardhaugh/lua/test.lua
I also revamped my Clojure implementation of Task 1.
=> Challenge 086 in Lua

challenge-086/shawn-wagner/perl/ch-1.pl, challenge-086/shawn-wagner/perl/ch-2.pl, challenge-086/shawn-wagner/tcl/ch-1.tcl
=> Challenge 086 solution

challenge-086/cheok-yin-fung/blog.txt, challenge-086/cheok-yin-fung/perl/ch-1.pl, challenge-086/cheok-yin-fung/perl/ch-2.pl
Please allow a small cheat: blog not yet finished (or two? sudoku codes not yet "completed")
=> CY's take on Challenge #086

challenge-086/alexander-pankoff/perl/ch-1.pl, challenge-086/alexander-pankoff/perl/ch-2.pl
My solutions for the current week
=> Challenge 086

challenge-086/duncan-c-white/README, challenge-086/duncan-c-white/perl/ch-1.pl, challenge-086/duncan-c-white/perl/ch-2.pl
damn hard problem to write a suduko solver in a few hours, isn't it?  I happened to already have a sudoku solver I wrote earlier, but I thought rather than just submit one I prepared earlier, I'd hack it: replace a set of clever deductions with a brute force solver, but I couldn't get it to work in time
=> imported my solution to task 1, got stuck on suduko solver

challenge-087/polettix/blog.txt, challenge-087/polettix/blog1.txt, challenge-087/polettix/perl/ch-1.pl, challenge-087/polettix/perl/ch-2.pl
Thank you for your relentless work.
Second blog post on its way to publishing tomorrow morning.
Cheers, Flavio.
=> Add polettix's solution to PWC087

challenge-087/alexander-pankoff/perl/ch-1.pl, challenge-087/alexander-pankoff/perl/ch-2.pl
=> Challenge 087

challenge-087/nunovieira220/js/ch-1.js, challenge-087/nunovieira220/js/ch-2.js, challenge-087/nunovieira220/perl/ch-1.pl, challenge-087/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 087.
=> Add solution to challenge 087

challenge-087/cheok-yin-fung/blog.txt, challenge-087/cheok-yin-fung/common-lisp/ch-1.lsp, challenge-087/cheok-yin-fung/perl/ch-1.pl, challenge-087/cheok-yin-fung/perl/ch-2.pl
2 Perl scripts, a blogpost, 1 Lisp script
(blogpost link fixed)
=> Cheok Yin's submission for challenge 087

challenge-087/athanasius/perl/ch-1.pl, challenge-087/athanasius/perl/ch-2.pl, challenge-087/athanasius/raku/ch-1.raku, challenge-087/athanasius/raku/ch-2.raku
On branch branch-for-challenge-087
new file:   challenge-087/athanasius/perl/ch-1.pl
new file:   challenge-087/athanasius/perl/ch-2.pl
new file:   challenge-087/athanasius/raku/ch-1.raku
new file:   challenge-087/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #087

challenge-087/duncan-c-white/README, challenge-087/duncan-c-white/perl/ch-1.pl, challenge-087/duncan-c-white/perl/ch-2.pl
I'm afraid I've done neither very elegantly…
=> added my solutions to this week's tasks..

challenge-086/juliodcs/raku/ch-2.raku
Minor changes from previous week. I forgot creating the pull request... 😄
=> Juliodcs week86

challenge-088/james-smith/perl/ch-1.pl, challenge-088/james-smith/perl/ch-2.pl
Nice challenges this week....
I like the fact that you don't need to worry about indicies in the 2nd example - just knowing when you can shift or pop elements!
=> First pass at ch 88

challenge-086/juliodcs/raku/ch-2.raku
Minor changes on week86 challenge
=> Minor changes

challenge-087/juliodcs/raku/ch-2.raku
Really minor tweak, removed useless parentheses
=> Minor tweak

challenge-088/wlmb/README, challenge-088/wlmb/blog.txt, challenge-088/wlmb/perl/ch-1.pl, challenge-088/wlmb/perl/ch-2.pl
Add solutions to challenge 088 using the perl data language.
=> Add pdl solution to challenge 88

challenge-088/miguel-prz/perl/Task088_1.pm, challenge-088/miguel-prz/perl/Task088_2.pm, challenge-088/miguel-prz/perl/ch-1.pl, challenge-088/miguel-prz/perl/ch-2.pl
=> Solutions to 088 challenge

challenge-088/nunovieira220/js/ch-1.js, challenge-088/nunovieira220/js/ch-2.js, challenge-088/nunovieira220/perl/ch-1.pl, challenge-088/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 088.
=> Add solution to challenge 088

challenge-088/polettix/blog.txt, challenge-088/polettix/blog1.txt, challenge-088/polettix/perl/ch-1.pl, challenge-088/polettix/perl/ch-2.pl
Hi, thanks for all the hard work.
This is my solution for this week's challenge. Blog posts are already in place.
Thanks!
=> Add polettix's solution to PWC088

challenge-088/walt-mankowski/README.md, challenge-088/walt-mankowski/perl/ch-1.pl, challenge-088/walt-mankowski/perl/ch-2.pl
Perl solutions for Challenge 88
My writeup is in README.md
=> Branch for challenge 088

challenge-088/athanasius/perl/ch-1.pl, challenge-088/athanasius/perl/ch-2.pl, challenge-088/athanasius/raku/ch-1.raku, challenge-088/athanasius/raku/ch-2.raku
On branch branch-for-challenge-088
new file:   challenge-088/athanasius/perl/ch-1.pl
new file:   challenge-088/athanasius/perl/ch-2.pl
new file:   challenge-088/athanasius/raku/ch-1.raku
new file:   challenge-088/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #088

challenge-088/tyler-wardhaugh/clojure/src/tw/weekly/c88/t1.clj, challenge-088/tyler-wardhaugh/lua/ch-1.lua, challenge-088/tyler-wardhaugh/lua/ch-2.lua, challenge-088/tyler-wardhaugh/lua/test.lua, challenge-088/tyler-wardhaugh/lua/util.lua
As well as a touchup to Task 1 in Clojure.
=> Challenge 088 in Lua

challenge-088/cheok-yin-fung/blog.txt, challenge-088/cheok-yin-fung/perl/ch-1.pl, challenge-088/cheok-yin-fung/perl/ch-2.pl
=> CY's take for the 88th Challenge

challenge-088/alexander-pankoff/perl/ch-1.pl, challenge-088/alexander-pankoff/perl/ch-2.pl
my solutions for the current week
=> add perl solutions for challenge-088:

challenge-088/duncan-c-white/README, challenge-088/duncan-c-white/perl/ch-1.pl, challenge-088/duncan-c-white/perl/ch-2.pl
especially the spiral path one which made me think…
=> imported my solutions; liked both tasks

challenge-088/jeongoon/blog.txt
Sorry. I forgot to add blog link.
And I'll be on holiday on PWC for a while.
I'll come back ~!!
=> [ch-088/jeongoon] Forgot to add blog T.T

challenge-088/jeongoon/raku/ch-2.raku
=> [ch-088/jeongoon] ch-2.raku had bug.. fixed.

challenge-089/aaronreidsmith/blog.txt, challenge-089/aaronreidsmith/raku/ch-1.raku, challenge-089/aaronreidsmith/raku/ch-2.raku
Glad I stumbled upon this last week. Here are my challenge 89 Raku solutions!
=> Challenge 89 Raku solutions

challenge-089/xliff/README, challenge-089/xliff/raku/ch-1.raku, challenge-089/xliff/raku/ch-2.raku
My first solution. This was fun! Thank you for organizing these!
=> - Solution for Weekly Challenge 089 by Xliff

challenge-088/adam-russell/prolog/ch-2.p
just a small fix to the last challenge
=> bug fix to Prolog solution for Part 2

challenge-089/walt-mankowski/README.md, challenge-089/walt-mankowski/perl/ch-1.pl, challenge-089/walt-mankowski/perl/ch-2.pl
Here's my Perl code for challenge 89.
=> Branch for challenge 089

challenge-089/alexander-pankoff/perl/ch-1.pl, challenge-089/alexander-pankoff/perl/ch-2.pl
=> Challenge 089

challenge-076/andinus/README.org, challenge-077/andinus/README.org, challenge-078/andinus/README.org, challenge-079/andinus/README.org, challenge-080/andinus/README.org, challenge-081/andinus/README.org, challenge-082/andinus/README.org, challenge-083/andinus/README.org, challenge-086/andinus/README.org
These are not solutions but just changing the `HTML_LINK_UP' property
of all README.org files. I changed the website layout.
=> Change "up" link in all README.org

challenge-089/nunovieira220/js/ch-1.js, challenge-089/nunovieira220/js/ch-2.js, challenge-089/nunovieira220/perl/ch-1.pl, challenge-089/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 089.
=> Add solution to challenge 089

challenge-089/cheok-yin-fung/blog.txt, challenge-089/cheok-yin-fung/perl/ch-1.pl, challenge-089/cheok-yin-fung/perl/ch-2.pl
2 Perl scripts and 1 blogpost focusing on the Task 2
=> CY's Take on Challenge 089

challenge-089/duncan-c-white/README, challenge-089/duncan-c-white/perl/ch-1.pl, challenge-089/duncan-c-white/perl/ch-2.pl
(magic square) particularly... nice brute force generate and test with a few constraint based optimizations
=> imported my solutions, two nice easy puzzles, I enjoyed the magic matrix

challenge-089/e-choroba/perl/ch-1.pl, challenge-089/e-choroba/perl/ch-2.pl
GCD Sum shows both the naive slow algorithm and the fast one based on
Euler's totient function (studied at
https://www.geeksforgeeks.org/summation-gcd-pairs-n/).
=> Add solutions by E. Choroba to 089: GCD Sum & Magical Matrix

challenge-090/polettix/blog.txt, challenge-090/polettix/blog1.txt, challenge-090/polettix/perl/ch-1.pl, challenge-090/polettix/perl/ch-2.pl
=> Add polettix's solution to PWC090

challenge-090/alexander-pankoff/perl/ch-1.pl, challenge-090/alexander-pankoff/perl/ch-2.pl
My solutions for the current challenge.
=> add solutions for challenge-090 in perl

challenge-090/ziameraj16/README.md, challenge-090/ziameraj16/java/EthiopianMultiplication.java
This is a Java solution to Ethiopian Multiplication
=> Java Solution for Ethiopian Multiplication

challenge-090/nunovieira220/js/ch-1.js, challenge-090/nunovieira220/js/ch-2.js, challenge-090/nunovieira220/perl/ch-1.pl, challenge-090/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 090.
=> Add solution to challenge 090

challenge-090/sgreen/README.md, challenge-090/sgreen/blog.txt, challenge-090/sgreen/perl/ch-1.pl, challenge-090/sgreen/perl/ch-2.pl
=> sgreen solution to challenge 090

challenge-091/james-smith/perl/ch-1.pl, challenge-091/james-smith/perl/ch-2.pl
This weeks were really nice - a little bit of thinking required - the first one is nice as you can use a one-liner "regex" regex....
- **r** -> return replaced string (rather than updating it)
- **e** -> execute the code in the replace string (rather than a direct replacement)
- **g** -> execute multiple times (ok most people now this one!)
- **e** -> superfluous - didn't need to put it in - but it makes the "trick" look better!
- **x** -> add whitespace and comment the regular expression to make it more readable
=> Solutios week 91

challenge-091/wlmb/blog.txt, challenge-091/wlmb/perl/ch-1.pl, challenge-091/wlmb/perl/ch-2.pl
=> Add solutions to challenge 91

challenge-091/nunovieira220/js/ch-1.js, challenge-091/nunovieira220/js/ch-2.js, challenge-091/nunovieira220/perl/ch-1.pl, challenge-091/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 091.
=> Add solution to challenge 091

challenge-091/polettix/blog.txt, challenge-091/polettix/blog1.txt, challenge-091/polettix/perl/ch-1.pl, challenge-091/polettix/perl/ch-2.pl
Thank you for all the hard work! Second blog post on its way...
=> Add polettix's solution to PWC091

challenge-091/aaronreidsmith/blog.txt, challenge-091/aaronreidsmith/raku/ch-1.raku, challenge-091/aaronreidsmith/raku/ch-2.raku
Raku solutions for challenge 91
=> Challenge 91 - Raku

challenge-091/alexander-pankoff/perl/ch-1.pl, challenge-091/alexander-pankoff/perl/ch-2.pl
Hey Mohammad,
my solutions for the current week. Thanks for keeping me hooked!
=> add perl solutions for challenge-091

challenge-091/cheok-yin-fung/perl/ch-1.pl, challenge-091/cheok-yin-fung/perl/ch-2.pl
=> Challenge 091

challenge-091/duncan-c-white/README, challenge-091/duncan-c-white/perl/ch-1.pl, challenge-091/duncan-c-white/perl/ch-2.pl
I thought the jump-game would be more challenging than it was; with negative values, and the ability to start at any position (not just pos 0). it might be quite cool..
=> imported my attempts at this week's puzzles

challenge-091/jaldhar-h-vyas/blog.txt, challenge-091/jaldhar-h-vyas/perl/ch-1.pl, challenge-091/jaldhar-h-vyas/perl/ch-2.pl, challenge-091/jaldhar-h-vyas/raku/ch-1.raku, challenge-091/jaldhar-h-vyas/raku/ch-2.raku
=> Challenge 91 by Jaldhar H. Vyas

challenge-092/e-choroba/perl/ch-1.pl, challenge-092/e-choroba/perl/ch-2.pl
Insert Interval can be solved by using the code form 050/1 Merge
Intervals which I did.
=> Add solutions to 092: Isomorphic Strings & Insert Interval

challenge-092/james-smith/perl/ch-1-firstpass.pl, challenge-092/james-smith/perl/ch-1-list-iso-words.pl, challenge-092/james-smith/perl/ch-1.pl
I've left my original solution around - I've also written a script that goes through a dictionary and finds and displays all isomorphic words....
=> Completely different solution to ch-1.. which I think is incredibly neat

challenge-092/nunovieira220/js/ch-1.js, challenge-092/nunovieira220/js/ch-2.js, challenge-092/nunovieira220/perl/ch-1.pl, challenge-092/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 092.
=> Add solution to challenge 092

challenge-092/alexander-pankoff/perl/ch-1.pl, challenge-092/alexander-pankoff/perl/ch-2.pl
My solutions in perl for the current challenge.
=> Challenge 092

challenge-092/polettix/blog.txt, challenge-092/polettix/blog1.txt, challenge-092/polettix/perl/ch-1.pl, challenge-092/polettix/perl/ch-2.pl
Hi Mohammad, thanks for your hard working. Please find my contribution for this week's challenge.
I hope you and your loved ones are all safe!
=> Add polettix's solution to 092

challenge-092/ziameraj16/README.md, challenge-092/ziameraj16/java/IsomorphicStrings.java
To compile the code run
```java
javac IsomorphicStrings.java
```
To run
```java
java IsomorphicStrings
```
```bash
/perlweeklychallenge-club/challenge-092/ziameraj16/java$ javac IsomorphicStrings.java
Note: IsomorphicStrings.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/perlweeklychallenge-club/challenge-092/ziameraj16/java$ java IsomorphicStrings
Enter first string
xyz
Enter second string
abc
Output: 1
```
=> Java solution of Isomorphic Strings

challenge-092/aaronreidsmith/blog.txt, challenge-092/aaronreidsmith/raku/ch-1.raku, challenge-092/aaronreidsmith/raku/ch-2.raku
Challenge 92 solutions in Raku
=> Challenge 92 - Raku

challenge-092/cheok-yin-fung/perl/ch-1.pl, challenge-092/cheok-yin-fung/perl/ch-2.pl
=> submission to challenge 092

challenge-027/stuart-little/README, challenge-027/stuart-little/raku/ch-1.p6, challenge-027/stuart-little/raku/ch-2.p6
Last one for `raku`! I guess I'd better find another language to redo all of the challenges in :D.
Thank you for the patience and encouragement @manwar !
=> 1st commit on 027

challenge-092/kordaff/README, challenge-092/kordaff/perl/ch-1.pl
=> challenge-092 #1 solution

challenge-092/duncan-c-white/README, challenge-092/duncan-c-white/perl/ch-1.pl, challenge-092/duncan-c-white/perl/ch-2.pl
I ran out of time to do the intervals one in an elegant way, I know there is one but couldn't quite see it, so instead I did it the totally dumb way: build a number line: an array x[] of booleans, setting each x[i] to true when i is part of an interval, either an existing interval or the new one, then walk the @x array to produce the minimal number of intervals.  of course the @x array automatically does the merging for us.  this, btw, merges even more intervals than your examples do.
=> imported my solutions to this week's challenge..

challenge-093/polettix/blog.txt, challenge-093/polettix/blog1.txt, challenge-093/polettix/perl/ch-1.pl, challenge-093/polettix/perl/ch-2.pl
Hi! This is my contribution for this week. Thanks for all the hard work.
I wish you and your loved ones a Happy New Year!
=> Add polettix's solutions to PWC093

challenge-093/dave-jacoby/perl/ch-1.pl, challenge-093/dave-jacoby/perl/ch-2.pl, challenge-093/dave-jacoby/perl/ch-2b.pl
ch-2b is a better solution, I think but I wrote ch-2 already, so there it is.
=> Challenge 93

.gitignore, challenge-093/paulo-custodio/basic/ch-1.bas, challenge-093/paulo-custodio/basic/ch-2.bas, challenge-093/paulo-custodio/c/ch-1.c, challenge-093/paulo-custodio/c/ch-2.c, challenge-093/paulo-custodio/cpp/ch-1.cpp, challenge-093/paulo-custodio/cpp/ch-2.cpp, challenge-093/paulo-custodio/forth/ch-1.fs, challenge-093/paulo-custodio/forth/ch-2.fs, challenge-093/paulo-custodio/perl/ch-1.pl, challenge-093/paulo-custodio/perl/ch-2.pl, challenge-093/paulo-custodio/test.pl
=> Add Perl, Basic, Forth, C and C++ solutions to challenge 093

challenge-093/nunovieira220/js/ch-1.js, challenge-093/nunovieira220/js/ch-2.js, challenge-093/nunovieira220/perl/ch-1.pl, challenge-093/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 093.
=> Add solution to challenge 093

challenge-004/paulo-custodio/perl/ch-2.pl, challenge-004/paulo-custodio/test.pl, challenge-005/paulo-custodio/README, challenge-005/paulo-custodio/perl/ch-1.pl, challenge-005/paulo-custodio/perl/ch-2.pl, challenge-005/paulo-custodio/test.pl
and remove one-letter solutions from challenge 004 task 2
=> Add Perl solution to challenge 005

challenge-093/duncan-c-white/README, challenge-093/duncan-c-white/perl/ch-1.pl, challenge-093/duncan-c-white/perl/ch-2.pl
first task interesting, I felt I wasn't seeing an elegant way to do it, but easy enough to do it the brute force way; the second task looks like a retread of challenge 56's task 2, so I reused most of the binary tree representation and input parsing from last time..  nice..
=> committed my solutions to this week's tasks..

challenge-093/cheok-yin-fung/perl/ch-1.pl, challenge-093/cheok-yin-fung/perl/ch-2.pl
Hey don't miss my submission~ :D
=> CY's submission for Challenge 093

challenge-093/cheok-yin-fung/perl/ch-1.pl
The time complexity of the case should be O(n log n), not as ideal as O(n)
=> Update ch-1.pl of Challenge 093

challenge-094/simon-proctor/raku/ch-1.raku
Here's part one (I really enjoyed having some time off but back on things ;) ) 
I'll take a look at part 2.
=> First part done

challenge-094/e-choroba/perl/ch-1.pl, challenge-094/e-choroba/perl/ch-2.pl
Group Anagrams & Binary Tree to Linked List
=> Add solutions to 094 by E. Choroba

challenge-094/wlmb/blog.txt, challenge-094/wlmb/perl/ch-1.pl, challenge-094/wlmb/perl/ch-2.pl
=> Add solutions to challenge 094

challenge-094/polettix/blog.txt, challenge-094/polettix/blog1.txt, challenge-094/polettix/perl/ch-1.pl, challenge-094/polettix/perl/ch-2.pl
Hi, and happy new year!
Here is my contribution for this week's challenge. Blog posts are on their way.
Thanks for all the hard work!
=> Add polettix's solution to PWC094

challenge-094/nunovieira220/js/ch-1.js, challenge-094/nunovieira220/js/ch-2.js, challenge-094/nunovieira220/perl/ch-1.pl, challenge-094/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 094.
=> Add solution to challenge 094

challenge-094/wlmb/perl/ch-2.pl, challenge-094/wlmb/perl/ch-2a.pl
I made a small change the the program for challenge 94, task 2, ch-2.pl, but I tried an alternate solution which I named ch-2a.pl. I don't know if there is some standard naming scheme when more than one solution to a task is submitted. 
Regards,
Luis
=> Challenges

challenge-094/aaronreidsmith/blog.txt, challenge-094/aaronreidsmith/raku/ch-1.raku, challenge-094/aaronreidsmith/raku/ch-2.raku
=> Week 94 - Raku

challenge-094/mimosinnet/raku/ch-1.raku, challenge-094/mimosinnet/raku/ch-2.raku
Thanks for the challenge! I have really struggled with the second one and I have had to use Luca Ferrary to be able to solve it. Superb Raku exercise! Thanks!
=> Mimosinnet raku solution

challenge-094/duncan-c-white/README, challenge-094/duncan-c-white/perl/ch-1.pl, challenge-094/duncan-c-white/perl/ch-2.pl
loved the anagram groups task as good old Bell Labs alumni Jon Bentley tackled precisely this problem in the wonderful book "Programming Pearls".  Core concept: signatures: the sorted bag of letters contained in a word.  All words that contain the same letters necessarily have the same signature.
=> imported my solutions to challenge 94

challenge-095/polettix/blog.txt, challenge-095/polettix/blog1.txt, challenge-095/polettix/perl/ch-1.pl, challenge-095/polettix/perl/ch-2.pl
Hi! Please find my contributions for PWC 095.
Blog posts are on their way.
I hope everything's fine, thank you very much!
=> Add polettix's solution to PWC095

challenge-094/wlmb/perl/ch-1.pl, challenge-094/wlmb/perl/ch-2.pl, challenge-094/wlmb/perl/ch-2a.pl, challenge-095/wlmb/blog.txt, challenge-095/wlmb/perl/ch-1.pl, challenge-095/wlmb/perl/ch-1a.pl, challenge-095/wlmb/perl/ch-2.pl
=> Add solutions to challenge 95: 1 (1a) and 2

challenge-094/pavel_kuptsov/perl/ch-1.pl, challenge-094/pavel_kuptsov/perl/ch-2.pl
task 1 and lazy sol for task 2 :)
=> Solution 094

challenge-095/nunovieira220/js/ch-1.js, challenge-095/nunovieira220/js/ch-2.js, challenge-095/nunovieira220/perl/ch-1.pl, challenge-095/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 095.
=> Add solution to challenge 095

challenge-001/mfoda/README, challenge-001/mfoda/nim/ch1.nim
Solution file is named `ch1.nim` as nim doesn't allow hyphens in module/file names.
=> Add ch-1 in nim

challenge-001/mfoda/haxe/Ch1.hx, challenge-001/mfoda/haxe/Ch2.hx
As close as possible to a one-liner in haxe xd
=> Add mfoda-001-haxe

challenge-001/mfoda/nim/ch2.nim
=> Add mfoda-001-ch2-nim

challenge-095/mimosinnet/raku/ch-1.raku, challenge-095/mimosinnet/raku/ch-2.raku
=> Solution for challenge-095

challenge-095/duncan-c-white/README, challenge-095/duncan-c-white/perl/ch-1.pl, challenge-095/duncan-c-white/perl/ch-2.pl
=> imported this week's solutions - two easy questions this week

challenge-096/polettix/blog.txt, challenge-096/polettix/blog1.txt, challenge-096/polettix/perl/ch-1.pl, challenge-096/polettix/perl/ch-2.pl
Thank you for the hard work! I tried to toss a monthly coffee in Patreon 😁 
Blog posts on their way as usual.
=> Add polettix's solution to PWC096

challenge-096/e-choroba/perl5/ch-1.pl, challenge-096/e-choroba/perl5/ch-2a.pl, challenge-096/e-choroba/perl5/ch-2b.pl
Edit Distance is solved both by Text::Levenshtein and my own
implementation.
=> Add solutions to 096: Reverse Words and Edit Distance by E. Choroba

challenge-096/ziameraj16/java/EditDistance.java, challenge-096/ziameraj16/java/ReverseWords.java
Java Solution for Challenge 96
=> Java Solution for Challenge 96

challenge-096/mimosinnet/blog.txt, challenge-096/mimosinnet/raku/ch-1.raku, challenge-096/mimosinnet/raku/ch-2.raku
I am thrilled to have been able to solve the second exercise with Raku OOP. Thanks a lot for the challenges! It is an excellent way to learn and practice raku.
=> Solutions for challenge 096

challenge-096/nunovieira220/js/ch-1.js, challenge-096/nunovieira220/js/ch-2.js, challenge-096/nunovieira220/perl/ch-1.pl, challenge-096/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 096.
=> Add solution to challenge 096

challenge-097/wlmb/blog.txt, challenge-097/wlmb/perl/ch-1.pl, challenge-097/wlmb/perl/ch-2.pl
=> Solutions to challenge 97

challenge-067/cheok-yin-fung/smalltalk/ch-2.st, challenge-095/cheok-yin-fung/smalltalk/ch-1.st, challenge-096/cheok-yin-fung/smalltalk/ch-1.st, challenge-097/cheok-yin-fung/smalltalk/ch-1.st
067_task2, 095_task1, 096_task1, 097_task1
=> Add a new guest languuage!

challenge-097/polettix/blog.txt, challenge-097/polettix/blog1.txt, challenge-097/polettix/perl/ch-1.pl, challenge-097/polettix/perl/ch-2.pl
Thank you for your hard work!!!
The second blog post is on its way...
=> Add polettix's solution to PWC097

challenge-097/alexander-pankoff/perl/ch-1.pl, challenge-097/alexander-pankoff/perl/ch-2.pl
My solutions for the current challenge. I'm happy to be back after a month of inactivity.
=> Challenge 097

challenge-097/aaronreidsmith/blog.txt, challenge-097/aaronreidsmith/raku/ch-1.raku, challenge-097/aaronreidsmith/raku/ch-2.raku
=> Challenge 97 - Raku

challenge-093/cheok-yin-fung/perl/ch-1.pl, challenge-097/cheok-yin-fung/perl/ch-2.pl
093 task 1: correction
097 task 2: removal of unnecessary variables
=> correction and improvement

challenge-096/sgreen/README.md, challenge-097/sgreen/README.md, challenge-097/sgreen/blog.txt, challenge-097/sgreen/perl/ch-1.pl, challenge-097/sgreen/perl/ch-2.pl
Done with a little less than 11 hours remaining :)
Hopefully will be back on schedule next week.
=> sgreen solution to challenge 097

challenge-097/nunovieira220/js/ch-1.js, challenge-097/nunovieira220/js/ch-2.js, challenge-097/nunovieira220/perl/ch-1.pl, challenge-097/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 097.
=> Add solution to challenge 097

challenge-097/duncan-c-white/README, challenge-097/duncan-c-white/perl/ch-1.pl, challenge-097/duncan-c-white/perl/ch-2.pl
enjoyed the Caesar cipher, the second task could have been rather more clearly specified, I hope I understood what it meant to do, fun to code anyway.
=> imported my solution's to this week's challenge

challenge-097/kai-burgdorf/perl/ch-1.pl, challenge-097/kai-burgdorf/perl/ch-2.pl
=> perl solution for week 97

challenge-098/dave-jacoby/blog.txt, challenge-098/dave-jacoby/perl/ch-1a.pl, challenge-098/dave-jacoby/perl/ch-1b.pl, challenge-098/dave-jacoby/perl/ch-2.pl
You coming up with some interesting ones for 100?
=> Challenge 98!

challenge-098/polettix/blog.txt, challenge-098/polettix/blog1.txt, challenge-098/polettix/perl/ch-1.pl, challenge-098/polettix/perl/ch-2.pl
Hi! These are my contributions to the 98th Perl Weekly Challenge. Thank you for all your dedication 😁
=> Add polettix's solution to PWC098

challenge-098/wlmb/blog.txt, challenge-098/wlmb/perl/ch-1.pl, challenge-098/wlmb/perl/ch-2.pl
=> Solutions to challenge 98

challenge-062/stuart-little/haskell/ch-1.hs, challenge-062/stuart-little/haskell/ch-2.hs
=> 1st commit on 062_haskell

challenge-098/nunovieira220/js/ch-1.js, challenge-098/nunovieira220/js/ch-2.js, challenge-098/nunovieira220/perl/ch-1.pl, challenge-098/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 098.
=> Add solution to challenge 098

challenge-098/frankivo/scala/SearchInsertPosition.scala
I'm happy that the function is a one-liner again :)
=> SearchInsertPosition

challenge-098/aaronreidsmith/blog.txt, challenge-098/aaronreidsmith/raku/ch-1.raku, challenge-098/aaronreidsmith/raku/ch-2.raku
Challenge 98 solutions in Raku
=> Challenge 98 - Raku

challenge-098/cheok-yin-fung/perl/ch-2.pl
a binary search tree for Task 2
oh haven't learnt File I/O properly and have no ideas for Task 1
=> CY's submission for 098

challenge-098/alexander-pankoff/perl/ch-1.pl, challenge-098/alexander-pankoff/perl/ch-2.pl
My solutions for last weeks challenge.
=> Challenge 098

challenge-099/wlmb/blog.txt, challenge-099/wlmb/perl/ch-1.pl, challenge-099/wlmb/perl/ch-2.pl
=> Solutions to ch. 99

challenge-099/polettix/blog.txt, challenge-099/polettix/blog1.txt, challenge-099/polettix/perl/ch-1.pl, challenge-099/polettix/perl/ch-2.pl
Hi, please find my contribution for PWC099.
Have a good time and thanks for all your work!
=> Add polettix's solutions to PWC099

challenge-099/nunovieira220/js/ch-1.js, challenge-099/nunovieira220/js/ch-2.js, challenge-099/nunovieira220/perl/ch-1.pl, challenge-099/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 099.
=> Add solution to challenge 099

challenge-098/james-smith/blog.txt, challenge-099/james-smith/blog.txt, challenge-099/james-smith/perl/ch-2.pl
Add blog links, add some comments - and include timings to show speeds of each fn.
=> tidied up and docs and blog links

challenge-097/james-smith/perl/ch-2.pl
Re-golfed challenge 2 from week 97.
The body of the function for ch-2.pl golfed so the code inside the function has been reduced to 145 characters from around 200
=> some better golfing - over 30% shorter solution for ch-2.pl

challenge-099/aaronreidsmith/blog.txt, challenge-099/aaronreidsmith/raku/ch-1.raku, challenge-099/aaronreidsmith/raku/ch-2.raku
Challenge 99 solutions in Raku
=> Challenge 99 - Raku

challenge-099/athanasius/perl/ch-1.pl, challenge-099/athanasius/perl/ch-2.pl, challenge-099/athanasius/raku/ch-1.raku, challenge-099/athanasius/raku/ch-2.raku
On branch branch-for-challenge-099
new file:   challenge-099/athanasius/perl/ch-1.pl
new file:   challenge-099/athanasius/perl/ch-2.pl
new file:   challenge-099/athanasius/raku/ch-1.raku
new file:   challenge-099/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #099

challenge-099/alexander-pankoff/perl/ch-1.pl, challenge-099/alexander-pankoff/perl/ch-2.pl
=> Challenge 099

challenge-099/mimosinnet/raku/ch-1.raku, challenge-099/mimosinnet/raku/ch-2.raku
Thanks for the challenge. Ready for challenge 100!  Tanks!
=> Solution for challenge 099

challenge-099/x1mandi/perl/ch1.pl
Hi Mohammad,
I apologize for the delay, this is my solution for last weeks challenge task#1.
I hope You will still accept it.
Kind regards,
Csaba
=> My solution to challenge 99/task#1

challenge-100/james-smith/blog.txt, challenge-100/james-smith/perl/ch-1.pl, challenge-100/james-smith/perl/ch-2.pl
Blog link is there - but will write write that later!
=> solutions to challenge 100 - nice to give me a one liner <g>!

challenge-100/simon-proctor/raku/ch-1.raku, challenge-100/simon-proctor/raku/ch-2.raku
Covering all the edge case and stuff :)
=> Challenge 1... bit more that 1 line

challenge-100/vinod-k/perl/ch-1.pl
Solution for challenge 100 - Task#1
=> Solution for challenge 100 - Task#1

challenge-100/wlmb/blog.txt, challenge-100/wlmb/perl/ch-1.pl, challenge-100/wlmb/perl/ch-2.pl
=> Solutions to challenge 100

challenge-100/frankivo/scala/TriangleSum.scala
It isn't much if you leave out the String garbage :P
=> TriangleSum

challenge-100/polettix/blog.txt, challenge-100/polettix/blog1.txt, challenge-100/polettix/perl/ch-1.pl, challenge-100/polettix/perl/ch-2.pl
Hi, here's my contribution for this week.
Congratulations for having made it to 💯 !!!
=> Add polettix's solutions to PWC100

challenge-100/lance-wicks/blog.txt
Adding a blog post :-)
Next I'll try a new language... hope I can learn it and get it submitted. :-)
=> Link to blog post for 100th

challenge-100/yet-ebreo/perl/ch-1.pl, challenge-100/yet-ebreo/perl/ch-2.pl
Hello :D
Added perl solution for ch100
=> Added solution for ch100

challenge-100/markjreed/README, challenge-100/markjreed/perl/ch-1.sh, challenge-100/markjreed/raku/ch-2.p6
My solutions to challenge #100.
=> markjreed solutions to challenge 100

challenge-100/lance-wicks/blog.txt, challenge-100/lance-wicks/perl/ch-2.pl, challenge-100/lance-wicks/perl/lib/Triangle.pm, challenge-100/lance-wicks/perl/t/2-triangle.t
=> Challenge 2 - Perl

challenge-100/aaronreidsmith/blog.txt, challenge-100/aaronreidsmith/raku/ch-1.raku, challenge-100/aaronreidsmith/raku/ch-2.raku
Challenge 100 solutions in Raku
=> Challenge 100 - Raku

challenge-100/athanasius/perl/ch-2.pl, challenge-100/athanasius/raku/ch-2.raku
On branch branch-for-challenge-100
new file:   challenge-100/athanasius/perl/ch-2.pl
new file:   challenge-100/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Task 2 of the Perl Weekly Challenge #100

challenge-100/alexander-pankoff/perl/ch-1.pl, challenge-100/alexander-pankoff/perl/ch-2.pl
My solution for the current challenge
=> Challenge 100

challenge-096/paulo-custodio/ada/ch_1.adb, challenge-096/paulo-custodio/ada/ch_2.adb, challenge-096/paulo-custodio/basic/ch-2.bas, challenge-096/paulo-custodio/c/ch-2.c, challenge-096/paulo-custodio/cpp/ch-2.cpp, challenge-096/paulo-custodio/forth/ch-2.fs, challenge-096/paulo-custodio/lua/ch-2.lua, challenge-096/paulo-custodio/perl/ch-2.pl, challenge-096/paulo-custodio/perl/ch-2a.pl, challenge-096/paulo-custodio/python/ch-2.py, challenge-096/paulo-custodio/t/test-2.yaml
Simplify all the other solutions: output only the number of steps, as requested, and not the list of steps.
=> Add Ada solution to challenge 096

challenge-100/kai-burgdorf/perl/ch-1.pl, challenge-100/kai-burgdorf/perl/ch-2.pl
=> solution for week 100

challenge-100/mimosinnet/raku/ch-1.raku, challenge-100/mimosinnet/raku/ch-2.raku
Solution for challenge 100. Thanks.
=> Solution for challenge 100

challenge-100/jaldhar-h-vyas/blog.txt, challenge-100/jaldhar-h-vyas/perl/ch-1.pl, challenge-100/jaldhar-h-vyas/perl/ch-2.pl, challenge-100/jaldhar-h-vyas/raku/ch-1.raku, challenge-100/jaldhar-h-vyas/raku/ch-2.raku
Aaargh almost forgot to submit this.
=> Challenge 100 by Jaldhar H. Vyas

challenge-101/wlmb/blog.txt, challenge-101/wlmb/perl/ch-1.pl, challenge-101/wlmb/perl/ch-1a.pl, challenge-101/wlmb/perl/ch-2.pl
=> Add solutions to challenge 101

challenge-101/aaronreidsmith/blog.txt, challenge-101/aaronreidsmith/raku/ch-1.raku, challenge-101/aaronreidsmith/raku/ch-2.raku
Challenge 101 solutions in Raku
=> Challenge 101 - Raku

challenge-101/athanasius/perl/ch-1.pl, challenge-101/athanasius/perl/ch-2.pl, challenge-101/athanasius/raku/ch-1.raku, challenge-101/athanasius/raku/ch-2.raku
On branch branch-for-challenge-101
new file:   challenge-101/athanasius/perl/ch-1.pl
new file:   challenge-101/athanasius/perl/ch-2.pl
new file:   challenge-101/athanasius/raku/ch-1.raku
new file:   challenge-101/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #101

challenge-102/wlmb/blog.txt, challenge-102/wlmb/perl/ch-1.pl, challenge-102/wlmb/perl/ch-1a.pl, challenge-102/wlmb/perl/ch-1b.pl, challenge-102/wlmb/perl/ch-2.pl
=> Add solutions to challenge 102 1, 1a and 2

challenge-102/james-smith/blogs.txt, challenge-102/james-smith/perl/ch-1.pl
Done some optimization - still in the order-of-magnitude of minutes for the more complex ones...
Applied a lot of filtering based on possible values for some of the digits, and the fact that the digit sum is restricted to certain values
Lots of screaming!...!
=> First one is nasty this time {well at least trying to find an efficient solution}

challenge-102/mimosinnet/raku/ch-1.raku, challenge-102/mimosinnet/raku/ch-2.raku
Thanks for the challenge. Learned a lot with challenge 1, and I had to look at other solutions to be able to solve it. Still, I am unsure this is the right approach. Good to practice recursion with challenge 2. Cheers!
=> Solution for challenge 102

challenge-102/athanasius/perl/ch-1.pl, challenge-102/athanasius/perl/ch-2.pl, challenge-102/athanasius/raku/ch-1.raku, challenge-102/athanasius/raku/ch-2.raku
On branch branch-for-challenge-102
new file:   challenge-102/athanasius/perl/ch-1.pl
new file:   challenge-102/athanasius/perl/ch-2.pl
new file:   challenge-102/athanasius/raku/ch-1.raku
new file:   challenge-102/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #102

challenge-102/maxim-kolodyazhny/perl/ch-2.pl, challenge-102/maxim-kolodyazhny/perl/lib/HashCounting.pm, challenge-102/maxim-kolodyazhny/perl/t/HashCounting.t
Hello! My long journey has ended, and I'm glad that finally I can send commit to PWC :3
=> Solution for challenge 102, Task 2 by k-mx

challenge-102/aaronreidsmith/blog.txt, challenge-102/aaronreidsmith/raku/ch-1.raku, challenge-102/aaronreidsmith/raku/ch-2.raku
Challenge 102 solutions in Raku
=> Challenge 102 - Raku

challenge-102/duncan-c-white/OptimizingTask1, challenge-102/duncan-c-white/README, challenge-102/duncan-c-white/perl/ch-1.pl, challenge-102/duncan-c-white/perl/ch-1a.pl, challenge-102/duncan-c-white/perl/ch-1b.pl, challenge-102/duncan-c-white/perl/ch-1c.pl, challenge-102/duncan-c-white/perl/ch-1d.pl, challenge-102/duncan-c-white/perl/ch-1e.pl, challenge-102/duncan-c-white/perl/ch-1f.pl, challenge-102/duncan-c-white/perl/ch-1g.pl, challenge-102/duncan-c-white/perl/ch-1h.pl, challenge-102/duncan-c-white/perl/ch-1i.pl, challenge-102/duncan-c-white/perl/ch-2.pl, challenge-102/duncan-c-white/perl/run.sh
SEE ALSO OptimizingTask1 for an account of a series of profiling-driven optimizations that I made to speed up finding rare numbers.  Overall, my fastest version ran approx 18 times faster than the original.
=> imported my solution's to this week's tasks

challenge-103/lance-wicks/perl/ch-1.pl, challenge-103/lance-wicks/perl/lib/Zodiac.pm, challenge-103/lance-wicks/perl/t/00-zodiac.t
Thanks @manwar I enjoyed this one. Learnt a little Chinese culture along the way. :-)
=> Add perl solution

challenge-103/polettix/blog.txt, challenge-103/polettix/blog1.txt, challenge-103/polettix/perl/ch-1.pl, challenge-103/polettix/perl/ch-2.pl, challenge-103/polettix/perl/filelist.csv
Hi! Please consider my contribution for this week's challenge.
Thanks for the hard work and have a nice week!
=> Add polettix's solution to PWC103

challenge-103/mimosinnet/raku/ch-1.raku, challenge-103/mimosinnet/raku/ch-2.raku, challenge-103/mimosinnet/raku/filelist.csv
Great challenge! Thanks a lot!
=> Solution for challenge 103

challenge-103/aaronreidsmith/blog.txt, challenge-103/aaronreidsmith/raku/ch-1.raku, challenge-103/aaronreidsmith/raku/ch-2.raku
Challenge 103 solutions in Raku
=> Challenge 103 - Raku

challenge-103/lance-wicks/blog.txt, challenge-103/lance-wicks/elm/elm.json, challenge-103/lance-wicks/elm/src/Zodiac.elm, challenge-103/lance-wicks/elm/tests/Zodiac_test.elm
Cheating a little @manwar as this is just a module and not console executable.
=> Add elm solution

challenge-103/athanasius/perl/ch-1.pl, challenge-103/athanasius/perl/ch-2.pl, challenge-103/athanasius/perl/filelist.csv, challenge-103/athanasius/raku/ch-1.raku, challenge-103/athanasius/raku/ch-2.raku, challenge-103/athanasius/raku/filelist.csv
On branch branch-for-challenge-103
new file:   challenge-103/athanasius/perl/ch-1.pl
new file:   challenge-103/athanasius/perl/ch-2.pl
new file:   challenge-103/athanasius/perl/filelist.csv
new file:   challenge-103/athanasius/raku/ch-1.raku
new file:   challenge-103/athanasius/raku/ch-2.raku
new file:   challenge-103/athanasius/raku/filelist.csv
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #103

challenge-101/polettix/blog.txt, challenge-101/polettix/blog1.txt
I forgot to add my blog post links in 101's contribution - what a shame, I lost the precious feedback from Colin Crain!
=> Add polettix's blog posts for PWC101

challenge-104/cheok-yin-fung/perl/ch-1.pl, challenge-104/cheok-yin-fung/perl/ch-2.pl
=> 2 Perl scripts

challenge-104/aaronreidsmith/blog.txt, challenge-104/aaronreidsmith/raku/ch-1.raku, challenge-104/aaronreidsmith/raku/ch-2.raku
Challenge 104 solutions in Raku
=> Challenge 104 - Raku

challenge-104/mimosinnet/raku/ch-1.raku, challenge-104/mimosinnet/raku/ch-2.raku
Solution for challenge 104. Great fun! Thanks!
=> Solution for challenge 104

challenge-104/duncan-c-white/README, challenge-104/duncan-c-white/perl/ch-1.pl, challenge-104/duncan-c-white/perl/ch-2.pl
but please note that TASK 2 WAS NOT NIM.  It's the "simple take away game".  Nim is played on multiple piles, with a single move being to take away ANY NUMBER of tokens from a single pile, and the winning solution involves reducing the xor-sum of the number of tokens on all piles to zero after your move.
=> imported my solutions to this week's tasks.. two nice questions

challenge-104/cheok-yin-fung/perl/ch-1.pl
no wonder why the seq terms were such small from my code
=> fix a serious bug! ... after deadline

challenge-105/james-smith/perl/ch-1.pl, challenge-105/james-smith/perl/ch-2.pl
1.  not using ** or log, but a "modified" binary search...
2.  with starting vowels & consonant and b/f/m rules applied
=> added in first pass

challenge-102/duncan-c-white/perl/ch-1.pl, challenge-102/duncan-c-white/perl/ch-1i.pl
=> (update to challenge 102): fixed a bug in ch-1i.pl and added a mention of OptimizingTask1 to ch-1a.pl

challenge-105/polettix/blog.txt, challenge-105/polettix/blog1.txt, challenge-105/polettix/perl/ch-1.pl, challenge-105/polettix/perl/ch-2.pl
Hi! Please find my contribution for PWC 105.
If you need me to rebase... please tell me - I see GitHub says that it's OK to merge it as-is though.
Cheers, Flavio.
=> Add polettix's solution to PWC105

challenge-105/aaronreidsmith/blog.txt, challenge-105/aaronreidsmith/raku/ch-1.raku, challenge-105/aaronreidsmith/raku/ch-2.raku
Challenge 105 solutions in Raku
=> Challenge 105 - Raku

challenge-105/duncan-c-white/README, challenge-105/duncan-c-white/perl/ch-1.pl, challenge-105/duncan-c-white/perl/ch-2.pl
not much to get excited about this weeks, nthroot was simple but dull, and the children's rhyme has no real clear rules, so doesn't deserve a deep solution
=> imported this week's solutions

challenge-106/aaronreidsmith/blog.txt, challenge-106/aaronreidsmith/raku/ch-1.raku, challenge-106/aaronreidsmith/raku/ch-2.raku
Challenge 106 solutions in Raku
=> Challenge 106 - Raku

challenge-106/wlmb/blog.txt, challenge-106/wlmb/perl/ch-1.pl, challenge-106/wlmb/perl/ch-2.pl
=> Add solutions to PWC 106

challenge-106/polettix/blog.txt, challenge-106/polettix/blog1.txt, challenge-106/polettix/perl/ch-1.pl, challenge-106/polettix/perl/ch-2.pl
Hi! Please find my takes on this week's challenges.
Thank you very much for all the hard work :grin:
=> Add polettix's solution to challenge-106

challenge-106/lance-wicks/perl/ch-1.pl, challenge-106/lance-wicks/perl/lib/Maxgap.pm, challenge-106/lance-wicks/perl/t/01-max_gap.t
Streamed at https://www.twitch.tv/videos/969893599
=> Add Perl solution for 106

challenge-106/athanasius/perl/ch-1.pl, challenge-106/athanasius/perl/ch-2.pl, challenge-106/athanasius/raku/ch-1.raku, challenge-106/athanasius/raku/ch-2.raku
On branch branch-for-challenge-106
new file:   challenge-106/athanasius/perl/ch-1.pl
new file:   challenge-106/athanasius/perl/ch-2.pl
new file:   challenge-106/athanasius/raku/ch-1.raku
new file:   challenge-106/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #106

challenge-106/mimosinnet/raku/ch-1.raku, challenge-106/mimosinnet/raku/ch-2.raku
Thanks for the challenge! Very nice to learn new methods like "base-repeating". Cheers!
=> Solutions to challenge 106

challenge-107/wlmb/blog.txt, challenge-107/wlmb/perl/Calc.pm, challenge-107/wlmb/perl/ch-1.pl, challenge-107/wlmb/perl/ch-1a.pl, challenge-107/wlmb/perl/ch-2.pl
=> Add solution to challenge 107

challenge-107/e-choroba/perl/ch-1.pl, challenge-107/e-choroba/perl/ch-2.pl, challenge-107/e-choroba/perl/lib/Calc.pm
Reuse 043 for the solution of Self-descriptive Numbers.
=> Add solution to 107: List Methods by E. Choroba

challenge-106/jaldhar-h-vyas/blog.txt, challenge-106/jaldhar-h-vyas/perl/ch-1.pl, challenge-106/jaldhar-h-vyas/perl/ch-2.pl, challenge-106/jaldhar-h-vyas/raku/ch-1.raku, challenge-106/jaldhar-h-vyas/raku/ch-2.raku
=> Challenge 106 by Jaldhar H. Vyas

challenge-106/duncan-c-white/README, challenge-106/duncan-c-white/perl/ch-1.pl, challenge-106/duncan-c-white/perl/ch-2.pl
Hi, I completely forgot to do challenge 106 yesterday, late submission..
=> imported last week's solutions (after forgetting to do it yesterday)

challenge-107/polettix/blog.txt, challenge-107/polettix/blog1.txt, challenge-107/polettix/perl/Calc.pm, challenge-107/polettix/perl/ch-1.pl, challenge-107/polettix/perl/ch-2.pl
Hi! Thanks for keeping this alive since so much time!
=> Add polettix's solution to challenge-107

challenge-107/mimosinnet/raku/ch-1.raku, challenge-107/mimosinnet/raku/ch-2.raku
Thanks very much for the challenges. Task #2 on methods and classes has been quite formative for those who are not so used to classes and methods. Great!
=> Solutions for challenge 107

challenge-107/aaronreidsmith/blog.txt, challenge-107/aaronreidsmith/raku/ch-1.raku, challenge-107/aaronreidsmith/raku/ch-2.raku
Challenge 107 solutions in Raku.
=> Challenge 107 - Raku

challenge-107/athanasius/perl/ch-1.pl, challenge-107/athanasius/raku/ch-1.raku
On branch branch-for-challenge-107
new file:   challenge-107/athanasius/perl/ch-1.pl
new file:   challenge-107/athanasius/raku/ch-1.raku
=> Perl & Raku solutions to Task 1 of the Perl Weekly Challenge #107

challenge-108/aaronreidsmith/blog.txt, challenge-108/aaronreidsmith/raku/ch-1.raku, challenge-108/aaronreidsmith/raku/ch-2.raku
Challenge 108 solutions in Raku
=> Challenge 108 - Raku

challenge-001/lakpatashi/README, challenge-001/lakpatashi/perl/ch-1.pl, challenge-001/lakpatashi/perl/ch-2.pl
=> challenge 1 finished.

challenge-002/lakpatashi/perl/ch-1.pl, challenge-002/lakpatashi/perl/ch-2.pl, challenge-003/lakpatashi/README
Thanks for the check manwar.
This is the correct submission.
=> Revision to challenge #002 perl

challenge-003/lakpatashi/ch-1.pl, challenge-003/lakpatashi/ch-2.pl
=> challenge-003 finished in perl

challenge-004/lakpatashi/README, challenge-004/lakpatashi/perl/ch-1.pl, challenge-004/lakpatashi/perl/ch-2.pl, challenge-004/lakpatashi/perl/inputFile
=> Finished challenge-004 with perl

challenge-108/perlboy1967/perl/ch-2.pl
Bit of a rush job between some real (paid) work.
- Added commandline argument
- Make use of array to store the triangle
- Do all index math using $_ or magical indexes (-1,-2)
=> I realized the code wasn't as clean as I wanted it to be.

challenge-005/lakptashi/README, challenge-005/lakptashi/perl/ch-1.pl, challenge-005/lakptashi/perl/ch-2.pl
=> Finished challenge-005 with perl

challenge-006/lakpatashi/README, challenge-006/lakpatashi/perl/ch-1.pl, challenge-006/lakpatashi/perl/ch-2.pl
=> Finished challenge-006 with perl

challenge-007/lakpatashi/README, challenge-007/lakpatashi/perl/ch-1.pl
=> Finished challenge-007 ch-1 only with perl

challenge-007/lakpatashi/README, challenge-007/lakpatashi/perl/ch-1.pl, challenge-008/lakpatashi/README, challenge-008/lakpatashi/perl/ch-1.pl, challenge-008/lakpatashi/perl/ch-2.pl
=> Finished challenge-008 with perl

challenge-009/lakpatashi/README, challenge-009/lakpatashi/perl/ch-1.pl, challenge-009/lakpatashi/perl/ch-2.pl
=> Finished challenge-009 with perl

challenge-108/athanasius/perl/ch-1.pl, challenge-108/athanasius/perl/ch-2.pl, challenge-108/athanasius/raku/ch-2.raku
On branch branch-for-challenge-108
new file:   challenge-108/athanasius/perl/ch-1.pl
new file:   challenge-108/athanasius/perl/ch-2.pl
new file:   challenge-108/athanasius/raku/ch-2.raku
=> Perl solution only to Task 1, and Perl & Raku solutions to Task 2, of the Perl Weekly Challenge #108

challenge-010/lakpatashi/README, challenge-010/lakpatashi/perl/ch-1.pl
=> Finished challenge-010 ch-1 only with perl

challenge-011/lakpatashi/README, challenge-011/lakpatashi/perl/ch-1.pl, challenge-011/lakpatashi/perl/ch-2.pl
=> Finished challenge-011 with perl

challenge-108/duncan-c-white/README, challenge-108/duncan-c-white/perl/ch-1.pl, challenge-108/duncan-c-white/perl/ch-2.pl
2 very simple tasks this week.. not much to get my teeth into.
=> imported my attempts this week

challenge-108/mimosinnet/raku/ch-1.raku, challenge-108/mimosinnet/raku/ch-2.raku
As I was unable to solve the second challenge, I have had a look to Aaron Smith solution. Brilliant! It is great to see the different approaches to solve the challenges. Thanks very much for the challenges!
=> Solutions for challenge 108

challenge-109/sgreen/README.md, challenge-109/sgreen/perl/ch-1.pl, challenge-109/sgreen/perl/ch-2.pl
I'll write the blog later in the week
=> sgreen solution to challenge 109

challenge-012/lakpatashi/README, challenge-012/lakpatashi/perl/ch-1.pl, challenge-012/lakpatashi/perl/ch-2.pl
=> Finished challenge-012 with perl

challenge-109/polettix/blog.txt, challenge-109/polettix/blog1.txt, challenge-109/polettix/perl/ch-1.pl, challenge-109/polettix/perl/ch-2.pl
Thanks for last week's submission, you're too kind!
This week's blogs are on their way to be published within the week.
Cheers!
=> Add polettix's solution to challenge-109

challenge-109/dave-jacoby/blog.txt, challenge-109/dave-jacoby/node/ch-1.js, challenge-109/dave-jacoby/perl/ch-1.pl, challenge-109/dave-jacoby/perl/ch-2.pl
Might go back and do the boxes in Node or Python later.
=> Challenge 109 in Perl and (some) JS, Blogged

challenge-109/brtastic/blog.txt
Just wanted to add in a blog post link. Thanks!
=> Blog post link for challenge 109

challenge-109/aaronreidsmith/blog.txt, challenge-109/aaronreidsmith/raku/ch-1.raku, challenge-109/aaronreidsmith/raku/ch-2.raku
Challenge 109 solutions in Raku
=> Challenge 109 - Raku

challenge-109/mimosinnet/raku/ch-1.raku, challenge-109/mimosinnet/raku/ch-2.raku
Managed to finish the challenges with help from Mark Anderson's solution. Thanks for the challenges! Ramadan Mubarak.
=> Solutions for challenge 109

challenge-108/cheok-yin-fung/perl/ch-2.pl, challenge-109/cheok-yin-fung/blog.txt, challenge-109/cheok-yin-fung/java/Box.java, challenge-109/cheok-yin-fung/java/NBoxesJavaFX.java, challenge-109/cheok-yin-fung/java/Point.java, challenge-109/cheok-yin-fung/perl/ch-1.pl, challenge-109/cheok-yin-fung/perl/ch-2.pl
2 Perl scripts , Java source codes for Task 2, a blogpost
=> Submission for Week 109

challenge-109/maxim-kolodyazhny/raku/ch-2.raku
=> Challenge 109 part 2 by Maxim Kolodyazhny

challenge-109/maxim-kolodyazhny/raku/ch-2.raku
+space separated arguments list
P.S. Sory, I'm late ):
=> Improvement for ch-2.raku by Maxim Kolodyazhny

challenge-110/polettix/blog.txt, challenge-110/polettix/blog1.txt, challenge-110/polettix/perl/ch-1.pl, challenge-110/polettix/perl/ch-2.pl
Hi! Thanks for keeping this up!
Blog posts are on their way... stay safe :grin:
=> Add polettix's solution to challenge-110

challenge-110/ryan-thompson/README.md, challenge-110/ryan-thompson/perl/ch-1.pl, challenge-110/ryan-thompson/perl/ch-2.pl, challenge-110/ryan-thompson/raku/ch-1.raku, challenge-110/ryan-thompson/raku/ch-2.raku
Hooray! I finally had some free time.
=> Ryan's week 110 solutions

challenge-110/perlboy1967/perl/ch-2a.pl
Based on solutions provided by other teammembers their '[split/,/]' usage.
=> Added a minimalistic solution for Task 2

challenge-110/wlmb/blog.txt, challenge-110/wlmb/perl/ch-1.pl, challenge-110/wlmb/perl/ch-2.pl, challenge-110/wlmb/perl/ch-2a.pl
=> Add solutions to challenge 110

challenge-110/aaronreidsmith/blog.txt, challenge-110/aaronreidsmith/raku/ch-1.raku, challenge-110/aaronreidsmith/raku/ch-2.raku
Challenge 110 solutions in Raku
=> Challenge 110 - Raku

challenge-013/lakpatashi/README, challenge-013/lakpatashi/perl/ch-1.pl, challenge-013/lakpatashi/perl/ch-2.pl
=> Finished challenge-013 with perl

challenge-013/lakpatashi/README, challenge-013/lakpatashi/perl/ch-1.pl, challenge-013/lakpatashi/perl/ch-2.pl, challenge-014/lakpatashi/README, challenge-014/lakpatashi/perl/ch-1.pl
=> Finished challenge-014 with perl

challenge-013/lakpatashi/README, challenge-013/lakpatashi/perl/ch-1.pl, challenge-013/lakpatashi/perl/ch-2.pl, challenge-014/lakpatashi/README, challenge-014/lakpatashi/perl/ch-1.pl, challenge-015/lakpatashi/README, challenge-015/lakpatashi/perl/ch-1.pl, challenge-015/lakpatashi/perl/ch-2.pl
=> Finished challenge-015 with perl

challenge-110/ryan-thompson/blog.txt, challenge-110/ryan-thompson/blog1.txt
I was wondering why you kept hoping I was going to blog, when I'd already done it! :-)
=> Whoops, forgot to link the blogs from last week.

challenge-111/wlmb/blog.txt, challenge-111/wlmb/perl/ch-1.pl, challenge-111/wlmb/perl/ch-2.pl, challenge-111/wlmb/perl/ch-2a.pl
=> Add solutions to PWC 111

challenge-111/perlboy1967/perl/ch-2.pl
After some benchmarking I came to the conclusion split is faster.
=> Move from 'unpack' back to split('').

challenge-111/polettix/blog.txt, challenge-111/polettix/blog1.txt, challenge-111/polettix/perl/ch-1.pl, challenge-111/polettix/perl/ch-2.pl
Hi! Thanks for keeping up with the excellent work.
Please find this week's PR - blog posts are already up.
=> Add polettix's solution to challenge-111

challenge-109/abigail/README.md, challenge-109/abigail/mmix/ch-1.mms
MMIX solution for week 109, part1
=> MMIX solution for week 109, part 1

challenge-111/aaronreidsmith/blog.txt, challenge-111/aaronreidsmith/raku/ch-1.raku, challenge-111/aaronreidsmith/raku/ch-2.raku
Challenge 111 solutions in Raku
=> Challenge 111 - Raku

challenge-013/cheok-yin-fung/README.md, challenge-013/cheok-yin-fung/java/LastFriday.java, challenge-013/cheok-yin-fung/perl/ch-1.pl, challenge-019/cheok-yin-fung/README.md, challenge-019/cheok-yin-fung/java/FiveWeekends.java, challenge-019/cheok-yin-fung/perl/ch-1.pl, challenge-038/cheok-yin-fung/README.md, challenge-038/cheok-yin-fung/java/DateFinder.java, challenge-038/cheok-yin-fung/perl/ch-1.pl
Perl and Java codes on Task 1's  of  Week 13, 19 and 38
=> Practice date and time stuff

challenge-016/lakpatashi/README, challenge-016/lakpatashi/perl/ch-1.pl
=> Finished challenge-016 ch-1 only with perl

challenge-016/lakpatashi/README, challenge-016/lakpatashi/perl/ch-1.pl, challenge-017/lakpatashi/README, challenge-017/lakpatashi/perl/ch-1.pl
=> Finished Challenge 017 ch-1 only with perl

challenge-111/dms061/perl/ch-1-example.txt, challenge-111/dms061/perl/ch-1.pl, challenge-111/dms061/perl/ch-2-example.txt, challenge-111/dms061/perl/ch-2.pl, challenge-111/dms061/python3/ch-2-example.txt, challenge-111/dms061/python3/ch-2.py, challenge-111/dms061/readme
Here is my submission for week 111. This is my first time submitting. Thanks for running the challenge and for the detailed readme on how to participate!
=> Perl Weekly Challenge 111 submission

challenge-018/lakpatashi/README, challenge-018/lakpatashi/perl/ch-1.pl, challenge-019/lakpatashi/README, challenge-019/lakpatashi/perl/ch-2.pl
=> Finished Challenge 019, ch-2 only with perl

challenge-018/lakpatashi/README, challenge-018/lakpatashi/perl/ch-1.pl, challenge-019/lakpatashi/README, challenge-019/lakpatashi/perl/ch-2.pl, challenge-020/lakpatashi/README, challenge-020/lakpatashi/perl/ch-1.pl, challenge-020/lakpatashi/perl/ch-2.pl
=> Finished Challenge-020 with perl

challenge-112/polettix/blog.txt, challenge-112/polettix/blog1.txt, challenge-112/polettix/perl/ch-1.pl, challenge-112/polettix/perl/ch-2.pl
Hi! Here are my contributions for this week. Thanks for all!!!
=> Add polettix's solution to challenge-112

challenge-112/james-smith/perl/ch-1.pl
"Optimal" code is just 74 characters long...
=> added optimal string method

challenge-021/lakpatashi/README, challenge-021/lakpatashi/perl/ch-1.pl
=> Finished challenge-021 ch-1 only with perl

challenge-112/wlmb/blog.txt, challenge-112/wlmb/perl/ch-1.pl, challenge-112/wlmb/perl/ch-2.pl, challenge-112/wlmb/perl/ch-2a.pl, challenge-112/wlmb/perl/ch-2b.pl
=> Solutions to challenge 112

challenge-112/kurkale6ka/perl/ch-1.pl
Hi, I see I was too slow to add this :)
=> Add human readable version

challenge-112/aaronreidsmith/blog.txt, challenge-112/aaronreidsmith/raku/ch-1.raku, challenge-112/aaronreidsmith/raku/ch-2.raku
Challenge 112 solutions in Raku
=> Challenge 112 - Raku

challenge-112/athanasius/perl/ch-1.pl, challenge-112/athanasius/perl/ch-2.pl, challenge-112/athanasius/raku/ch-1.raku, challenge-112/athanasius/raku/ch-2.raku
On branch branch-for-challenge-112
new file:   challenge-112/athanasius/perl/ch-1.pl
new file:   challenge-112/athanasius/perl/ch-2.pl
new file:   challenge-112/athanasius/raku/ch-1.raku
new file:   challenge-112/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #112

challenge-112/tyler-wardhaugh/clojure/README.md, challenge-112/tyler-wardhaugh/clojure/deps.edn, challenge-112/tyler-wardhaugh/clojure/src/tw/weekly/c112/core.clj, challenge-112/tyler-wardhaugh/clojure/src/tw/weekly/c112/t1.clj, challenge-112/tyler-wardhaugh/clojure/src/tw/weekly/c112/t2.clj, challenge-112/tyler-wardhaugh/clojure/test/tw/weekly/c112_test.clj
I'm back! And I'll be sending my interview later today.
=> Ch112: Tasks 1 & 2

challenge-022/lakpatashi/README, challenge-022/lakpatashi/perl/ch-1.pl
=> Finished challenge-022 ch-1 only with perl

challenge-022/lakpatashi/README, challenge-022/lakpatashi/perl/ch-1.pl, challenge-023/lakpatashi/README, challenge-023/lakpatashi/perl/ch-1.pl, challenge-023/lakpatashi/perl/ch-2.pl
=> Finished challenge-023 with perl

challenge-112/mimosinnet/raku/ch-1.raku, challenge-112/mimosinnet/raku/ch-2.raku
Solutions for this week contest!  I really like Roger Well West solution to challenge 2! Cheers!
=> Solutions for challenge 112

challenge-112/duncan-c-white/README, challenge-112/duncan-c-white/perl/ch-1.pl, challenge-112/duncan-c-white/perl/ch-2.pl
=> imported my solutions to this week's tasks

challenge-113/dave-jacoby/perl/ch-1.pl, challenge-113/dave-jacoby/perl/ch-2.pl
=> Coded While Sleepy. Might return to fix.

challenge-113/polettix/blog.txt, challenge-113/polettix/blog1.txt, challenge-113/polettix/perl/ch-1.pl, challenge-113/polettix/perl/ch-2.pl
Hi! Please find my week's contribution to PWC. Thank you for the hard work and for donating me so many ideas for new posts :wink:
=> Add polettix's solution to challenge-113

challenge-113/cheok-yin-fung/blog.txt, challenge-113/cheok-yin-fung/perl/ch-1.pl, challenge-113/cheok-yin-fung/perl/ch-2.pl
=> submission for Week 113

challenge-113/ben-davies/raku/ch-2.raku
Nits as far as the challenge is concerned.
=> Revise Ben Davies' solution to part 2 of challenge 113

challenge-113/aaronreidsmith/blog.txt, challenge-113/aaronreidsmith/raku/ch-1.raku, challenge-113/aaronreidsmith/raku/ch-2.raku
Challenge 113 solutions in Raku
=> Challenge 113 - Raku

challenge-113/wlmb/blog.txt, challenge-113/wlmb/perl/ch-1.pl, challenge-113/wlmb/perl/ch-1a.pl, challenge-113/wlmb/perl/ch-2.pl
=> Solutions to pwc 113

challenge-113/mimosinnet/raku/ch-1.raku, challenge-113/mimosinnet/raku/ch-2.raku
Solutions for this week! Great to learn and practice Raku functions. Thanks a lot!
=> Solutions for challenge 113

challenge-113/polettix/raku/ch-1.raku, challenge-113/polettix/raku/ch-2.raku
Hi! I decided to give Raku a try... and here's my almost-literal translation of the Perl code into it. It's a start!
Thank you for your hard work, Flavio.
=> Add polettix's solutions for Raku

challenge-114/wlmb/blog.txt, challenge-114/wlmb/perl/ch-1.pl, challenge-114/wlmb/perl/ch-2.pl
=> Solutions to PWC114

challenge-114/polettix/blog.txt, challenge-114/polettix/blog1.txt, challenge-114/polettix/perl/ch-1.pl, challenge-114/polettix/perl/ch-2.pl, challenge-114/polettix/raku/ch-1.raku, challenge-114/polettix/raku/ch-2.raku
Hi! Please find my contributions for this week's challenge. Thank you so much 😀
=> Add polettix's solution to challenge-114

challenge-114/lance-wicks/perl/lib/Palindrome.pm, challenge-114/lance-wicks/perl/t/00-palindrome.t
Hey!
Back after some busy busy weeks!
Celebrating the long weekend with some Friday evening Perl. :)
=> Lance joins the fun once again

challenge-114/mimosinnet/raku/ch-1.raku, challenge-114/mimosinnet/raku/ch-2.raku
Done! Fascinated by the possibility of writing code like this in Raku. 
`($number^..^∞).grep({ $_ eq $_.flip }).first;`
Thaks!
=> Solutions for challenge 114

challenge-114/athanasius/perl/ch-1.pl, challenge-114/athanasius/perl/ch-2.pl, challenge-114/athanasius/raku/ch-1.raku, challenge-114/athanasius/raku/ch-2.raku
On branch branch-for-challenge-114
new file:   challenge-114/athanasius/perl/ch-1.pl
new file:   challenge-114/athanasius/perl/ch-2.pl
new file:   challenge-114/athanasius/raku/ch-1.raku
new file:   challenge-114/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #114

challenge-114/cheok-yin-fung/perl/ch-1.pl, challenge-114/cheok-yin-fung/perl/ch-2.pl
=> submission for week 114

challenge-114/christian-jaeger/blog.txt, challenge-114/christian-jaeger/haskell/Makefile, challenge-114/christian-jaeger/perl/ch-1.pl
Only one solution due to lack of time.
=> Add solutions and post

challenge-115/sgreen/README.md, challenge-115/sgreen/blog.txt, challenge-115/sgreen/perl/ch-1.pl, challenge-115/sgreen/perl/ch-2.pl
Second time lucky hopefully :)
=> sgreen solution to challenge 115

challenge-115/wlmb/blog.txt, challenge-115/wlmb/perl/ch-1.pl, challenge-115/wlmb/perl/ch-2.pl
=> Add solutions to PWC115

challenge-115/polettix/blog.txt, challenge-115/polettix/blog1.txt, challenge-115/polettix/perl/ch-1.pl, challenge-115/polettix/perl/ch-2.pl, challenge-115/polettix/raku/ch-1.raku, challenge-115/polettix/raku/ch-2.raku
Hi! Please find my contribution for this week's challenge... and thanks again!
=> Add polettix's solution to challenge-115

challenge-115/wlmb/perl/ch-1a.pl
=> Add new solution to task 1

challenge-115/athanasius/perl/ch-2.pl, challenge-115/athanasius/raku/ch-2.raku
On branch branch-for-challenge-115
new file:   challenge-115/athanasius/perl/ch-2.pl
new file:   challenge-115/athanasius/raku/ch-2.raku
=> Perl & Raku solutions for Task 2 of the Perl Weekly Challenge #115

challenge-115/mimosinnet/raku/ch-1.raku, challenge-115/mimosinnet/raku/ch-2.raku
Arrived on time! :) Thanks for the challenge! :)
=> Solutions for challenge 115

challenge-116/simon-proctor/raku/ch-1.raku, challenge-116/simon-proctor/raku/ch-2.raku
Was on holiday last week but I'm back on it :)
=> Challenge 116

challenge-116/polettix/blog.txt, challenge-116/polettix/blog1.txt, challenge-116/polettix/perl/ch-1.pl, challenge-116/polettix/perl/ch-2.pl, challenge-116/polettix/raku/ch-1.raku, challenge-116/polettix/raku/ch-2.raku
Hi! Here's my contribution for this week's challenge. Blog posts are on their way to be published...
Thanks for all your hard and excellent work!
=> Add polettix's solution to challenge-116

challenge-115/aaronreidsmith/blog.txt, challenge-115/aaronreidsmith/raku/ch-1.raku, challenge-115/aaronreidsmith/raku/ch-2.raku, challenge-116/aaronreidsmith/blog.txt, challenge-116/aaronreidsmith/raku/ch-1.raku, challenge-116/aaronreidsmith/raku/ch-2.raku
Had a busy weekend and didn't get to push challenge 115 over the weekend so I just rolled my 116 solutions into the same branch.
=> Challenges 115 & 116 - Raku

challenge-116/perlboy1967/perl/ch-1.pl, challenge-116/perlboy1967/perl/ch-2.pl
- Task 1: More informative print statement
- Task 2: Replace isIntSqr with more straightforward version (no caching)
=> Small updates

challenge-116/james-smith/README.md, challenge-116/james-smith/perl/ch-1.pl
Added some code so more efficient in large number cases!
=> Optimizations

challenge-116/wlmb/blog.txt, challenge-116/wlmb/perl/ch-1.pl, challenge-116/wlmb/perl/ch-2.pl
=> Add solutions to PWC116

challenge-116/athanasius/perl/ch-1.pl, challenge-116/athanasius/perl/ch-2.pl, challenge-116/athanasius/raku/ch-1.raku, challenge-116/athanasius/raku/ch-2.raku
On branch branch-for-challenge-116
new file:   challenge-116/athanasius/perl/ch-1.pl
new file:   challenge-116/athanasius/perl/ch-2.pl
new file:   challenge-116/athanasius/raku/ch-1.raku
new file:   challenge-116/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #116

challenge-116/duncan-c-white/README, challenge-116/duncan-c-white/perl/ch-1.pl, challenge-116/duncan-c-white/perl/ch-2.pl
fortunate as I didn't have much time this week..
=> imported my solutions to this week's challenge.. two easy tasks..

challenge-117/luc65r/README, challenge-117/luc65r/input.txt, challenge-117/luc65r/raku/ch-1.raku, challenge-117/luc65r/raku/ch-2.raku
My first challenge, I hope I'm doing this right
=> Challenge 117

challenge-117/polettix/blog.txt, challenge-117/polettix/blog1.txt, challenge-117/polettix/ch-1.input, challenge-117/polettix/perl/ch-1.pl, challenge-117/polettix/perl/ch-2.pl, challenge-117/polettix/raku/ch-1.raku, challenge-117/polettix/raku/ch-2.raku
Hi! Please find my contribution for PWC 117.
Thanks for your dedication :grin:
=> Add polettix's solution to challenge-117

challenge-117/luc65r/zig/ch-1.zig, challenge-117/luc65r/zig/ch-2.zig
As I saw other languages in the repo, I did it in Zig
=> Challenge 117 in Zig

challenge-117/athanasius/perl/Example.txt, challenge-117/athanasius/perl/ch-1.pl, challenge-117/athanasius/perl/ch-2.pl, challenge-117/athanasius/raku/Example.txt, challenge-117/athanasius/raku/ch-1.raku, challenge-117/athanasius/raku/ch-2.raku
On branch branch-for-challenge-117
new file:   challenge-117/athanasius/perl/Example.txt
new file:   challenge-117/athanasius/perl/ch-1.pl
new file:   challenge-117/athanasius/perl/ch-2.pl
new file:   challenge-117/athanasius/raku/Example.txt
new file:   challenge-117/athanasius/raku/ch-1.raku
new file:   challenge-117/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #117

challenge-117/aaronreidsmith/raku/ch-1.raku
I only had time for part 1 this week; maybe I will come back and do part 2, but figured I would submit what I have! 🎉
=> Challenge 117 (Part 1) - Raku

challenge-117/e-choroba/perl5/ch-1.pl, challenge-117/e-choroba/perl5/ch-2.pl
In the POD of the second task, I explain why the task origianlly
requested the number of paths instead of their list.
=> Add solutions to 115: Missing Row & Find Possible Paths

challenge-118/e-choroba/perl/ch-1.pl, challenge-118/e-choroba/perl/ch-2.pl
The second task is solved using A* with a simple heuristic: the number
of treasures to pick up. Try commenting out the line that adds it to the
score to see its effect.
=> Add solutions to 118: Binary Palindrome & Adventure of Knight

challenge-117/frankivo/scala/LineFinder.scala
=> LineFinder

challenge-118/luc65r/nix/ch-1.nix, challenge-118/luc65r/nix/ch-2.nix
Nix isn't the most suitable language for tasks like these, but it works
=> Challenge 118 Nix

challenge-118/wlmb/blog.txt, challenge-118/wlmb/perl/ch-1.pl, challenge-118/wlmb/perl/ch-2.pl
=> Add solutions to challenge 118

challenge-118/cheok-yin-fung/perl/ch-1.pl, challenge-118/cheok-yin-fung/perl/ch-2.pl, challenge-118/cheok-yin-fung/perl/pre-ch-2.pl
but maybe some people out there are eager and curious to the problem creator's approach
=> the codes are not in their best shapes

challenge-118/athanasius/perl/ch-1.pl, challenge-118/athanasius/raku/ch-1.raku
On branch branch-for-challenge-118
new file:   challenge-118/athanasius/perl/ch-1.pl
new file:   challenge-118/athanasius/raku/ch-1.raku
=> Perl & Raku solutions to Task 1 of the Perl Weekly Challenge #118

challenge-118/duncan-c-white/README, challenge-118/duncan-c-white/perl/ch-1.pl, challenge-118/duncan-c-white/perl/ch-2.pl
second task (knight's moves) was surprisingly hard.. sorry I missed last week's, was away on holiday
=> imported challenge 118 solutions (hour and a half late)

challenge-119/polettix/blog.txt, challenge-119/polettix/blog1.txt, challenge-119/polettix/perl/ch-1.pl, challenge-119/polettix/perl/ch-2.pl, challenge-119/polettix/raku/ch-1.raku, challenge-119/polettix/raku/ch-2.raku
Hi! Please find a pull request for my solution to PWC 119.
Thanks for keeping this up!
=> Add polettix's solution to challenge-119

challenge-119/lance-wicks/perl/ch-1.pl, challenge-119/lance-wicks/perl/lib/Nibble.pm, challenge-119/lance-wicks/perl/t/01-nibble.t
I did a live stream too. :)
https://www.twitch.tv/videos/1075491044
=> Simple (unsafe) solution to task 1

challenge-119/lance-wicks/perl/ch-2.pl, challenge-119/lance-wicks/perl/lib/Sequence.pm, challenge-119/lance-wicks/perl/t/02-seq.t
I thought that would be harder. Pretty simplistic approach but seems to work. :)
=> Task 2 in Perl

challenge-105/mimosinnet/raku/ch-1.raku, challenge-105/mimosinnet/raku/ch-2.raku, challenge-119/mimosinnet/raku/ch-1.raku, challenge-119/mimosinnet/raku/ch-2.raku
I have moved house and have not been able to keep the challenges up to date. Let's see if I can make up for the lost fun! I include solutions for challenge 105 and 109. Thank you!
=> Branch for challenge 119

challenge-119/luc65r/myrddin/ch-1.myr, challenge-119/luc65r/myrddin/ch-2.myr, challenge-119/luc65r/raku/ch-1.raku, challenge-119/luc65r/raku/ch-2.raku
=> Challenge 119

challenge-119/duncan-c-white/README, challenge-119/duncan-c-white/perl/ch-1.pl, challenge-119/duncan-c-white/perl/ch-2.pl
.. both thankfully easy after last week's Knight's adventure question..
=> imported my solutions to challenge-119's two tasks..

challenge-120/roger-bell-west/perl/ch-1.pl, challenge-120/roger-bell-west/perl/ch-2.pl, challenge-120/roger-bell-west/python/ch-1.py, challenge-120/roger-bell-west/python/ch-2.py, challenge-120/roger-bell-west/raku/ch-1.p6, challenge-120/roger-bell-west/raku/ch-2.p6, challenge-120/roger-bell-west/ruby/ch-1.rb, challenge-120/roger-bell-west/ruby/ch-2.rb, challenge-120/roger-bell-west/rust/ch-1.rs, challenge-120/roger-bell-west/rust/ch-2.rs
Hope you're feeling better now!
=> Solutions for challenge #120

challenge-120/polettix/blog.txt, challenge-120/polettix/blog1.txt, challenge-120/polettix/perl/ch-1.pl, challenge-120/polettix/perl/ch-2.pl, challenge-120/polettix/raku/ch-1.raku, challenge-120/polettix/raku/ch-2.raku
Hi! Please find my contribution for this week's challenge. Blog posts are on their way.
Thank you for the hard work, Mohammad!
=> Add polettix's solution to challenge-120

challenge-120/cheok-yin-fung/bash/ch-1.sh, challenge-120/cheok-yin-fung/bash/ch-2.sh, challenge-120/cheok-yin-fung/perl/ch-1.pl, challenge-120/cheok-yin-fung/perl/ch-2.pl
2 Perl scripts, 2 bash scripts
=> Submission for Week 120

challenge-120/simon-proctor/raku/ch-1.raku, challenge-120/simon-proctor/raku/ch-2.raku
=> Challenge 120

challenge-121/cheok-yin-fung/perl/ch-2.pl
Submit a brute-force solution; 
don't understand how to apply A* search, BFS, etc. (all advanced algorithms in wk 118) in this task;
maybe someone would like to have some handy test data for $N > 10 .
=> Task 2 via Brute Force

challenge-121/wlmb/blog.txt, challenge-121/wlmb/perl/ch-1.pl, challenge-121/wlmb/perl/ch-2-helper.pl, challenge-121/wlmb/perl/ch-2.pl, challenge-121/wlmb/perl/ch-2a.pl, challenge-121/wlmb/perl/ch-2b.pl
=> Solutions to PWC121

challenge-121/perlboy1967/perl/ch-2.pl
Using libraries:
* MCE;
* Algorithm::Combinatorics qw(permutations);
* List::MoreUtils qw(slide);
* List::Util qw(sum min);
=> Task 2 - Fun using brute force solution

challenge-121/polettix/blog.txt, challenge-121/polettix/blog1.txt, challenge-121/polettix/perl/ch-1.pl, challenge-121/polettix/perl/ch-2.pl, challenge-121/polettix/raku/ch-1.raku, challenge-121/polettix/raku/ch-2.raku
Hi! Please find my contributions for this week's challenge.
Thank you for all your hard work!
=> Add polettix's solution to challenge-121

challenge-121/jdos22/README, challenge-121/jdos22/perl/ch-1.pl
=> jdos22 challenge for Challenge 1.

challenge-121/duncan-c-white/README, challenge-121/duncan-c-white/perl/ch-1.pl
=> only had a go at task 1 this time; not in the mood for TSP tonight

challenge-119/mattneleigh/README, challenge-119/mattneleigh/perl/ch-1.pl, challenge-119/mattneleigh/perl/ch-2.pl, challenge-120/mattneleigh/README, challenge-120/mattneleigh/perl/ch-1.pl, challenge-120/mattneleigh/perl/ch-2.pl, challenge-121/mattneleigh/README, challenge-121/mattneleigh/perl/ch-1.pl, challenge-121/mattneleigh/perl/ch-2.pl
new file:   challenge-119/mattneleigh/perl/ch-1.pl
new file:   challenge-119/mattneleigh/perl/ch-2.pl
new file:   challenge-120/mattneleigh/README
new file:   challenge-120/mattneleigh/perl/ch-1.pl
new file:   challenge-120/mattneleigh/perl/ch-2.pl
new file:   challenge-121/mattneleigh/README
new file:   challenge-121/mattneleigh/perl/ch-1.pl
new file:   challenge-121/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-119/mattneleigh/README

challenge-121/sgreen/README.md, challenge-121/sgreen/perl/ch-1.pl
=> sgreen solution to challenge 121, task 1

challenge-121/jaldhar-h-vyas/blog.txt, challenge-121/jaldhar-h-vyas/perl/ch-1.sh, challenge-121/jaldhar-h-vyas/raku/ch-1.sh
Unfortunately I was really low on time so this is only the first challenge.  I'll try to do the other one tomorrow.
=> Challenge 121 part 1 by Jaldhar H. Vyas.

challenge-122/polettix/blog.txt, challenge-122/polettix/blog1.txt, challenge-122/polettix/perl/ch-1.pl, challenge-122/polettix/perl/ch-2.pl, challenge-122/polettix/raku/ch-1.raku, challenge-122/polettix/raku/ch-2.raku
Hi! Please consider my contributions for this week's challenge.
Thank you for the time and dedication!
=> Add polettix's solution to challenge-122

challenge-122/sgreen/blog.txt, challenge-122/sgreen/perl/ch-1.pl, challenge-122/sgreen/perl/ch-2.pl
It always helps if I add new the files to my git repo. Sorry about that.
=> sgreen solution to challenge 122

challenge-122/duncan-c-white/README, challenge-122/duncan-c-white/perl/ch-1.pl, challenge-122/duncan-c-white/perl/ch-2.pl
BTW, I think there was a bug in task 2? - surely there was one more solution to $S = 5: "3 2"?  that's how I've coded it up, anyway.
=> imported my solutions to this week's challenges

challenge-122/mattneleigh/perl/ch-1.pl, challenge-122/mattneleigh/perl/ch-2.pl
new file:   challenge-122/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-122/mattneleigh/perl/ch-1.pl

challenge-123/sgreen/README.md, challenge-123/sgreen/blog.txt, challenge-123/sgreen/perl/ch-1.pl, challenge-123/sgreen/perl/ch-2.pl
I remembered to run git add this week :) #winning
=> sgreen solution to challenge 123

challenge-123/perlboy1967/perl/ch-2.pl
And add equilateral triangle check :: Thanks to James Curtis-Smith
=> Task 2  - Check diffently distance frequency count

challenge-123/wlmb/blog.txt, challenge-123/wlmb/perl/ch-1.pl, challenge-123/wlmb/perl/ch-2.pl
=> Add solutions to PWC123

challenge-123/simon-proctor/raku/ch-2.raku
Updated Challenge 2 to make it a bit less verbose.
=> Reducing code by making more Rakuish

challenge-123/polettix/blog.txt, challenge-123/polettix/blog1.txt, challenge-123/polettix/perl/ch-1.pl, challenge-123/polettix/perl/ch-2.pl, challenge-123/polettix/raku/ch-1.raku, challenge-123/polettix/raku/ch-2.raku
Hi! This is my contribution for PWC 123. Thank you for keeping this up!
=> Add polettix's solution to challenge-123

challenge-123/mattneleigh/perl/ch-1.pl, challenge-123/mattneleigh/perl/ch-2.pl
new file:   challenge-123/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-123/mattneleigh/perl/ch-1.pl

challenge-124/sgreen/README.md, challenge-124/sgreen/blog.txt, challenge-124/sgreen/perl/ch-2.pl
=> sgreen solution to task 2 challenge 124

challenge-124/bruce-gray/perl/ch-1.pl, challenge-124/bruce-gray/perl/ch-2.pl, challenge-124/bruce-gray/raku/ch-1.raku, challenge-124/bruce-gray/raku/ch-2.raku, challenge-124/bruce-gray/svg/ch-1.svg
=> Add Raku and Perl (and SVG for first task) solutions for #124 by Bruce Gray

challenge-124/wlmb/blog.txt, challenge-124/wlmb/perl/ch-1.pl, challenge-124/wlmb/perl/ch-2.pl, challenge-124/wlmb/perl/ch-2a.pl
=> Add solutions to PWC124

challenge-124/mattneleigh/perl/ch-1.pl
Only did Challenge 1 this week.
=> 	new file:   challenge-124/mattneleigh/perl/ch-1.pl

challenge-124/duncan-c-white/README, challenge-124/duncan-c-white/perl/ch-1.pl, challenge-124/duncan-c-white/perl/ch-2.pl
I enjoyed the second task; I'm not at all that my way is "the best way", or even a "reasonably good way"; but it's a simple way to do:-)
=> imported solutions to this week's challenge tasks

challenge-124/jaredor/blog.txt, challenge-124/jaredor/perl/ch-1.pl
Here you go, @manwar, I might even be a minute early! :-D
=> solution for TWC 124, task 1

challenge-125/simon-proctor/raku/ch-1.raku, challenge-125/simon-proctor/raku/ch-2.raku
And my BTree Role is getting it's own repo now :)
=> Challenge 125 all done

challenge-125/wlmb/blog.txt, challenge-125/wlmb/perl/ch-1.pl, challenge-125/wlmb/perl/ch-2.pl
=> Solve PWC125

challenge-125/polettix/blog.txt, challenge-125/polettix/blog1.txt, challenge-125/polettix/perl/ch-1.pl, challenge-125/polettix/perl/ch-2.pl, challenge-125/polettix/raku/ch-1.raku, challenge-125/polettix/raku/ch-2.raku
Hi! Please find my contribution for this week's challenge. Blog posts are on their way.
Thank you so much for your dedication!
=> Add polettix's solution to challenge-125

challenge-125/cheok-yin-fung/perl/ch-1.pl, challenge-125/cheok-yin-fung/perl/ch-2.pl
=> submission for Week 125

challenge-125/cheok-yin-fung/perl/ch-1.pl
=> improve submission

challenge-125/mattneleigh/perl/ch-1.pl, challenge-125/mattneleigh/perl/ch-2.pl
new file:   challenge-125/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-125/mattneleigh/perl/ch-1.pl

challenge-125/mimosinnet/raku/ch-1.raku, challenge-125/mimosinnet/raku/ch-2.raku
Manage to have the solutions for this week! :) Thanks! :)
=> Solutions for challenge 125

challenge-125/duncan-c-white/README, challenge-125/duncan-c-white/perl/ch-1.pl, challenge-125/duncan-c-white/perl/ch-2.pl
The first task was surprisingly tricky given the problem of when to STOP generating Pythagorean Triples, and the second task was reasonably straightforward once I decided how to represent the tree this time to make it easy to traverse "up" to a node's parent, or left or right.
=> imported my solutions to this week's challenge - both quite tricky

challenge-126/ash/raku/ch-1.raku
It adds a better Raku mechanisms for multiple "if" branches.
=> use given/when

challenge-126/simon-proctor/raku/ch-2.raku
(I'll probably add one to read in a map at some point)
=> Challenge 2 with random maps

challenge-126/polettix/blog.txt, challenge-126/polettix/blog1.txt, challenge-126/polettix/perl/ch-1.pl, challenge-126/polettix/perl/ch-2.pl, challenge-126/polettix/raku/ch-1.raku, challenge-126/polettix/raku/ch-2.raku
Hi! Please find attached my contribution for PWC 126. Thanks for everything!
=> Add polettix's solution to challenge-126

challenge-126/mattneleigh/perl/ch-1.pl, challenge-126/mattneleigh/perl/ch-2.pl
new file:   challenge-126/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-126/mattneleigh/perl/ch-1.pl

challenge-126/wlmb/blog.txt, challenge-126/wlmb/perl/ch-1.pl, challenge-126/wlmb/perl/ch-2.pl
=> Solve challenge 126

challenge-126/andrezgz/perl/ch-1.pl, challenge-126/andrezgz/perl/ch-1.sh, challenge-126/andrezgz/perl/ch-2.pl
Hi @manwar, I'm back for this week's challenge :)
=> challenge-126 andrezgz solution

challenge-126/wlmb/perl/ch-2.pl
=> Simplify code

challenge-126/mimosinnet/raku/2, challenge-126/mimosinnet/raku/ch-1.raku, challenge-126/mimosinnet/raku/ch-2.raku
Manage to get here! Thanks for the challenge! Cheers! :)
=> Solutions for challenge 126

challenge-127/wlmb/blog.txt, challenge-127/wlmb/perl/ch-1.pl, challenge-127/wlmb/perl/ch-2.pl
=> Solve pwc127

challenge-127/polettix/blog.txt, challenge-127/polettix/blog1.txt, challenge-127/polettix/perl/ch-1.pl, challenge-127/polettix/perl/ch-2.pl, challenge-127/polettix/raku/ch-1.raku, challenge-127/polettix/raku/ch-2.raku
Thank you so much for keeping this going, I think you're the real champion week after week.
=> Add polettix's solution to challenge-127

challenge-127/mimosinnet/raku/ch-1.raku, challenge-127/mimosinnet/raku/ch-2.raku
Thanks for the challenges! Great fun! :)
=> Solutions for challenge 127

challenge-128/polettix/blog.txt, challenge-128/polettix/blog1.txt, challenge-128/polettix/perl/ch-1.pl, challenge-128/polettix/perl/ch-2.pl, challenge-128/polettix/raku/ch-1.raku, challenge-128/polettix/raku/ch-2.raku
Hi! Please find my contribution for PWC 128. Still funny after all these weeks, thanks!
=> Add polettix's solution to challenge-128

challenge-128/wlmb/blog.txt, challenge-128/wlmb/perl/ch-1.pl, challenge-128/wlmb/perl/ch-2.pl
=> Add solutions to pwc128

challenge-128/cheok-yin-fung/blog.txt, challenge-128/cheok-yin-fung/perl/ch-1.pl, challenge-128/cheok-yin-fung/perl/ch-2.pl
=> Submission for Week 128

challenge-128/mattneleigh/perl/ch-1.pl, challenge-128/mattneleigh/perl/ch-2.pl
new file:   challenge-128/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-128/mattneleigh/perl/ch-1.pl

challenge-129/wlmb/blog.txt, challenge-129/wlmb/perl/ch-1.pl, challenge-129/wlmb/perl/ch-2.pl
=> Solve PWC 129

challenge-129/polettix/blog.txt, challenge-129/polettix/blog1.txt, challenge-129/polettix/perl/ch-1.pl, challenge-129/polettix/perl/ch-2.pl, challenge-129/polettix/raku/ch-1.raku, challenge-129/polettix/raku/ch-2.raku
Hi! Looks like it's that time in the week again... Thanks for your hard work, much appreciated!
=> Add polettix's solution to challenge-129

challenge-129/cheok-yin-fung/blog.txt, challenge-129/cheok-yin-fung/perl/ch-1.pl, challenge-129/cheok-yin-fung/perl/ch-2.pl
=> Submission for Week 129

challenge-129/mattneleigh/perl/ch-1.pl
Just did Challenge 1 this week.
=> 	new file:   challenge-129/mattneleigh/perl/ch-1.pl

challenge-130/simon-proctor/raku/ch-1.raku, challenge-130/simon-proctor/raku/ch-2.raku
=> Challenege 1

challenge-130/polettix/blog.txt, challenge-130/polettix/blog1.txt, challenge-130/polettix/perl/ch-1.pl, challenge-130/polettix/perl/ch-2.pl, challenge-130/polettix/raku/ch-1.raku, challenge-130/polettix/raku/ch-2.raku
Hi! I hope you're doing fine.
Please find my contribution for this week's challenge. Thanks for this, much appreciated (and a huge amount of work I daresay).
=> Add polettix's solution to challenge-130

challenge-130/cybersnyder/README, challenge-130/cybersnyder/perl/ch-1.pl
Trying to get started, only did #1 this time.
=> First time trying this, mostly going through the motions

challenge-130/wlmb/blog.txt, challenge-130/wlmb/perl/ch-1.pl, challenge-130/wlmb/perl/ch-2.pl
=> Add solutions to PWC130

challenge-130/conor-hoekstra/apl/ch-1.apl, challenge-130/conor-hoekstra/j/ch-1.ijs
=> Challenge 130 in APL & J

challenge-130/mattneleigh/perl/ch-1.pl, challenge-130/mattneleigh/perl/ch-2.pl
new file:   challenge-130/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-130/mattneleigh/perl/ch-1.pl

challenge-131/ziruzavar/perl/ch1.pl, challenge-131/ziruzavar/perl/ch2.pl
Both solutions for challenge 131
=> Challenge 131 by ziruzavar

challenge-131/perlboy1967/perl/ch-1.pl
* slightly condensed code
* add "no warnings 'once'"
=> Small performance change (Suggestion by Tod McQuillin)

challenge-131/wlmb/blog.txt, challenge-131/wlmb/perl/ch-1.pl, challenge-131/wlmb/perl/ch-2.pl
=> Add solutioins to PWC131

challenge-131/cybersnyder/perl/ch-1.pl, challenge-131/cybersnyder/perl/ch-2.pl
Thanks for doing these challenges!
=> Perl solutions for challenge 131, need to up my test framework game

challenge-131/mattneleigh/perl/ch-1.pl, challenge-131/mattneleigh/perl/ch-2.pl
new file:   challenge-131/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-131/mattneleigh/perl/ch-1.pl

challenge-131/iangoodnight/javascript/README.md, challenge-131/iangoodnight/javascript/ch-1.js, challenge-131/iangoodnight/javascript/ch-2.js, challenge-131/iangoodnight/perl/README.md, challenge-131/iangoodnight/perl/ch-1.pl, challenge-131/iangoodnight/perl/ch-2.pl
=> challenge 131

challenge-131/polettix/blog.txt, challenge-131/polettix/blog1.txt, challenge-131/polettix/perl/ch-1.pl, challenge-131/polettix/perl/ch-2.pl, challenge-131/polettix/raku/ch-1.raku, challenge-131/polettix/raku/ch-2.raku
Hi! Please find my contributions and my thanks for your hard work :grin:
=> Add polettix's solution to challenge-131

challenge-131/ben-davies/raku/ch-1.raku, challenge-131/ben-davies/raku/ch-2.raku
Have seen `rotor`-oriented solutions to the first challenge, but don't
depend on it here. Have not seen any solutions for the second one.
=> Add Ben Davies' Raku solutions for challenge 131

challenge-131/adam-russell/perl/ch-1.pl
not much time this week, was able to just do one part
=> Perl solution for challenge 131

challenge-132/cheok-yin-fung/java/MirrorDates.java, challenge-132/cheok-yin-fung/julia/ch-1.jl, challenge-132/cheok-yin-fung/perl/ch-1.pl
1 Java source code, 1 Julia script, 1 Perl script
=> TWC 132, Task 1 in 3 languages

challenge-132/wlmb/blog.txt, challenge-132/wlmb/perl/ch-1.pl, challenge-132/wlmb/perl/ch-2.pl
=> Add solutions to PWC132

challenge-132/ben-davies/scala/ch-1.scala, challenge-132/ben-davies/scala/ch-2.scala
The JVM can cope with this challenge fairly well.
=> Add Ben Davies' Scala 3 solutions for challenge 132

challenge-132/polettix/blog.txt, challenge-132/polettix/blog1.txt, challenge-132/polettix/perl/ch-1.pl, challenge-132/polettix/perl/ch-2.pl, challenge-132/polettix/perl/cpanfile, challenge-132/polettix/perl/cpanfile.snapshot, challenge-132/polettix/raku/ch-1.raku, challenge-132/polettix/raku/ch-2.raku
Hi! Please find my contribution for PWC 132, along with my thanks and greetings!
=> Add polettix's solution to challenge-132

challenge-132/mattneleigh/perl/ch-1.pl, challenge-132/mattneleigh/perl/ch-2.pl
new file:   challenge-132/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-132/mattneleigh/perl/ch-1.pl

challenge-133/cheok-yin-fung/perl/ch-2.pl
=> Week 133 - Task 2

challenge-133/james-raspass/raku/ch-1.raku, challenge-133/james-raspass/raku/ch-2.raku
`$large²` and `^∞` are fun uses of unicode imo.
=> 133 JRaspass

challenge-133/polettix/blog.txt, challenge-133/polettix/blog1.txt, challenge-133/polettix/perl/ch-1.pl, challenge-133/polettix/perl/ch-2.pl, challenge-133/polettix/raku/ch-1.raku, challenge-133/polettix/raku/ch-2.raku
Hi! Please find my contributions for this week's challenge. Blog posts are on their way!
Thanks!
=> Add polettix's solution to challenge-133

challenge-133/ben-davies/raku/ch-1.raku
Actually use one of the square root algorithms suggested.
=> Revise Ben Davies' challenge 133 task 1 solution

challenge-136/abigail/awk/ch-1.gawk, challenge-136/abigail/bash/ch-1.sh, challenge-136/abigail/bc/ch-1.bc, challenge-136/abigail/c/ch-1.c, challenge-136/abigail/go/ch-1.go, challenge-136/abigail/java/ch-1.java, challenge-136/abigail/lua/ch-1.lua, challenge-136/abigail/node/ch-1.js, challenge-136/abigail/pascal/ch-1.p, challenge-136/abigail/perl/ch-1.pl, challenge-136/abigail/python/ch-1.py, challenge-136/abigail/r/ch-1.r, challenge-136/abigail/ruby/ch-1.rb, challenge-136/abigail/scheme/ch-1.scm, challenge-136/abigail/tcl/ch-1.tcl
In week 136, part 1, if one or both numbers are odd, the pair
cannot be two-friendly.
=> Check for even numbers.

challenge-136/mattneleigh/perl/ch-1.pl
Only had time for Challenge 1 so far; may not have time for 2.
=> 	new file:   challenge-136/mattneleigh/perl/ch-1.pl

challenge-136/duncan-c-white/README, challenge-136/duncan-c-white/perl/ch-1.pl, challenge-136/duncan-c-white/perl/ch-2.pl
.. both pretty straightforward ones this week
=> imported my solutions to this week's challenges; two nice tasks

challenge-137/polettix/blog.txt, challenge-137/polettix/blog1.txt, challenge-137/polettix/perl/ch-1.pl, challenge-137/polettix/perl/ch-2.pl, challenge-137/polettix/raku/ch-1.raku, challenge-137/polettix/raku/ch-2.raku
Hi! Please find this week's contribution, probably a bit ahead of time thanks to the bank holiday today in Italy :smile:
Blog posts will appear in due time.
Thank you for your hard work and keep it up!
=> Add polettix's solution to challenge-137

challenge-137/mattneleigh/perl/ch-1.pl, challenge-137/mattneleigh/perl/ch-2.pl
new file:   challenge-137/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-137/mattneleigh/perl/ch-1.pl

challenge-137/wlmb/blog.txt, challenge-137/wlmb/perl/ch-1.pl, challenge-137/wlmb/perl/ch-2.pl
=> Add solution to pwc137

challenge-137/cheok-yin-fung/java/LongYear.java, challenge-137/cheok-yin-fung/julia/ch-1.jl, challenge-137/cheok-yin-fung/perl/ch-1.pl, challenge-137/cheok-yin-fung/perl/ch-2.pl
2 Perl scripts, 1 Julia script, 1 Java code
=> Challenge 137

challenge-137/duncan-c-white/README, challenge-137/duncan-c-white/perl/ch-1.pl, challenge-137/duncan-c-white/perl/ch-2.pl
.. as it's trying to prove a negative
=> imported my solutions to this week's tasks..  task 2 was a bit strange

challenge-138/wlmb/blog.txt, challenge-138/wlmb/perl/ch-1.pl, challenge-138/wlmb/perl/ch-2.pl
=> Solve PWC 138

challenge-138/polettix/blog.txt, challenge-138/polettix/blog1.txt, challenge-138/polettix/perl/ch-1.pl, challenge-138/polettix/perl/ch-2.pl, challenge-138/polettix/raku/ch-1.raku, challenge-138/polettix/raku/ch-2.raku
Hi! Please find my contribution for this week's challenge. This time... a little late 😄 
Thanks for all the hard work, much appreciated!
=> Add polettix's solution to challenge-138

challenge-138/mattneleigh/perl/ch-1.pl
Only had time for Challenge 1 this week.
=> 	new file:   challenge-138/mattneleigh/perl/ch-1.pl

challenge-138/duncan-c-white/README, challenge-138/duncan-c-white/perl/ch-1.pl, challenge-138/duncan-c-white/perl/ch-2.pl, challenge-138/duncan-c-white/perl/tabulate-split-sums
called "tabulate-square-sums" which investigates our split sums more systematically, investigating the first N perfect squares to see which of them have the "split sum is the sqrt" property
=> imported my solutions to this week's questions, including a bonus program

challenge-138/cheok-yin-fung/perl/ch-2.pl
Some fix on ch-2.pl . 
Sorry for causing inconvenience.
=> fix case N=1 and fix optimization

challenge-138/jaldhar-h-vyas/blog.txt, challenge-138/jaldhar-h-vyas/perl/ch-1.pl, challenge-138/jaldhar-h-vyas/perl/ch-2.pl, challenge-138/jaldhar-h-vyas/raku/ch-1.raku, challenge-138/jaldhar-h-vyas/raku/ch-2.raku
There is a blog post but it might not be visible for a few hours as I am having problems with my server.
=> Challenge 138 by Jaldhar H. Vyas.

challenge-139/polettix/blog.txt, challenge-139/polettix/blog1.txt, challenge-139/polettix/perl/ch-1.pl, challenge-139/polettix/perl/ch-2.pl, challenge-139/polettix/raku/ch-1.raku, challenge-139/polettix/raku/ch-2.raku
Hi! Please find my contribution for this week's challenge. Thank you for running this!
=> Add polettix's solution to challenge-139

challenge-139/polettix/blog.txt, challenge-139/polettix/blog1.txt
Hi! Sorry for the additional trouble this week, I figured that my blog post paths had to be renamed... so here I am :smile:
=> Correct polettix blog entries for PWC139

challenge-139/jake/perl/ch-1.pl
hi, here's my first contribution to the weekly challenge ever. i'm really excited.
cheers jake
=> 139 add jake's solution to challenge 139

challenge-139/mattneleigh/perl/ch-1.pl, challenge-139/mattneleigh/perl/ch-2.pl
new file:   challenge-139/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-139/mattneleigh/perl/ch-1.pl

challenge-140/wlmb/blog.txt, challenge-140/wlmb/perl/ch-1.pl, challenge-140/wlmb/perl/ch-2.pl
=> Add solution to PWC140

challenge-140/alexander-pankoff/perl/ch-1.pl, challenge-140/alexander-pankoff/perl/ch-2.pl
My first contribution since challenge 100. 
Thanks for keeping up the great work. :+1:
=> Solutions for Challenge 140

challenge-141/wlmb/blog.txt, challenge-141/wlmb/perl/ch-1.pl, challenge-141/wlmb/perl/ch-2.pl
=> Solve PWC141

challenge-141/polettix/blog.txt, challenge-141/polettix/blog1.txt, challenge-141/polettix/perl/ch-1.pl, challenge-141/polettix/perl/ch-2.pl, challenge-141/polettix/raku/ch-1.raku, challenge-141/polettix/raku/ch-2.raku
Hi! Early submission this week, so that I'll not forget this time!!! Blog posts are on their way.
Thanks for everything, stay safe with your dear ones 😄
=> Add polettix's solution to challenge-141

challenge-141/jake/perl/ch-1.pl
=> 141 ch-1.pl

challenge-141/alexander-pankoff/perl/ch-1.pl, challenge-141/alexander-pankoff/perl/ch-2.pl
=> Challenge 141

challenge-141/jake/perl/ch-1.pl
sorry for the redundant pull request. i've just received feedback that caused my comments to be improved
=> 141 ch-1.pl clarify comments

challenge-141/duncan-c-white/README, challenge-141/duncan-c-white/perl/ch-1.pl, challenge-141/duncan-c-white/perl/ch-2.pl
=> imported my solutions to this week's two tasks.. both nice ones

challenge-142/abigail/README.md, challenge-142/abigail/perl/ch-1.pl, challenge-142/abigail/perl/ch-2.pl
We lack the resources to implement task 2 (this requires a real time
operating system, and a perl with threads compiled in).
Task 1 is just a repeat of last week, and the week before. I can't be
assed to copy-and-paste most of last weeks code, so, we just have
a Perl solution.
=> Solution for week 142.

challenge-142/polettix/blog.txt, challenge-142/polettix/blog1.txt, challenge-142/polettix/perl/ch-1.pl, challenge-142/polettix/perl/ch-2.pl, challenge-142/polettix/raku/ch-1.raku, challenge-142/polettix/raku/ch-2.raku
Hi! Please find my weekly contribution to PWC (or, maby, TWC right now...). Keep up with the patience and good work!
=> Add polettix's solution to challenge-142

challenge-142/alexander-pankoff/perl/ch-1.pl, challenge-142/alexander-pankoff/perl/ch-2.pl
=> Challenge 142

challenge-142/wlmb/blog.txt, challenge-142/wlmb/perl/ch-1.pl, challenge-142/wlmb/perl/ch-2.pl
=> Solve PWC142

challenge-142/duncan-c-white/README, challenge-142/duncan-c-white/perl/ch-1.pl
=> added my solution (task 1 only) for this week

challenge-142/sgreen/README.md, challenge-142/sgreen/blog.txt, challenge-142/sgreen/perl/ch-1.pl, challenge-142/sgreen/perl/ch-2.pl, challenge-142/sgreen/python/ch-1.py, challenge-142/sgreen/python/ch-2.py
Oops, wrote the code before the deadline, forgot to submit the pull request.
=> sgreen solutions to challenge 142

challenge-143/alexander-pankoff/perl/ch-1.pl, challenge-143/alexander-pankoff/perl/ch-2.pl
=> Challenge 143

challenge-143/polettix/blog.txt, challenge-143/polettix/blog1.txt, challenge-143/polettix/perl/ch-1.pl, challenge-143/polettix/perl/ch-2.pl, challenge-143/polettix/raku/ch-1.raku, challenge-143/polettix/raku/ch-2.raku
Hi! Please find my contribution for this week. I hope everything is fine!
=> Add polettix's solution to challenge-143

challenge-143/wlmb/blog.txt, challenge-143/wlmb/perl/ch-1.pl, challenge-143/wlmb/perl/ch-2.pl
=> Solve PWC143

challenge-143/mattneleigh/perl/ch-1.pl
Only had time to do Challenge 1 this week
=> 	new file:   challenge-143/mattneleigh/perl/ch-1.pl

challenge-144/wlmb/blog.txt, challenge-144/wlmb/perl/ch-1.pl, challenge-144/wlmb/perl/ch-2.pl
=> Solve PWC144

challenge-144/sgreen/README.md, challenge-144/sgreen/perl/ch-1.pl, challenge-144/sgreen/perl/ch-2.pl, challenge-144/sgreen/python/ch-1.py, challenge-144/sgreen/python/ch-2.py
Sorry, no blog this week. Hopefully the code is easy enough to understand. Blog will return next week :)
=> sgreen solutions to challenge 144

challenge-144/polettix/blog.txt, challenge-144/polettix/blog1.txt, challenge-144/polettix/perl/ch-1.pl, challenge-144/polettix/perl/ch-2.pl, challenge-144/polettix/raku/ch-1.raku, challenge-144/polettix/raku/ch-2.raku
I hope you and your dear ones are fine... and I'd like to wish you a happy new "western" year, should I not place the contribution for the coming week before the start of the new year!
=> Add polettix's solution to challenge-144

challenge-144/alexander-pankoff/perl/ch-1.pl, challenge-144/alexander-pankoff/perl/ch-2.pl
My solutions for this week.
Kind regards and merry Christmas.
=> Add Alexander Pankoffs solutions for challenge-144

challenge-144/duncan-c-white/README, challenge-144/duncan-c-white/perl/MakePrimes.pm, challenge-144/duncan-c-white/perl/ch-1.pl, challenge-144/duncan-c-white/perl/ch-2.pl
=> imported my solutions to this week's tasks; particularly enjoyed task 2 (the Ulam sequence one)

challenge-145/wlmb/blog.txt, challenge-145/wlmb/perl/ch-1.pl, challenge-145/wlmb/perl/ch-2.pl
=> Solve PWC145

challenge-145/polettix/blog.txt, challenge-145/polettix/blog1.txt, challenge-145/polettix/perl/ch-1.pl, challenge-145/polettix/perl/ch-2.pl, challenge-145/polettix/raku/ch-1.raku, challenge-145/polettix/raku/ch-2.raku
Hi! It seems that I made it by the end of the (western) year, eventually.
Here is my contribution, as usual.
Let me wish you the best!
=> Add polettix's solution to challenge-145

challenge-145/jake/perl/ch-1.pl
=> 145 add solution for ch-1.pl

challenge-145/andrezgz/perl/ch-1.pl, challenge-145/andrezgz/perl/ch-2.pl
Happy new year, @manwar! Hope my solution arrives before the due date-time
=> challenge-145 andrezgz solution

challenge-145/mattneleigh/perl/ch-1.pl
Only had time for Challenge 1 again
=> 	new file:   challenge-145/mattneleigh/perl/ch-1.pl

challenge-145/morayj/README, challenge-145/morayj/raku/ch-1.raku
=> Add dot challenge for 145

challenge-146/roger-bell-west/javascript/ch-1.js, challenge-146/roger-bell-west/javascript/ch-2.js, challenge-146/roger-bell-west/kotlin/ch-1.kt, challenge-146/roger-bell-west/kotlin/ch-2.kt, challenge-146/roger-bell-west/lua/ch-1.lua, challenge-146/roger-bell-west/lua/ch-2.lua, challenge-146/roger-bell-west/perl/ch-1.pl, challenge-146/roger-bell-west/perl/ch-2.pl, challenge-146/roger-bell-west/postscript/ch-1.ps, challenge-146/roger-bell-west/postscript/ch-2.ps, challenge-146/roger-bell-west/python/ch-1.py, challenge-146/roger-bell-west/python/ch-2.py, challenge-146/roger-bell-west/raku/ch-1.p6, challenge-146/roger-bell-west/raku/ch-2.p6, challenge-146/roger-bell-west/ruby/ch-1.rb, challenge-146/roger-bell-west/ruby/ch-2.rb, challenge-146/roger-bell-west/rust/ch-1.rs, challenge-146/roger-bell-west/rust/ch-2.rs
Up to nine languages, where will this madness end?
=> Solutions for challenge #146

challenge-146/wlmb/blog.txt, challenge-146/wlmb/perl/ch-1.pl, challenge-146/wlmb/perl/ch-2.pl
=> Solve PWC146

challenge-146/polettix/blog.txt, challenge-146/polettix/blog1.txt, challenge-146/polettix/perl/ch-1.pl, challenge-146/polettix/perl/ch-2.pl, challenge-146/polettix/raku/ch-1.raku, challenge-146/polettix/raku/ch-2.raku
Hi! First contribution of the year, yay!
I hope everything's fine, congratulations for drawing your brother in the lot - your dedication deserves this and much more!
Blog posts are on their way.
=> Add polettix's solution to challenge-146

challenge-146/simon-proctor/raku/ch-1.raku, challenge-146/simon-proctor/raku/ch-2.raku
So back on the challenge after the holidays. This weeks were fun and nice and easy in Raku.
=> Challenge 146 : Back in the saddle

challenge-146/andrezgz/perl/ch-1.pl, challenge-146/andrezgz/perl/ch-2.pl
Hi @manwar , my solution to tasks for this week!
=> challenge-146 andrezgz solution

challenge-146/duncan-c-white/README, challenge-146/duncan-c-white/perl/MakePrimes.pm, challenge-146/duncan-c-white/perl/ch-1.pl, challenge-146/duncan-c-white/perl/ch-2.pl
liked both, and only took 30 minutes to do both overall, so nice and straightforward (once you'd worked out the rules for the curious fraction tree)
=> imported my solutions to both tasks

challenge-146/bruce-gray/README, challenge-146/bruce-gray/Test_data/ch-2_test_generator.raku, challenge-146/bruce-gray/Test_data/ch-2_tests.txt, challenge-146/bruce-gray/blog.txt, challenge-146/bruce-gray/perl/ch-1.pl, challenge-146/bruce-gray/perl/ch-2.pl, challenge-146/bruce-gray/perl/ch-2_via_module.pl, challenge-146/bruce-gray/raku/ch-1.raku, challenge-146/bruce-gray/raku/ch-2.raku
Add Raku and Perl solutions for TWC 146 by Bruce Gray.
Also 200+ tests for Task 2, and a Raku test generator with utility routines to explore the CW tree.
=> Add Raku and Perl solutions for TWC 146 by Bruce Gray.

challenge-147/simon-proctor/raku/ch-1.raku, challenge-147/simon-proctor/raku/ch-2.raku
=> Challenge 147

challenge-147/luca-ferrari/blog-1.txt, challenge-147/luca-ferrari/blog-2.txt, challenge-147/luca-ferrari/blog-3.txt, challenge-147/luca-ferrari/blog-4.txt, challenge-147/luca-ferrari/blog-5.txt, challenge-147/luca-ferrari/postgresql/ch-2.sql, challenge-147/luca-ferrari/postgresql/ch-2b.sql
Added a different solution to task 2 for PostgreSQL.
=> Pwc147 - another PostgreSQL solution to task 2

challenge-147/wlmb/blog.txt, challenge-147/wlmb/perl/ch-1.pl, challenge-147/wlmb/perl/ch-2.pl, challenge-147/wlmb/perl/ch-2a.pl, challenge-147/wlmb/perl/ch-2b.pl
=> Solve PWC147

challenge-147/polettix/blog.txt, challenge-147/polettix/blog1.txt, challenge-147/polettix/perl/ch-1.pl, challenge-147/polettix/perl/ch-2.pl, challenge-147/polettix/raku/ch-1.raku, challenge-147/polettix/raku/ch-2.raku
Hi! Here's my contribution for PWC 147. I hope everything is fine with you and your dear ones 😄
=> Add polettix's solution to challenge-147

challenge-145/alexander-pankoff/perl/ch-1.pl
My solution for challenge 145 task 1.
=> Add solution for challenge 145 task 1

challenge-147/2colours/README, challenge-147/2colours/raku/ch-1.raku, challenge-147/2colours/raku/ch-2.raku
Hello,
it's time I would also join the race, can I? Thank you in advance.
=> Challenge #147 added by new enforcer 2colours :)

challenge-148/polettix/blog.txt, challenge-148/polettix/blog1.txt, challenge-148/polettix/perl/ch-1-alt.pl, challenge-148/polettix/perl/ch-1.pl, challenge-148/polettix/perl/ch-2.pl, challenge-148/polettix/perl/cpanfile, challenge-148/polettix/perl/cpanfile.snapshot, challenge-148/polettix/raku/ch-1.raku, challenge-148/polettix/raku/ch-2.raku
Hi! Please find my contribution... and have a good time!
=> Add polettix's solution to challenge-148

challenge-148/mattneleigh/perl/ch-1.pl, challenge-148/mattneleigh/perl/ch-2.pl
new file:   challenge-148/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-148/mattneleigh/perl/ch-1.pl

challenge-148/duncan-c-white/README, challenge-148/duncan-c-white/perl/ch-1.pl, challenge-148/duncan-c-white/perl/ch-2.pl, challenge-148/duncan-c-white/perl/ch-2FAST.pl
I liked both questions, the Eban numbers are very cute.  Cardano triples were initially less pleasant as I dislike floating point algorithms.  But note that I included a bonus ch-2FAST.pl Cardano generator using a sneaky parameterised generation technique.  basic solutions took about an hour to develop, and I spent a second hour researching and build ch-2FAST.
=> imported my solutions to this week's puzzles..

challenge-148/alexander-pankoff/perl/ch-1.pl
=> Add solution for challenge 148 task 1

challenge-149/wlmb/blog.txt, challenge-149/wlmb/perl/ch-1.pl, challenge-149/wlmb/perl/ch-2.pl, challenge-149/wlmb/perl/ch-2a.pl
=> Solve PWC149

challenge-149/mattneleigh/perl/ch-1.pl, challenge-149/mattneleigh/perl/ch-2.pl
new file:   challenge-149/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-149/mattneleigh/perl/ch-1.pl

challenge-149/alexander-pankoff/perl/ch-1.pl, challenge-149/alexander-pankoff/perl/ch-2.pl
My solutions for the current challenges.
=> Challenge 149

challenge-148/bruce-gray/blog.txt
manwar, as the originator of the "Cardano Triplets" task, you might be interested in my analysis. Thanks!
=> Added (very late) blog entry for TWC 148.

challenge-149/e-choroba/perl/ch-2.pl
It can handle larger integers without a problem.
=> Fix 149/2 by switching to Math::Base::Convert

challenge-149/duncan-c-white/README, challenge-149/duncan-c-white/perl/Perms.pm, challenge-149/duncan-c-white/perl/ch-1.pl, challenge-149/duncan-c-white/perl/ch-2.pl
did both pretty basically as I didn't have much time:-)  two nice questions..  took about 40 minutes overall
=> imported my solutions to this week's questions

challenge-150/2colours/raku/ch-1.raku, challenge-150/2colours/raku/ch-2-no-use.raku, challenge-150/2colours/raku/ch-2.raku
Hello,
I got a bit behind by the overwhelming input size of the last challenge - on the other hand, this week's tasks would run under 1 second even on a soroban. :D 
Thank you for the tasks and see you soon.
M Polgár
=> 2colours (initial) solutions for challenge No. 150

challenge-150/0rir/README, challenge-150/0rir/raku/ch-1.raku, challenge-150/0rir/raku/ch-2.raku
=> raku challenge 150

challenge-150/polettix/blog.txt, challenge-150/polettix/blog1.txt, challenge-150/polettix/perl/ch-1.pl, challenge-150/polettix/perl/ch-2.pl, challenge-150/polettix/raku/ch-1.raku, challenge-150/polettix/raku/ch-2.raku
Hi! Please find my contribution for this week's challenge... a bit late 😁
=> Add polettix's solution to challenge-150

challenge-150/alexander-pankoff/blog1.txt, challenge-150/alexander-pankoff/blog2.txt, challenge-150/alexander-pankoff/perl/ch-1.pl, challenge-150/alexander-pankoff/perl/ch-2.pl
My solutions for the current week and my first blog posts ever. Exactly (150/2) weeks after my first pwc submission in challenge 75.
Kind regards.
=> Challenge 150

challenge-150/duncan-c-white/README, challenge-150/duncan-c-white/perl/ch-1.pl, challenge-150/duncan-c-white/perl/ch-2.pl
two nice questions..  took about 50 minutes overall
=> imported my solutions to this week's tasks; two nice tasks

challenge-151/wlmb/blog.txt, challenge-151/wlmb/perl/ch-1.pl, challenge-151/wlmb/perl/ch-2.pl
=> Solve PWC151

challenge-151/polettix/blog.txt, challenge-151/polettix/blog1.txt, challenge-151/polettix/perl/ch-1.pl, challenge-151/polettix/perl/ch-2.pl, challenge-151/polettix/raku/ch-1.raku, challenge-151/polettix/raku/ch-2.raku
Hi Mohammad! Here's my contribution for this week's challenge. Thanks for all the effort and the dedication!
=> Add polettix's solution to challenge-151

challenge-151/cheok-yin-fung/perl/ch-2.pl
Nice Task 2
The previous pull request overlooked the condition of "always starting with the first".
=> Week 151 Task 2

challenge-151/2colours/raku/ch-1.raku, challenge-151/2colours/raku/ch-2.raku
Hello,
at last, it's time to add the solutions... I wanted to test them more (especially the first one) but it doesn't seem like I will have enough time for that so let's hope for the best. :)
=> 2colours Raku solutions added

challenge-151/alexander-pankoff/perl/ch-1.pl, challenge-151/alexander-pankoff/perl/ch-2.pl
=> Challenge 151

challenge-151/mattneleigh/perl/ch-2.pl
=> 	modified:   challenge-151/mattneleigh/perl/ch-2.pl

challenge-152/wlmb/blog.txt, challenge-152/wlmb/perl/ch-1.pl, challenge-152/wlmb/perl/ch-2.pl
=> Solve PWC152

challenge-152/alexander-pankoff/perl/ch-1.pl, challenge-152/alexander-pankoff/perl/ch-2.pl
My solutions for this weeks challenge. 
Kind Regards,
Alexander
=> Add solutions for challenge 152

challenge-152/polettix/blog.txt, challenge-152/polettix/blog1.txt, challenge-152/polettix/perl/ch-1.pl, challenge-152/polettix/perl/ch-2.pl, challenge-152/polettix/raku/ch-1.raku, challenge-152/polettix/raku/ch-2.raku
Congratulations for keeping up with the good work!
=> Add polettix's solution to challenge-152

challenge-152/duncan-c-white/README, challenge-152/duncan-c-white/perl/ch-1.pl, challenge-152/duncan-c-white/perl/ch-2.pl
Had to remind myself of the way of detecting whether two rectangles overlap, and if so what their area is, otherwise straightforward.
=> imported my solutions to this week's tasks, straightforward ones

challenge-153/wlmb/blog.txt, challenge-153/wlmb/perl/ch-1.pl, challenge-153/wlmb/perl/ch-2.pl
=> Solve PWC153

challenge-153/cheok-yin-fung/dart/ch-1.dart, challenge-153/cheok-yin-fung/dart/ch-2.dart
=> The Weekly Challenge 153: Dart solution

challenge-153/mattneleigh/perl/ch-1.pl, challenge-153/mattneleigh/perl/ch-2.pl
new file:   challenge-153/mattneleigh/perl/ch-2.pl
=> 	new file:   challenge-153/mattneleigh/perl/ch-1.pl

challenge-153/mattneleigh/perl/ch-2.pl
Minor correction to return value in ch-2
=> 	modified:   challenge-153/mattneleigh/perl/ch-2.pl

challenge-153/polettix/blog.txt, challenge-153/polettix/blog1.txt, challenge-153/polettix/perl/ch-1.pl, challenge-153/polettix/perl/ch-2.pl, challenge-153/polettix/raku/ch-1.raku, challenge-153/polettix/raku/ch-2.raku
Hi Mohammad... please find my latest contribution 😄
=> Add polettix's solution to challenge-153

challenge-152/pokgopun/perl/ch-2.pl
Fix logic that supports n rectangles as well as adding comments to make it easier for later review
=> late fix for pwc152 support of n rectangle

challenge-153/0rir/raku/ch-2.raku
=> Factorions

challenge-153/alexander-pankoff/blog1.txt, challenge-153/alexander-pankoff/blog2.txt, challenge-153/alexander-pankoff/haskell/ch-1.hs, challenge-153/alexander-pankoff/haskell/ch-2.hs, challenge-153/alexander-pankoff/perl/ch-1.pl, challenge-153/alexander-pankoff/perl/ch-2.pl, challenge-153/alexander-pankoff/raku/ch-1.raku, challenge-153/alexander-pankoff/raku/ch-2.raku
Good evening @manwar 
my solutions and blog posts for the current challenge.
Have a nice start into the week,
Alex
=> Challenge 153
