manwar/perlweeklychallenge-club

challenge-001/bob-kleemann/README
It's a common mistake to spell it without the proper number of n's.
=> Corrected spelling of my last name

challenge-001/john-barrett/perl5/README.md, challenge-002/john-barrett/perl5/ch-1.pl, challenge-002/john-barrett/perl5/ch-2.pl
- Writeup for challenge 1 copied from original gist
- Challenge 2 part 1 - Can `printf()` do it?
- Challenge 2 part 2 - I think this is correct :)
=> Challenge 2

challenge-001/andrezgz/README, challenge-001/andrezgz/perl5/ch-1.pl, challenge-001/andrezgz/perl5/ch-2.sh
Hi Mohammad. Is it possible to add my resolution for the first challenge now?
=> Solution challenge-001 andrezgz

challenge-002/andrezgz/README, challenge-002/andrezgz/perl5/ch-1.pl, challenge-002/andrezgz/perl5/ch-2.pl
Hi Mohammad, here's my first resolution.
=> Solution challenge-002 andrezgz

challenge-001/kian-meng-ang/blog.txt, challenge-002/kian-meng-ang/perl5/ch-1.sh, challenge-002/kian-meng-ang/perl5/ch-2.pl
Add week 2 challenges answers and week 1 blog post.
=> Challenges 2 answers

challenge-002/andrezgz/perl5/ch-1.pl
Hi @manwar, reading the recap for ther first weekly challenge saw that "members can improve their solutions any time". Thanks for allowing it.
=> challenge-002 andrezgz fix ch-1

challenge-002/jaime/README.md, challenge-002/jaime/perl5/ch-1.pl, challenge-002/jaime/perl5/ch-2.pl
[@tortsnare on Twitter](https://twitter.com/tortsnare) submitting pull request, instead of a tweet.
=> Perl Weekly Challenge 002

challenge-003/lars-balker/perl5/ch-1.pl, challenge-003/lars-balker/perl5/ch-2.pl
I imagine the perl6 solutions will be radically different because of cleverness, if I get around to them!
=> some naive perl5 solutions

challenge-003/andrezgz/perl5/ch-1.pl, challenge-003/andrezgz/perl5/ch-2.pl
Hi @manwar this is my challenge-003 solution
=> challenge-003 andrezgz solution

challenge-003/duncan-c-white/perl5/README, challenge-003/duncan-c-white/perl5/ch-1.pl, challenge-003/duncan-c-white/perl5/ch-2.pl
hi manwar, hope I'm doing this right, while I use git all the time, I've never forked or worked with branches and pull requests.  If I have done it right, this pull request should ?contain? my solutions to weekly challenge#3
=> imported my solutions plus a basic readme in the new perl5 directory

challenge-003/fjwhittle/perl6/ch-1.p6
Somewhat embarrassed that I missed the – I guess that's what I get for not double-checking after selectively not commiting my timing code...
Figured I may as well include the timing code.
=> Fix typo in output, add optional timing output.

challenge-003/joelle-maslak/perl6/ch-1.p6, challenge-003/joelle-maslak/perl6/ch-2.p6
Initial solutions in Perl 6.  Note that they don't have the normal comments - busy week!
=> Add Perl6 solutions for Week 3

challenge-004/james-smith/README.md, challenge-004/james-smith/perl5/ch-2a.pl, challenge-004/james-smith/perl6/ch-2.p6
Just made some changes to look at performance issues - Perl 6 is slow Slow SLOW - not sure why tho!
=> changes to solution for challenge 2 - a bit longer but non-destructive!

challenge-003/doug-schrag/perl6/ch-1.p6, challenge-003/doug-schrag/perl6/ch-2.p6, challenge-004/doug-schrag/perl6/ch-1.p6, challenge-004/doug-schrag/perl6/ch-2.p6
The high-precision sqrt / pi calculations are a module (Math::Precise) in progress :-)
=> Submit solutions by Doug Schrag

challenge-004/maxim-kolodyazhny/perl5/ch-2.pl
Hello, Mohammad! Yet another solution.
=> Challenge 4 task 2 by Maxim Kolodyazhny

challenge-001/veesh-goldman/perl5/ch-1.pl, challenge-002/veesh-goldman/perl5/ch-2.pl, challenge-004/veesh-goldman/perl5/ch-01.pl, challenge-004/veesh-goldman/perl5/ch-02.pl
I actually found the easy challenge to be harder than the advanced challenge this week.
=> My answers to this week's challenge

challenge-004/maxim-kolodyazhny/perl5/ch-2.pl
I thought it was worth mentioning B::Deparse.
P.S. Sorry for late PR.
=> Comment about B::Deparse - musthave feature for perl developer

challenge-004/duncan-c-white/README, challenge-004/duncan-c-white/perl5/ch-1.pl, challenge-004/duncan-c-white/perl5/ch-2.pl
Hi Manwar,
If I've done this right, please find my solutions to this week's problems - please tell me if I got it wrong, as I'm really not into all this "fork/pull request" stuff.
Working out how to refresh last week's fork was the hardest part, as I've not used forks before.  You might want to write out a simple guide for pull request/fork novices to say what to do THE SECOND TIME..  In my cloned fork from last week, I hoped "git pull" would freshen it up, but no chance.  I googled and found that I had to add your repo to my repo as the remote called "upstream", then "git fetch upstream", "git status" and "git merge upstream" (scary) and then "git push" back to my repo, before I could even start to add my solutions to challenge-004/duncan-c-white.  I didn't bother to create a branch this …
=> my solutions to challenge004

challenge-004/gustavo-chaves/perl5/ch-2b.pl
The new solution is more concise and easier to use, because it uses the
<> filehandle to read words from STDIN or from a sequence of files
provided as arguments.
=> Another solution to challenge 004

challenge-005/gustavo-chaves/perl5/ch-2b.pl
The ch-2b.pl script is shorter, faster, and uses no modules.
=> Another solution to PWC 005

challenge-005/andrezgz/perl5/ch-1.pl, challenge-005/andrezgz/perl5/ch-2.pl
Hi @manwar, this week I've started reusing some code from the previous challenge for ch-1 but then I was forced to change the approach for ch-2. **Good one!**
=> challenge-005 andrezgz solution

challenge-005/simon-proctor/perl6/anagram.p6, challenge-005/simon-proctor/perl6/lib/Anagrams.pm6, challenge-005/simon-proctor/perl6/longest-anagram-string.p6
Hi Mohammad, 
Here's my finished solutions for this weeks challenge in Perl6. I'm working on a blog post for it now which will also cover some of the false starts for part 2 and I'll send you a link to that when it's done.
=> Added Perl6 Solutions for Challenge 5

challenge-005/adam-russell/blog.txt, challenge-005/adam-russell/perl5/ch-1.pl, challenge-005/adam-russell/perl5/ch-2.pl
=> Challenge 005

challenge-005/jaldhar-h-vyas/perl5/ch-1.pl, challenge-005/jaldhar-h-vyas/perl5/ch-2.pl, challenge-005/jaldhar-h-vyas/perl6/ch-1.p6, challenge-005/jaldhar-h-vyas/perl6/ch-2.p6
=> Challenge 5 by Jaldhar H. Vyas

challenge-005/duncan-c-white/README, challenge-005/duncan-c-white/perl5/ch-1.pl, challenge-005/duncan-c-white/perl5/ch-2.pl
=> Imported my solutions, plus modified README explaining how.

challenge-005/mark-senn/perl6/ch-1.p6, challenge-005/mark-senn/perl6/ch-2.p6
=> Changed    join()

challenge-006/simon-proctor/perl6/ch-1.p6
I'll blog this later. And I might get challenge 2 done.
=> Challenge 1

challenge-006/andrezgz/perl5/ch-1.pl, challenge-006/andrezgz/perl5/ch-2.pl
Hi @manwar, I've enjoyed this week challenge about creating the compact form of a list of numbers
=> challenge-006 andrezgz solution

challenge-006/simon-proctor/perl6/ch-1.p6
So 1,2,4,5,6 becomes 1,2,4-6 :)
=> Handle a case where the range start and finish differ by one

challenge-006/duncan-c-white/README, challenge-006/duncan-c-white/perl5/ch-1.pl, challenge-006/duncan-c-white/perl5/ch-2.sh
Dear Manwar, sorry for the late submission, not sure what I did wrong but I couldn't get git fetch upstream and git merge upstream/master --ff-only to work. Wasted an hour faffing about, recloning my forked repo, couldn't get that to work either, then I did it a third time and it works, my fault no doubt. Was going to write a blog, didn't get to it.
cheers
duncan
=> imported my solutions, after some difficulty with git fetch/merge..

challenge-006/daniel-mantovani/perl5/ch-1.pl, challenge-006/daniel-mantovani/perl5/perltidy.LOG
=> solution challenge 006-1

challenge-006/jaldhar-h-vyas/perl5/ch-1.pl, challenge-006/jaldhar-h-vyas/perl5/ch-2.pl, challenge-006/jaldhar-h-vyas/perl6/ch-1.p6, challenge-006/jaldhar-h-vyas/perl6/ch-2.p6
My solutions for Challenge 6.  Sorry they're a little late.
=> Challenge 6 by Jaldhar H. Vyas

challenge-007/simon-proctor/perl6/ch-1.p6
Here's challenge one in perl6. I'll look at doing challenge 2 later and blogging them.
=> Challenge 1. Niven numbers.

challenge-007/andrezgz/perl5/ch-1.pl
Hi @manwar, this week I've only managed to solve the first challenge. The other one I felt it was out of my league.
=> challenge-007 andrezgz solution

challenge-006/kian-meng-ang/blog.txt, challenge-007/kian-meng-ang/perl5/ch-1.pl
=> Challenge #007 C1 answer and challenge #006 blog link

challenge-007/daniel-mantovani/perl5/ch-1.pl, challenge-007/daniel-mantovani/perl5/ch-2.pl, challenge-007/daniel-mantovani/perl5/list.txt
=> ch-1 & 2 for challenge 007

challenge-007/adam-russell/blog.txt, challenge-007/adam-russell/perl5/ch-1.pl, challenge-007/adam-russell/perl5/ch-2.pl
=> Challenge 007

challenge-007/jaldhar-h-vyas/perl5/ch-1.pl, challenge-007/jaldhar-h-vyas/perl6/ch-1.p6
Owing to a severe lack of time, only the first problem today.  But I will try to do the second one tomorrow.
=> Challenge 7 problem 1 by Jaldhar H. Vyas

challenge-008/simon-proctor/perl6/ch-1.p6
Good morning. I'm hoping I'll be a bit more chirpy this week and will blog this one.
Plus I think the second test should be done soonish.
Not sure about the API thing.
=> Perfect numbers 

challenge-008/joelle-maslak/perl5/ch-1.pl
Solution for week 8 problem 1 in Perl 5
=> Perl 5 solution to week 8 problem 1

challenge-008/andrezgz/perl5/ch-1.pl, challenge-008/andrezgz/perl5/ch-2.pl
Hi @manwar, this week I was able to solve them both again :)
=> challenge-008 andrezgz solution

challenge-008/daniel-mantovani/perl5/ch-1.pl, challenge-008/daniel-mantovani/perl5/ch-2.pl
sorry didn't have the time for ch-3
I would like to take advance of this space to propose a problem to be included in a future challenge:
> Write a function, 'miner', whose first argument is a number greater than one, and then a list of strings, which will be lines of text. The function will return the same list of strings, followed by a line with only a number, so that the SHA256 hash of the whole returned list joined by "\n" end of lines will give a hash starting with "n" (or more) binary 0 positions, where "n" is the first argument mentioned.
The only perl module that should be used is Digest::SHA module (in perl5, in perl6 you may suggest an equivalent module I guess)
For example:
> miner(14, 'This', 'are my', 'test lines');
should return a list like:
> 'This', 'are my', 'test lines', …
=> my solutions to ch-1 & 2 in perl5

challenge-007/kian-meng-ang/blog.txt, challenge-008/kian-meng-ang/perl5/ch1.pl, challenge-008/kian-meng-ang/perl5/ch2.pl
=> Challenge #008 answers and challenge #007 blog link

challenge-007/jaldhar-h-vyas/perl5/ch-2.pl, challenge-007/jaldhar-h-vyas/perl6/ch-2.p6
The missing challenge from last week.
=> Challenge 7 problem 2 by Jaldhar H. Vyas

challenge-008/jaldhar-h-vyas/perl5/ch-1.pl, challenge-008/jaldhar-h-vyas/perl5/ch-2.pl, challenge-008/jaldhar-h-vyas/perl6/ch-1.p6, challenge-008/jaldhar-h-vyas/perl6/ch-2.p6
Really late again sorry but I should be back on track from this week.
=> Challenge 8 by Jaldhar H. Vyas

challenge-009/yozen-hernandez/README, challenge-009/yozen-hernandez/blog.txt, challenge-009/yozen-hernandez/perl5/ch-1.pl, challenge-009/yozen-hernandez/perl5/ch-2.pl, challenge-009/yozen-hernandez/wdi_world_bank_gini_most_recent.tsv
I included some external data for the second part of the challenge, which was CC BY-4.0 licensed. I hope the attribution I included in the README, along with the data, is acceptable.
=> Perl5 Solutions to challenge 009 by Yozen Hernandez

challenge-009/adam-russell/blog.txt, challenge-009/adam-russell/perl5/ch-1.pl, challenge-009/adam-russell/perl5/ch-2.pl
=> Challenge 009

challenge-009/kian-meng-ang/perl5/ch-1.pl, challenge-009/kian-meng-ang/perl5/ch-2.pl
=> Challenge #009 C1 & C2 answers

challenge-009/daniel-mantovani/perl5/ch-1.pl, challenge-009/daniel-mantovani/perl5/ch-2.pl
hope is not too late!
BR & many thanks!
=> my answers for challenge009

challenge-010/kivanc-yazan/perl5/ch-1.pl
=> Kivanc Week 10 Challenge 1 solution

challenge-010/simon-proctor/perl6/ch-1.p6
but I've tweaked my result with a unicode option
(Not using all the unicode points though, gets a bit weird for some of them).
=> I'd done this before for Exercism 

challenge-010/simon-proctor/perl6/ch-1.p6
Can handle both ASCII and unicode numeral strings. Including the special unicode character for sopme of the numbers between 1 and 12.
=> Now reads Roman numeral strings

challenge-010/daniel-mita/perl6/ch-1-arabic.p6, challenge-010/daniel-mita/perl6/ch-1.p6
Will eventually get round to the decoding
=> Support larger numbers and include script with arabic numerals

challenge-010/pavel-jurca/perl5/ch-1.pl
Thank you @manwar for the hard work you're putting into! 👍
=> Submit the updated solution

challenge-010/andrezgz/perl5/ch-1.pl, challenge-010/andrezgz/perl5/ch-2.pl
Hi @manwar , here are the solutions for this week challenge.
=> challenge-010 andrezgz solution

challenge-010/daniel-mantovani/perl5/ch-1.pl, challenge-010/daniel-mantovani/perl5/ch-2.pl
=> my solutions for challenge 010 ch-1 & 2 in p5

challenge-010/e-choroba/perl5/pwc010-1.pl, challenge-010/e-choroba/perl5/pwc010-2.pl
The Wikipedia page of Jaro-Winkler is a bit unclear (reflected also in
its Talk page), so I settled for a CPAN solution.
=> Solve #010

challenge-010/joelle-maslak/blog.txt
=> Add blog for 10.1

challenge-010/andrezgz/perl5/ch-2.pl
Sorry @manwar, still making changes
=> challenge-010 andrezgz minor opt

challenge-010/joelle-maslak/blog.txt, challenge-010/joelle-maslak/perl5/ch-3.pl, challenge-010/joelle-maslak/perl5/ch-3.readme, challenge-010/joelle-maslak/perl6/ch-3.p6, challenge-010/joelle-maslak/perl6/ch-3.readme
=> Solutions for week 10, problem 3 in P6 and P5

challenge-010/yozen-hernandez/README, challenge-010/yozen-hernandez/blog.txt, challenge-010/yozen-hernandez/perl5/ch-1.pl, challenge-010/yozen-hernandez/perl5/ch-2.pl
=> Added solutions for challenge 10 by Yozen Hernandez

challenge-011/simon-proctor/perl6/ch-1.p6, challenge-011/simon-proctor/perl6/ch-2.p6
Here we go. I think I got them both OK.
Rational numbers for the win in the case of challenge 1.
=> Week 11 challenges

challenge-011/dave-jacoby/pc011c1.pl, challenge-011/dave-jacoby/pc011c3.pl
1 and 3.
May get to 2 this week, but that's a part of math that, if I've had to contend with it before, I have blocked it out.
=> Challenge 11

challenge-011/andrezgz/perl5/ch-1.pl, challenge-011/andrezgz/perl5/ch-2.pl
Hi @manwar, the solutions for this week challenge
=> challenge-011 andrezgz solution

challenge-011/adam-russell/blog.txt, challenge-011/adam-russell/perl5/ch-1.pl, challenge-011/adam-russell/perl5/ch-2.pl
thank you as always for administering the weekly challenge!
=> solution for challenge 011

challenge-011/daniel-mantovani/perl5/ch-1.pl
=> my proposed solution for challenge-011, ch-1.pl

challenge-011/athanasius/perl5/ch-1.pl, challenge-011/athanasius/perl5/ch-2.pl, challenge-011/athanasius/perl5/ch-3.pl
new file:   challenge-011/athanasius/perl5/ch-1.pl
new file:   challenge-011/athanasius/perl5/ch-2.pl
new file:   challenge-011/athanasius/perl5/ch-3.pl
=> On branch new-branch

challenge-011/kian-meng-ang/perl5/ch-1.pl, challenge-011/kian-meng-ang/perl5/ch-2.pl
=> Add C1 & C2 solutions for weekly #011

challenge-012/simon-proctor/perl6/ch-1.p6
Got to love infinite lazy lists. This is probably why Laurent suggested this. He wanted to show off.
=> Non Prime Euclids.

challenge-012/simon-proctor/perl6/ch-2.p6
=> Longest shared path solution 

challenge-012/yozen-hernandez/blog.txt, challenge-012/yozen-hernandez/perl5/ch-1.pl, challenge-012/yozen-hernandez/perl5/ch-2.pl
I'll try to get to challenge 3 this week, hopefully!
=> Added solutions by Yozen Hernandez for challenges 1 and 2 for week 12

challenge-012/aaron-sherman/README, challenge-012/aaron-sherman/perl6/ch-1.p6, challenge-012/aaron-sherman/perl6/ch-2.p6
My weekly challenge solutions.
=> Aaron's solutions for 012.1 and 012.2 in P6

challenge-012/andrezgz/perl5/ch-1.pl, challenge-012/andrezgz/perl5/ch-2.pl
Hi @manwar, hope you’re having a great week!
=> challenge-012 andrezgz solution

challenge-012/jaime/README, challenge-012/jaime/perl5/ch-1.pl, challenge-012/jaime/perl5/ch-2.pl, challenge-012/jaime/perl5/ch-3.pl
Solutions to Challenge 1 and 2. Opt-out optional Challenge 3.
=> Solutions to Challenge 012

challenge-012/daniel-mantovani/perl5/ch-1.pl, challenge-012/daniel-mantovani/perl5/ch-2.pl
=> my proposed solutions for challenge-012, p5 1 & 2

challenge-012/fjwhittle/perl6/ch-3.p6
My API key came through so I did some testing, and found I had to fix up my script.
=> fjwhittle ch-3.p6 fixes after testing.

challenge-012/joelle-maslak/perl5/ch-3-simulator.pl, challenge-012/joelle-maslak/perl5/ch-3.pl, challenge-012/joelle-maslak/perl6/ch-3.p6
The documentation for the API's JSON output is just plain incorrect.  Now that I have actual access to the API, not just sample output from the API docs, this will work with the real API.
=> Work with actual API, not documented API!

challenge-013/dave-jacoby/c1.pl, challenge-013/dave-jacoby/c2.pl
Coded during Sawyer X's talk. I'm not proud.
=> Friday, Friday! Gotta deploy on Friday!

challenge-013/andrezgz/perl5/ch-1.pl, challenge-013/andrezgz/perl5/ch-2.pl
Hi @manwar, here are the solutions to this week challenge
=> challenge-013 andrezgz solution

challenge-013/jaldhar-h-vyas/perl5/ch-1.pl, challenge-013/jaldhar-h-vyas/perl6/ch-1.p6
That's what I get for doing last minute edits without tests :-)
=> Challenge 13 by Jaldhar H. Vyas: BUG FIXES

challenge-013/e-choroba/blog.txt, challenge-013/e-choroba/perl5/ch-2.pl
Also, adapt one of the solutions acording to the blogpost.
=> Add a link to choroba's blogpost

challenge-013/kian-meng-ang/perl5/ch-1.pl, challenge-013/kian-meng-ang/perl5/ch-3.pl
=> Add C1 & C3 answer for challenge #013

challenge-013/athanasius/blog.txt, challenge-013/athanasius/perl5/ch-1.pl, challenge-013/athanasius/perl5/ch-2.pl, challenge-013/athanasius/perl6/ch-1.p6, challenge-013/athanasius/perl6/ch-2.p6
On branch branch-for-challenge-013
new file:   challenge-013/athanasius/blog.txt
new file:   challenge-013/athanasius/perl5/ch-1.pl
new file:   challenge-013/athanasius/perl5/ch-2.pl
new file:   challenge-013/athanasius/perl6/ch-1.p6
new file:   challenge-013/athanasius/perl6/ch-2.p6
=> Solutions to Challenge #013 + blog URL

challenge-013/daniel-mantovani/perl5/ch-1.pl, challenge-013/daniel-mantovani/perl5/ch-2.pl
=> my proposed solutions for challenge-013, p5 1 & 2

challenge-013/duncan-c-white/README, challenge-013/duncan-c-white/perl5/ch-1.pl, challenge-013/duncan-c-white/perl5/ch-2.pl
Did the challenges starting at 1700 on Sunday 23rd.  got them both working by 1730..
=> challenge 13.. good questions

challenge-013/jaldhar-h-vyas/blog.txt
I've been meaning to blog for some time and now I've finally gotten around to it.  This is the post for the current challenge.  I've also written posts for all the previous challenges but they are not ready yet.  (Of course I have to write my own blog script first!)  The appearance will change a bit but the URL should remain stable.
=> Challenge 13 by Jaldhar H. Vyas: blog post

challenge-014/rob-van-dam/README, challenge-014/rob-van-dam/perl5/ch-1.pl, challenge-014/rob-van-dam/perl5/ch-2.pl, challenge-014/rob-van-dam/perl5/ch-3.pl
I'm new.  I also sent an email to be added but perhaps this is simpler.
=> Challenge 014

challenge-014/simon-proctor/perl6/ch-1.p6
Here you go. I'll take a look at the next one in a bit when my head stops aching.
=> Challenge 1. Van Eck's Sequnce

challenge-012/feng-chang/perl5/ch-3.pl, challenge-013/feng-chang/perl5/ch-1.pl, challenge-013/feng-chang/perl5/ch-2.pl, challenge-014/feng-chang/perl5/ch-1.pl, challenge-014/feng-chang/perl5/ch-2.pl, challenge-014/feng-chang/perl6/ch-1.p6, challenge-014/feng-chang/perl6/ch-2.p6
=> challeng 014

challenge-014/e-choroba/blog.txt, challenge-014/e-choroba/perl5/ch-2.pl, challenge-014/e-choroba/perl5/ch-2a.pl
Also, remove unneccesary condition.
=> Add link to Choroba's blogpost and the solution to the extra task

challenge-014/daniel-mantovani/perl5/ch-1.pl, challenge-014/daniel-mantovani/perl5/ch-2.pl
=> my proposed solutions for challenge-014, p5 1 & 2

challenge-014/kian-meng-ang/perl5/ch-3.pl
=> Add challenge #03 answer

challenge-014/yozen-hernandez/blog.txt, challenge-014/yozen-hernandez/perl5/ch-1.pl, challenge-014/yozen-hernandez/perl5/ch-2.pl, challenge-014/yozen-hernandez/perl5/ch-2a.pl
Additional challenge 2a is included as `ch-2a.pl`
Blog will be up soon :)
=> Added solutions by Yozen Hernandez for challenges 1 and 2 for week 14

challenge-009/veesh-goldman/perl5/ch-1.pl, challenge-009/veesh-goldman/perl5/ch-2.pl, challenge-009/veesh-goldman/perl5/ch-3.pl, challenge-011/veesh-goldman/perl5/ch-01.pl, challenge-011/veesh-goldman/perl5/ch-02.pl, challenge-015/veesh-goldman/perl5/ch-01.pl, challenge-015/veesh-goldman/perl5/ch-02.pl, challenge-015/veesh-goldman/perl5/ch-extra.pl
I think I may actually write a blog post about this week, now that I'm back into things.
This is really fun, thank you so very much!
=> Finished this weeks, finally submitted some old ones I did

challenge-015/andrezgz/perl5/ch-1.pl, challenge-015/andrezgz/perl5/ch-2.pl
Hi @manwar, good challenges this week!
=> challenge-015 andrezgz solution

challenge-015/yozen-hernandez/blog.txt, challenge-015/yozen-hernandez/perl5/ch-1.pl, challenge-015/yozen-hernandez/perl5/ch-2.pl
I added two links to the blog.txt. Not sure if this is "legal"!
=> Added solutions by Yozen Hernandez for challenges 1 and 2 for week 15

challenge-015/simon-proctor/perl6/ch-1.p6
=> Strong and week primes

challenge-015/daniel-mantovani/perl5/ch-1.pl, challenge-015/daniel-mantovani/perl5/ch-2.pl
=> Branch for challenge 015

challenge-015/athanasius/perl5/ch-1.pl, challenge-015/athanasius/perl5/ch-2.pl, challenge-015/athanasius/perl5/ch-3.pl, challenge-015/athanasius/perl6/ch-1.p6, challenge-015/athanasius/perl6/ch-2.p6, challenge-015/athanasius/perl6/ch-3.p6
new file:   challenge-015/athanasius/perl5/ch-1.pl
new file:   challenge-015/athanasius/perl5/ch-2.pl
new file:   challenge-015/athanasius/perl5/ch-3.pl
new file:   challenge-015/athanasius/perl6/ch-1.p6
new file:   challenge-015/athanasius/perl6/ch-2.p6
new file:   challenge-015/athanasius/perl6/ch-3.p6
=> Perl 5 & 6 solutions to Tasks 1, 2, and 3 of Challenge #015

challenge-015/kian-meng-ang/perl5/ch-1.pl
=> Challenge #1 answer

challenge-015/duncan-c-white/README, challenge-015/duncan-c-white/perl5/ch-1.pl, challenge-015/duncan-c-white/perl5/ch-2.pl
Hi Manwar,
I didn't feel I used much elegance this week, there must have been more
elegant ways to do them, especially the cipher.  Ah well
cheers
duncan
=> added my solutions to this week's challenge

challenge-016/roger-bell-west/perl5/ch-1.pl, challenge-016/roger-bell-west/perl5/ch-2.pl
See Attack of the 50 Foot Blockchain for why.
=> Roger's solution. I hate everything to do with Bitcoin.

challenge-016/andrezgz/perl5/ch-1.pl
Hi @manwar, I've only managed to solve the first challenge of this week
=> challenge-016 andrezgz solution ch-1

challenge-016/daniel-mantovani/perl5/ch-1.pl, challenge-016/daniel-mantovani/perl5/ch-2.pl
=> my proposed solutions for challenge-016, p5 1 & 2

challenge-016/noud/perl6/ch-1.p6, challenge-016/noud/perl6/ch-2.p6
Problem 2 was a difficult problem! It took me some time to find a good solution for problem 2.
=> Solutions to challenge 016 problem 1 and 2 in perl6 by Noud

challenge-015/pyrrhlin/README, challenge-015/pyrrhlin/perl5/GetPrime.pm, challenge-015/pyrrhlin/perl5/Vigenere.pm, challenge-015/pyrrhlin/perl5/ch-1.pl, challenge-015/pyrrhlin/perl5/ch-2.pl, challenge-015/pyrrhlin/perl5/t1-prime-types.pl, challenge-015/pyrrhlin/perl5/t2-vig-cipher.pl, challenge-015/pyrrhlin/perl5/task1.txt, challenge-015/pyrrhlin/perl5/task2.txt
yeah, i'm late for week 15.  but it's cool.
=> Pyrrhlin pwc

challenge-016/veesh-goldman/blog.txt, challenge-016/veesh-goldman/perl5/ch-01.pl
I blogged this week, hope you enjoy it. The bitcoin challenge was too confusing for my limited schedule, and I didn't get around to the API, but hopefully next week I'll do everything again. With more blogging.
=> Solved one, bitcoin was too confusing

challenge-015/feng-chang/perl5/ch-1.pl, challenge-015/feng-chang/perl5/ch-2.pl, challenge-015/feng-chang/perl6/ch-1.p6, challenge-015/feng-chang/perl6/ch-2.p6, challenge-016/feng-chang/perl5/ch-1.p6, challenge-016/feng-chang/perl5/ch-1.pl, challenge-016/feng-chang/perl6/ch-2.p6, challenge-016/feng-chang/perl6/ch-2.pl
Feng Chang's solution for challenge #15 and #16
=> challenge 015 and 016

challenge-016/yozen-hernandez/blog.txt, challenge-016/yozen-hernandez/blog1.txt, challenge-016/yozen-hernandez/perl5/ch-1.pl, challenge-016/yozen-hernandez/perl5/ch-2.pl
=> Added solutions by Yozen Hernandez for challenges 1 and 2 for week 16

challenge-016/duncan-c-white/README, challenge-016/duncan-c-white/perl5/ch-1.pl, challenge-016/duncan-c-white/perl5/ch-2.pl
The first question was beautifully clear, and a fun question.
But the Bitcoin address decoding question was horrid - I got rather bogged down in understanding how Bitcoin addreses were encoded, after reading various web pages starting with the wiki page you suggested, but it really wasn't clear what the algorithm was, until I found a reference implementation already written in Perl 5.
I simply couldn't be bothered to rewrite this code, after all I wouldn't have known what code to write to solve the problem without reading the reference implementation, which meant that I'd already seen a perfectly good solution.  So I nicked it, and adapted it slightly.
=> imported my solutions (nb: I really didn't solve ch-2.pl myself, see README)

challenge-016/jaldhar-h-vyas/perl5/ch-1.pl, challenge-016/jaldhar-h-vyas/perl6/ch-1.p6
I've been travelling all weekend so I've had even less time than usual.  I've managed to complete the first task however.
=> Challenge 16 Problem 1 by Jaldhar H. Vyas

challenge-017/veesh-goldman/blog.txt, challenge-017/veesh-goldman/perl5/arrows.pl, challenge-017/veesh-goldman/perl5/ch-01.pl, challenge-017/veesh-goldman/perl5/ch-02.pl, challenge-017/veesh-goldman/perl6/ch-01.p6, challenge-017/veesh-goldman/perl6/first.p6, challenge-017/veesh-goldman/perl6/second.p6, challenge-017/veesh-goldman/perl6/third.p6
I did perl 5 and 6 this week, with a lengthy blog post on the topic. I'm gonna try and improve my perl5 answer for challenge 1 to see if I can get my up arrows working.
=> Cool answers, lengthy blog post

challenge-016/roger-bell-west/blog.txt
=> Challenge 16 blog post

challenge-017/andrezgz/perl5/ch-1.pl, challenge-017/andrezgz/perl5/ch-2.pl
Hi @manwar , I leave my solutions for this week challenge
=> challenge 017 andrezgz solutions

challenge-017/andrezgz/perl5/ch-2.pl
Minor fix, sorry for the inconvenience :)
=> challenge-017 ch-2 fix

challenge-017/noud/perl6/ch-1.p6, challenge-017/noud/perl6/ch-2.p6
Again two interesting challenges to be solved. I enjoyed finding solutions, and studying the solutions of the other participants. I'm looking forward to the challenges of next week. Keep up the good work!
=> Solutions for challenge 017 problem 1 and 2 in Perl 6 by Noud

challenge-017/feng-chang/perl5/ch-1.pl, challenge-017/feng-chang/perl5/ch-2.pl, challenge-017/feng-chang/perl6/ch-1.p6, challenge-017/feng-chang/perl6/ch-2.p6
challenge #017 solutions from Feng Chang
=> challenge 017

challenge-017/joelle-maslak/perl5/ch-1.pl, challenge-017/joelle-maslak/perl6/ch-1.p6
Implemented in P6 and then translated into P5.
=> Solutions for 17.1

challenge-017/athanasius/perl5/ch-1.pl, challenge-017/athanasius/perl5/ch-2.pl, challenge-017/athanasius/perl6/ch-1.p6, challenge-017/athanasius/perl6/ch-2.p6
new file:   challenge-017/athanasius/perl5/ch-1.pl
new file:   challenge-017/athanasius/perl5/ch-2.pl
new file:   challenge-017/athanasius/perl6/ch-1.p6
new file:   challenge-017/athanasius/perl6/ch-2.p6
=> Perl 5 and Perl 6 solutions to Tasks 1 & 2 of Challenge #017

challenge-017/daniel-mantovani/perl5/ch-1.pl, challenge-017/daniel-mantovani/perl5/ch-2.pl
=> my proposed solutions for challenge-017, p5 1 & 2

challenge-017/kian-meng-ang/perl5/ch-1.pl, challenge-017/kian-meng-ang/perl5/ch-2.pl
=> Add T1 and T2 for challenge 017

challenge-017/duncan-c-white/README, challenge-017/duncan-c-white/perl5/ch-1.pl, challenge-017/duncan-c-white/perl5/ch-2.pl
Hi Manwar,
Think I got these working, although neither question really inspired me.
=> imported my solutions for this week

challenge-018/roger-bell-west/perl5/1.pl, challenge-018/roger-bell-west/perl5/2.pl
In both cases there are CPAN implementations that will do _most_ of the work… but that wouldn't have been as much fun.
=> Solutions to #18

challenge-018/ozzy/perl6/ch-2b.p6, perl6/ch-2a.p6
Hi Mohammad, 
Here's my homework for this week's challenge 2 :-). Thanks for organizing!
Best regards,
Alexander
=> Threadless screw wk18ch2p6

challenge-018/andrezgz/perl5/ch-1.pl, challenge-018/andrezgz/perl5/ch-2.pl
Hi @manwar, I've started running perlcritic over the scripts to consider other practices
=> challenge-018 andrezgz solution

challenge-018/e-choroba/perl5/ch-1a.pl, challenge-018/e-choroba/perl5/ch-1b.pl, challenge-018/e-choroba/perl5/ch-2.pl
There are two different files for the first task, one of them searches
the longest common substring naively, the second one uses a suffix
tree.
The priority queue is also implemented in two different ways, but in
one file only: using an array or a heap.
=> Add solutions to 018 by E. Choroba

challenge-018/e-choroba/blogs.txt, challenge-018/e-choroba/perl5/ch-1a.pl, challenge-018/e-choroba/perl5/ch-2.pl
- small errors in the code translated from Java
- use a counter instead of a float priority
=> Fix solutions to 018 by E. Choroba, add a blog post (part 1)

challenge-018/roger-bell-west/blog.txt
=> Blog post for challenge 18

challenge-018/feng-chang/perl6/ch-1.p6, challenge-018/feng-chang/perl6/ch-2.p6
feng chang's perl6 solutions for challenge #018
=> challeng 018 perl6 solutions

challenge-018/daniel-mantovani/perl5/ch-1.pl, challenge-018/daniel-mantovani/perl5/ch-2.pl
=> my proposed solutions for challenge-018, p5 1 & 2

challenge-018/jaime/README, challenge-018/jaime/perl5/ch-1.pl, challenge-018/jaime/perl5/ch-2.pl
I learned about nesting arrays and hashmaps. This exercise allows me to create more complex structures within Perl 5.
=> Solutions to Challenge 018, #1 and #2.

challenge-018/athanasius/perl5/MyPriorityQueue.pm, challenge-018/athanasius/perl5/ch-1.pl, challenge-018/athanasius/perl5/ch-2.pl, challenge-018/athanasius/perl6/MyPriorityQueue.pm6, challenge-018/athanasius/perl6/ch-1.p6, challenge-018/athanasius/perl6/ch-2.p6
On branch branch-for-challenge-018
new file:   challenge-018/athanasius/perl5/MyPriorityQueue.pm
new file:   challenge-018/athanasius/perl5/ch-1.pl
new file:   challenge-018/athanasius/perl5/ch-2.pl
new file:   challenge-018/athanasius/perl6/MyPriorityQueue.pm6
new file:   challenge-018/athanasius/perl6/ch-1.p6
new file:   challenge-018/athanasius/perl6/ch-2.p6
=> Perl 5 & 6 solutions to Tasks 1 & 2 of Challenge #018

challenge-018/athanasius/perl6/MyPriorityQueue.pm6, challenge-018/athanasius/perl6/ch-1.p6, challenge-018/athanasius/perl6/ch-2.p6
modified:   challenge-018/athanasius/perl6/MyPriorityQueue.pm6
modified:   challenge-018/athanasius/perl6/ch-1.p6
modified:   challenge-018/athanasius/perl6/ch-2.p6
=> Fixed formatting by converting tabs to spaces

challenge-018/noud/perl6/ch-1.p6, challenge-018/noud/perl6/ch-2.p6
Thank you for organizing another interesting challenge. Here are my solutions for task 1 and 2. I'm looking forward to the solutions of the other participants.
=> Perl 6 solutions for task 1 and 2 of challenge 018 by Noud

challenge-018/kian-meng-ang/perl5/ch-1.pl
=> Add task #1 answer for challenge 018

challenge-018/duncan-c-white/README, challenge-018/duncan-c-white/perl5/PQ.pm, challenge-018/duncan-c-white/perl5/ch-1.pl, challenge-018/duncan-c-white/perl5/ch-2.pl
Hi Manwar,
Two nice questions to get my teeth into, especially the Priority Queue ADT.
=> added my (dcw803) solutions to challenge 18

challenge-018/yozen-hernandez/blog.txt, challenge-018/yozen-hernandez/blog1.txt, challenge-018/yozen-hernandez/perl5/ch-2.pl
Not much time for me this week on challenge 1. Might have to submit it later. Blogs are also not up yet!
=> Added solutions by Yozen Hernandez for challenge 2 for week 18

challenge-018/jaldhar-h-vyas/perl5/ch-2.pl, challenge-018/jaldhar-h-vyas/perl6/ch-2.p6
Ugh ran out of time again.  Problem one and blog to follow later tonight.
=> challenge 18 by Jaldhar H. Vyas

challenge-019/andrezgz/perl5/ch-1.pl, challenge-019/andrezgz/perl5/ch-2.pl
Hi @manwar, this week solutions were pretty straightforward!
=> challenge-019 andrezgz solution

challenge-019/jaime/README, challenge-019/jaime/perl5/ch-1.pl, challenge-019/jaime/perl5/ch-2.pl
This week's solutions make use of the PERL standard library and standard UNIX programs to speed up the development time.
=> Challenge 019, Task #1 and #2

challenge-019/noud/perl6/ch-1.p6, challenge-019/noud/perl6/ch-2.p6
I'm looking forward to the solutions of the others. Keep up the good work!
=> Solutions to challenge 19 problem 1 and 2 in perl 6 by Noud

challenge-019/feng-chang/perl5/ch-1.pl, challenge-019/feng-chang/perl5/ch-2.pl, challenge-019/feng-chang/perl6/ch-1.p6, challenge-019/feng-chang/perl6/ch-2.p6
Feng Chang's solutions for challenge #019
=> #019 solutions

challenge-019/kian-meng-ang/perl5/ch-1.pl, challenge-019/kian-meng-ang/perl5/ch-2.pl
=> Added task 1 and 2 solution

challenge-019/athanasius/perl5/ch-1.pl, challenge-019/athanasius/perl5/ch-2.pl, challenge-019/athanasius/perl6/ch-1.p6, challenge-019/athanasius/perl6/ch-2.p6
new file:   challenge-019/athanasius/perl5/ch-1.pl
new file:   challenge-019/athanasius/perl5/ch-2.pl
new file:   challenge-019/athanasius/perl6/ch-1.p6
new file:   challenge-019/athanasius/perl6/ch-2.p6
=> Solutions in Perl 5 & 6 to Tasks 1 & 2

challenge-019/duncan-c-white/README, challenge-019/duncan-c-white/perl5/ch-1.pl, challenge-019/duncan-c-white/perl5/ch-2.pl
Hi Manwar,
Two nice questions, prretty easy to do both of them.  Keep up the good work.
cheers
duncan
=> added my solutions to challenge 19

challenge-018/jaldhar-h-vyas/blog.txt, challenge-018/jaldhar-h-vyas/perl5/ch-1.pl, challenge-018/jaldhar-h-vyas/perl5/ch-2.pl, challenge-018/jaldhar-h-vyas/perl6/ch-1.p6, challenge-018/jaldhar-h-vyas/perl6/ch-2.p6
The missing problem from challenge 18 plus URL to my blog post.
=> Challenge 018

challenge-020/andrezgz/perl5/ch-1.pl, challenge-020/andrezgz/perl5/ch-1.sh, challenge-020/andrezgz/perl5/ch-2.pl
Hi @manwar, my solutions for the first 2 tasks (plus a one-liner for the first one)
=> challenge-020 andrezgz solution

challenge-020/roger-bell-west/perl6/ch-2.p6
I'll try to stop pestering you now…
=> More idiomatic, using a SetHash rather than a list

challenge-020/simon-proctor/perl6/ch-1.p6, challenge-020/simon-proctor/perl6/ch-2.p6
Hope you are enjoying (or enjoyed) the conference. Here's this weeks challenge.
=> Challenge 20 all done.

challenge-020/feng-chang/perl5/ch-1.pl, challenge-020/feng-chang/perl5/ch-2.pl, challenge-020/feng-chang/perl6/ch-1.p6, challenge-020/feng-chang/perl6/ch-2.p6
Feng Chang's challenge #020 solution
=> #020 solutions

challenge-020/athanasius/perl5/ch-1.pl, challenge-020/athanasius/perl5/ch-2.pl, challenge-020/athanasius/perl6/ch-1.p6, challenge-020/athanasius/perl6/ch-2.p6
On branch branch-for-challenge-020
new file:   challenge-020/athanasius/perl5/ch-1.pl
new file:   challenge-020/athanasius/perl5/ch-2.pl
new file:   challenge-020/athanasius/perl6/ch-1.p6
new file:   challenge-020/athanasius/perl6/ch-2.p6
=> Perl 5 & 6 solutions to Tasks 1 & 2

challenge-020/noud/perl6/ch-1.p6, challenge-020/noud/perl6/ch-2.p6
I'm proud of my solution for problem 2. For the problem I create a lazy list with all Amicable Numbers. Moreover I use an anonymous cache handle to speed up the calculations. Making it possible to compute the first three Amicable Numbers within a couple of seconds. (on my laptop at least)
I'm looking forward to the challenges of next week!
=> Solutions to challenge 20 problem 1 and 2 in Perl 6 by Noud

challenge-020/kian-meng-ang/perl5/ch-1.pl, challenge-020/kian-meng-ang/perl5/ch-2.pl
=> Add task 1 & 2 answer

challenge-020/adam-russell/blog.txt, challenge-020/adam-russell/perl5/ch-1.pl, challenge-020/adam-russell/perl5/ch-2.pl, challenge-020/adam-russell/perl6/ch-1.rk, challenge-020/adam-russell/perl6/ch-2.rk
=> Challenge 020

challenge-020/duncan-c-white/README, challenge-020/duncan-c-white/perl5/ch-1.pl, challenge-020/duncan-c-white/perl5/ch-2.pl
Hi Manwar,
Two very simple but nicely specified problems this week.  A pleasure to do them both.
cheers
duncan
=> Checked in my (dcw)'s solutions for this week

challenge-020/veesh-goldman/blog.txt, challenge-020/veesh-goldman/perl5/ch-01.sh, challenge-020/veesh-goldman/perl5/ch-02.pl, challenge-020/veesh-goldman/perl5/t/factors.t
I had a lot of fun this week. Hope I made the deadline
=> Added answers to challenge 20. Many regexes

challenge-020/andrezgz/perl5/ch-1.pl, challenge-020/andrezgz/perl5/ch-1.sh, challenge-020/andrezgz/perl5/ch-2.pl
I've copy-pasted the scripts from the previous challenge as a baseline and forgot to adjust the url
=> andrezgz challenge-020 fix challenge url in comment

challenge-021/andrezgz/perl5/ch-1.pl, challenge-021/andrezgz/perl5/ch-2.pl
Hi @manwar, the task about standarized url was nice!
=> Challenge 021

challenge-021/daniel-mantovani/perl5/ch-1.pl, challenge-021/daniel-mantovani/perl5/ch-2.pl
=> my proposed solutions for challenge-021, p5 1 & 2

challenge-021/noud/perl6/ch-1.p6, challenge-021/noud/perl6/ch-2.p6
* Problem 1 has been solved with continuous fractions. One of the fastest ways for approximating Euler's number.
* It's probably possible to make Problem 2 more efficient. I'm looking forward to see how others solved this problem.
=> Solutions to challenge 021 problem 1 and 2 in Perl 6 by Noud

challenge-021/kian-meng-ang/perl5/ch-1.pl
=> Add task 1 for weekly challenge 021

challenge-021/athanasius/perl5/ch-1.pl, challenge-021/athanasius/perl6/ch-1.p6
new file:   challenge-021/athanasius/perl5/ch-1.pl
new file:   challenge-021/athanasius/perl6/ch-1.p6
=> Perl 5 & 6 solutions to Task 1 of Challenge #021

challenge-022/simon-proctor/perl6/ch-1.p6
Nice and simple really. Can you mention me to Laurent? ;)
=> Finding 'sexy' primes.

challenge-022/yet-ebreo/perl5/ch-1.pl, challenge-022/yet-ebreo/perl5/ch-2.pl
Fixed some bug and added  comments
=> code update

challenge-022/yet-ebreo/perl6/ch-1.p6, challenge-022/yet-ebreo/perl6/ch-2.p6
Add perl6 solution for ch022-1
=> Add perl6 solution for ch022-1

challenge-022/andrezgz/perl5/ch-1.pl
Hi @manwar, only the first task this week
=> challenge-022 andrezgz solution

challenge-022/daniel-mantovani/perl5/ch-1.pl
Sorry too late to try solving lzw compression challenge today!
BR,
=> my proposed solutions for challenge-022, p5 1

challenge-022/kian-meng-ang/perl5/ch-1.pl
=> Add t1 answer

challenge-022/athanasius/perl5/ch-1.pl, challenge-022/athanasius/perl5/ch-2.pl, challenge-022/athanasius/perl6/ch-1.p6, challenge-022/athanasius/perl6/ch-2.p6
On branch branch-for-challenge-022
new file:   challenge-022/athanasius/perl5/ch-1.pl
new file:   challenge-022/athanasius/perl5/ch-2.pl
new file:   challenge-022/athanasius/perl6/ch-1.p6
new file:   challenge-022/athanasius/perl6/ch-2.p6
=> Perl 5 & 6 solutions to Tasks 1 & 2 of Challenge #022

challenge-023/andrezgz/perl5/ch-1.pl, challenge-023/andrezgz/perl5/ch-2.pl
Hi @manwar , this week my solution has arrived early! Hope I've understood correctly the first task :)
=> challenge-023 andrezgz solution

challenge-023/simon-proctor/perl6/ch-1.p6
Sorry @manwar I thought of a neater way of testing my value.
=> Move the test for n into the parameters

challenge-023/randy-lauen/perl5/ch-1.pl, challenge-023/randy-lauen/perl5/ch-2.pl, challenge-023/randy-lauen/perl5/ch-3.pl, challenge-023/randy-lauen/perl6/ch-1.p6, challenge-023/randy-lauen/perl6/ch-2.p6, challenge-023/randy-lauen/perl6/ch-3.p6
This week's tasks were easier, which was very welcome after the tough (but fun) compression algorithm last week! Thanks, @manwar.
=> Solutions for challenge 23 tasks

challenge-023/andrezgz/perl5/ch-3.pl
Me again this week! I've managed to solve the API task for the first time :)
=> challenge-023 andrezgz task3 solution

challenge-023/daniel-mantovani/perl5/ch-1.pl, challenge-023/daniel-mantovani/perl5/ch-2.pl
=> my proposed solutions for challenge-023, p5 1 & 2

challenge-023/noud/perl6/ch-1.p6, challenge-023/noud/perl6/ch-2.p6
I had not time last week to do challenge 022. But this week I could find some time again to work on the Perl Weekly Challenges. Here are to solutions for challenge 023 in Perl 6.
=> Solutions to challenge 023 problem 1 and 2 in Perl 6 by Noud

challenge-022/duncan-c-white/perl5/LZW.pm, challenge-022/duncan-c-white/perl5/testlzw.pl, challenge-023/duncan-c-white/README, challenge-023/duncan-c-white/perl5/MakePrimes.pm, challenge-023/duncan-c-white/perl5/ch-1.pl, challenge-023/duncan-c-white/perl5/ch-2.pl, challenge-023/duncan-c-white/perl5/ch-3.pl
Hi Manwar,
Very early solutions from me - did them in the week actually.  I had a go at all 3 - including
the api question. Ppretty easy to do all of them.
cheers
duncan
=> hi manwar, early solutions - including the api question this time

challenge-023/athanasius/perl5/ch-1.pl, challenge-023/athanasius/perl5/ch-2.pl, challenge-023/athanasius/perl5/ch-3.pl, challenge-023/athanasius/perl6/ch-1.p6, challenge-023/athanasius/perl6/ch-2.p6
On branch branch-for-challenge-023
new file:   challenge-023/athanasius/perl5/ch-1.pl
new file:   challenge-023/athanasius/perl5/ch-2.pl
new file:   challenge-023/athanasius/perl5/ch-3.pl
new file:   challenge-023/athanasius/perl6/ch-1.p6
new file:   challenge-023/athanasius/perl6/ch-2.p6
=> Perl 5 & 6 solutions to Tasks #1 & #2, and Perl 5 solution to Task #3.

challenge-023/kian-meng-ang/perl5/ch-1.pl, challenge-023/kian-meng-ang/perl5/ch-2.pl
=> Add task 1 & 2 for challenge 023

challenge-024/andrezgz/perl5/ch-1.pl, challenge-024/andrezgz/perl5/ch-2.pl, challenge-024/andrezgz/perl5/father_sons.txt, challenge-024/andrezgz/perl5/herdsman_bull.txt, challenge-024/andrezgz/perl5/lion_mouse.txt, challenge-024/andrezgz/perl5/wolf_lamb.txt
Hi @manwar these are the solutions for the first 2 tasks of this week challenge. I've added some txt files with Aesop's Fables to use them with ch-2.pl
=> challenge-024 andrezgz solution

challenge-024/noud/perl6/ch-1.p6, challenge-024/noud/perl6/ch-2.p6
I understand the idea behind problem 1. Unfortunately Rakudo doesn't complain often. It's not really a clang for perl6. ;)
Looking forward to the new challenges next week!
=> Solutions for challenge 023 problem 1 and 2 in Perl 6 by Noud

challenge-024/kian-meng-ang/perl5/ch-1.pl
=> Add task 01

challenge-024/e-choroba/blog.txt
plus the shortest script that doesn't do anything special but doesn't
throw an error either.
=> Add a link to E. Choroba's blog post

challenge-025/yet-ebreo/perl5/ch-1.pl, challenge-025/yet-ebreo/perl5/ch-2.pl
Added perl5 solution for task#2
Updated solution for task#1
=> Added perl5 solution for task#2

challenge-025/yet-ebreo/perl5/ch-1.pl, challenge-025/yet-ebreo/perl5/ch-2.pl, challenge-025/yet-ebreo/perl6/ch-1.p6, challenge-025/yet-ebreo/perl6/ch-2.p6
=> Added Perl6 solutions

challenge-025/yet-ebreo/perl5/ch-1.pl, challenge-025/yet-ebreo/perl6/ch-1.p6, challenge-025/yet-ebreo/perl6/ch-2.p6
=> Improvement in perl6 solution

challenge-025/yet-ebreo/perl6/ch-1.p6
Sorry for the multiple pull requests
=> Perl6 Ch#1 runtime is now under a minute

challenge-025/andrezgz/perl5/ch-1.pl, challenge-025/andrezgz/perl5/ch-2.pl
Hi @manwar, both tasks this week were really challenging!
=> challenge-025 andrezgz solution

challenge-025/athanasius/perl5/ch-1.pl, challenge-025/athanasius/perl6/ch-1.p6
On branch branch-for-challenge-025
new file:   challenge-025/athanasius/perl5/ch-1.pl
new file:   challenge-025/athanasius/perl6/ch-1.p6
=> Perl 5 & 6 solutions to Task #1 of the Perl Weekly Challenge #025

challenge-025/jaldhar-h-vyas/perl5/ch-1.pl
Barely any time at all this week.  Hopefully I can get the rest in early next week.
=> Challenge 25 task 1 by Jaldhar H. Vyas.

challenge-026/e-choroba/perl5/ch-1.pl
Introduction of a new secret operator, +=()=, that could be called
"Voyager approaching Saturn".
=> Add solution to 026/1 (stones & jewels) by E. Choroba

challenge-026/andrezgz/perl5/ch-1.pl, challenge-026/andrezgz/perl5/ch-1.sh, challenge-026/andrezgz/perl5/ch-2.pl
Hi @manwar I've got a one-liner for the first one!
=> challenge-026 andrezgz solution

challenge-026/markus-holzer/perl6/ch-1.p6, challenge-026/markus-holzer/perl6/ch-2.p6
=> Revised the code to make it leaner. Added comments.

challenge-026/markus-holzer/perl6/ch-1.p6, challenge-026/markus-holzer/perl6/ch-2.p6
=> Better wording, now enforcing the alphabet

challenge-026/athanasius/perl5/ch-1.pl, challenge-026/athanasius/perl5/ch-2.pl, challenge-026/athanasius/perl6/ch-1.p6, challenge-026/athanasius/perl6/ch-2.p6
On branch branch-for-challenge-026
new file:   perl5/ch-1.pl
new file:   perl5/ch-2.pl
new file:   perl6/ch-1.p6
new file:   perl6/ch-2.p6
=> Perl 5 & 6 solutions to Tasks 1 & 2 of the Perl Weekly Challenge #026

challenge-026/daniel-mantovani/perl5/ch-1.pl, challenge-026/daniel-mantovani/perl5/ch-2.pl
=> my proposed solutions for challenge-026, p5 1 & 2

challenge-027/andrezgz/perl5/ch-1.pl, challenge-027/andrezgz/perl5/ch-2.pl
Hi @manwar, hope the second task meets the requirement
=> challenge-027 andrezgz solution

challenge-027/e-choroba/blog.txt, challenge-027/e-choroba/perl5/ch-1.pl
=> Add blogpost for 027 by E. Choroba

challenge-027/duncan-c-white/README, challenge-027/duncan-c-white/perl5/ch-1.pl, challenge-027/duncan-c-white/perl5/ch-2.pl
Hi Manwar,  Had a go at both challenges, used Gnuplot (optionally) to visualize the results in both occasions.  The second challenge was rather ill-defined, but I've interpreted it in a particular way, a sequence of "x += 10" type input lines, then I track all values of each variable over simulated time (assuming line N happens at time N), then display the results.
=> imported my challenge-027 solutions..

challenge-028/simon-proctor/perl6/ch-2.p6
Might make it more fancy later :)
=> First draft.

challenge-028/veesh-goldman/perl5/ch-01.pl
I actually just learned about the character class `[[^:ascii:]]`, so it was fun to use it!
=> Solved challenge 1

challenge-028/dave-jacoby/blog.txt, challenge-028/dave-jacoby/ch-2.html
Should this count as two? We'll see
=> And Blogged It

challenge-028/andrezgz/perl5/ch-1.pl, challenge-028/andrezgz/perl5/ch-2.pl
Hi @manwar, my solutions for this week tasks
=> challenge-028 andrezgz solution

challenge-028/kivanc-yazan/perl5/ch-1.pl, challenge-028/kivanc-yazan/perl5/ch-2.pl
=> Add solution for week 28

challenge-028/athanasius/perl5/ch-1.pl, challenge-028/athanasius/perl5/ch-2.pl, challenge-028/athanasius/perl6/ch-1.p6, challenge-028/athanasius/perl6/ch-2.p6
On branch branch-for-challenge-028
new file:   challenge-028/athanasius/perl5/ch-1.pl
new file:   challenge-028/athanasius/perl5/ch-2.pl
new file:   challenge-028/athanasius/perl6/ch-1.p6
new file:   challenge-028/athanasius/perl6/ch-2.p6
=> Perl 5 & 6 solutions to Tasks 1 & 2 of the Perl Weekly Challenge #028

challenge-028/duncan-c-white/README, challenge-028/duncan-c-white/perl5/ch-1.pl, challenge-028/duncan-c-white/perl5/ch-2.pl
ch-2.pl is a rather cool 7-segment led based digital clock (that resizes properly too)
=> incorporated my solutions.. ch-1.pl is ridiculous, but

challenge-029/noud/perl6/ch1.p6, challenge-029/noud/perl6/ch2.p6, challenge-029/noud/perl6/make.sh, challenge-029/noud/perl6/rot13.c
I like the tasks of this week. I found concise solutions to both of the tasks. I'm especially impressed with how much ease it is to call c functions within perl6. Thank you!
=> Solutions to challenge 29 tasks 1 and 2 in Perl 6 by Noud

challenge-029/andrezgz/perl5/ch-1.pl, challenge-029/andrezgz/perl5/ch-2.pl
Hi @manwar, the C task was completely new to me but I've learned tons of interesting stuff. The other one was more like try/error. Sure, I didn't catch all the "extreme cases" but I'm confident I've got a decent solution
=> challenge-029 andrezgz solution

challenge-029/duncan-c-white/README, challenge-029/duncan-c-white/perl5/ch-1.pl, challenge-029/duncan-c-white/perl5/ch-2.pl
two interesting questions, made me think.  Haven't used XS or Inline::C before, gave the latter a go  For the first question, did it from whole cloth. Tricky!
=> imported my solutions..

challenge-029/mark-senn/perl6/ch-1.p6
If I've done the git stuff right this is ok to merge.
=> added Mark Senn's solution to PWC 029 task 1 in Perl 6

challenge-029/ozzy/perl6/ch-1.p6
When staring at the ceiling last night, two little things kept me awake :-)
=> minor corrections

challenge-030/simon-proctor/perl6/ch-1.p6, challenge-030/simon-proctor/perl6/ch-2.p6
Sorry I missed last week. Been a bit under the weather. But here's part one for this week.
=> Challenge 1 : Christmas sundays

challenge-027/jaldhar-h-vyas/blog.txt, challenge-027/jaldhar-h-vyas/perl5/ch-1.pl, challenge-027/jaldhar-h-vyas/perl5/ch-2.pl, challenge-027/jaldhar-h-vyas/perl6/ch-1.p6, challenge-027/jaldhar-h-vyas/perl6/ch-2.p6
Sorry, this is extremely late I know.  I went to India for two weeks and ended up having no internet connectivity the whole time.
=> Challenge 27 by Jaldhar H. Vyas

challenge-028/jaldhar-h-vyas/blog.txt, challenge-028/jaldhar-h-vyas/perl5/ch-1.sh, challenge-028/jaldhar-h-vyas/perl5/ch-2.pl, challenge-028/jaldhar-h-vyas/perl6/ch-1.p6, challenge-028/jaldhar-h-vyas/perl6/ch-2.p6
The next one of my missing entries.
=> Challenge 28 by Jaldhar H. Vyas

challenge-029/jaldhar-h-vyas/blog.txt, challenge-029/jaldhar-h-vyas/c/Makefile, challenge-029/jaldhar-h-vyas/c/hello.c, challenge-029/jaldhar-h-vyas/c/hello.h, challenge-029/jaldhar-h-vyas/perl5/Hello.i, challenge-029/jaldhar-h-vyas/perl5/Makefile, challenge-029/jaldhar-h-vyas/perl5/ch-1.pl, challenge-029/jaldhar-h-vyas/perl5/ch-2.pl, challenge-029/jaldhar-h-vyas/perl6/Hello.pm6, challenge-029/jaldhar-h-vyas/perl6/ch-1.p6, challenge-029/jaldhar-h-vyas/perl6/ch-2.p6
And I should be all caught up now.
=> Challenge 29 by Jaldhar H. Vyas

challenge-030/andrezgz/perl5/ch-1.pl, challenge-030/andrezgz/perl5/ch-1.sh, challenge-030/andrezgz/perl5/ch-2.pl
Hi @manwar, got a one-liner for the first task :)
=> challenge-030 andrezgz solution

challenge-030/jaldhar-h-vyas/blog.txt, challenge-030/jaldhar-h-vyas/perl5/ch-1.pl, challenge-030/jaldhar-h-vyas/perl5/ch-2.pl, challenge-030/jaldhar-h-vyas/perl6/ch-1.sh, challenge-030/jaldhar-h-vyas/perl6/ch-2.p6
=> Challenge 30 by Jaldhar H. Vyas

challenge-030/andrezgz/perl5/ch-2-r.pl
Hi @manwar, I was personally challenged by ndelucca to get a recursive solution for the second task
=> challenge-030 andrezgz task2 recursive

challenge-030/kivanc-yazan/perl5/ch-1.pl, challenge-030/kivanc-yazan/perl5/ch-2.pl
=> Add Kivanc solutions for w-030

challenge-030/athanasius/perl5/ch-1.pl, challenge-030/athanasius/perl5/ch-2.pl, challenge-030/athanasius/perl6/ch-1.p6, challenge-030/athanasius/perl6/ch-2.p6
On branch branch-for-challenge-030
new file:   challenge-030/athanasius/perl5/ch-1.pl
new file:   challenge-030/athanasius/perl5/ch-2.pl
new file:   challenge-030/athanasius/perl6/ch-1.p6
new file:   challenge-030/athanasius/perl6/ch-2.p6
=> Perl 5 & 6 solutions to Tasks 1 & 2 of the Perl Weekly Challenge #030

challenge-030/duncan-c-white/README, challenge-030/duncan-c-white/perl5/ch-1.pl, challenge-030/duncan-c-white/perl5/ch-2.pl
=> two very straighforward problems this week.. no particular subtlety..

challenge-031/maxim-kolodyazhny/perl5/ch-1.pl
=> improved challenge-031.1 by Maxim Kolodyazhny

challenge-031/tyler-limkemann/README, challenge-031/tyler-limkemann/ch-1.p6, challenge-031/tyler-limkemann/ch-2.p6
=> Tyler's solutions for #31

challenge-031/andrezgz/perl5/ch-1.pl, challenge-031/andrezgz/perl5/ch-2.pl
Hi @manwar, I was very close to solve both tasks with eval, but changed my mind for the second one just before commiting
=> challenge-031 andrezgz solution

challenge-031/e-choroba/perl5/ch-1.pl, challenge-031/e-choroba/perl5/ch-2.pl
=> Add solutions to 031 (Division by zero + Dynamic variable name)

challenge-031/athanasius/perl5/ch-1.pl, challenge-031/athanasius/perl5/ch-2.pl, challenge-031/athanasius/perl6/ch-1.p6, challenge-031/athanasius/perl6/ch-2.p6
On branch branch-for-challenge-031
new file:   challenge-031/athanasius/perl5/ch-1.pl
new file:   challenge-031/athanasius/perl5/ch-2.pl
new file:   challenge-031/athanasius/perl6/ch-1.p6
new file:   challenge-031/athanasius/perl6/ch-2.p6
=> Perl 5 & 6 solutions to Tasks 1 & 2 of Challenge #031

challenge-031/noud/perl6/ch1.p6, challenge-031/noud/perl6/ch2.p6
Another interesting challenge. Instead of using the obvious try/catch, I solved problem 1 in an unusual way. I compute the division in the stereographic projection. In the stereographic projection it is possible to divide by zero, which gives the north pole as result. Equivalent to checking if the denominator is zero, is to check if the division is equal to the north pole (the complex number i) in the stereographic projection.
=> Solutions to challenge 031 problem 1 and 2 in Perl 6

challenge-031/duncan-c-white/README, challenge-031/duncan-c-white/perl5/ch-1.pl, challenge-031/duncan-c-white/perl5/ch-2.pl
this is the "eval" challenge, yes?
=> imported my solutions to challenge 31

challenge-030/jaldhar-h-vyas/perl6/ch-1.sh
Doh! Laurent correctly points out my Perl6 solution for task 1 should compare the day of week with 7 not 0 as in Perl5.
=> Challenge 30 by Jaldhar H. Vyas: typo fix.

challenge-032/simon-proctor/all.csv, challenge-032/simon-proctor/all.txt, challenge-032/simon-proctor/perl6/ch-2.p6
Sooooo there's a lot to it but that's because I decided to make it read the data from challenge one (in both csv and spaced output) and add all the sorting options.
The bit to draw the graph is pretty simple really. 
There are a few neat bits in there though. Have fun.
=> Graph all the things

challenge-032/simon-proctor/perl6/ch-2.p6
Small fix as the thing to look for the available width my not work.
=> Added a test incase the widt check fails

challenge-032/e-choroba/perl5/ch-1.pl, challenge-032/e-choroba/perl5/ch-1.sh, challenge-032/e-choroba/perl5/ch-2.pl
Plus a standard, many years old bash script to count instances.
=> Solve 032 (ASCII Bar chart + Count instances)

challenge-032/andrezgz/perl5/ch-1.pl, challenge-032/andrezgz/perl5/ch-2.pl
Hi @manwar, extra credit and  bonus for the additional options on each task
=> challenge-032 andrezgz solution

challenge-032/ndelucca/perl5/ch-1.pl, challenge-032/ndelucca/perl5/ch-2.pl, challenge-032/ndelucca/perl5/example1.txt, challenge-032/ndelucca/perl5/example2.txt
I really enjoyed this challenge, thank you.
=> challenge-032/ndelucca

challenge-032/noud/perl6/ch1.p6, challenge-032/noud/perl6/ch2.p6
Thank you for the challenge of this week!
=> Solutions to challenge 32 problem 1 and 2 in Perl 6 by Noud

challenge-032/athanasius/perl5/ch-1.pl, challenge-032/athanasius/perl5/ch-2.pl, challenge-032/athanasius/perl6/ch-1.p6, challenge-032/athanasius/perl6/ch-2.p6
On branch branch-for-challenge-032
new file:   challenge-032/athanasius/perl5/ch-1.pl
new file:   challenge-032/athanasius/perl5/ch-2.pl
new file:   challenge-032/athanasius/perl6/ch-1.p6
new file:   challenge-032/athanasius/perl6/ch-2.p6
=> Perl 5 & 6 solutions to Tasks 1 & 2 of Challenge #032

challenge-032/duncan-c-white/README, challenge-032/duncan-c-white/perl5/ch-1.pl, challenge-032/duncan-c-white/perl5/ch-2.pl
I like these questions, histograms of hashrefs..
=> my solutions for challenge 32.. done fast and dirty

challenge-033/simon-proctor/perl6/ch-1.p6, challenge-033/simon-proctor/perl6/ch-2.p6
This gives the counts of all the letters even if none occur.
=> Challenge 1 : A-Z Counter

challenge-033/simon-proctor/perl6/ch-1.p6, challenge-033/simon-proctor/perl6/ch-2.p6
Updated the challenge 2 so it'll do any size of table.
=> Update Challenge 2 to specify the size of chart to draw

challenge-033/petr-roubicek/perl5/ch-1.pl, challenge-033/petr-roubicek/perl5/ch-2.pl
new file:   challenge-033/petr-roubicek/perl5/ch-2.pl
=> 	new file:   challenge-033/petr-roubicek/perl5/ch-1.pl

challenge-033/ndelucca/perl5/ch-2-recursive.pl
Added a recursive oriented solution to challenge 2
=> challenge-033/ndelucca

challenge-033/noud/perl6/ch1.p6, challenge-033/noud/perl6/ch2.p6, challenge-033/noud/perl6/sample.txt
Looking forward to the solutions of others and to the challenge of next week. Have a nice weekend!
=> Solutions to challenge 33 task 1 and 2 in Perl 6 by Noud

challenge-033/athanasius/perl5/ch-1.pl, challenge-033/athanasius/perl5/ch-2.pl, challenge-033/athanasius/perl6/ch-1.p6, challenge-033/athanasius/perl6/ch-2.p6
On branch branch-for-challenge-033
new file:   perl5/ch-1.pl
new file:   perl5/ch-2.pl
new file:   perl6/ch-1.p6
new file:   perl6/ch-2.p6
=> Perl 5 & 6 solutions to Tasks 1 & 2 of Challenge #033

challenge-033/duncan-c-white/README, challenge-033/duncan-c-white/perl5/ch-1.pl, challenge-033/duncan-c-white/perl5/ch-2.pl
=> imported my (dcw803) solutions to challenge 33, pretty easy this week

challenge-033/markus-holzer/perl6/ch-2.p6
=> consistency.

challenge-034/noud/perl6/ch1.p6, challenge-034/noud/perl6/ch2.p6
Two short but interesting problems. Thank you!
=> Solution to challenge 34 problem 1 and 2 in perl 6 by Noud

challenge-034/jaldhar-h-vyas/blog.txt, challenge-034/jaldhar-h-vyas/perl5/ch-2.pl, challenge-034/jaldhar-h-vyas/perl6/ch-1.p6, challenge-034/jaldhar-h-vyas/perl6/ch-2.p6
Missing perl5/challenge 1.  Will be along shortly.
=> Challenge 34 by Jaldhar H. Vyas (missing one.)

challenge-034/jaldhar-h-vyas/perl5/ch-1.pl
=> Challenge 34 by Jaldhar H. Vyas: the missing challenge.

challenge-035/roger-bell-west/perl5/ch-1.pl, challenge-035/roger-bell-west/perl5/ch-2.pl, challenge-035/roger-bell-west/perl6/ch-1.p6, challenge-035/roger-bell-west/perl6/ch-2.p6
=> Fixed inter-word separator to seven "0"

challenge-035/andrezgz/perl5/ch-1.pl, challenge-035/andrezgz/perl5/ch-2.pl
Hi @manwar, I've tried to recover from badly formed morse code but my attempts were unsuccessful
=> challenge-035 andrezgz solution

README.md
I should have read the whole thing first
=> fixed typo 'branh'->'branch'

challenge-035/petr-roubicek/perl5/ch-1.pl, challenge-035/petr-roubicek/perl5/ch-2.pl, challenge-035/petr-roubicek/perl5/ch-2_2.pl, challenge-035/petr-roubicek/perl5/text.txt
new file:   challenge-035/petr-roubicek/perl5/ch-2.pl
new file:   challenge-035/petr-roubicek/perl5/ch-2_2.pl
new file:   challenge-035/petr-roubicek/perl5/text.txt
=> 	new file:   challenge-035/petr-roubicek/perl5/ch-1.pl

challenge-035/burkhard-nickels/README, challenge-035/burkhard-nickels/blogs.txt, challenge-035/burkhard-nickels/perl5/ch-1.pl, challenge-035/burkhard-nickels/perl5/ch-2.pl
Solution for PWC #35 from Burkhard Nickels
=> Solution for PWC #35 from Burkhard Nickels

challenge-036/andrezgz/ch-1.pl, challenge-036/andrezgz/ch-2.pl
Hi @manwar, the VIN validation task was hard cause the definitions about it are somewhat imprecise on wikipedia. The Knapsack Problem was great and I've been able to find a solution, checking all the possible combinations due to the small amount of input.
=> challenge-036 andrezgz solution

challenge-036/andrezgz/perl5/ch-2.pl
It's me again @manwar, I've added some comments and fix others to the second task solution
=> challenge-036 andrezgz task 2 minor fixes

challenge-036/saiftynet/README, challenge-036/saiftynet/perl5/ch-1.pl, challenge-036/saiftynet/perl5/ch-2.pl
Not sure if I am doing it right...
=> Uploading my first challenge attempt Challenge 36

challenge-036/petr-roubicek/perl5/ch-1.pl, challenge-036/petr-roubicek/perl5/ch-2.pl
new file:   challenge-036/petr-roubicek/perl5/ch-2.pl
=> 	new file:   challenge-036/petr-roubicek/perl5/ch-1.pl

challenge-036/jaldhar-h-vyas/perl/ch-1.pl, challenge-036/jaldhar-h-vyas/raku/ch-1.p6
Sorry late again.  I will send you part 2 and the blog later tonight or tomorrow.
=> Challenge 36 part 1 by Jaldhar H. Vyas

challenge-037/saiftynet/perl5/ch-1.pl, challenge-037/saiftynet/perl5/ch-2.pl
=> Answers uploaded for ch037

challenge-037/duncan-c-white/README, challenge-037/duncan-c-white/perl5/ch-1-Date-Manip.pl, challenge-037/duncan-c-white/perl5/ch-1-in-postscript.ps, challenge-037/duncan-c-white/perl5/ch-1.pl, challenge-037/duncan-c-white/perl5/ch-2.pl
including 3 versions of ch-1 (the first challenge): 2 in Perl (one using a few Date::Manip functions, the other implementing those functions ourselves, i.e. doing leap year calculations, calculating number of days in each month, and finding out what day of the week a given date is by starting on a known data/day-of-week pair and rolling forward to the date you're interested in).
The 3rd version is a translation of the second Perl version into Postscript.  Yes, POSTSCRIPT, the language mainly used inside printers for page layout, is actually a full blown programming language.  It's a relatively straightforward translation of the Perl code into Postscript, but before that you need approx 3 pages of support routines - functions to append strings (!), and to produce a series of debugging …
=> imported my solutions to challenge037

challenge-037/daniel-mita/js/ch-1.js
May as well throw on another language while I'm at it
=> Add JS solution for 037-1

challenge-037/noud/perl6/ch1.p6
Due to time constrains I could only manage to solve problem 1. I hope to have more time next week.
=> Solution challenge 37 problem 1 in Perl 6 by Noud

challenge-038/andrezgz/perl5/ch-1.pl, challenge-038/andrezgz/perl5/ch-2.pl
Hi @manwar, this week solutions were straightforward. Regex for Task#1 and code reused from one of the first challenges for the other.
=> challenge-038 andrezgz solution

challenge-038/saiftynet/perl5/ch-1.pl, challenge-038/saiftynet/perl5/ch-1.sh, challenge-038/saiftynet/perl5/ch-2.pl
=> Another couple of challenges accepted

challenge-038/noud/perl6/ch1.p6, challenge-038/noud/perl6/ch2.p6
Hello Sajid,
The pre-christmas stress at work seems to get lower. That means I have a bit more time to work out the latest perl weekly challenges. ;) Again two interesting problems. I like problems where I can use grammar to solve them (problem 1). Thank you!
Best,
Noud
=> Solutions to challenge 38 problem 1 and 2 by Noud in Raku

challenge-001/ruben-westerberg/README, challenge-001/ruben-westerberg/perl/ch-1.pl, challenge-001/ruben-westerberg/perl/ch-2.sh, challenge-001/ruben-westerberg/raku/ch-1.p6, challenge-001/ruben-westerberg/raku/ch-2.sh
=> Finally added solutions to Week 1!

challenge-038/duncan-c-white/README, challenge-038/duncan-c-white/perl5/ch-1.pl, challenge-038/duncan-c-white/perl5/ch-2.pl
no extra clever bits this week:-)
=> imported my solutions for challenge 38

challenge-039/andrezgz/perl5/ch-1.pl, challenge-039/andrezgz/perl5/ch-2.pl, challenge-039/andrezgz/perl5/guest_book_1.txt, challenge-039/andrezgz/perl5/guest_book_2.txt
Hi @mawar, it was nice to see my proposal as a task! Thanks a lot
The first one made me battle for a while because I considered noncontiguous periods of time registered on the guest book.
=> challenge-039 andrezgz solution

challenge-035/daniel-mita/perl6/ch-1.p6, challenge-035/daniel-mita/perl6/ch-2.p6
Cleanup for older solution, as I misunderstood captures in signatures
=> Remove unneeded pipes

challenge-039/noud/perl6/ch1.p6, challenge-039/noud/perl6/ch2.p6, challenge-039/noud/perl6/guestbook.txt
=> Solution to challenge 39 task 1 and 2 in Raku by Noud

challenge-039/saiftynet/perl5/ch-1.pl, challenge-039/saiftynet/perl5/ch-2.pl
The data in **Task 1** has only overlapping times which merge into on cotinuous block.  The logs are also conveniently sequential.   The response therefore includes modifications to the data to allow handling of non-continuous data (periods with no residents) and out-of-sequence data entries.
**Task 2** response has been extended to convert many of Perl's internal operators, including string handling. Absent operations (e.g. asin etc) are also added, some coded as RPN scripts.  Stack manipulation operations (del, dup, swap)  are also included. Over 50 operations are included in roughly 100 lines of code.
[Blog regarding these submissions](http://blogs.perl.org/users/saif/2019/12/the-times-you-want-to-avoid-the-short-cuts.html)
=> Task-1: Handles non-contiguous data Task-2: Offers 50+ RPN operations

challenge-039/duncan-c-white/README, challenge-039/duncan-c-white/perl5/Tuple.pm, challenge-039/duncan-c-white/perl5/ch-1.pl, challenge-039/duncan-c-white/perl5/guestbook, challenge-039/duncan-c-white/perl5/guestbook2
(to show RPN expression order), so here's just the part 1 solution..
=> ran out of time to get a Postscript code generator working..

challenge-039/adam-russell/perl/ch-1.pl
I noticed I had some bugs! must've happened in my hurry to get the solutions in on time. This seems to fix the issues.
=> updated solution for challenge 039

challenge-038/andrezgz/perl5/ch-1.pl
Quick regex fix after reading Kian-Meng Ang's review
https://perlweeklychallenge.org/blog/review-challenge-038/
=> challenge-038 andrezgz ch-1 regex fix

challenge-040/simon-proctor/perl6/ch-1.p6, challenge-040/simon-proctor/perl6/ch-2.p6
=> Wasn't feeling great last week, but I'm better (ish) today.

challenge-040/saiftynet/perl5/ch-1.pl, challenge-040/saiftynet/perl5/ch-2.pl
nice and staright forward for Christmas
=> saiftynet's responses for the "Happy Lights" Challenges

challenge-040/wanderdoc/README, challenge-040/wanderdoc/perl5/ch-1.pl, challenge-040/wanderdoc/perl5/ch-2.pl
Dear Anwar, here my first attempt to participate.
Yours,
wanderdoc
amateur Perl hacker
=> Perl Weekly Challenge 040

challenge-040/andrezgz/perl5/ch-1.pl, challenge-040/andrezgz/perl5/ch-2.pl
Hi @manwar , have a merry christmas!
=> challenge-040 andrezgz solution

challenge-039/e-choroba/perl5/ch-1.pl, challenge-039/e-choroba/perl5/ch-2.pl
Guest House Lights use Set::IntSpan which I learned from RFC: The Lazy Manager's Calendar with Inversion Lists: http://perlmonks.org/index.pl?node_id=908453
=> Add solution to 039 by E. Choroba (Guest House Lights + RPN)

challenge-040/duncan-c-white/README, challenge-040/duncan-c-white/perl5/ch-1.pl, challenge-040/duncan-c-white/perl5/ch-2.pl
Very simple tasks this week, fortunate as I left them to the last few hours:-)
=> imported my (dcw803) solutions

challenge-040/wanderdoc/R/ch-1.R, challenge-040/wanderdoc/R/ch-2.R
Dear Anwar,
I hope I did not break the rules to use the choroba's idea in R solution (ch-2). Otherwise please discard it!
Yours,
wanderdoc
=> Just tried the same in R.

challenge-040/adam-russell/blog.txt, challenge-040/adam-russell/perl/ch-1.pl, challenge-040/adam-russell/perl/ch-2.pl
Final challenge of 2019. Happy new year!
=> solutions for challenge 040

challenge-041/andrezgz/perl5/ch-1.pl, challenge-041/andrezgz/perl5/ch-2-fib.pl, challenge-041/andrezgz/perl5/ch-2.pl
Hi @manwar, both challenges were very similar! So I've solved really quickly this time!
=> challenge-041 andrezgz solution

challenge-041/andrezgz/perl5/ch-1.pl
=> challenge-041 ch-1 prime fix

challenge-023/andrezgz/perl5/ch-2.pl
Found an issue when checking if 1 or lower numbers were prime and its prime factors
=> challenge-023 ch-2 minor issue

challenge-041/walt-mankowski/perl5/ch-1.pl
Small tweak to the code I submitted yesterday.
=> break out of the loop when $i > $n

challenge-041/kivanc-yazan/.gitignore, challenge-041/kivanc-yazan/perl5/ch-1.pl, challenge-041/kivanc-yazan/perl5/ch-2.pl, challenge-041/kivanc-yazan/python3/ch-1.py, challenge-041/kivanc-yazan/python3/ch-2.py
=> My solutions for W041

challenge-041/duncan-c-white/README, challenge-041/duncan-c-white/perl5/MakePrimes.pm, challenge-041/duncan-c-white/perl5/PrimeFactors.pm, challenge-041/duncan-c-white/perl5/ch-1.pl, challenge-041/duncan-c-white/perl5/ch-2.pl
=> imported my challenge-041 submissions, 2 easy ones this week

challenge-041/noud/perl6/ch-1.p6, challenge-041/noud/perl6/ch-2.p6
Happy new year! I wish Perl Weekly Challenge all the best!
=> Solutions to challenge 41 task 1 and 2 in Raku by Noud

challenge-041/saiftynet/perl5/ch-1.pl, challenge-041/saiftynet/perl5/ch-2.pl
Trying multiple methods of improving performance.  The tasks make only minor demands on the code performance, but with  extra demands ( e.g. looking for 200 Leonardo numbers or 1,000,000 factorisations) simple code becomes too slow.  These solutions each try three ways  to improve performance.
=> Stashing 'n caching in hashes for smashing performance

challenge-042/wanderdoc/perl5/ch-1.pl, challenge-042/wanderdoc/perl5/ch-2.pl
=> Challenge 042: Solutions in Perl 5.

challenge-042/alicia-bielsa/perl/ch-1.pl, challenge-042/alicia-bielsa/perl/ch-2.pl
=> challenge-042

challenge-042/saiftynet/perl5/ch-1.pl, challenge-042/saiftynet/perl5/ch-2.pl
Another week, another set of challenges, with only minor extensions to the challenges this time
=> Brackets and Bases solutions submitted

challenge-042/peter-scott/perl/ch-1.sh, challenge-042/peter-scott/perl/ch-2.pl, challenge-042/peter-scott/perl/ch-2.pl~
=> Branch for challenge 042

challenge-042/noud/perl6/ch-1.p6, challenge-042/noud/perl6/ch-2.p6
As always, two interesting tasks! Have a nice weekend!
=> Challenge 042 noud

challenge-042/jaldhar-h-vyas/blog.txt, challenge-042/jaldhar-h-vyas/perl/ch-1.sh, challenge-042/jaldhar-h-vyas/perl/ch-2.pl, challenge-042/jaldhar-h-vyas/raku/ch-1.sh, challenge-042/jaldhar-h-vyas/raku/ch-2.p6
It's been a difficult past two months but I'm back.  Now I'll start working on all the ones I've missed.
=> Challenge 42 by Jaldhar H. Vyas

challenge-042/duncan-c-white/README, challenge-042/duncan-c-white/perl5/ch-1.pl, challenge-042/duncan-c-white/perl5/ch-2.pl
=> imported my solutions to this week's challenge

challenge-043/e-choroba/perl5/ch-1a.pl, challenge-043/e-choroba/perl5/ch-1b.pl, challenge-043/e-choroba/perl5/ch-2.pl
There are two solutions for task 1: one uses combinatorics, the second
one is much simpler and faster.
The function in task 2 returns the number in its base if only one
parameter is specified, or in base 10 otherwise.
=> Add solutions to 043 by E. Choroba

challenge-042/andrezgz/perl/ch-1.pl, challenge-042/andrezgz/perl/ch-2.pl
Hi @manwar, I've missed the deadline. Just getting up to date
=> challenge-042 andrezgz solution

challenge-043/andrezgz/perl/ch-1.pl, challenge-043/andrezgz/perl/ch-2.pl
Hi @manwar, I'm back on track. Discovering self-descriptive number for higher bases was tough. The formula from Wikipedia works like a charm :)
=> challenge-043 andrezgz solution

challenge-043/saiftynet/perl5/ch-1.pl, challenge-043/saiftynet/perl5/ch-2.pl
Thanks for keeping up the challenges
=> Rings and Self-Descriptive Numbers

challenge-043/jaldhar-h-vyas/blog.txt, challenge-043/jaldhar-h-vyas/perl/ch-1.pl, challenge-043/jaldhar-h-vyas/perl/ch-2.pl, challenge-043/jaldhar-h-vyas/raku/ch-1.p6, challenge-043/jaldhar-h-vyas/raku/ch-2.p6
A little late but here you go.  Still working on the ones I missed.
=> Challenge 43 by Jaldhar H. Vyas

challenge-044/simon-proctor/raku/ch-1.p6, challenge-044/simon-proctor/raku/ch-2.p6
I hope things at home are going OK and your Dad is good.
No rush on this but I do think it's a nice solution. I may even blog about it.
=> Challenge number 1. Functional Raku for the win

challenge-044/peter-scott/perl/ch-1.pl
=> Just time for the first one

challenge-044/dave-jacoby/perl/ch-1.pl, challenge-044/dave-jacoby/perl/ch-1a.pl, challenge-044/dave-jacoby/perl/ch-2.pl
I hope your father is feeling better.
=> Challenge 44

challenge-044/simon-proctor/raku/ch-2.p6
Sorry Mohammed, for some reason (probably left over from the first challenge) I went with 100 not 200. Fixed it.
=> Helps if I use the correct final number.

challenge-044/andrezgz/perl/ch-1.pl, challenge-044/andrezgz/perl/ch-2.pl
Hi @manwar. This week tasks were really challenging to me. I think I've proposed a decent solution for each one. Looking forward to compare with others!
=> challenge-044 andrezgz solution

challenge-044/saiftynet/perl/ch-1.pl, challenge-044/saiftynet/perl/ch-2.pl
Hope your dad is getting better mate...
=> Blending Numbers and operations together

challenge-044/daniel-mantovani/perl/ch-1.pl, challenge-044/daniel-mantovani/perl/ch-2.pl
=> my proposed solutions for challenge-044, p5 1 & 2

challenge-044/noud/raku/ch-1.p6, challenge-044/noud/raku/ch-2.p6
Mohammad, I'm sorry to hear about the illness of your father. I wish you and your father all the best and I hope he recovers quickly.
=> Solutions to challenge 44 task 1 and 2 in Raku by Noud

challenge-044/e-choroba/blog.txt, challenge-044/e-choroba/perl/ch-1.pl, challenge-044/e-choroba/perl/ch-2.pl
Also, update the solutions: don't skip the last mask in task 1 and
don't use an additional variable for a negligible reduction of the hash.
=> Add a link to E. Choroba's blog about 044

challenge-044/duncan-c-white/README, challenge-044/duncan-c-white/perl/ch-1.pl, challenge-044/duncan-c-white/perl/ch-2.pl
two nice easy but interesting challenges this week
=> imported my solutions to challenge 044

challenge-045/peter-scott/perl/ch-1.sh
=> Another one-liner

challenge-045/andrezgz/perl/ch-1.pl, challenge-045/andrezgz/perl/ch-2.pl
Hi @manwar, I've made a quine for the second task. I'm proud of such an ugly code :)
=> challenge-045 andrezgz solution

challenge-045/e-choroba/blog.txt, challenge-045/e-choroba/perl/ch-2a.pl
Also, shorten one of the solutions.
=> Add a link to E. Choroba's blog about 045

challenge-045/alicia-bielsa/perl/ch-1.pl, challenge-045/alicia-bielsa/perl/ch-2.pl
=> challenge-045

challenge-045/maxim-kolodyazhny/perl/ch-1.pl, challenge-045/maxim-kolodyazhny/perl/ch-2.pl, challenge-045/maxim-kolodyazhny/perl/t/ch-1.t
Hello!
Nice that PWC keep going and there is so many new players!
=> challenge-045, pt. 1

challenge-045/duncan-c-white/README, challenge-045/duncan-c-white/perl/ch-1.pl, challenge-045/duncan-c-white/perl/ch-2.pl
two nice easy but interesting challenges this week.. did decoding as well as encoding in the first task
=> imported my solutions

challenge-046/e-choroba/perl/ch-1.pl, challenge-046/e-choroba/perl/ch-2a.pl, challenge-046/e-choroba/perl/ch-2b.pl, challenge-046/e-choroba/perl/ch-2c.pl
=> Add solutions to 046 (Cryptic Message + Is the Room Open?)

challenge-046/simon-proctor/raku/ch-1.p6, challenge-046/simon-proctor/raku/ch-2.p6
Hope you're well. I'm somewhat tired :)
=> Here we go

challenge-046/andrezgz/perl/ch-1.pl, challenge-046/andrezgz/perl/ch-2.pl
Hi @manwar, similar algorithms for both tasks this week
=> challenge-046 andrezgz solution

challenge-046/saiftynet/Perl/ch-1.pl, challenge-046/saiftynet/Perl/ch-2.pl
Testing EZPWC...some bugs ironed out
=> Testing EZPWC

challenge-046/alicia-bielsa/perl/ch-1.pl, challenge-046/alicia-bielsa/perl/ch-2.pl
=> challenge 046

challenge-046/noud/blog.txt, challenge-046/noud/raku/ch-1.p6, challenge-046/noud/raku/ch-2.p6
I liked task #2 so much I wrote a short blog post about it, see blog.txt. A very well picked challenge! It took me quite a while before I figured out how to do it. Thanks!
=> Challenge 046 noud

challenge-046/athanasius/perl/ch-1.pl, challenge-046/athanasius/perl/ch-2.pl
On branch branch-for-challenge-046
new file:   challenge-046/athanasius/perl/ch-1.pl
new file:   challenge-046/athanasius/perl/ch-2.pl
=> Perl solutions to Tasks 1 & 2 of the Perl Weekly Challenge #046

challenge-047/andrezgz/perl/ch-1.pl, challenge-047/andrezgz/perl/ch-2.pl
Hi @manwar, I've reused code from previous challenges for the first task. I was close to a one-liner for the second one.
=> challenge-047 andrezgz solution

challenge-010/e-choroba/perl5/ch-1a.pl, challenge-047/e-choroba/perl/MyRoman.pm, challenge-047/e-choroba/perl/ch-1.pl, challenge-047/e-choroba/perl/ch-2.pl
Code to handle Roman Numberals extracted from 010.
=> Solve 047 (Roman Calculator and Gapful Number) by E. Choroba

challenge-047/duncan-c-white/README, challenge-047/duncan-c-white/perl/Roman.pm, challenge-047/duncan-c-white/perl/ch-1.pl, challenge-047/duncan-c-white/perl/ch-2.pl, challenge-047/duncan-c-white/postscript/ch-2.ps
I like getting into the "Guest" section too:-)
=> please find my solutions - both in perl, ch-2 in postscript as well

challenge-044/jaldhar-h-vyas/blog.txt, challenge-044/jaldhar-h-vyas/c++/ch-2.cc, challenge-044/jaldhar-h-vyas/perl/ch-1.pl, challenge-044/jaldhar-h-vyas/perl/ch-2.pl, challenge-044/jaldhar-h-vyas/raku/ch-1.p6, challenge-044/jaldhar-h-vyas/raku/ch-2a.p6, challenge-044/jaldhar-h-vyas/raku/ch-2b.p6
Slowly working my way through all my missing weeks.
=> Challenge 44 by Jaldhar H. Vyas

challenge-047/alicia-bielsa/perl/ch-1.pl, challenge-047/alicia-bielsa/perl/ch-2.pl, challenge-047/alicia-bielsa/raku/ch-2.p6
Perl solutions and first attempt to raku challenge 2
=> challenge 047

challenge-047/jaldhar-h-vyas/perl/ch-2.pl, challenge-047/jaldhar-h-vyas/raku/ch-2.p6
My solutions for problem 1 have a couple of bugs so they will be submitted a little late.
=> Challenge 47 by Jaldhar H. Vyas - problem 2

challenge-048/peter-scott/perl/ch-2.pl, challenge-048/peter-scott/perl/ch-2.pl~
A bit too long for a one-liner
=> A bit too long for a one-liner

challenge-048/simon-proctor/raku/ch-1.p6, challenge-048/simon-proctor/raku/ch-2.p6
I tried brute force on challlenge 2 at first. Then I got smart.
=> Here's this weeks :)

challenge-047/jaldhar-h-vyas/blog.txt, challenge-047/jaldhar-h-vyas/perl/ch-1.pl, challenge-047/jaldhar-h-vyas/raku/ch-1.p6
So here are the other solutions for challenge 47.  I implemented actual addition and subtraction of Roman numerals which I don't think anyone did.  Do check it out and the accompanying blog post.
=> Challenge 47 by Jaldhar H. Vyas - problem 1 and blog.

challenge-048/luca-ferrari/raku/ch-2.p6
I realized that task 2 could have been done with a simpler approach.
I've already blogged about this approach, so it is fine to keep the old solution I already submitted (and merged).
=> Smarter implementation of task 2.

challenge-048/ianrifkin/README, challenge-048/ianrifkin/perl/ch-1.pl, challenge-048/ianrifkin/perl/ch-2.pl
Challenge 048 solutions by IanRifkin
=> Submitting challenge048 - my first submission (IanRifkin)

challenge-048/andrezgz/perl/ch-1.pl, challenge-048/andrezgz/perl/ch-2.pl
Hi @manwar , both tasks were great for improving the solution after the first try
=> challenge-048 andrezgz solution

challenge-048/xkr47/README, challenge-048/xkr47/raku/ch-1.p6, challenge-048/xkr47/raku/ch-2.p6
=> xkr47 / 048

challenge-048/noud/raku/ch-1.p6, challenge-048/noud/raku/ch-2.p6
To interesting problems! I managed to write to compact and concise solutions. Enjoy the weekend!
=> Solution to challenge 048 task 1 and 2 in Raku by Noud

challenge-048/xkr47/rust/Cargo.toml, challenge-048/xkr47/rust/ch-1.rs, challenge-048/xkr47/rust/ch-2.rs
I already participated in Raku language but thought I'd challenge myself a bit as I'm learning the Rust language as well.. So if you can consider accepting Rust as a language, here's my shot at it. I chose to implement it very similarly to my Raku version to make them comparable. If you can't, I guess interested people can read this PR instead :)
=> xkr47 / 048 / Rust version!

challenge-049/simon-proctor/raku/ch-1.p6, challenge-049/simon-proctor/raku/ch-2.p6
This is not Thread safe though it would be simple enough to make it so using OO::Monitors on the methods.
=> Challenge 49

challenge-047/arne-sommer/raku/lib/Number/Roman.rakumod, challenge-047/arne-sommer/raku/lib/Number/Roman/OO.rakumod
Source: https://raku-musings.com/code/roman-gap.zip
Page:   https://raku-musings.com/roman-gap.html
=> Add lib/ at Arne's request

challenge-049/kevin-colyer/raku/ch-1.p6, challenge-049/kevin-colyer/raku/ch-2.p6
=> PWC 49 complete

challenge-049/e-choroba/blog.txt, challenge-049/e-choroba/perl/ch-2.pl, challenge-049/e-choroba/perl/ch-2b.pl
Also, clean up the code according to the blog post.
=> Add blog post by E. Choroba about 049: Smallest Multiple + LRU Cache

challenge-049/duncan-c-white/README, challenge-049/duncan-c-white/perl/cache-input, challenge-049/duncan-c-white/perl/ch-1.pl, challenge-049/duncan-c-white/perl/ch-2.pl
two interesting challenges this week..
=> added this week's challenge solutions

challenge-049/jaldhar-h-vyas/blog.txt, challenge-049/jaldhar-h-vyas/perl/ch-1.pl, challenge-049/jaldhar-h-vyas/raku/ch-1.p6
My LRU cache has problems so that will be along shortly.  Here are the other bits.
=> Challenge 49 by Jaldhar H. Vyas - task 1 and blog.

challenge-049/ianrifkin/perl/ch-1.pl, challenge-049/ianrifkin/perl/ch-2.pl
=> Branch for challenge 049

challenge-050/sol-demuth/perl/ch-1.pl, challenge-050/sol-demuth/perl/ch-2.pl
ch-1.pl = merge intervals
ch-2.pl = noble integer
=> challenge 050 - sol demuth

challenge-050/e-choroba/perl/ch-1.pl
Singles can be represented by another bitmask value if we ignore it
when checking for left and right boundaries.
=> Use enum instead of bitmask literals, remove the nested hash

challenge-050/saiftynet/perl/ch-1.pl
removed unnecessary loop in ch-1.pl
=> Challenge-050 solutions by saiftynet

challenge-050/e-choroba/blog.txt, challenge-050/e-choroba/perl/ch-1.pl
Also, remove the useless condition from the code.
=> Add blogpost from E. Choroba(050: Merge Intervals + Noble Integer)

challenge-050/noud/raku/ch-1.p6, challenge-050/noud/raku/ch-2.p6
Sorry for skipping last week challenge. I was attending a conference.
I spend my last hour on the airport waiting for the next flight while trying to solve this challenge. The solution for task 1 is a bit of a mess. It's probably possible to find a more neat solution. For task 2, I think Noble integers are always unique, i.e. there cannot be two (unique) Noble integers in the same list. In the comments you find a formal proof for my statement.
Looking forward to the challenge of next week! Enjoy the weekend!
=> Solutions to challenge 050 task 1 and 2 in Raku by Noud

challenge-049/kevin-colyer/raku/ch-1.p6, challenge-050/kevin-colyer/raku/ch-1.p6, challenge-050/kevin-colyer/raku/ch-2.p6, challenge-050/kevincolyer
=> Branch 050

challenge-050/duncan-c-white/README, challenge-050/duncan-c-white/perl/ch-1.pl, challenge-050/duncan-c-white/perl/ch-2.pl
just the basic 2 Perl solutions this week, cos today's my birthday
=> incorporated my solutions for this week's challenges

challenge-050/alicia-bielsa/perl/ch-1.pl, challenge-050/alicia-bielsa/perl/ch-2.pl, challenge-050/alicia-bielsa/raku/ch-2.p6
Sorry, forgot to do pull request yesterday. :-(
=> challenge 050 perl

challenge-051/phillip-harris/perl/ch-2.pl
This was challenge was fun, thanks.
=> Challenge-051 solutions by phillip-harris

challenge-049/andrezgz/perl/ch-1.pl, challenge-049/andrezgz/perl/ch-2.pl
Hi @manwar, I've been busy. I'm trying to get up-to-date
=> challenge-049 andrezgz solution

challenge-051/walt-mankowski/perl/ch-1.pl, challenge-051/walt-mankowski/perl/ch-2.pl
This is my perl code for challenge 51
=> Branch for challenge 051

challenge-039/andrezgz/perl5/ch-1.pl
Hi @manwar, when I was coding the solution for the first task of challenge 50 (Merge Intervals), I reminded doing something similar some time ago. So I grep my older solutions and I've found the guest house task in challenge 39. A little omission appeared in a condition while I was reviewing it, but now is fixed.
=> challenge-039 andrezgz task1 fix

challenge-050/andrezgz/perl/ch-1.pl
Hi @manwar, I've reviewed my solution and the command-line arguments for task 1 were incorrectly joined. Fixed that.
=> challenge-050 andrezgz task1 fix

challenge-051/saiftynet/perl/ch-2.pl
=> Challenge-051 solutions by saiftynet...edit commit message and code

challenge-051/kevin-colyer/raku/ch-1.p6, challenge-051/kevin-colyer/raku/ch-2.p6, challenge-051/kevincolyer
=> Branch 051

challenge-051/alicia-bielsa/perl/ch-1.pl, challenge-051/alicia-bielsa/perl/ch-2.pl, challenge-051/alicia-bielsa/raku/ch-1.p6
=> challenge 051 perl and raku

challenge-051/duncan-c-white/README, challenge-051/duncan-c-white/perl/ch-1.pl, challenge-051/duncan-c-white/perl/ch-2.pl
just the basic 2 Perl solutions this week, 2 interesting questions
=> committed my Perl solutions to challenge 51

challenge-051/e-choroba/blog.txt, challenge-051/e-choroba/perl/ch-2.pl
Also, simplify the solution of the second task: we don't need to pad
the array.
=> Add blog post by E. Choroba about 051 (3Sum and Colourful Numbers)

challenge-052/e-choroba/perl/ch-1.pl, challenge-052/e-choroba/perl/ch-2.pl
Stepping Numbers are optimized, try increasing the length to 16.
Lucky Winner is implemented as an interactive game. The starting
player can always win unless they make a mistake, so the computer
always wins if it starts; if you start, it looses unless you make a
mistake.
=> Add solutions to 052 (Stepping Numbers + Lucky Winner) by E. Choroba

challenge-052/saiftynet/perl/ch-1.pl, challenge-052/saiftynet/perl/ch-2.pl
=> Challenge-052 solutions by saiftynet

challenge-052/cheok-yin-fung/perl/ch-2.pl
matching the question statement more
=> an improved version of my code 

challenge-052/noud/raku/ch-1.p6, challenge-052/noud/raku/ch-2.p6
Interesting challenges this week! Especially task 2. When you figure out that it is a min-max game, the solution becomes elegant. Looking forward to the challenges of next week.
=> Solution for challenge 052 task 1 and 2 in Raku by Noud

challenge-052/andrezgz/perl/ch-1.pl, challenge-052/andrezgz/perl/ch-2.pl
Hi @manwar, just today I've found time to do the tasks. There's a lot of movement these days, and the this challenge is a way to escape from all of that
=> challenge-052 andrezgz solution

challenge-052/e-choroba/blog.txt, challenge-052/e-choroba/perl/ch-2.pl
Also, fix the Lucky Winner according to it: init_arg was 0 instead of
undef and turns were implemented twice.
=> Add link to a blog post by E. Choroba

challenge-052/athanasius/perl/ch-1.pl, challenge-052/athanasius/perl/ch-2.pl
On branch branch-for-challenge-052
new file:   challenge-052/athanasius/perl/ch-1.pl
new file:   challenge-052/athanasius/perl/ch-2.pl
=> Perl solutions to Tasks 1 & 2 of the Perl Weekly Challenge #052

challenge-052/duncan-c-white/README, challenge-052/duncan-c-white/perl/ch-1.pl, challenge-052/duncan-c-white/perl/ch-2.pl
task 1 was simple, task 2 rather badly defined, if I've understood it right: first player always wins, both players try to ensure that they can take the £2 coin
=> imported my solutions for challenge 52..

challenge-053/simon-proctor/raku/ch-1.p6, challenge-053/simon-proctor/raku/ch-2.p6
Lots of brute force and ignorance as normal.
=> Challenge 53 in the bag.

challenge-053/dave-jacoby/node/ch-1.js, challenge-053/dave-jacoby/node/ch-2.js, challenge-053/dave-jacoby/perl/ch-1.pl, challenge-053/dave-jacoby/perl/ch-2.pl, challenge-053/dave-jacoby/perl/rotate_matrix.pl, challenge-053/dave-jacoby/rust/ch-1.rs, challenge-053/dave-jacoby/rust/ch-2.rs
=> mostly the vowel one

challenge-053/andrezgz/perl/ch-1.pl, challenge-053/andrezgz/perl/ch-2.pl
Hi @manwar, we're on quarantine & holiday so I did a session of online pair programming with a friend to solve this challenge
=> challenge-053 andrezgz solution

challenge-053/athanasius/perl/ch-1.pl, challenge-053/athanasius/perl/ch-2.pl, challenge-053/athanasius/raku/ch-1.raku, challenge-053/athanasius/raku/ch-2.raku
On branch branch-for-challenge-053
new file:   challenge-053/athanasius/perl/ch-1.pl
new file:   challenge-053/athanasius/perl/ch-2.pl
new file:   challenge-053/athanasius/raku/ch-1.raku
new file:   challenge-053/athanasius/raku/ch-2.raku
=> Perl and Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #053

challenge-053/noud/raku/ch-1.p6, challenge-053/noud/raku/ch-2.p6
=> Solution to challenge 53 task 1 and 2 in Raku by Noud

challenge-053/duncan-c-white/README, challenge-053/duncan-c-white/perl/ch-1.pl, challenge-053/duncan-c-white/perl/ch-2.pl
task 1 was simple so I livened it up slightly via a Matrix class (inline Perl package); task 2 was vaguely interesting, as a sort of recursive generator
=> imported this week's challenges; nearly forgot to do them..

challenge-054/simon-proctor/raku/ch-1.p6
=> I added check that k is in range

challenge-054/simon-proctor/raku/ch-2-extra.p6
My attempt at the extra credits.... it takes a while.
I tried caching the chains but that was eating memory so I decided to go with parallel tasks instead.
=> So here's a thing

challenge-054/andrezgz/perl/ch-1.pl, challenge-054/andrezgz/perl/ch-2.pl
Hi @manwar, this week tasks where tough and defying. I really enjoyed solving them
=> challenge-054 andrezgz solution

challenge-054/peter-meszaros/perl/ch-1.pl, challenge-054/peter-meszaros/perl/ch-2.pl
Please find my solution for ch-054.
=> Challange 054 by Peter Meszaros

challenge-054/athanasius/perl/ch-1.pl, challenge-054/athanasius/perl/ch-2.pl, challenge-054/athanasius/raku/ch-1.raku, challenge-054/athanasius/raku/ch-2.raku
On branch branch-for-challenge-054
new file:   challenge-054/athanasius/perl/ch-1.pl
new file:   challenge-054/athanasius/perl/ch-2.pl
new file:   challenge-054/athanasius/raku/ch-1.raku
new file:   challenge-054/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #054

challenge-054/kevin-colyer/raku/ch-1.p6, challenge-054/kevin-colyer/raku/ch-2.p6, challenge-054/kevincolyer
Correctly added the challenge solutions this time
=> completed challenge

challenge-054/saiftynet/perl/ch-1.pl, challenge-054/saiftynet/perl/ch-2.pl
=> Challenge-054 solutions by saiftynet

challenge-054/noud/raku/ch-1.p6, challenge-054/noud/raku/ch-2.p6
Hello Mohammad,
I hope you're doing fine in these weird and unpredictable times. In this PR you find the solution of challenge 054 task 1 and 2 in Raku.
Looking forward to the next challenges!
Noud
=> Solution to challenge 054 task 1 and 2 in Raku by Noud

challenge-055/andrezgz/perl/ch-1.pl, challenge-055/andrezgz/perl/ch-2.pl
Hi @manwar, thanks for keeping this proyect alive!
=> challenge-055 andrezgz solution

challenge-055/noud/raku/ch-1.p6, challenge-055/noud/raku/ch-2.p6
Both tasks were more difficult than I thought they would be. I'm curious to find out if there were smart (i.e. shorter) solutions to these tasks. Looking forward to the tasks of next week!
=> Solutions for challenge 055 task 1 and 2 in Raku by Noud

challenge-055/duncan-c-white/README, challenge-055/duncan-c-white/perl/ch-1.pl, challenge-055/duncan-c-white/perl/ch-2.pl
Two nice questions this week, for some reason I found the second task quite hard to get my head round in order to start thinking about it, but easy after I'd started..
=> imported my solutions for this week's tasks

challenge-055/jaredor/README, challenge-055/jaredor/perl/ch-1.pl, challenge-055/jaredor/perl/ch-2.pl
Removed non-core debugging library.
=> update to ch-2.pl

challenge-056/kevin-colyer/raku/ch-1.p6, challenge-056/kevin-colyer/raku/ch-2.p6, challenge-056/kevincolyer
=> Branch 056

challenge-056/simon-proctor/raku/ch-2.p6
So now we get 
```
1         
┌─┴─────┐   
2       3   
┌┴┐   ┌──┴─┐ 
3 4   4    5 
┌┴─┐ ┌┴┐
10 15 6 7
```
=> Use line art characters

challenge-056/andrezgz/perl/ch-1.pl, challenge-056/andrezgz/perl/ch-2.pl
Hi @manwar, cool tasks this week. The one with the tree was harder. Do you know a simple way to pass the tree nodes as arguments to the script?
=> challenge-056 andrezgz solution

challenge-055/jaredor/blog.txt, challenge-055/jaredor/blog1.txt, challenge-056/jaredor/blog.txt, challenge-056/jaredor/perl/pwc056t1.pl, challenge-056/jaredor/perl/pwc056t2.pl
jaredor submissions for PWC 056
=> New branch

challenge-056/athanasius/perl/ch-1.pl, challenge-056/athanasius/perl/ch-2.pl, challenge-056/athanasius/raku/ch-1.raku
On branch branch-for-challenge-056
new file:   challenge-056/athanasius/perl/ch-1.pl
new file:   challenge-056/athanasius/perl/ch-2.pl
new file:   challenge-056/athanasius/raku/ch-1.raku
=> Perl and Raku solutions to Challenge #056

challenge-056/noud/raku/ch-1.p6, challenge-056/noud/raku/ch-2.p6
Enjoy the last part of Sunday! Looking forward to the challenge of next week.
=> Solutions to challenge 056 task 1 and 2 in Raku by Noud

challenge-056/duncan-c-white/README, challenge-056/duncan-c-white/perl/ch-1.pl, challenge-056/duncan-c-white/perl/ch-2.pl
first one very simple; second one surprisingly complex (I had to build the machinery for representing a binary tree first, parsing it from a string form on the command line, before writing the path-sum-finding code)
=> imported my solutions for this week's tasks..

challenge-056/e-choroba/blog.txt, challenge-056/e-choroba/perl/ch-1.pl, challenge-056/e-choroba/perl/ch-1b.pl
Also, fix the order of indices in the solution to Task 1, and add
another solution that works for repeated numbers.
=> Add blog post by E. Choroba about 056 (Diff-K + Path Sum)

challenge-057/e-choroba/perl/Tree.pm, challenge-057/e-choroba/perl/ch-1a.pl, challenge-057/e-choroba/perl/ch-1b.pl, challenge-057/e-choroba/perl/ch-1c.pl, challenge-057/e-choroba/perl/ch-2.pl, challenge-057/e-choroba/perl/tree.t
There are a bit more files than usually. Hopefully, I'll have enough
time to explain everything in a blog post.
=> Add 057 (Invert Tree & Shortest Unique Prefix) solved by E. Choroba

challenge-057/andrezgz/perl/ch-1.pl, challenge-057/andrezgz/perl/ch-2.pl
Hi @manwar, dealing with the full binary tree was fun and took me a couple of hours to leave it the way I wanted
=> challenge-057 andrezgz solution

challenge-057/kevin-colyer/raku/ch-1.p6, challenge-057/kevin-colyer/raku/ch-2.p6, challenge-057/kevincolyer
=> Branch 057

challenge-058/saiftynet/perl/ch-1.pl, challenge-058/saiftynet/perl/ch-2.pl
=> Challenge-058 solutions by saiftynet

challenge-058/duncan-c-white/README, challenge-058/duncan-c-white/perl/ch-1.pl, challenge-058/duncan-c-white/perl/ch-2.pl
my solution works, but doesn't scale even to the 64-person example, clearly some better algorithm needed.
=> imported my solutions to this week's problems; task 2 is very interesting

challenge-058/e-choroba/blog.txt, challenge-058/e-choroba/perl/ch-2.pl
Also, add more test cases to 058/1.
=> Add a 058 blog post by E. Choroba (Compare Version & Ordered Lineup)

challenge-059/simon-proctor/raku/ch-1.raku
because it's a weird thing to do in Perl or Raku.
=> doesn't use a linked list directly 

challenge-059/e-choroba/perl/ch-2.pl
Don't count in pairs, count all at once.
=> Include faster implementation of Bit Sum

challenge-059/e-choroba/blog.txt, challenge-059/e-choroba/perl/ch-2.pl
Simplify the code according to the blog post, too.
=> Add link to E. Choroba's blog post about 059: Linked List + Bit Sum

challenge-059/noud/raku/ch-1.p6, challenge-059/noud/raku/ch-2.p6
I couldn't find the function of task 2 in the online encyclopedia of integer sequences (OEIS). This either means that I made a mistake in the algorithm, or that the sequence really isn't known in the OEIS. If the latter is the case I would like to understand more about this function. Perhaps it would be a good idea to add this function to the OEIS.
=> Solution to challenge 059 task 1 and 2 in Raku by Noud

challenge-059/athanasius/perl/ch-1.pl, challenge-059/athanasius/perl/ch-2.pl, challenge-059/athanasius/raku/ch-1.raku, challenge-059/athanasius/raku/ch-2.raku
On branch branch-for-challenge-059
new file:   challenge-059/athanasius/perl/ch-1.pl
new file:   challenge-059/athanasius/perl/ch-2.pl
new file:   challenge-059/athanasius/raku/ch-1.raku
new file:   challenge-059/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #059

challenge-059/duncan-c-white/README, challenge-059/duncan-c-white/perl/ch-1.pl, challenge-059/duncan-c-white/perl/ch-2.pl
=> oops; completely forgot to submit this until now (finished 8am BST)

challenge-060/sangeet-kar/perl/ch-1.sh, challenge-060/sangeet-kar/perl/ch-2.pl
Ch-1 - One-liner (though not very efficient)
Ch-2 - Algorithm::Combinatorics to the rescue
=> Solutions to Challenge060

challenge-060/saiftynet/perl/ch-1.pl, challenge-060/saiftynet/perl/ch-2.pl
=> Challenge-060 solutions by saiftynet

challenge-060/e-choroba/blog.txt, challenge-060/e-choroba/perl/ch-2.pl
Also, fix the edge case where input numbers of the target length were
ignored in "Find Numbers".
=> Add blog post by E. Choroba about 060: Excel Column + Find Numbers

challenge-060/sangeet-kar/raku/ch-1.raku, challenge-060/sangeet-kar/raku/ch-2.raku
=> Adding raku solutons

challenge-060/athanasius/perl/ch-1.pl, challenge-060/athanasius/raku/ch-1.raku
On branch branch-for-challenge-060
new file:   challenge-060/athanasius/perl/ch-1.pl
new file:   challenge-060/athanasius/raku/ch-1.raku
=> Perl and Raku solutions to Task 1 of the Perl Weekly Challenge #060

challenge-060/duncan-c-white/README, challenge-060/duncan-c-white/perl/ch-1.pl, challenge-060/duncan-c-white/perl/ch-2.pl
=> two nice simple questions this week, easy enough to do

challenge-061/roger-bell-west/perl/ch-1.pl, challenge-061/roger-bell-west/perl/ch-2.pl, challenge-061/roger-bell-west/raku/ch-1.p6
Hope the use of "perl" and "raku" directories is convenient for you.
=> Solutions for challenge #61.

challenge-061/e-choroba/perl/ch-1.pl, challenge-061/e-choroba/perl/ch-2.pl
Unfortunately, using List::Util isn't possible for Product SubArray,
see https://rt.cpan.org/Ticket/Display.html?id=132653.
=> Solve 061 by E. Choroba

challenge-061/e-choroba/blog.txt, challenge-061/e-choroba/perl/ch-1.pl
Also, fix the code to also return the sublist
=> Add blog post 061 Product SubArray + IPv4 Partition by E. Choroba

challenge-018/e-choroba/perl5/ch-1a.pl
Thanks capfan for finding the bug.
=> Fix the 018/1 by E. Choroba (LCS via Suffix Tree)

challenge-061/athanasius/perl/ch-1.pl, challenge-061/athanasius/perl/ch-2.pl, challenge-061/athanasius/raku/ch-1.raku, challenge-061/athanasius/raku/ch-2.raku
On branch branch-for-challenge-061
new file:   challenge-061/athanasius/perl/ch-1.pl
new file:   challenge-061/athanasius/perl/ch-2.pl
new file:   challenge-061/athanasius/raku/ch-1.raku
new file:   challenge-061/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #061

challenge-061/PerlBoy1967/README, challenge-061/PerlBoy1967/perl/ch-1.pl, challenge-061/PerlBoy1967/perl/ch-2.pl
Please accept my contribution.
Regards,
Niels
=> Perl Weekly Challenge #61 contribution.

challenge-061/duncan-c-white/README, challenge-061/duncan-c-white/perl/ch-1.pl, challenge-061/duncan-c-white/perl/ch-2.pl
=> incorporated this week's solutions..

challenge-062/perlboy1967/perl/ch-1.pl, challenge-062/perlboy1967/perl/ch-2.pl
Task 2 - With bonus: Create random solution up to dimension of 8 x 8 x 8
=> Branch for challenge 062

challenge-062/athanasius/perl/ch-1.pl, challenge-062/athanasius/raku/ch-1.raku
On branch branch-for-challenge-062
new file:   challenge-062/athanasius/perl/ch-1.pl
new file:   challenge-062/athanasius/raku/ch-1.raku
=> Perl & Raku solutions to Task 1 of the Perl Weekly Challenge #062

challenge-061/jaredor/perl/ch-1.pl, challenge-061/jaredor/perl/ch-2.pl, challenge-062/jaredor/perl/ch-1.pl
=> jaredor #1 & #2 of PWC 061 and #1 of PWC 062

challenge-062/duncan-c-white/README, challenge-062/duncan-c-white/perl/ch-1.pl
... and didn't much like the question anyway:-)
=> imported solution to first task, sorry no time to do second task

challenge-063/brtastic/README, challenge-063/brtastic/blog.txt, challenge-063/brtastic/perl/ch-1.pl, challenge-063/brtastic/perl/ch-2.pl
=> challenge 63 solution by brtastic

challenge-063/noud/raku/ch-1.p6, challenge-063/noud/raku/ch-2.p6
=> Solution to challenge 063 task 1 and 2 in Raku by Noud

challenge-063/athanasius/perl/ch-1.pl, challenge-063/athanasius/perl/ch-2.pl, challenge-063/athanasius/raku/ch-1.raku, challenge-063/athanasius/raku/ch-2.raku
On branch branch-for-challenge-063
new file:   challenge-063/athanasius/perl/ch-1.pl
new file:   challenge-063/athanasius/perl/ch-2.pl
new file:   challenge-063/athanasius/raku/ch-1.raku
new file:   challenge-063/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #063

challenge-018/e-choroba/perl5/ch-1a.pl
Also, make it general by not using high unicode characters as
separators, but rather using arrays instead of strings to store the
characters, and making the markers a special array elements.
Moreover, optimize the coverage computing by iterating over the
numbers rather than the covered characters.
=> Optimize LCS via Suffix Tree

challenge-062/e-choroba/perl5/ch-1.pl
Use Email::Address::XS to correctly parse addresses containing @ and "
in the user part.
=> Solve 062/1 Sort Email Address by E. Choroba

challenge-063/duncan-c-white/README, challenge-063/duncan-c-white/perl/ch-1.pl, challenge-063/duncan-c-white/perl/ch-2.pl
=> incorporated last week's solutions - two nice little problems

challenge-063/jaldhar-h-vyas/blog.txt, challenge-063/jaldhar-h-vyas/perl/ch-1.pl, challenge-063/jaldhar-h-vyas/perl/ch-2.pl, challenge-063/jaldhar-h-vyas/raku/ch-1.p6, challenge-063/jaldhar-h-vyas/raku/ch-2.p6
Its been too long but I'm back. :-)
=> Challenge 63 by Jaldhar H. Vyas

challenge-064/brtastic/blog.txt, challenge-064/brtastic/perl/ch-1.pl, challenge-064/brtastic/perl/ch-2.pl
=> Challenge 64 solution by brtastic

challenge-064/simon-proctor/raku/ch-1.raku, challenge-064/simon-proctor/raku/ch-2.raku
=> I thought I'd put the first one in the other day

challenge-009/e-choroba/perl5/ch-1.pl, challenge-057/e-choroba/perl/Tree.pm, challenge-060/e-choroba/perl/ch-2.pl
as it works even when @a is empty.
=> Use @h{@a} = () instead of undef @h{@a}

challenge-064/athanasius/perl/ch-1.pl, challenge-064/athanasius/raku/ch-1.raku
On branch branch-for-challenge-064
new file:   challenge-064/athanasius/perl/ch-1.pl
new file:   challenge-064/athanasius/raku/ch-1.raku
=> Perl & Raku solutions to Task 1 of the Perl Weekly Challenge #064

challenge-064/duncan-c-white/README, challenge-064/duncan-c-white/perl/ch-1.pl, challenge-064/duncan-c-white/perl/ch-2.pl
=> checked in my solutions for this week's challenge

challenge-064/brtastic/perl/ch-1.pl
I've noticed I misunderstood the last challenge #1 and only returned the path sum. This is a small tweak to return the path as well
=> Challenge 64 fix

challenge-065/noud/raku/ch-1.p6, challenge-065/noud/raku/ch-2.p6
I didn't understand task 2 well. I gave some alternative solutions how I understood the exercise.
=> Solutions to challenge 65 task 1 and 2 in Raku by Noud

challenge-065/cheok-yin-fung/BLOG.txt
=> blog written

challenge-065/cheok-yin-fung/perl/ch-1a.pl
=> fix bugs on ch-1a.pl

challenge-065/jaldhar-h-vyas/blog.txt, challenge-065/jaldhar-h-vyas/perl/ch-1.pl, challenge-065/jaldhar-h-vyas/perl/ch-2.pl, challenge-065/jaldhar-h-vyas/raku/ch-1.p6, challenge-065/jaldhar-h-vyas/raku/ch-2.p6
=> Challenge 65 by Jaldhar H. Vyas

challenge-066/3ter/ch-1.pl, challenge-066/3ter/ch-2.pl
Thank you for your work @manwar !
I got inspired in taking part when I saw your video of challenge 064 ;-).
=> Branch for challenge 066

challenge-066/brtastic/blog.txt, challenge-066/brtastic/perl/ch-1.pl, challenge-066/brtastic/perl/ch-2.pl
Blog post yet to be written later today
=> Challenge 66 solutions

challenge-066/noud/raku/ch-1.p6, challenge-066/noud/raku/ch-2.p6
"Execute order 66..."
Enjoy the weekend. ;)
=> Challenge 066 noud

challenge-066/brtastic/perl/ch-1.pl
I've actually meant to have xor here, not the binary xor
=> Fix challenge 66

challenge-066/athanasius/perl/ch-1.pl, challenge-066/athanasius/perl/ch-2.pl, challenge-066/athanasius/raku/ch-1.raku, challenge-066/athanasius/raku/ch-2.raku
On branch branch-for-challenge-066
new file:   challenge-066/athanasius/perl/ch-1.pl
new file:   challenge-066/athanasius/perl/ch-2.pl
new file:   challenge-066/athanasius/raku/ch-1.raku
new file:   challenge-066/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #066

challenge-067/simon-proctor/raku/ch-1.raku, challenge-067/simon-proctor/raku/ch-2.raku
I had taken the week off for the conference but didn't feel up for it so just chilled out. 
Here's this week's challenge.
=> Had last week off but I'm back.

challenge-067/luca-ferrari/raku/ch-1.p6
Sorry to bother, but here is a more compact and correct version of task 1 in raku
=> Still an enhanced task 1.

challenge-067/walt-mankowski/perl/ch-1.pl, challenge-067/walt-mankowski/perl/ch-2.pl
These are my Perl solutions to challenge 67
=> Branch for challenge 067

challenge-067/athanasius/perl/ch-1.pl, challenge-067/athanasius/perl/ch-2.pl, challenge-067/athanasius/raku/ch-1.raku, challenge-067/athanasius/raku/ch-2.raku
On branch branch-for-challenge-067
new file:   challenge-067/athanasius/perl/ch-1.pl
new file:   challenge-067/athanasius/perl/ch-2.pl
new file:   challenge-067/athanasius/raku/ch-1.raku
new file:   challenge-067/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #067

challenge-067/noud/raku/ch-1.p6, challenge-067/noud/raku/ch-2.p6
=> Solution to challenge 067 task 1 and 2 in Raku by Noud

challenge-067/walt-mankowski/python/ch-1.py, challenge-067/walt-mankowski/python/ch-2.py
These turned out to be a lot simpler than my Perl versions, in large part
because you don't have to worry about references in Python.
=> python 3 code for challenge 67

challenge-067/duncan-c-white/README, challenge-067/duncan-c-white/perl/ch-1.pl, challenge-067/duncan-c-white/perl/ch-2.pl
two nice questions this week, although for some reason I started off on the wrong foot on the first task.
=> imported my solutions for challenge 67

challenge-067/cheok-yin-fung/BLOG.txt, challenge-067/cheok-yin-fung/perl/ch-2.pl
good, I can finish two scripts and a blogpost for this week.
=> Cheok Yin's submission for task #2 and blog

challenge-068/ash/raku/ch-1.raku
Pardon me, the previous solution has a design error.
=> Fix the solution

challenge-068/walt-mankowski/perl/Node.pm, challenge-068/walt-mankowski/perl/ch-1.pl, challenge-068/walt-mankowski/perl/ch-2.pl
This is my perl code for challenge 68
=> Branch for challenge 068

challenge-068/walt-mankowski/python/ch-1.py, challenge-068/walt-mankowski/python/ch-2.py
I don't know why I started writing Python versions of these challenges but here you go!
=> python code for challenge 68

challenge-068/noud/raku/ch-1.p6, challenge-068/noud/raku/ch-2.p6
Enjoy the rest of the weekend!
=> Solution to challenge 68 task 1 and 2 in Raku by Noud

challenge-068/jeongoon/raku/ch-1.raku, challenge-068/jeongoon/raku/ch-2.raku
May be too late to request. Thanks anyway.
=> add raku solution task1 task2

challenge-069/simon-miner/perl/ch-1.pl
Includes solution to task 1 on strobogrammatic numbers.
=> Add ch-1.pl from strobogrammatic numbers task

challenge-069/walt-mankowski/perl/ch-1.pl, challenge-069/walt-mankowski/perl/ch-2.pl
This is my perl code for challenge 69.
=> Branch for challenge 069

challenge-069/rage311/perl5/ch-1.pl, challenge-069/rage311/perl5/ch-2.pl
rage311's solutions for weekly challenge 069
=> Added solutions for challenge 069

challenge-070/walt-mankowski/perl/ch-1.pl, challenge-070/walt-mankowski/perl/ch-2.pl
These are my Perl solutions for challenge 70
=> Branch for challenge 070

challenge-070/athanasius/perl/ch-1.pl, challenge-070/athanasius/perl/ch-2.pl, challenge-070/athanasius/raku/ch-1.raku, challenge-070/athanasius/raku/ch-2.raku
On branch branch-for-challenge-070
new file:   challenge-070/athanasius/perl/ch-1.pl
new file:   challenge-070/athanasius/perl/ch-2.pl
new file:   challenge-070/athanasius/raku/ch-1.raku
new file:   challenge-070/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #070

challenge-070/x1mandi/README, challenge-070/x1mandi/perl/ch-1.pl
Hi Mohammad,
this is Csaba from Budapest, Hungary.
I am learning Perl and I find Your challenges a great resource for practicing and showcasing solutions on my Github page. 
I already wrote some simpler Perl scirpts during my work as Sysadmin, which aren't publishe but I would like to become a Perl developer in the near future.
Actually until now I wasn't brave enough to submit solutions, so this is my first pull request for PWC, however I only solved the first task in Perl yet.
During the solution of task 1 a lot of questions came up, but I am not sure where I could get them answered.
Shall I wait for the solutions next week? Or may I ask in advance?
I don't know if I can finish task 2 until Sunday midnight, if not I will work on it next week. 
Thank You!
Kind regards,
Csaba
=> Solution for challenge-070 taks1 in Perl by x1mandi.

challenge-070/e-choroba/perl5/ch-1.pl, challenge-070/e-choroba/perl5/ch-2.pl
Character Swapping - I don't know what's the problem with $C > $O. For
a simple fast implementation, I needed a different additional
constraint: $C + $O < $N.
Grey Code Sequence - Two solutions. The shorter iterative one is
slightly faster, but the difference decreases with the sequence
length.
=> Add solutions to 070 by E. Choroba

challenge-070/jeongoon/perl/ch-1.pl, challenge-070/jeongoon/perl/ch-2.pl, challenge-070/jeongoon/raku/ch-1.raku, challenge-070/jeongoon/raku/ch-2.raku
=> challenge 070 completed

challenge-070/duncan-c-white/README, challenge-070/duncan-c-white/perl/ch-1.pl, challenge-070/duncan-c-white/perl/ch-2.pl
two nice easy questions this week, although there wasn't much elegance to my task 1 solution..
total solving time: 40 minutes.
=> imported this week's solutions; two easy problems

challenge-070/bob-lied/README, challenge-070/bob-lied/perl/ch-1.pl, challenge-070/bob-lied/perl/ch-2.pl
First-time submission, working through github flow.  Last week's problem, but better late than never.
=> Submit challenge 70 solutions

challenge-071/walt-mankowski/perl/Node.pm, challenge-071/walt-mankowski/perl/ch-1.pl, challenge-071/walt-mankowski/perl/ch-2.pl
Here's my Perl code for challenge 71
=> Branch for challenge 071

challenge-071/jaldhar-h-vyas/blog.txt, challenge-071/jaldhar-h-vyas/perl/ch-1.pl, challenge-071/jaldhar-h-vyas/perl/ch-2.pl, challenge-071/jaldhar-h-vyas/raku/ch-1.p6, challenge-071/jaldhar-h-vyas/raku/ch-2.p6
Early this week.  :-) It will give me more time to work on the ones I've missed.
=> Challenge 71 by Jaldhar H. Vyas

challenge-071/noud/raku/ch-1.p6, challenge-071/noud/raku/ch-2.p6
=> Solution to challenge 071 task 1 and 2 in Raku by Noud

challenge-071/walt-mankowski/blog.txt, challenge-071/walt-mankowski/c/ch-1.c, challenge-071/walt-mankowski/perl/ch-1.pl, challenge-071/walt-mankowski/python/ch-1.py
I updated my code because I just realized the elements in task 1 needed to be unique.
=> for task 1, make the elements on the array unique

challenge-071/athanasius/perl/ch-1.pl, challenge-071/athanasius/perl/ch-2.pl, challenge-071/athanasius/raku/ch-1.raku, challenge-071/athanasius/raku/ch-2.raku
On branch branch-for-challenge-071
new file:   challenge-071/athanasius/perl/ch-1.pl
new file:   challenge-071/athanasius/perl/ch-2.pl
new file:   challenge-071/athanasius/raku/ch-1.raku
new file:   challenge-071/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #071

challenge-071/jo-37/perl/ch-2.pl
=> simplified ch-2.pl

challenge-071/cheok-yin-fung/common-lisp/ch-1.lsp, challenge-071/cheok-yin-fung/perl/ch-1.pl
The Lisp script is not fixed. The Perl script is fixed.
=> miss out the uniqueness requirement in Task #2 !

challenge-072/duncan-c-white/README, challenge-072/duncan-c-white/perl/ch-1.pl, challenge-072/duncan-c-white/perl/ch-1a.pl, challenge-072/duncan-c-white/perl/ch-2.pl
I also did a tabulation version (ch-1a.pl) of task 1 too
had been busy last week (with actual Perl programming, gasp) so skipped last week's challenge
=> two easy questions this week

challenge-072/simon-miner/perl/ch-1.pl, challenge-072/simon-miner/perl/ch-2.pl
=> 072 simon miner

challenge-060/jaldhar-h-vyas/blog.txt, challenge-060/jaldhar-h-vyas/perl/ch-1.pl, challenge-060/jaldhar-h-vyas/perl/ch-2.pl, challenge-060/jaldhar-h-vyas/raku/ch-1.p6, challenge-060/jaldhar-h-vyas/raku/ch-2.p6
One more I couldn't submit yesterday.
=> Challenge 60 by Jaldhar H. Vyas

challenge-072/jeongoon/common-lisp/ch-1.lisp, challenge-072/jeongoon/haskell/ch-1.hs, challenge-072/jeongoon/haskell/ch-2.hs, challenge-072/jeongoon/perl/ch-1.pl, challenge-072/jeongoon/perl/ch-2.pl, challenge-072/jeongoon/raku/ch-1.raku, challenge-072/jeongoon/raku/ch-2.raku
I have more time this week so I have a look into some other language.
=> Challenge 72 Completed by Jeon

challenge-072/jeongoon/haskell/ch-2.hs
=> [ch-072/jeongoon] tiny improvement in haskell

challenge-072/WmMonty/README, challenge-072/WmMonty/perl/ch-1.pl
My first ever solution! My first ever git related anything!
Lots of firsts!
=> Commit for weekly challenge.

challenge-072/lance-wicks/README, challenge-072/lance-wicks/elm/elm.json, challenge-072/lance-wicks/elm/src/Main.elm, challenge-072/lance-wicks/perl/calc_factorial_and_count_trailing_zeroes.pl, challenge-072/lance-wicks/perl/lib/Trailing/Zeroes.pm, challenge-072/lance-wicks/perl/t/00-basic.t
Hope this is ok. Perl is just fine.
Elm is I hope ok
=> Add solutions in Perl and Elm by Lance Wicks

challenge-072/jeongoon/perl/ch-1.pl, challenge-072/jeongoon/raku/ch-1.raku
=> ch-072/jeongoon bug fixed in both perl and raku when matching "/0+$/" has no result

challenge-072/athanasius/perl/ch-1.pl, challenge-072/athanasius/perl/ch-2.pl, challenge-072/athanasius/raku/ch-1.raku, challenge-072/athanasius/raku/ch-2.raku
On branch branch-for-challenge-072
new file:   challenge-072/athanasius/perl/ch-1.pl
new file:   challenge-072/athanasius/perl/ch-2.pl
new file:   challenge-072/athanasius/raku/ch-1.raku
new file:   challenge-072/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #072

challenge-069/jeongoon/haskell/ch-1.hs, challenge-072/jeongoon/haskell/ch-1.hs
=> [ch-072/jeongoon] add brute force method for haskell/ch-1.hs; add Haskell for  [ch-069:Task1]

challenge-073/shawn-wagner/README, challenge-073/shawn-wagner/perl/ch-1.pl, challenge-073/shawn-wagner/perl/ch-2.pl, challenge-073/shawn-wagner/tcl/ch-1.tcl, challenge-073/shawn-wagner/tcl/ch-2.tcl
My first submission to the weekly challenge.
Uses perl + sqlite (Depends on `DBI` and `DBD::SQLite` 1.59_01 or newer).
=> Challenge 073 solution, both tasks

challenge-073/simon-proctor/raku/ch-1.raku, challenge-073/simon-proctor/raku/ch-2.raku
=> List fiddling FTW

challenge-073/pavel_kuptsov/README, challenge-073/pavel_kuptsov/perl/ch-1.pl, challenge-073/pavel_kuptsov/perl/ch-2.pl
Added solutions by Pavel Kuptsov for Task-1
=> Added Perl solutions by Pavel Kuptsov for Task-1

challenge-073/jason-messer/raku/ch-1.p6, challenge-073/jason-messer/raku/ch-2.p6
Weekly challenge #73 raku solution by Jason Messer
=> Weekly challenge #73 raku solution by Jason Messer

challenge-071/cheok-yin-fung/perl/ch-1.pl
modify in order to accord the task statement
=> Fix PWC#071  ch-1.pl

challenge-071/perlboy1967/perl/ch-1.pl, challenge-073/perlboy1967/perl/ch-1.pl, challenge-073/perlboy1967/perl/ch-2.pl
Added fix for challenge 071 - task 1
=> Branch for challenge 073

challenge-073/athanasius/perl/ch-1.pl, challenge-073/athanasius/perl/ch-2.pl, challenge-073/athanasius/raku/ch-1.raku, challenge-073/athanasius/raku/ch-2.raku
On branch branch-for-challenge-073
new file:   challenge-073/athanasius/perl/ch-1.pl
new file:   challenge-073/athanasius/perl/ch-2.pl
new file:   challenge-073/athanasius/raku/ch-1.raku
new file:   challenge-073/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #073

challenge-073/noud/raku/ch-1.p6, challenge-073/noud/raku/ch-2.p6
=> Solution for challenge 073 task 1 and 2 in Raku by Noud

challenge-074/shawn-wagner/README, challenge-074/shawn-wagner/java/ch1.java, challenge-074/shawn-wagner/java/ch2.java, challenge-074/shawn-wagner/perl/ch-1.pl, challenge-074/shawn-wagner/perl/ch-2.pl, challenge-074/shawn-wagner/tcl/ch-1.tcl, challenge-074/shawn-wagner/tcl/ch-2.tcl
Both parts, in perl, tcl and java.
=> Solutions for challenge 074.

challenge-074/jeongoon/common-lisp/ch-1.lsp, challenge-074/jeongoon/common-lisp/ch-2.lsp, challenge-074/jeongoon/haskell/JRandomList.hs, challenge-074/jeongoon/haskell/ch-1.hs, challenge-074/jeongoon/haskell/ch-2.hs
Thank you.
I'm wondering how earlier can I access the new challenge?
because my day off has been changed from weekend, so I feel like I have to access earlier.
=> [ch-074/jeongoon] Haskell, Common-lisp solution

challenge-074/athanasius/perl/ch-1.pl, challenge-074/athanasius/perl/ch-2.pl, challenge-074/athanasius/raku/ch-1.raku, challenge-074/athanasius/raku/ch-2.raku
On branch branch-for-challenge-074
new file:   challenge-074/athanasius/perl/ch-1.pl
new file:   challenge-074/athanasius/perl/ch-2.pl
new file:   challenge-074/athanasius/raku/ch-1.raku
new file:   challenge-074/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #074

challenge-074/jeongoon/common-lisp/ch-2.lsp, challenge-074/jeongoon/haskell/ch-1.hs, challenge-074/jeongoon/haskell/ch-2.hs, challenge-074/jeongoon/perl/ch-1.pl, challenge-074/jeongoon/perl/ch-2.pl, challenge-074/jeongoon/raku/ch-1.raku, challenge-074/jeongoon/raku/ch-2.raku
=> [ch-074/jeongoon] Perl and Raku solution

challenge-075/xkr47/rust/Cargo.toml, challenge-075/xkr47/rust/ch-1.rs, challenge-075/xkr47/rust/ch-2.rs
Rust soooon in top3 languages? :grin:
=> pwc075 / task 1 + 2

challenge-075/xkr47/rust/ch-1.rs, challenge-075/xkr47/rust/ch-2.rs
Gah you merged already, too quick :) .. Some fixes sorry
=> Whoops, fix some bugs

challenge-075/luca-ferrari/raku/ch-2.p6
=> Bonus track graph.

challenge-075/simon-proctor/raku/ch-2.raku
Call with `-g` option to get the graph ;)
=> Largest rectangle. With graphs

challenge-075/simon-proctor/raku/ch-1.raku
Defaults to false but you can add it to get the complete list.
=> Now added a verbose option

challenge-075/james-smith/README.md, challenge-075/james-smith/ch-1.pl, challenge-075/james-smith/ch-2.pl
I've changed back to my main git account... just to confuse slightly...
The coin counting problem is really quite interesting...!
=> Week 75 soultions

challenge-075/walt-mankowski/blog.txt, challenge-075/walt-mankowski/perl/ch-1.pl, challenge-075/walt-mankowski/perl/ch-2.pl, challenge-075/walt-mankowski/python/ch-1.py, challenge-075/walt-mankowski/python/ch-2.py
This is my Perl and Python code for challenge 75. There's also a link to a blog post.
=> Branch for challenge 075

challenge-075/simon-proctor/raku/ch-1.raku
=> Added a pretty print option

challenge-075/alexander-pankoff/README, challenge-075/alexander-pankoff/perl/ch-1.pl, challenge-075/alexander-pankoff/perl/ch-2.pl
Hey,
I'm Alexander Pankoff, a software developer from Hannover, Germany.
I'd like to join the team and participate in the weekly challenges. It would be great if you could add me to the Mailinglist using the mail from the commit.
I started using Perl professionally and recreationally around 5 years ago. I also work with TypeScript and use Haskell for hobby projects. 
This PR contains my solutions to the current challenge.
=> Join the team and add solutions to challenge-75

challenge-075/nunovieira220/perl/ch-1.pl, challenge-075/nunovieira220/perl/ch-2.pl
This PR aims to add my solution to challenge 075.
=> Add solution to challenge 075

challenge-075/noud/raku/ch-1.p6, challenge-075/noud/raku/ch-2.p6
=> Challenge 075 noud

challenge-075/athanasius/perl/ch-1.pl, challenge-075/athanasius/perl/ch-2.pl, challenge-075/athanasius/raku/ch-1.raku, challenge-075/athanasius/raku/ch-2.raku
On branch branch-for-challenge-075
new file:   challenge-075/athanasius/perl/ch-1.pl
new file:   challenge-075/athanasius/perl/ch-2.pl
new file:   challenge-075/athanasius/raku/ch-1.raku
new file:   challenge-075/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #075

challenge-075/duncan-c-white/README, challenge-075/duncan-c-white/perl/ch-1.pl, challenge-075/duncan-c-white/perl/ch-2.pl
..especially the second one which made me think quite hard..  I suspect there's a more elegant algorithmic approach, but I went with what seemed reasonably obvious..
=> incorporated my solution of this week's tasks.. 2 mildly tricky questions

challenge-076/xkr47/README, challenge-076/xkr47/rust/Cargo.toml, challenge-076/xkr47/rust/ch-2.rs
Learned a lot new about Rust again, great task :)
=> pwc076 / task 2

challenge-076/xkr47/rust/ch-2.rs
I failed to traverse the whole grid in case width != height, which it was! Doh! Now it finds "hazard" also :)
=> Pwc076 task 2 bugfix

challenge-076/markus-holzer/raku/ch-2.board.small, challenge-076/markus-holzer/raku/ch-2.explained.raku, challenge-076/markus-holzer/raku/ch-2.raku, challenge-076/markus-holzer/raku/ch-2.words, challenge-076/markus-holzer/raku/ch-2.words.small
I added a small 4x4 grid example and a version of the script with verbose output for you Mohammad. 
It should be easy understand now what it does and how it works.
Just run `perl6 ch-2.explained.raku ch-2.words.small ch-2.board.small`
=> improved and explained

challenge-076/wambash/raku/ch-1.raku
=> solution week 076-1

challenge-077/walt-mankowski/blog.txt, challenge-077/walt-mankowski/perl/ch-1.pl, challenge-077/walt-mankowski/perl/ch-2.pl, challenge-077/walt-mankowski/perl/test1.txt, challenge-077/walt-mankowski/perl/test2.txt
perl code and blog for this week's challenge
=> Branch for challenge 077

challenge-077/jeongoon/haskell/ch-1.hs, challenge-077/jeongoon/haskell/ch-2.hs, challenge-077/jeongoon/perl/ch-1.pl, challenge-077/jeongoon/perl/ch-2.pl
=> [ch-077/jeongoon] Haskell, Perl solution

challenge-077/andinus/README, challenge-077/andinus/blog-1.txt, challenge-077/andinus/perl/ch-1.pl
It's incomplete because it will not print all possible sums.
I had written this on the same day the challenge was posted & thought
I'll work on it later but it's Thursday & I don't think I'll work on
it this week so I'm pushing it in this state, maybe will complete it
next week.
=> Add challenge-077's ch-1 incomplete solution in Perl

challenge-077/nunovieira220/perl/ch-1.pl, challenge-077/nunovieira220/perl/ch-2.pl
This PR aims to add my solution to challenge 077.
=> Add solution to challenge 077

challenge-077/ash/javascript/ch-2.html, challenge-077/ash/python/ch-2.py
Python and JavaScript solutions.
=> 77-2 in Python 3

challenge-077/ash/cpp/ch-2a.cpp, challenge-077/ash/cpp/ch-2b.cpp
ch-2a.cpp is a copy of ch-2.cpp but I added the counter that counts the number of checks that the program makes for testing the neighbours.
The second version, ch-2b.cpp, is the modified program that makes less checks if there are neighbouring cells with X.
=> 77-2: update the solution to make less cell checks

challenge-077/athanasius/perl/ch-1.pl, challenge-077/athanasius/perl/ch-2.pl, challenge-077/athanasius/raku/ch-1.raku, challenge-077/athanasius/raku/ch-2.raku
On branch branch-for-challenge-077
new file:   challenge-077/athanasius/perl/ch-1.pl
new file:   challenge-077/athanasius/perl/ch-2.pl
new file:   challenge-077/athanasius/raku/ch-1.raku
new file:   challenge-077/athanasius/raku/ch-2.raku
=> Perl & Raku solutions to Tasks 1 & 2 of the Perl Weekly Challenge #077

challenge-077/alexander-pankoff/perl/ch-1.pl, challenge-077/alexander-pankoff/perl/ch-2.pl
My solutions for this week.
Thanks for the challenge.
=> Challenge 077

challenge-076/jason-messer/raku/ch-2.p6, challenge-077/jason-messer/raku/ch-1.p6, challenge-077/jason-messer/raku/ch-2.p6
I realized I had searched for words 4 and longer in my submitted solution. Also I had repeated loop that could be simplified.
=> Corrections for challenge 076

challenge-078/alexander-pankoff/perl/ch-1.pl, challenge-078/alexander-pankoff/perl/ch-2.pl
Quick solutions for this weeks challenge. Thanks for the brainteaser to begin the week.
=> Challenge 078

challenge-078/james-smith/README.md, challenge-078/james-smith/perl/ch-1.pl, challenge-078/james-smith/perl/ch-2.pl
Nice fun little challenges - good as they show where Perl works really well..!
=> #78 solutions... kept nice and short!

challenge-078/walt-mankowski/blog.txt, challenge-078/walt-mankowski/perl/ch-1.pl, challenge-078/walt-mankowski/perl/ch-2.pl, challenge-078/walt-mankowski/python/ch-1.py, challenge-078/walt-mankowski/python/ch-2.py
Perl code, python code, and a blog pointer for challenge 78
=> Branch for challenge 078

challenge-078/markus-holzer/raku/ch-1.raku
Now works correctly with negative numbers
=> C, Final answer

challenge-078/nunovieira220/js/ch-1.js, challenge-078/nunovieira220/js/ch-2.js, challenge-078/nunovieira220/perl/ch-1.pl, challenge-078/nunovieira220/perl/ch-2.pl
This PR aims to add my solution (perl & js) to challenge 078.
=> Add solution to challenge 078

challenge-078/gugod/raku/ch-1.raku, challenge-078/gugod/raku/ch-2.raku
Hi @manwar ,
Here's my first participation of PWC. :-)
=> week 78 / Raku solutions from gugod

challenge-078/vinod-k/ch-1.pl
Solution for challenge 78 - Task 1
=> Solution for challenge 78 - 1

challenge-078/polettix/blog.txt, challenge-078/polettix/blog1.txt, challenge-078/polettix/perl/ch-1.pl, challenge-078/polettix/perl/ch-2.pl
One of the two blog items will be published tomorrow morning... For the rest it should be OK :-)
=> Solutions to PWC078 by Flavio Poletti (polettix)
