challenge-153/duncan-c-white/README
challenge-153/duncan-c-white/perl/ch-1.pl
challenge-153/duncan-c-white/perl/ch-2.pl

imported my solutions to this week's tasks; factorials everywhere:-)

---

challenge-154/wlmb/blog.txt
challenge-154/wlmb/perl/ch-1.pl
challenge-154/wlmb/perl/ch-2.pl

Solve PWC154

---

challenge-154/2colours/raku/ch-1.raku
challenge-154/2colours/raku/ch-2.raku

Hello,
thank you for the challenges as usual; very interesting second task indeed, as gfldex pointed out. :) Please merge my solutions.
M. Polgár

Raku solutions for challenge 154 (2colours)

---

challenge-154/mattneleigh/perl/ch-1.pl
challenge-154/mattneleigh/perl/ch-2.pl

new file:   challenge-154/mattneleigh/perl/ch-2.pl

	new file:   challenge-154/mattneleigh/perl/ch-1.pl

---

challenge-155/wlmb/blog.txt
challenge-155/wlmb/perl/ch-1.pl
challenge-155/wlmb/perl/ch-2.pl

Solve PWC155

---

challenge-155/roger-bell-west/javascript/ch-1.js
challenge-155/roger-bell-west/javascript/ch-2.js
challenge-155/roger-bell-west/kotlin/ch-1.kt
challenge-155/roger-bell-west/kotlin/ch-2.kt
challenge-155/roger-bell-west/lua/ch-1.lua
challenge-155/roger-bell-west/lua/ch-2.lua
challenge-155/roger-bell-west/perl/ch-1.pl
challenge-155/roger-bell-west/perl/ch-2.pl
challenge-155/roger-bell-west/postscript/ch-1.ps
challenge-155/roger-bell-west/postscript/ch-2.ps
challenge-155/roger-bell-west/python/ch-1.py
challenge-155/roger-bell-west/python/ch-2.py
challenge-155/roger-bell-west/raku/ch-1.p6
challenge-155/roger-bell-west/raku/ch-2.p6
challenge-155/roger-bell-west/ruby/ch-1.rb
challenge-155/roger-bell-west/ruby/ch-2.rb
challenge-155/roger-bell-west/rust/ch-1.rs
challenge-155/roger-bell-west/rust/ch-2.rs

Finally, using the traditional git approach of "trash everything and rebuild from scratch".

Solutions for challenge #155

---

challenge-155/2colours/raku/ch-1.raku
challenge-155/2colours/raku/ch-2.raku

Hello,
another nice pair of tasks for those who love arithmetics. :) Lot of stuff to learn during the solution. Please welcome my take for them.
M. Polgár

Weekly Raku solutions #155 (2colours)

---

challenge-155/polettix/blog.txt
challenge-155/polettix/blog1.txt
challenge-155/polettix/perl/ch-1.pl
challenge-155/polettix/perl/ch-2.pl
challenge-155/polettix/perl/cpanfile
challenge-155/polettix/perl/cpanfile.snapshot
challenge-155/polettix/raku/ch-1.raku
challenge-155/polettix/raku/ch-2.raku

Hi! I thought you did not have much time to read through these comments, but I was clearly wrong 😄 
Please find my contribution for this week's challenge. The wikipedia page for Pisano periods is particularly... *itchy*, so to say, which eventually led me to a brute force attack because, you know... you we asking for the PP modulo 3 😄 
Keep up with the good work and see you next week!

Add polettix's solution to challenge-155

---

challenge-155/polettix/blog1.txt

Whooops... I misnamed the file name for a blog post, and I changed it. Sorry for the traffic!

Change location of blog post

---

challenge-155/mattneleigh/perl/ch-1.pl
challenge-155/mattneleigh/perl/ch-2.pl

new file:   challenge-155/mattneleigh/perl/ch-2.pl

	new file:   challenge-155/mattneleigh/perl/ch-1.pl

---

challenge-155/bruce-gray/blog.txt
challenge-155/bruce-gray/julia/ch-1.jl
challenge-155/bruce-gray/julia/ch-2.jl
challenge-155/bruce-gray/perl/ch-1.pl
challenge-155/bruce-gray/perl/ch-2.pl
challenge-155/bruce-gray/perl/ch-2_very_fast.pl
challenge-155/bruce-gray/raku/ch-1.raku
challenge-155/bruce-gray/raku/ch-1_generator.raku
challenge-155/bruce-gray/raku/ch-2.raku

Julia has been used in TWC before, but this is the first time I have used it.

Add TWC 155 blogpost and solutions by Bruce Gray : Raku, Perl, Julia

---

challenge-155/duncan-c-white/README
challenge-155/duncan-c-white/perl/ch-1.pl
challenge-155/duncan-c-white/perl/ch-2.pl

These two tasks were a bit tricky.  My solutions work for the size of problem requested, but I can't guarantee that they always generate the right answers for larger problems, or produce the answers in reasonable amounts of time.

imported my solutions to this week's (rather tricky) challenge

---

challenge-155/adam-russell/blog.txt
challenge-155/adam-russell/perl/ch-1.pl
challenge-155/adam-russell/perl/ch-2.pl

The US switch to Daylight Savings Time has given me an extra hour this week!

initial commit

---

challenge-156/2colours/raku/ch-1.raku
challenge-156/2colours/raku/ch-2.raku

Hello,
my latest solutions are here - the rather mundane code doesn't show how much discussion it linked me to, mostly because of junctions that I eventually barely used.
Anyways, this is a part of the process. :)
M Polgár

Solutions for #156

---

challenge-156/polettix/blog.txt
challenge-156/polettix/blog1.txt
challenge-156/polettix/perl/ch-1.pl
challenge-156/polettix/perl/ch-2.pl
challenge-156/polettix/perl/cpanfile
challenge-156/polettix/perl/cpanfile.snapshot
challenge-156/polettix/raku/ch-1.raku
challenge-156/polettix/raku/ch-2.raku

Hi Mohammad, good to see that you restarted participating! I hope you feel better now.
Please find my contribution to this week's challenge, it found a **very** lazy... me.

Add polettix's solution to challenge-156

---

challenge-156/cheok-yin-fung/blog.txt
challenge-156/cheok-yin-fung/perl/ch-1.pl
challenge-156/cheok-yin-fung/perl/ch-2.pl

Week 156 Submission

---

challenge-156/duncan-c-white/README
challenge-156/duncan-c-white/perl/ch-1.pl
challenge-156/duncan-c-white/perl/ch-2.pl

I liked the first task a lot, struggled slightly with the second just because I was a bit tired.  Overall took 1h30m or so.

imported my solutions to this week's tasks.. 2 nice ones

---

challenge-156/mattneleigh/perl/ch-1.pl

Only had time to do Challenge 1 this week.

	new file:   challenge-156/mattneleigh/perl/ch-1.pl

---

challenge-157/cheok-yin-fung/perl/ch-2.pl

Finish it faster than I thought; though there were some tricky points for my algorithm (e.g. n=6)

Week 157 Task 2

---

challenge-157/2colours/raku/ch-1.raku
challenge-157/2colours/raku/ch-2.raku

Hello,
thank you for the wholesome tasks, and here goes my weekly solution^^

Alternative ch-2 functions added

---

challenge-157/duncan-c-white/README
challenge-157/duncan-c-white/perl/ch-1.pl
challenge-157/duncan-c-white/perl/ch-2.pl

I liked both tasks a lot this week.  2 hours in total.

added and committed my solutions to this week's tasks.. two nice taks

---

challenge-158/2colours/raku/ch-1.raku
challenge-158/2colours/raku/ch-2.raku

Hello,
this week seems a bit easier than usual, anyway, please welcome my solutions :)

#158 challenge solutions (2colours)

---

challenge-158/wlmb/blog.txt
challenge-158/wlmb/perl/ch-1.pl
challenge-158/wlmb/perl/ch-2.pl

Solve PWC158

---

challenge-158/dave-jacoby/blog.txt

Couldn't get the link earlier because GitHub Pages was flaky.

I blogged it, like I said

---

challenge-158/mattneleigh/perl/ch-1.pl
challenge-158/mattneleigh/perl/ch-2.pl

new file:   challenge-158/mattneleigh/perl/ch-2.pl

	new file:   challenge-158/mattneleigh/perl/ch-1.pl

---

challenge-158/polettix/blog.txt
challenge-158/polettix/blog1.txt
challenge-158/polettix/perl/ch-1.pl
challenge-158/polettix/perl/ch-2.pl
challenge-158/polettix/perl/cpanfile
challenge-158/polettix/perl/cpanfile.snapshot
challenge-158/polettix/raku/ch-1.raku
challenge-158/polettix/raku/ch-2.raku

Hi! Thanks for keeping this thing up week after week, and congratulations for your 100th issue of the Perl Weekly!

Add polettix's solution to challenge-158

---

challenge-158/andrezgz/ch-1.pl
challenge-158/andrezgz/ch-2.pl

Hi @manwar , another week, another challenge solved!

challenge-158 andrezgz solution

---

challenge-158/alexander-pankoff/perl/ch-1.pl
challenge-158/alexander-pankoff/perl/ch-2.pl

Add solutions for challenge 158

---

challenge-158/duncan-c-white/README
challenge-158/duncan-c-white/perl/MakePrimes.pm
challenge-158/duncan-c-white/perl/ch-1.pl
challenge-158/duncan-c-white/perl/ch-2.pl

I liked both tasks a lot this week.  Took only 25 minutes in total (reusing my MakePrimes module that I've used in several earlier Perl Weekly Languages).

imported my solutions to this week's challenge; 2 nice easy questions

---

challenge-158/bruce-gray/go/ch-1.go
challenge-158/bruce-gray/go/ch-2.go
challenge-158/bruce-gray/perl/ch-1.pl
challenge-158/bruce-gray/perl/ch-1.sh
challenge-158/bruce-gray/perl/ch-2.pl
challenge-158/bruce-gray/perl/ch-2.sh
challenge-158/bruce-gray/raku/ch-1.raku
challenge-158/bruce-gray/raku/ch-1.sh
challenge-158/bruce-gray/raku/ch-2.raku
challenge-158/bruce-gray/raku/ch-2.sh

Raku and Perl also have .sh files containing additional one-liner versions.

Add TWC 158 solutions by Bruce Gray : Raku, Perl, Go.

---

challenge-159/2colours/raku/ch-1.raku
challenge-159/2colours/raku/ch-2.raku

Hello,
another inspiring week, thank you for the challenges. I hope others like arithmetics as much as I do - anyway, I think these tasks were good for Raku.
Please add my solutions to the common repo.^^

Week #159 solutions (2colours)

---

challenge-159/wlmb/blog.txt
challenge-159/wlmb/perl/ch-1.pl
challenge-159/wlmb/perl/ch-2.pl

Solve PWC 159

---

challenge-160/mattneleigh/perl/ch-1.pl
challenge-160/mattneleigh/perl/ch-2.pl

new file:   challenge-160/mattneleigh/perl/ch-2.pl

	new file:   challenge-160/mattneleigh/perl/ch-1.pl

---

challenge-159/cheok-yin-fung/java/Moebius.java
challenge-159/cheok-yin-fung/perl/ch-1.pl
challenge-159/cheok-yin-fung/perl/ch-2.pl

Java Exception Handling
I felt like having Olympiad in Informatics and English Writing Exam together yesterday.
Thanks!

improvement of codes in TWC 159

---

challenge-160/simon-proctor/raku/ch-1.raku
challenge-160/simon-proctor/raku/ch-2.raku

Note for challenge 2 the script outputs all the equilibrium points not just the first. 
A fun test list 1, -1, 1, -1, 1 (keep adding -1, 1 pairs as long as you like) every point is an equilibrium point.

Challenge 1 and 2

---

challenge-160/maxim-kolodyazhny/elixir/four_is_magic.ex

First Elixir solution? (^:
elixir -e 'FourIsMagic.encode(8) |> IO.puts()'

Challenge-160/1 by Maxim Kolodyazhny

---

challenge-160/wlmb/blog.txt
challenge-160/wlmb/perl/ch-1.pl
challenge-160/wlmb/perl/ch-1a.pl
challenge-160/wlmb/perl/ch-2.pl

Solve PWC160

---

challenge-160/mattneleigh/perl/ch-1.pl

Minor correction to output in ch-1.pl

	modified:   challenge-160/mattneleigh/perl/ch-1.pl

---

challenge-160/polettix/blog.txt
challenge-160/polettix/blog1.txt
challenge-160/polettix/perl/ch-1.pl
challenge-160/polettix/perl/ch-2.pl
challenge-160/polettix/raku/ch-1.raku
challenge-160/polettix/raku/ch-2.raku

Hi! I hope you're doing great, thanks for your amazing dedication.

Add polettix's solution to challenge-160

---

challenge-160/alexander-pankoff/blog1.txt
challenge-160/alexander-pankoff/blog2.txt
challenge-160/alexander-pankoff/perl/ch-1.pl
challenge-160/alexander-pankoff/perl/ch-2.pl

Add solutions for challenge 160

---

challenge-160/duncan-c-white/README
challenge-160/duncan-c-white/perl/ch-1.pl
challenge-160/duncan-c-white/perl/ch-2.pl

imported my solutions to this week's tasks; quite easy and fun tasks

---

challenge-160/duncan-c-white/C/.build
challenge-160/duncan-c-white/C/Makefile
challenge-160/duncan-c-white/C/README
challenge-160/duncan-c-white/C/ch-1.c
challenge-160/duncan-c-white/README

task 1 redone in C (see C/c-1.c)

Decided to add a GUEST LANGUAGE contribution, first time in ages

---

challenge-160/bruce-gray/blog.txt
challenge-160/bruce-gray/perl/ch-1.pl
challenge-160/bruce-gray/perl/ch-1.sh
challenge-160/bruce-gray/perl/ch-2.pl
challenge-160/bruce-gray/perl/ch-2.sh
challenge-160/bruce-gray/raku/ch-1.raku
challenge-160/bruce-gray/raku/ch-1.sh
challenge-160/bruce-gray/raku/ch-2.raku
challenge-160/bruce-gray/raku/ch-2.sh
challenge-160/bruce-gray/raku/ch-2_closest_half.raku
challenge-160/bruce-gray/yabasic/ch-1.yab
challenge-160/bruce-gray/yabasic/ch-2.yab

Solutions in Raku, Perl, and YaBasic

Add TWC 160 blog post and solutions by Bruce Gray

---

challenge-161/wlmb/blog.txt
challenge-161/wlmb/perl/ch-1.pl
challenge-161/wlmb/perl/ch-2.pl

Solve PWC161

---

challenge-160/cheok-yin-fung/blog.txt
challenge-160/cheok-yin-fung/perl/ch-2.pl
challenge-161/cheok-yin-fung/perl/ch-1.pl
challenge-161/cheok-yin-fung/perl/ch-2.pl

Week 161 is easier than I thought! :)

Week 161 Submission and Modifications codes in Week 160

---

challenge-161/polettix/blog.txt
challenge-161/polettix/blog1.txt
challenge-161/polettix/perl/ch-1.pl
challenge-161/polettix/perl/ch-2.pl
challenge-161/polettix/raku/ch-1.raku
challenge-161/polettix/raku/ch-2.raku

Hi! Always happy to read from you at the beginning of a week, keep up with the good work!

Add polettix's solution to challenge-161

---

challenge-161/andrezgz/perl/ch-1.pl

Hi @manwar, this week I share the first task only

challenge-161 ch-1 andrezgz solution

---

challenge-161/alexander-pankoff/perl/DictReader.pm
challenge-161/alexander-pankoff/perl/My/List/Util.pm
challenge-161/alexander-pankoff/perl/ch-1.pl
challenge-161/alexander-pankoff/perl/ch-2.pl

Add solutions for challenge 161

---

challenge-161/2colours/raku/ch-1.raku
challenge-161/2colours/raku/ch-2.raku

Hello,
I didn't want to miss out - here is a pretty humble effort for the weekly. The tasks were really good for a change though. :)

Solutions for week #161

---

challenge-161/jaldhar-h-vyas/perl/ch-1.pl
challenge-161/jaldhar-h-vyas/raku/ch-1.raku
challenge-161/jaldhar-h-vyas/raku/ch-2.raku

Perl version of problem 2 still has me tied in knots so I'm going to have to spend more time on that one and on the blog post but I have done problem 1 and the raku solution of problem 2.

Partial challenge 161 by Jaldhar H. Vyas.

---

challenge-161/ildar-shaimordanov/README
challenge-161/ildar-shaimordanov/perl/ch-1.pl

Hi Mohammad,
I seem not posting the solution in time. However I kindly ask you to merge it with upstream as it has a bit another approach with no split/sort/join.
Thank you,
Ildar

Add the solution for challenge-161/ch-1 by Ildar Shaimordanov

---

challenge-162/wlmb/blog.txt
challenge-162/wlmb/perl/ch-1.pl
challenge-162/wlmb/perl/ch-2.pl

Solve PWC162

---

challenge-162/julien-fiegehenn/perl/1.pl
challenge-162/julien-fiegehenn/perl/2.pl

Two in a row, and no API keys in this one \o/

Challenge 162

---

challenge-162/daniel-aberger/README
challenge-162/daniel-aberger/go/ch-1.go

I can't get my head around task 2 right now but at least I got this one pretty quick ;)

Solution for week 162, task 1

---

challenge-162/mattneleigh/perl/ch-1.pl
challenge-162/mattneleigh/perl/ch-2.pl

new file:   challenge-162/mattneleigh/perl/ch-2.pl

	new file:   challenge-162/mattneleigh/perl/ch-1.pl

---

challenge-162/2colours/raku/ch-1.raku
challenge-162/2colours/raku/ch-2.raku

Hello,
The suffering was real as I finished the second task; at least I've come across loads of novelties. :) I hope at least I didn't mess up what is supposed to just work as intended.
Thanks for the challenges as usual. :+1:

Huge suffering @ 162nd week

---

challenge-162/duncan-c-white/C/.build
challenge-162/duncan-c-white/C/Makefile
challenge-162/duncan-c-white/C/README
challenge-162/duncan-c-white/C/ch-1.c
challenge-162/duncan-c-white/README
challenge-162/duncan-c-white/perl/ch-1.pl
challenge-162/duncan-c-white/perl/ch-2.pl

(plus a bonus ch-1 in C in C/ch-1.c).. two enjoyable tasks which took 1h20m in total.  unfortunately I only left 1h10m before the deadline:-)

imported my solutions to this week's 2 tasks

---

challenge-162/rick-bychowski/raku/ch-2.raku

Oops, found a bug in the double letter handling. Maybe too late?

fix double letter handling

---

challenge-162/jaldhar-h-vyas/blog.txt
challenge-162/jaldhar-h-vyas/perl/ch-1.pl
challenge-162/jaldhar-h-vyas/raku/ch-1.raku

Unfortunately I'm too tired to finish part 2 right now but I thought I'd submit part 1 atleast.

Challenge 162 part 1 by Jaldhar H. Vyas.

---

challenge-163/bruce-gray/raku/ch-1.raku
challenge-163/bruce-gray/raku/ch-2.raku

Result of 4AM-cannot-fall-back-asleep-so-lets-check-the-new-TWC-tasks .
/me sleeps.

Add TWC 163 solutions by Bruce Gray : only Raku.

---

challenge-163/wlmb/blog.txt
challenge-163/wlmb/perl/ch-1.pl
challenge-163/wlmb/perl/ch-2.pl

Solve PWC163

---

challenge-163/2colours/raku/ch-1.raku
challenge-163/2colours/raku/ch-2.raku

Hello,
this week seems to be more chill, the second task was still very educational for me but at least I'm not lagging behind this week. :D So thank you, as usual, and please take my humble weekly attempt :P

Weekly solutions (2colours)

---

challenge-163/polettix/blog.txt
challenge-163/polettix/blog1.txt
challenge-163/polettix/perl/ch-1.pl
challenge-163/polettix/perl/ch-2.pl
challenge-163/polettix/raku/ch-1.raku
challenge-163/polettix/raku/ch-2.raku

Hi! Thank you so much for last week, I'm ashamed to have forgotten about publishing my solution here. Thanks again!

Add polettix's solution to challenge-163

---

challenge-163/mattneleigh/perl/ch-1.pl
challenge-163/mattneleigh/perl/ch-2.pl

new file:   challenge-163/mattneleigh/perl/ch-2.pl

	new file:   challenge-163/mattneleigh/perl/ch-1.pl

---

challenge-163/luiz-felipe/README
challenge-163/luiz-felipe/perl/ch-1.pl
challenge-163/luiz-felipe/perl/ch-2.pl

Hi! This is my first contribution to this project. I believe this pull request is up to standard. Any kind of feedback is great. Thank you for this week's challenges.

Challenge 163 Solutions

---

challenge-001/alexander-pankoff/haskell/ch-1.hs
challenge-001/alexander-pankoff/haskell/ch-2.hs
challenge-002/alexander-pankoff/haskell/ch-1.hs
challenge-002/alexander-pankoff/haskell/ch-2.hs
challenge-160/alexander-pankoff/haskell/ch-1.hs
challenge-160/alexander-pankoff/haskell/ch-2.hs
challenge-161/alexander-pankoff/haskell/ch-1.hs
challenge-163/alexander-pankoff/haskell/ch-1.hs
challenge-163/alexander-pankoff/haskell/ch-2.hs
challenge-163/alexander-pankoff/perl/ch-1.pl
challenge-163/alexander-pankoff/perl/ch-2.pl

My solutions for the current challenge and few solutions for old challenge in haskell

Challenge 163 solution and some old challenges

---

challenge-163/cheok-yin-fung/julia/ch-2.jl
challenge-163/cheok-yin-fung/perl/ch-1.pl
challenge-163/cheok-yin-fung/perl/ch-2.pl
challenge-163/cheok-yin-fung/python/ch-2.py

2 Perl scripts
For Task 2 Guest contribution
1 Python script
1 Julia script

Week 163 from CY

---

challenge-163/rick-bychowski/raku/ch-1.raku
challenge-163/rick-bychowski/raku/ch-2.raku

ch-163 Raku

---

challenge-163/jaldhar-h-vyas/blog.txt
challenge-163/jaldhar-h-vyas/perl/ch-1.pl
challenge-163/jaldhar-h-vyas/perl/ch-2.pl
challenge-163/jaldhar-h-vyas/raku/ch-1.sh

Challenge 163 by Jaldhar H. Vyas.

---

challenge-163/jaldhar-h-vyas/raku/ch-2.raku

Terribly sorry; I did this one but somehow forgot to add it to the pull request.

Raku solution for challenge 163 problem 2.

---

challenge-164/mattneleigh/perl/ch-1.pl
challenge-164/mattneleigh/perl/ch-2.pl

new file:   challenge-164/mattneleigh/perl/ch-2.pl

	new file:   challenge-164/mattneleigh/perl/ch-1.pl

---

challenge-164/2colours/raku/ch-1.raku
challenge-164/2colours/raku/ch-2.raku

Hello,
thank you for the new challenges, it was about time to revisit loop detection for sequences. Here is the absolute overthinker solution. :)

Added weekly Raku solution @2colours

---

challenge-164/wlmb/blog.txt
challenge-164/wlmb/perl/ch-1.pl
challenge-164/wlmb/perl/ch-2.pl

solve pwc164

---

challenge-164/luiz-felipe/perl/ch-1.pl
challenge-164/luiz-felipe/perl/ch-2.pl

Adding this week's exercise resolution

Adding week 164 resolutions

---

challenge-164/polettix/blog.txt
challenge-164/polettix/blog1.txt
challenge-164/polettix/perl/ch-1.pl
challenge-164/polettix/perl/ch-2.pl
challenge-164/polettix/raku/ch-1.raku
challenge-164/polettix/raku/ch-2.raku

Hi! Back on track, I hope... thanks again for last week. Cheers!

Add polettix's solution to challenge-164

---

challenge-165/polettix/blog.txt
challenge-165/polettix/blog1.txt
challenge-165/polettix/perl/ch-1.pl
challenge-165/polettix/perl/ch-2.pl
challenge-165/polettix/perl/cpanfile
challenge-165/polettix/perl/cpanfile.snapshot
challenge-165/polettix/raku/ch-1.raku
challenge-165/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenges. Thank you for your hard work!

Add polettix's solution to challenge-165

---

challenge-165/cheok-yin-fung/blog.txt
challenge-165/cheok-yin-fung/julia/ch-2.jl
challenge-165/cheok-yin-fung/perl/ch-1.pl
challenge-165/cheok-yin-fung/perl/ch-2.pl

2 Perl scripts, 1 blogpost, 1 Julia script

Week 165 Submission

---

challenge-165/wlmb/blog.txt
challenge-165/wlmb/perl/ch-1.pl
challenge-165/wlmb/perl/ch-2.pl

Solve PWC165

---

challenge-166/wlmb/blog.txt
challenge-166/wlmb/perl/ch-1.pl
challenge-166/wlmb/perl/ch-2.pl

Solve pwc166

---

challenge-077/ryan-thompson/README.md
challenge-077/ryan-thompson/perl/ch-1.pl
challenge-077/ryan-thompson/perl/ch-2.pl
challenge-166/ryan-thompson/README.md
challenge-166/ryan-thompson/blog.txt
challenge-166/ryan-thompson/blog1.txt
challenge-166/ryan-thompson/perl/ch-1-short.pl
challenge-166/ryan-thompson/perl/ch-1.pl
challenge-166/ryan-thompson/perl/ch-2.pl

Going to try slowly submitting some of the weeks I've missed, over time.

rjt's week 166 & week 77

---

challenge-166/mattneleigh/perl/ch-1.pl
challenge-166/mattneleigh/perl/ch-2.pl

new file:   challenge-166/mattneleigh/perl/ch-2.pl

	new file:   challenge-166/mattneleigh/perl/ch-1.pl

---

challenge-166/julien-fiegehenn/blog.txt
challenge-166/julien-fiegehenn/perl/ch-1.pl
challenge-166/julien-fiegehenn/perl/ch-2.pl
challenge-166/julien-fiegehenn/perl/cpanfile
challenge-166/julien-fiegehenn/typescript/ch-1.ts
challenge-166/julien-fiegehenn/typescript/package-lock.json
challenge-166/julien-fiegehenn/typescript/package.json
challenge-166/julien-fiegehenn/typescript/tsconfig.json

All of this code is written with Github Copilot. Blog is coming.

Challenge 166

---

challenge-167/wlmb/blog.txt
challenge-167/wlmb/perl/ch-1.pl
challenge-167/wlmb/perl/ch-2.pl

Solve PWC167

---

challenge-167/michael-dicicco/java/challenge167/circularprime.java
challenge-167/michael-dicicco/java/challenge167/task1.java
challenge-167/michael-dicicco/python/task1.py

challenge-167 entry

---

challenge-167/mattneleigh/perl/ch-1.pl
challenge-167/mattneleigh/perl/ch-2.pl

new file:   challenge-167/mattneleigh/perl/ch-2.pl

	new file:   challenge-167/mattneleigh/perl/ch-1.pl

---

challenge-167/duncan-c-white/README
challenge-167/duncan-c-white/perl/MakePrimes.pm
challenge-167/duncan-c-white/perl/ch-1.pl

although I've decided not to do task 2 as it's way too mathematical for me.  Complex numbers, the Gamma function that I've never heard of, and formulae that sound way too complex to understand: that's not for me.
Also, my task 1 gives more circular primes than your output, i.e. all of them, because that's what the question asked for, whereas I suspect the output shown is not actually "the first 10 N-or-more digit circular primes", but "the first 10 N-or-more digit smallest representative prime from all known cycles of circular primes", and that's not what the question asked for.

imported my solution to task 1 of this week's tasks

---

challenge-168/wlmb/blog.txt
challenge-168/wlmb/perl/ch-1.pl
challenge-168/wlmb/perl/ch-2.pl

Solve PWC168

---

challenge-168/2colours/raku/ch-1.raku
challenge-168/2colours/raku/ch-2.raku

Hello,
after some hiatus, I managed to return to the weeklies; please take my solutions. :)
M. Polgár

Challenge #168 solutions by 2colours

---

challenge-168/julien-fiegehenn/perl/ch-1.pl
challenge-168/julien-fiegehenn/perl/ch-2.pl

challenge 168, in Perl

---

challenge-168/massa/raku/ch-1.raku
challenge-168/massa/raku/ch-2.raku

There was one little thing that I didn't like in the challenge 1: I had to guesstimate how many Perrin primes would be enough to have 13 distinct primes, went with 20, and was successful with not a lot of overhead.

Answer to challenge 168 by Massa, Humberto

---

challenge-168/cheok-yin-fung/perl/ch-1.pl
challenge-168/cheok-yin-fung/perl/ch-2.pl

Week 168 Submission

---

challenge-168/polettix/blog.txt
challenge-168/polettix/blog1.txt
challenge-168/polettix/perl/ch-1.pl
challenge-168/polettix/perl/ch-2.pl
challenge-168/polettix/perl/cpanfile
challenge-168/polettix/perl/cpanfile.snapshot
challenge-168/polettix/raku/ch-1.raku
challenge-168/polettix/raku/ch-2.raku

Thank you for your dedication and hard work, I see people around appreciate this a lot.
And good luck for your contribution to the perl core!

Add polettix's solution to challenge-168

---

challenge-168/duncan-c-white/README
challenge-168/duncan-c-white/perl/PrimeFactors.pm
challenge-168/duncan-c-white/perl/ch-1.pl
challenge-168/duncan-c-white/perl/ch-2.pl

two nice tasks this week, thanks.
cheers
duncan

imported my solutions to this week's tasks, both relatively easy

---

challenge-167/rick-bychowski/raku/ch-1.raku
challenge-167/rick-bychowski/raku/ch-2.raku

Last week was busy for me. Merge if you can. Thanks!

ch-167; Circular Primes and Gamma Function

---

challenge-168/jaldhar-h-vyas/perl/ch-1.pl

I accidently left in a redundant line from an older version of my Perl solution to task 1.

Small typo.

---

challenge-160/sgreen/README.md
challenge-161/sgreen/README.md
challenge-162/sgreen/README.md
challenge-163/sgreen/README.md
challenge-164/sgreen/README.md
challenge-165/sgreen/README.md
challenge-166/sgreen/README.md
challenge-167/sgreen/README.md
challenge-168/sgreen/README.md
challenge-169/sgreen/README.md
challenge-169/sgreen/blog.txt
challenge-169/sgreen/perl/ch-1.pl
challenge-169/sgreen/perl/ch-2.pl
challenge-169/sgreen/python/ch-1.py
challenge-169/sgreen/python/ch-2.py

Also fixed a typo in a previous README, and deleted README.md files for the weeks I was away.

My solutions to challenge 169

---

challenge-169/wlmb/blog.txt
challenge-169/wlmb/perl/ch-1.pl
challenge-169/wlmb/perl/ch-2.pl

Solve PWC169

---

challenge-169/cheok-yin-fung/blog.txt
challenge-169/cheok-yin-fung/perl/ch-1.pl
challenge-169/cheok-yin-fung/perl/ch-2.pl

Week 169 Submission

---

challenge-169/polettix/blog.txt
challenge-169/polettix/blog1.txt
challenge-169/polettix/perl/ch-1.pl
challenge-169/polettix/perl/ch-2.pl
challenge-169/polettix/perl/cpanfile
challenge-169/polettix/perl/cpanfile.snapshot
challenge-169/polettix/raku/ch-1.raku
challenge-169/polettix/raku/ch-2.raku

Here we go with this week's contribution. Thank you for running this and guarding our backs (like the two or three times you did the work to publish my solutions because I forgot...).

Add polettix's solution to challenge-169

---

challenge-169/cheok-yin-fung/perl/ch-1.pl

Week 169 Task 1

---

challenge-169/2colours/raku/ch-1.raku
challenge-169/2colours/raku/ch-2.raku

Hello,
it's better late than never, so I put together an attempt for this weekly again. Thank you for making us think this week as well. :)

Weekly solutions by 2colours

---

challenge-169/rick-bychowski/ch-1.raku
challenge-169/rick-bychowski/ch-2.raku

Brilliant and Achilles Numbers

Brilliant and Achilles Numbers

---

challenge-169/mattneleigh/perl/ch-1.pl
challenge-169/mattneleigh/perl/ch-2.pl

new file:   challenge-169/mattneleigh/perl/ch-2.pl

	new file:   challenge-169/mattneleigh/perl/ch-1.pl

---

challenge-168/duncan-c-white/perl/PrimeFactors.pm
challenge-169/duncan-c-white/README
challenge-169/duncan-c-white/perl/PrimeFactors.pm
challenge-169/duncan-c-white/perl/ch-1.pl
challenge-169/duncan-c-white/perl/ch-2.pl

two quite nice tasks - but I'm getting very bored of prime-based number theory tasks.

imported solutions tp this week's tasks

---

challenge-170/wlmb/blog.txt
challenge-170/wlmb/perl/ch-1.pl
challenge-170/wlmb/perl/ch-2.pl

Solve PWC170

---

challenge-170/mattneleigh/perl/ch-1.pl
challenge-170/mattneleigh/perl/ch-2.pl

new file:   challenge-170/mattneleigh/perl/ch-2.pl

	new file:   challenge-170/mattneleigh/perl/ch-1.pl

---

challenge-170/mattneleigh/perl/ch-2.pl

Extremely minor efficiency tweak to ch-2.pl

	modified:   challenge-170/mattneleigh/perl/ch-2.pl

---

challenge-144/brxfork/README
challenge-144/brxfork/perl/ch-1.sh

one-liner with regex for challenge 144

---

challenge-170/polettix/blog.txt
challenge-170/polettix/blog1.txt
challenge-170/polettix/perl/ch-1.pl
challenge-170/polettix/perl/ch-2.pl
challenge-170/polettix/perl/cpanfile
challenge-170/polettix/perl/cpanfile.snapshot
challenge-170/polettix/raku/ch-1.raku
challenge-170/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Thank you very much for your work, I hope you realize the appreciation that you get around.

Add polettix's solution to challenge-170

---

challenge-170/rick-bychowski/raku/ch-1.raku
challenge-170/rick-bychowski/raku/ch-2.raku

solutions by Rick Bychowski: challenge-170 Primorial Numbers and Kronecker Product

ch-170: Primorial Numbers and Kronecker Product

---

challenge-170/duncan-c-white/C/.build
challenge-170/duncan-c-white/C/Makefile
challenge-170/duncan-c-white/C/README
challenge-170/duncan-c-white/C/ch-1.c
challenge-170/duncan-c-white/C/ch-2.c
challenge-170/duncan-c-white/C/primes.c
challenge-170/duncan-c-white/C/primes.h
challenge-170/duncan-c-white/README
challenge-170/duncan-c-white/perl/MakePrimes.pm
challenge-170/duncan-c-white/perl/ch-1.pl
challenge-170/duncan-c-white/perl/ch-2.pl

two nice easy tasks this week (I'm not complaining:-))

imported my two perl solutions (45 mins), then went back and translated them to C (another hour)

---

challenge-171/brxfork/perl/ch-1.sh

Fun with regex engine to find OEIS A005231

Abundant use of regex engine to find 20 Abundant Odd Numbers

---

challenge-171/2colours/raku/ch-1.raku
challenge-171/2colours/raku/ch-2.raku

Hello,
thank you for the tasks as usual, and please take my solutions, as usual. :)
M Polgár

Week 171 solutions by 2colours

---

challenge-171/polettix/blog.txt
challenge-171/polettix/blog1.txt
challenge-171/polettix/perl/ch-1.pl
challenge-171/polettix/perl/ch-2.pl
challenge-171/polettix/raku/ch-1.raku
challenge-171/polettix/raku/ch-2.raku

Hi! Better near-to-late than never! Thank you for all the hard work and keep it up, you're the best!

Add polettix's solution to challenge-171

---

challenge-172/wlmb/blog.txt
challenge-172/wlmb/perl/ch-1.pl
challenge-172/wlmb/perl/ch-2.pl

Solve PWC172

---

challenge-172/walt-mankowski/README.md
challenge-172/walt-mankowski/perl/ch-1.pl
challenge-172/walt-mankowski/perl/ch-2.pl
challenge-172/walt-mankowski/perl/primes.pm
challenge-172/walt-mankowski/python/ch-1.py
challenge-172/walt-mankowski/python/ch-2.py
challenge-172/walt-mankowski/python/primes.py

Here's my code for challenge 172. I've got Perl and Python solutions this week.

Branch for challenge 172

---

challenge-172/cheok-yin-fung/perl/ch-2.pl

my personal busy month starts, only one of the tasks

Week 172 Task 2

---

challenge-172/polettix/blog.txt
challenge-172/polettix/blog1.txt
challenge-172/polettix/perl/ch-1.pl
challenge-172/polettix/perl/ch-2.pl
challenge-172/polettix/raku/ch-1.raku
challenge-172/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Thanks for the dedication and the infinite well of interesting topics!

Add polettix's solution to challenge-172

---

challenge-172/steve-g-lynn/julia/ch-1.jl
challenge-172/steve-g-lynn/julia/ch-2.jl
challenge-172/steve-g-lynn/perl/ch-1.pl
challenge-172/steve-g-lynn/perl/ch-2.pl
challenge-172/steve-g-lynn/raku/ch-1.p6
challenge-172/steve-g-lynn/raku/ch-2.p6

Was able to re-create (whew) after I lost my files in a github merge

pwc 172 solution

---

challenge-172/0rir/raku/ch-1.raku
challenge-172/0rir/raku/ch-2.raku

Whitespace and remove cruft missed in rearranging.

---

challenge-173/simon-proctor/raku/ch-1.raku
challenge-173/simon-proctor/raku/ch-2.raku

Moved into new house things calming down, figured I'd give this week a shot (also both are pretty easy in the Raku's)

Challenge 173

---

challenge-173/cheok-yin-fung/perl/ch-1.pl

Submission for Week 173
Again busy, good luck!

Week 173 Task 1

---

challenge-173/jaldhar-h-vyas/blog.txt
challenge-173/jaldhar-h-vyas/perl/ch-1.pl
challenge-173/jaldhar-h-vyas/perl/ch-2.pl
challenge-173/jaldhar-h-vyas/raku/ch-1.raku
challenge-173/jaldhar-h-vyas/raku/ch-2.raku

Challenge 173 by Jaldhar H. Vyas.

---

challenge-173/wlmb/blog.txt
challenge-173/wlmb/perl/ch-1.pl
challenge-173/wlmb/perl/ch-2.pl

Solve PWC173

---

challenge-173/polettix/blog.txt
challenge-173/polettix/blog1.txt
challenge-173/polettix/perl/ch-1.pl
challenge-173/polettix/perl/ch-2.pl
challenge-173/polettix/raku/ch-1.raku
challenge-173/polettix/raku/ch-2.raku

Hi! Here it is my contribution for this week's challenge. I hope my questions don't bother you, anyway no real questions this time in the second challenge... and for the first too, actually :grin:

Add polettix's solution to challenge-173

---

challenge-173/walt-mankowski/README.md
challenge-173/walt-mankowski/perl/ch-1.pl
challenge-173/walt-mankowski/perl/ch-2.pl

Here's my Perl code for Challenge 173

Branch for challenge 173

---

challenge-173/2colours/raku/ch-1.raku
challenge-173/2colours/raku/ch-2.raku

Hello,
please take the latest solutions to the current challenge. :)

Week 173 solutions by 2colours

---

challenge-174/wlmb/blog.txt
challenge-174/wlmb/perl/ch-1.pl
challenge-174/wlmb/perl/ch-2.pl

Solve PWC174

---

challenge-174/brxfork/perl/ch-2.pl

execessive use of regex engine

---

challenge-174/polettix/blog.txt
challenge-174/polettix/blog1.txt
challenge-174/polettix/blog2.txt
challenge-174/polettix/perl/ch-1.pl
challenge-174/polettix/perl/ch-2.pl
challenge-174/polettix/raku/ch-1.raku
challenge-174/polettix/raku/ch-2.raku

Ahoy! Please find my contribution for this week's challenge, and keep up with your great work!

Add polettix's solution to challenge-174

---

challenge-174/bhat_gurunandan/README
challenge-174/bhat_gurunandan/perl/ch-1.pl
challenge-174/bhat_gurunandan/perl/ch-2.pl

Hi Mohammad, 
Sorry to join this wonderful initiative a bit late. 
I should be able to contribute more regularly going forward. 
Cheers

Perl Solution to Challenge 174

---

challenge-174/wlmb/perl/ch-1.pl
challenge-174/wlmb/perl/ch-1a.pl

Faster solution for PWC174-1

---

challenge-174/mattneleigh/perl/ch-1.pl
challenge-174/mattneleigh/perl/ch-2.pl

new file:   challenge-174/mattneleigh/perl/ch-2.pl

	new file:   challenge-174/mattneleigh/perl/ch-1.pl

---

challenge-175/wlmb/blog.txt
challenge-175/wlmb/perl/ch-1.pl
challenge-175/wlmb/perl/ch-2.pl

Solve PWC175

---

challenge-175/polettix/blog.txt
challenge-175/polettix/blog1.txt
challenge-175/polettix/perl/ch-1.pl
challenge-175/polettix/perl/ch-2.pl
challenge-175/polettix/perl/cpanfile
challenge-175/polettix/perl/cpanfile.snapshot
challenge-175/polettix/raku/ch-1.raku
challenge-175/polettix/raku/ch-2.raku

Hi! I hope everything is fine with this hot wave in the northern emisphere.
Please find my contribution for this week's challenge. Blog posts are scheduled for publication.
Cheers!

Add polettix's solution to challenge-175

---

challenge-175/walt-mankowski/README.md
challenge-175/walt-mankowski/c/Makefile
challenge-175/walt-mankowski/c/ch-1.c
challenge-175/walt-mankowski/c/ch-2.c
challenge-175/walt-mankowski/perl/ch-1.pl
challenge-175/walt-mankowski/perl/ch-2.pl

Here's code for challenge 175. I did it this week in Perl and C.

Branch for challenge 175

---

challenge-175/2colours/raku/ch-1.raku
challenge-175/2colours/raku/ch-2.raku

Hello,
those 20-digit numbers last week got a little scary (and hopeless to execute before the end of the universe) but this week, even the perfect totients could execute within a couple of seconds so I was content with the result. Please take my weekly solutions.

Weekly solutions (175) by 2colours

---

challenge-175/bhat_gurunandan/go/ch-2.go
challenge-175/bhat_gurunandan/perl/ch-2.pl

Hi Mohammad, 
An interesting thing happened when I started to code the solution to Challenge-2. I was playing with the code and trying different variations when I discovered that if you increment the iterated sum of totients by 1 (add the successive totients and then add 1) and then you check which number matches the sum, you get perfect powers of 2. (2, 4, 8, 16, ....)!!! I spent a lot of time looking at Number Theory sources to find if this was discussed somewhere. Sadly could not find any. Maybe someone on the list who is strong on Number Theory might explain why that happens. :)
In any case, the bad news is that I spent so much time trying to investigate this startling (to me, maybe it is commonplace for number theorists) that I have no time to code the solution to Challenge-2. I am …

Solution to Challenge 2 in Perl and Go

---

challenge-175/mattneleigh/perl/ch-1.pl
challenge-175/mattneleigh/perl/ch-2.pl

new file:   challenge-175/mattneleigh/perl/ch-2.pl

	new file:   challenge-175/mattneleigh/perl/ch-1.pl

---

challenge-175/duncan-c-white/C/.cbuild
challenge-175/duncan-c-white/C/Makefile
challenge-175/duncan-c-white/C/README
challenge-175/duncan-c-white/C/args.c
challenge-175/duncan-c-white/C/args.h
challenge-175/duncan-c-white/C/ch-1.c
challenge-175/duncan-c-white/C/ch-2.c
challenge-175/duncan-c-white/README
challenge-175/duncan-c-white/perl/ch-1.pl
challenge-175/duncan-c-white/perl/ch-2.pl

I had a surprising amount of trouble on ch-1.c, i.e. the translation of task 1 (last sunday) into C, it's clearly been too long since I last used the time.h functions..

imported my solutions (2 Perl + 2 C) to this weeks' tasks..

---

challenge-176/walt-mankowski/README.md
challenge-176/walt-mankowski/perl/ch-1.pl
challenge-176/walt-mankowski/perl/ch-2.pl

Perl solutions and a blog post for challenge 176

Branch for challenge 176

---

challenge-176/wlmb/blog.txt
challenge-176/wlmb/perl/ch-1.pl
challenge-176/wlmb/perl/ch-2.pl

Solve PWC176

---

challenge-176/polettix/blog.txt
challenge-176/polettix/blog1.txt
challenge-176/polettix/perl/ch-1.pl
challenge-176/polettix/perl/ch-2.pl
challenge-176/polettix/raku/ch-1.raku
challenge-176/polettix/raku/ch-2.raku

I hope I didn't annoy you with my comments/messages on twitter. In case, please accept my apology, it was not my intention 😅

Add polettix's solution to challenge-176

---

challenge-176/2colours/raku/ch-1.raku
challenge-176/2colours/raku/ch-2.raku

Hello,
this week was rather "Raku friendly" so here we go... I'm not really a QA person so I was okay with the ~ 5 seconds the first script takes to execute. Thank you as usual and please take this humble effort. ^^

176th week by 2colours

---

challenge-176/bhat_gurunandan/perl/ch-1.pl
challenge-176/bhat_gurunandan/perl/ch-2.pl

Here is my perl solution to Challenge 176

Solution to Challenge 176 in perl

---

challenge-176/wlmb/emacs-lisp/ch-1.el
challenge-176/wlmb/emacs-lisp/ch-2.el

I added solutions in emacs-lisp, for fun and curiosity

Solutions in emacs-lisp to PWC176

---

challenge-176/duncan-c-white/C/Makefile
challenge-176/duncan-c-white/C/README
challenge-176/duncan-c-white/C/args.c
challenge-176/duncan-c-white/C/args.h
challenge-176/duncan-c-white/C/ch-1.c
challenge-176/duncan-c-white/C/ch-2.c
challenge-176/duncan-c-white/README
challenge-176/duncan-c-white/perl/ch-1.pl
challenge-176/duncan-c-white/perl/ch-2.pl

2 nice easy questions this week, hurrah..

imported my solutions to this week's tasks in Perl and C

---

challenge-177/wlmb/blog.txt
challenge-177/wlmb/perl/ch-1.pl
challenge-177/wlmb/perl/ch-2.pl

Solve PWC177

---

challenge-177/wlmb/emacs-lisp/ch-1.el
challenge-177/wlmb/emacs-lisp/ch-2.el
challenge-177/wlmb/perl/ch-1.pl

Elisp solutions and minor corrections to PWC177

---

challenge-177/mattneleigh/perl/ch-1.pl
challenge-177/mattneleigh/perl/ch-2.pl

new file:   challenge-177/mattneleigh/perl/ch-2.pl

	new file:   challenge-177/mattneleigh/perl/ch-1.pl

---

challenge-177/polettix/blog.txt
challenge-177/polettix/blog1.txt
challenge-177/polettix/perl/ch-1.pl
challenge-177/polettix/perl/ch-2.pl
challenge-177/polettix/perl/cpanfile
challenge-177/polettix/perl/cpanfile.snapshot
challenge-177/polettix/raku/ch-1.raku
challenge-177/polettix/raku/ch-2.raku

I hope your neck improved in the meanwhile, all my best wishes!

Add polettix's solution to challenge-177

---

challenge-177/mattneleigh/perl/ch-1.pl

	modified:   challenge-177/mattneleigh/perl/ch-1.pl

---

challenge-177/walt-mankowski/perl/ch-1.pl
challenge-177/walt-mankowski/perl/ch-2.pl
challenge-177/walt-mankowski/perl/primes.pm

Here's my code for challenge 177. It's just Perl this week, and no time for a blog post.

Branch for challenge 177

---

challenge-178/polettix/blog.txt
challenge-178/polettix/blog1.txt
challenge-178/polettix/perl/ch-1.pl
challenge-178/polettix/perl/ch-2.pl
challenge-178/polettix/raku/ch-1.raku
challenge-178/polettix/raku/ch-2.raku

I hope you completely recovered :-)

Add polettix's solution to challenge-178

---

challenge-178/wlmb/blog.txt
challenge-178/wlmb/perl/ch-1.pl
challenge-178/wlmb/perl/ch-2.pl

Solve PWC178

---

challenge-179/wlmb/blog.txt
challenge-179/wlmb/perl/ch-1.pl
challenge-179/wlmb/perl/ch-2.pl

Solve PWC179

---

challenge-179/polettix/blog.txt
challenge-179/polettix/blog1.txt
challenge-179/polettix/perl/ch-1.pl
challenge-179/polettix/perl/ch-2.pl
challenge-179/polettix/raku/ch-1.raku
challenge-179/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge!
Thanks for running all of this, Mohammad!

Add polettix's solution to challenge-179

---

challenge-177/duncan-c-white/C/.cbuild
challenge-177/duncan-c-white/C/Makefile
challenge-177/duncan-c-white/C/README
challenge-177/duncan-c-white/C/args.c
challenge-177/duncan-c-white/C/args.h
challenge-177/duncan-c-white/C/ch-1.c
challenge-177/duncan-c-white/C/ch-2.c
challenge-177/duncan-c-white/C/isprime.c
challenge-177/duncan-c-white/C/isprime.h
challenge-177/duncan-c-white/C/prarray.c
challenge-177/duncan-c-white/C/prarray.h
challenge-177/duncan-c-white/README
challenge-177/duncan-c-white/perl/IsPrime.pm
challenge-177/duncan-c-white/perl/ch-1.pl
challenge-177/duncan-c-white/perl/ch-2.pl

… 2 nice tasks, done in C and Perl

belatedly had a crack at challenge 177 (was on holiday at the time)

---

challenge-178/duncan-c-white/C/.cbuild
challenge-178/duncan-c-white/C/Makefile
challenge-178/duncan-c-white/C/README
challenge-178/duncan-c-white/C/args.c
challenge-178/duncan-c-white/C/args.h
challenge-178/duncan-c-white/C/ch-1.c
challenge-178/duncan-c-white/C/ch-2a.c
challenge-178/duncan-c-white/README
challenge-178/duncan-c-white/perl/ch-1.pl
challenge-178/duncan-c-white/perl/ch-2.pl
challenge-178/duncan-c-white/perl/ch-2a.pl
challenge-179/duncan-c-white/C/.cbuild
challenge-179/duncan-c-white/C/Makefile
challenge-179/duncan-c-white/C/README
challenge-179/duncan-c-white/C/args.c
challenge-179/duncan-c-white/C/args.h
challenge-179/duncan-c-white/C/ch-1.c
challenge-179/duncan-c-white/README
challenge-179/duncan-c-white/perl/ch-1.pl

base -2i is very weird, the business date task was quite interesting to do without pre-built business hours support.  Translated both tasks to C as well.

imported my belated attempt at challenge 178, still away last week..

---

challenge-180/wlmb/blog.txt
challenge-180/wlmb/perl/ch-1.pl
challenge-180/wlmb/perl/ch-2.pl

Solve PWC180

---

challenge-180/mattneleigh/perl/ch-1.pl
challenge-180/mattneleigh/perl/ch-2.pl

new file:   challenge-180/mattneleigh/perl/ch-2.pl

	new file:   challenge-180/mattneleigh/perl/ch-1.pl

---

challenge-180/kueppo-wesley/Perl/ch-1.pl
challenge-180/kueppo-wesley/Perl/ch-2.pl

Kueppo pwc 180

---

challenge-180/massa/raku/ch-1.raku
challenge-180/massa/raku/ch-2.raku

They could both benefit from longer explanations, but raku made both operations quite trivial...

my quick-and-dirty raku answers (to ch-180), as usual

---

challenge-180/ben-davies/raku/ch-1.raku
challenge-180/ben-davies/raku/ch-2.raku

Trying something different for the first problem.

Add Ben Davies' Raku solutions for challenge 180

---

challenge-180/polettix/blog.txt
challenge-180/polettix/blog1.txt
challenge-180/polettix/perl/ch-1.pl
challenge-180/polettix/perl/ch-2.pl
challenge-180/polettix/raku/ch-1.raku
challenge-180/polettix/raku/ch-2.raku

Hi! Please find my contributions for this week's challenge. I hope you and your dear ones are fine!

Add polettix's solution to challenge-180

---

challenge-180/tyler-wardhaugh/clojure/README.md
challenge-180/tyler-wardhaugh/clojure/build.clj
challenge-180/tyler-wardhaugh/clojure/deps.edn
challenge-180/tyler-wardhaugh/clojure/src/c180/t1.clj
challenge-180/tyler-wardhaugh/clojure/src/c180/t2.clj
challenge-180/tyler-wardhaugh/clojure/test/c180/t1_test.clj
challenge-180/tyler-wardhaugh/clojure/test/c180/t2_test.clj
challenge-180/tyler-wardhaugh/fennel/LICENSE
challenge-180/tyler-wardhaugh/fennel/README.md
challenge-180/tyler-wardhaugh/fennel/bb.edn
challenge-180/tyler-wardhaugh/fennel/t1.fnl
challenge-180/tyler-wardhaugh/fennel/t2.fnl
challenge-180/tyler-wardhaugh/fennel/test.fnl

Hello @manwar, 
I believe this is the first contribution in [Fennel](https://fennel-lang.org/)!

Challenge 180 in Clojure and Fennel

---

challenge-180/duncan-c-white/C/.cbuild
challenge-180/duncan-c-white/C/Makefile
challenge-180/duncan-c-white/C/README
challenge-180/duncan-c-white/C/args.c
challenge-180/duncan-c-white/C/args.h
challenge-180/duncan-c-white/C/ch-1.c
challenge-180/duncan-c-white/C/ch-2.c
challenge-180/duncan-c-white/C/parseints.c
challenge-180/duncan-c-white/C/parseints.h
challenge-180/duncan-c-white/C/prarray.c
challenge-180/duncan-c-white/C/prarray.h
challenge-180/duncan-c-white/README
challenge-180/duncan-c-white/perl/ch-1.pl
challenge-180/duncan-c-white/perl/ch-2.pl

two relatively simple tasks this week (suits me perfectly).

imported my solutions to this week's tasks..

---

challenge-181/wlmb/blog.txt
challenge-181/wlmb/perl/ch-1.pl
challenge-181/wlmb/perl/ch-2.pl

Solve PWC181

---

challenge-181/polettix/blog.txt
challenge-181/polettix/blog1.txt
challenge-181/polettix/perl/ch-1.pl
challenge-181/polettix/perl/ch-2.pl
challenge-181/polettix/raku/ch-1.raku
challenge-181/polettix/raku/ch-2.raku

Hi! Please find this week's contributions. Thanks for all the hard work!

Add polettix's solution to challenge-181

---

challenge-181/ben-davies/raku/ch-1.raku
challenge-181/ben-davies/raku/ch-2.raku

Add Ben Davies' Raku solutions for challenge 181

---

challenge-181/cheok-yin-fung/perl/ch-2.pl

Week 181: Task 2

---

challenge-182/mattneleigh/perl/ch-1.pl
challenge-182/mattneleigh/perl/ch-2.pl

new file:   challenge-182/mattneleigh/perl/ch-2.pl

	new file:   challenge-182/mattneleigh/perl/ch-1.pl

---

challenge-182/wlmb/blog.txt
challenge-182/wlmb/perl/ch-1.pl
challenge-182/wlmb/perl/ch-2.pl

Solve PWC182

---

challenge-182/happy-barney/perl/ch-1.pl
challenge-182/happy-barney/perl/ch-1.t
challenge-182/happy-barney/perl/ch-2.pl
challenge-182/happy-barney/perl/ch-2.t

PR also contains poc for shared tests (should used naming pattern be required and calling convention specified)

Guest contribution / challenge 182 / happy-barney

---

challenge-182/polettix/blog.txt
challenge-182/polettix/blog1.txt
challenge-182/polettix/perl/ch-1.pl
challenge-182/polettix/perl/ch-2.pl
challenge-182/polettix/raku/ch-1.raku
challenge-182/polettix/raku/ch-2.raku

Hi Mohammad! Please find my contributions for this week. I hope everything is fine :grin:

Add polettix's solution to challenge-182

---

challenge-182/2colours/raku/ch-1.raku
challenge-182/2colours/raku/ch-2.raku

Hello,
lest I forget, I upload my mini solutions for the new tasks. Please accept this really humble effort. :)

Solutions for week 182 by 2colours

---

challenge-182/kueppo-wesley/Perl/ch-1.pl
challenge-182/kueppo-wesley/Perl/ch-2.pl

My Perl solution to the pwc-182

Kueppo pwc 182

---

challenge-183/wlmb/blog.txt
challenge-183/wlmb/perl/ch-1.pl
challenge-183/wlmb/perl/ch-2.pl

Solve PWC183

---

challenge-183/polettix/blog.txt
challenge-183/polettix/blog1.txt
challenge-183/polettix/perl/ch-1.pl
challenge-183/polettix/perl/ch-2.pl
challenge-183/polettix/raku/ch-1.raku

I skipped Raku in the second task because... I could not come up with a nice compact way to do things, I hate fiddling with dates and to be honest this years+days thing made little sense to me :grin:

Add polettix's solution to challenge-183

---

challenge-183/solathian/perl/183ch-1.pl
challenge-183/solathian/perl/183ch-2.pl

Adding files for perl weekly challenge

 Solutions for pwc 183

---

challenge-183/kueppo-wesley/Perl/ch-1.pl
challenge-183/kueppo-wesley/Perl/ch-2.pl

Kueppo pwc 183

---

challenge-183/jaldhar-h-vyas/blog.txt
challenge-183/jaldhar-h-vyas/perl/ch-1.pl
challenge-183/jaldhar-h-vyas/perl/ch-2.pl
challenge-183/jaldhar-h-vyas/raku/ch-1.raku
challenge-183/jaldhar-h-vyas/raku/ch-2.raku

Challenge 183 by Jaldhar H. Vyas.

---

challenge-184/mattneleigh/perl/ch-1.pl
challenge-184/mattneleigh/perl/ch-2.pl

new file:   challenge-184/mattneleigh/perl/ch-2.pl

	new file:   challenge-184/mattneleigh/perl/ch-1.pl

---

challenge-184/wlmb/blog.txt
challenge-184/wlmb/perl/ch-1.pl
challenge-184/wlmb/perl/ch-2.pl

Solve PWC184

---

challenge-184/happy-barney/perl/ch-1-test-scenario.pl
challenge-184/happy-barney/perl/ch-1.pl
challenge-184/happy-barney/perl/ch-1.t
challenge-184/happy-barney/perl/ch-2-test-scenario.pl
challenge-184/happy-barney/perl/ch-2.pl
challenge-184/happy-barney/perl/ch-2.t

with next step towards shared challenge tests

PWC 184 - guest contribution happy-barney/perl

---

challenge-184/kueppo-wesley/Perl/ch-2.pl

pwc-184 ch-2.pl

---

challenge-182/dave-jacoby/perl/ch-1.pl
challenge-182/dave-jacoby/perl/ch-2.pl

Challenge 182

---

challenge-184/polettix/blog.txt
challenge-184/polettix/blog1.txt
challenge-184/polettix/perl/ch-1.pl
challenge-184/polettix/perl/ch-2.pl
challenge-184/polettix/raku/ch-1.raku
challenge-184/polettix/raku/ch-2.raku

Hi! Sorry for being late this week :smile:

Add polettix's solution to challenge-184

---

challenge-184/2colours/raku/ch-1.raku
challenge-184/2colours/raku/ch-2.raku

Hello,
a mini solution written in a hurry but I didn't want to skip this week. :D 
I think it's easy to see by the solution but it's worth clarifying nevertheless: both solutions have optimistic input handling - in the first case, data is consumed in [a-z]{2}[0-9]{4} blocks, in the second case, it's consumed between apostrophes and then character by character, optionally space-separated.
Looking forward to next week, and please excuse me for the superficial solutions. ^^

Weeklies by 2colours

---

challenge-185/massa/raku/ch-1.raku
challenge-185/massa/raku/ch-2.raku

Those are problems that Raku #rakulang solves quite easily ;-)

my answers to challenge 185

---

challenge-185/kueppo-wesley/Perl/ch-1.pl

kueppo pwc-185 ch-1.pl

---

challenge-185/wlmb/blog.txt
challenge-185/wlmb/perl/ch-1.pl
challenge-185/wlmb/perl/ch-2.pl

Solve PWC185

---

challenge-185/mattneleigh/perl/ch-1.pl
challenge-185/mattneleigh/perl/ch-2.pl

new file:   challenge-185/mattneleigh/perl/ch-2.pl

	new file:   challenge-185/mattneleigh/perl/ch-1.pl

---

challenge-185/mattneleigh/perl/ch-2.pl

	modified:   challenge-185/mattneleigh/perl/ch-2.pl

---

challenge-185/polettix/blog.txt
challenge-185/polettix/blog1.txt
challenge-185/polettix/perl/ch-1.pl
challenge-185/polettix/perl/ch-2.pl
challenge-185/polettix/raku/ch-1.raku
challenge-185/polettix/raku/ch-2.raku

Hi! Early contribution, just to balance last week. The second blog post is on its way, due tomorrow. Cheers and thanks for all the hard work and dedication!

Add polettix's solution to challenge-185

---

challenge-185/solathian/perl/ch-1.pl
challenge-185/solathian/perl/ch-2.pl

Adding files for challange 185

---

challenge-185/2colours/raku/ch-1.raku
challenge-185/2colours/raku/ch-2.raku

Hello,
thank you for the weeklies, although this week Raku clearly did the heavy lifting for me. Anyway, sometimes it's good to have it easy; more time to focus on other things, like trying to lift Raku itself. :D

Raku beating challenge 185 :P

---

challenge-001/karishma-rajput/README
challenge-001/karishma-rajput/node/ch-1.js

Add solution by karishma rajput

---

challenge-185/0rir/raku/ch-1.raku

change 184 to 185

---

challenge-186/wlmb/blog.txt
challenge-186/wlmb/perl/ch-1.pl
challenge-186/wlmb/perl/ch-2.pl

Solve PWC186

---

challenge-186/wlmb/perl/ch-2.pl

Generalize to all printable ascii

---

challenge-185/ealvar3z/python/ch-1.py
challenge-186/ealvar3z/python/ch-1.py
challenge-186/ealvar3z/python/ch-2.py

- Python solutions
- Python solution for week 185

PWC 185 solution by E. Alvarez

---

challenge-186/polettix/blog.txt
challenge-186/polettix/blog1.txt
challenge-186/polettix/perl/ch-1.pl
challenge-186/polettix/perl/ch-2.pl
challenge-186/polettix/raku/ch-1.raku
challenge-186/polettix/raku/ch-2.raku

Hi! Please find my contribution for week 186. Thank you for everything!

Add polettix's solution to challenge-186

---

challenge-185/ealvar3z/python/ch-2.py

Perl Weekly Challenge 185

---

challenge-184/ealvar3z/python/ch-1.py
challenge-184/ealvar3z/python/ch-2.py
challenge-185/ealvar3z/python/ch-2.py

Perl Weekly Challenge 184: e. alvarez

---

challenge-183/ealvar3z/python/ch-1.py
challenge-183/ealvar3z/python/ch-2.py
challenge-184/ealvar3z/python/ch-1.py
challenge-184/ealvar3z/python/ch-2.py
challenge-185/ealvar3z/python/ch-2.py

Perl Weekly Challenge 183: e. alvarez

---

challenge-186/joaofel/blog.txt

Hi! I added a blog link for week 186 in my folder.

Added blog link

---

challenge-186/cheok-yin-fung/java/UnicodeMakeover.java
challenge-186/cheok-yin-fung/perl/ch-1.pl
challenge-186/cheok-yin-fung/perl/ch-2.pl

2 Perl scripts, 1 Java soln for Task 2
I am not bored by the Task 2 and writing a blogpost for it!

Week 186 Codes

---

challenge-186/2colours/raku/ch-1.raku
challenge-186/2colours/raku/ch-2.raku

Hello,
another chill week regarding weeklies as Raku solves the tasks by itself. :P I'm hoping for some arithmetics to return to the weeklies. Anyways, please take this really humble and minimalistic submission, trying to be persistent. :)

Raku ft. 2colours solved challenge 186

---

challenge-186/cheok-yin-fung/blog.txt

blog for Week 186 Task 2

---

challenge-187/joaofel/python/ch-2.py

Hi! I solved task 2 of week 187 in Python. Task 1 using dates just feels uncomfortable for me.

Solved task 2 in Python

---

challenge-187/wlmb/blog.txt
challenge-187/wlmb/perl/ch-1.pl
challenge-187/wlmb/perl/ch-2.pl

Solve PWC187

---

challenge-187/mattneleigh/perl/ch-1.pl
challenge-187/mattneleigh/perl/ch-2.pl

new file:   challenge-187/mattneleigh/perl/ch-2.pl

	new file:   challenge-187/mattneleigh/perl/ch-1.pl

---

challenge-187/polettix/blog.txt
challenge-187/polettix/blog1.txt
challenge-187/polettix/perl/ch-1.pl
challenge-187/polettix/perl/ch-2.pl
challenge-187/polettix/raku/ch-1.raku
challenge-187/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Very interesting indeed, thanks!

Add polettix's solution to challenge-187

---

challenge-187/solathian/perl/ch-1.pl
challenge-187/solathian/perl/ch-2.pl

Added files for challange 187

---

challenge-187/paul-fajman/perl/ch-1.pl
challenge-187/paul-fajman/perl/ch-2.pl

Committing for challenge 187. Apologies for being late.

Late pull request for challenge 187

---

challenge-188/wlmb/blog.txt
challenge-188/wlmb/perl/ch-1.pl
challenge-188/wlmb/perl/ch-2.pl

Solve PWC 188

---

challenge-188/alexander-pankoff/perl/ch-1.pl
challenge-188/alexander-pankoff/perl/ch-2.pl

My solutions for the current challenge.

Add solutions for challenge 188

---

challenge-188/mattneleigh/perl/ch-1.pl
challenge-188/mattneleigh/perl/ch-2.pl

new file:   challenge-188/mattneleigh/perl/ch-2.pl

	new file:   challenge-188/mattneleigh/perl/ch-1.pl

---

challenge-188/2colours/raku/ch-1.raku
challenge-188/2colours/raku/ch-2.raku

Hello,
I still haven't gotten around to do the next weekly but today I've done so much Raku that I had inspiration to do this quickly. :D
Hopefully the code is simple enough to understand for someone who knows Raku - although the expressivity of this regex sublanguage is still surprising for me as well...
The other thing is, I felt the second challenge was a bit hard to decipher. The examples suggest that $x == $y > 0 turns into $x == $y == 0 in one step, that's the presumption I used.
Thank you for the persistence, and I hope the things I've been working on, instead of the last weekly, will start paying out for Raku as well. :P

Weekly challenges by 2colours

---

challenge-188/polettix/blog.txt
challenge-188/polettix/blog1.txt
challenge-188/polettix/perl/ch-1.pl
challenge-188/polettix/perl/ch-2.pl
challenge-188/polettix/raku/ch-1.raku
challenge-188/polettix/raku/ch-2.raku

Well... sorry for being late!!! :smile:

Add polettix's solution to challenge-188

---

challenge-189/alexander-pankoff/perl/ch-1.pl
challenge-189/alexander-pankoff/perl/ch-2.pl

My solutions for this weeks challenge.

Add solutions for challenge 189

---

challenge-189/wlmb/blog.txt
challenge-189/wlmb/perl/ch-1.pl
challenge-189/wlmb/perl/ch-2.pl

Solve PWC189

---

challenge-189/spazm/perl/ch-1.pl
challenge-189/spazm/perl/ch-2.pl

Ch2 was tricky for quite a bit.
The key was realizing that any minimum length set would span from the first to last of the element setting the degree.

Week 189 - solution for @spazm in perl 5

---

challenge-189/2colours/raku/ch-1.raku
challenge-189/2colours/raku/ch-2.raku

Hi,
thanks for the challenges - they help me develop/revise my coding conventions. My latest favorite input processing is: I take the format of the provided examples and parse CLI arguments based on that format. I'm not saying that this is a superior style but a good way to practice regex parsing and also an approach that can be applied consistently.
Keep up the good work - I hope I can, too. :)

Current weeklies by 2colours

---

challenge-189/polettix/blog.txt
challenge-189/polettix/blog1.txt
challenge-189/polettix/perl/ch-1.pl
challenge-189/polettix/perl/ch-2.pl
challenge-189/polettix/raku/ch-1.raku
challenge-189/polettix/raku/ch-2.raku

Hi! This time I didn't forget. Blog posts are scheduled for publication... thanks for all the dedication!

Add polettix's solution to challenge-189

---

challenge-189/ealvar3z/python/ch-1.py

Perl Week Challenge 188: Part I

---

challenge-190/wlmb/blog.txt
challenge-190/wlmb/perl/ch-1.pl
challenge-190/wlmb/perl/ch-2.pl

Solve PWC190

---

challenge-190/2colours/raku/ch-1.raku
challenge-190/2colours/raku/ch-2.raku

Hello,
some of the solutions might be a little on the optimistic end but it was fun and also, I'm not sure if I'd have time later on, so there it goes...
Thank you for keeping up the good work and please take my solutions-in-a-hurry. :)

Weeklies no. 190 by 2colours

---

challenge-190/massa/raku/ch-1.raku
challenge-190/massa/raku/ch-2.raku

I tried to leave my reasoning well-documented...

decode-counts gave me some trouble

---

challenge-190/polettix/blog.txt
challenge-190/polettix/blog1.txt
challenge-190/polettix/perl/ch-1.pl
challenge-190/polettix/perl/ch-2.pl
challenge-190/polettix/raku/ch-1.raku
challenge-190/polettix/raku/ch-2.raku

Hi Mohammad! Please find my contribution for this week. Very interesting challenges, congratulations!

Add polettix's solution to challenge-190

---

challenge-190/ealvar3z/blog.txt
challenge-190/ealvar3z/python/ch-1.py
challenge-190/ealvar3z/python/ch-2.py

Python solutions for PWC 190

---

challenge-190/kueppo-wesley/perl/ch-1.pl

Perl solution to ch-1(episode 190) of the PWC

pwc-190 ch-1.pl

---

challenge-190/alexander-pankoff/blog-de.txt
challenge-190/alexander-pankoff/blog-en.txt
challenge-190/alexander-pankoff/perl/ch-1.pl
challenge-190/alexander-pankoff/perl/ch-2.pl

Add solutions for challenge 190

---

challenge-190/bruce-gray/perl/ch-1.pl
challenge-190/bruce-gray/perl/ch-2.pl
challenge-190/bruce-gray/raku/ch-1.raku
challenge-190/bruce-gray/raku/ch-2.raku

No blog post this week.
Thanks!

Add TWC 190 solutions (Perl and Raku) by Bruce Gray.

---

challenge-190/LoneWolfiNTj/perl/ch-1.pl
challenge-190/LoneWolfiNTj/perl/ch-2.pl

Ok, here's my third attempt at a pull request for my solutions for 190. (I had to compltely, recursivesly delete my entire fork of PWCC, both on Github and on my computer, re-fork, re-clone, re-branch, re-write, re-commit, re-push, and re-request; lets hope this works.)

Robbie Hatley's Perl solutions for 190.

---

challenge-191/simon-proctor/raku/ch-1.raku
challenge-191/simon-proctor/raku/ch-2.raku

Note challenge 1 returns True / False 
Challenge 2 will calculate all values between 1 and 15 if not given a value (and in the same time (near enough) it takes to do 15 by itself).

Both challenges.

---

challenge-191/wlmb/blog.txt
challenge-191/wlmb/perl/ch-1.pl
challenge-191/wlmb/perl/ch-2.pl

Solve PWC191

---

challenge-191/wlmb/perl/ch-2c.pl

Add faster solution

---

challenge-191/LoneWolfiNTj/perl/ch-1.pl
challenge-191/LoneWolfiNTj/perl/ch-2.pl

Fun pair of problems. I used recursion again. :-)

Robbie Hatley's Perl solutions for 191

---

challenge-191/polettix/blog.txt
challenge-191/polettix/blog1.txt
challenge-191/polettix/perl/ch-1.pl
challenge-191/polettix/perl/ch-2.pl
challenge-191/polettix/raku/ch-1.raku
challenge-191/polettix/raku/ch-2.raku

Hi! Thanks for your dedication... and your patience with my questions :grin:

Add polettix's solution to challenge-191

---

challenge-191/2colours/raku/ch-1.raku
challenge-191/2colours/raku/ch-2.raku

Hi,
thank you for the challenges - the second one is my favorite in a while, I hope Bruce Gray has something insightful to say about it on the Raku Study Group meetup. :) Please merge this less-humble-than-usual attempt at them. :)

Solutions of week 191 by 2colours

---

challenge-191/wlmb/perl/ch-2d.pl

Had some fun playing with iterators.

Add fastest nested iterator solution

---

challenge-191/vamsi-meenavilli/perl/ch-1.pl
challenge-191/vamsi-meenavilli/perl/ch-2.pl
challenge-191/vamsi-meenavilli/python/ch-1.py
challenge-191/vamsi-meenavilli/python/ch-2.py

Weekly Challenge 191 Perl and Python Solutions

Vamsi challenge 191

---

challenge-191/alexander-pankoff/perl/ch-1.pl
challenge-191/alexander-pankoff/perl/ch-2.pl

My solutions for the current week

Add solutions for challenge 191

---

challenge-191/bruce-gray/raku/ch-1.raku
challenge-191/bruce-gray/raku/ch-2.raku

Second task references work by @jo-37 , @2colours , and @abigail .

Add TWC 191 solutions (Raku only) by Bruce Gray.

---

challenge-192/LoneWolfiNTj/perl/ch-1.pl
challenge-192/LoneWolfiNTj/perl/ch-2.pl

Robbie Hatley's Perl solutions for 192.

---

challenge-191/ealvar3z/python/ch-2.py

Per the FB thread between @James_Smith and me. I refactored my Python
code to handle bigger inputs and optimize the code.

refactored Python solution

---

challenge-192/alexander-pankoff/haskell/ch-1.hs
challenge-192/alexander-pankoff/haskell/ch-2.hs
challenge-192/alexander-pankoff/perl/ch-1.pl
challenge-192/alexander-pankoff/perl/ch-2.pl
challenge-192/alexander-pankoff/raku/ch-1.raku
challenge-192/alexander-pankoff/raku/ch-2.raku

Solutions in:
- perl
- raku
- haskell

Add solutions for challenge 192

---

challenge-192/2colours/raku/ch-1.raku
challenge-192/2colours/raku/ch-2.raku

Hello,
thank you for the interesting challenges, I learned from them again... I can only hope my heuristics is both correct and well-implemented for the second task but I didn't feel I could prove it and I didn't have more time for it now. :D 
Anyways, off we go - please let them make the the collection of solutions a tad more colorful. :P

A shot at week 192 by 2colours

---

challenge-192/alexander-pankoff/blog.txt
challenge-192/alexander-pankoff/haskell/ch-2.hs

Add blog post and minor change.

Challenge 192

---

challenge-192/polettix/blog.txt
challenge-192/polettix/blog1.txt
challenge-192/polettix/perl/ch-1.pl
challenge-192/polettix/perl/ch-2.pl
challenge-192/polettix/raku/ch-1.raku
challenge-192/polettix/raku/ch-2.raku

Hi! Please find this week's contribution, and thanks for the great work!

Add polettix's solution to challenge-192

---

challenge-193/jeanluc2020/README
challenge-193/jeanluc2020/perl/ch-1.pl
challenge-193/jeanluc2020/perl/ch-2.pl

Add solution for challenge 193.

---

challenge-193/wlmb/blog.txt
challenge-193/wlmb/perl/ch-1.pl
challenge-193/wlmb/perl/ch-2.pl

Solve PWC193

---

challenge-193/polettix/blog.txt
challenge-193/polettix/blog1.txt
challenge-193/polettix/perl/ch-1.pl
challenge-193/polettix/perl/ch-2.pl
challenge-193/polettix/raku/ch-1.raku
challenge-193/polettix/raku/ch-2.raku

I saw that Colin Crain stopped doing their reviews, I hope everything is fine!
Thanks as always Mohammad.

Add polettix's solution to challenge-193

---

challenge-194/wlmb/blog.txt
challenge-194/wlmb/perl/ch-1.pl
challenge-194/wlmb/perl/ch-2.pl

Solve PWC194

---

challenge-194/jeanluc2020/perl/ch-1.pl
challenge-194/jeanluc2020/perl/ch-2.pl

Add solution for challenge 194

---

challenge-194/polettix/blog.txt
challenge-194/polettix/blog1.txt
challenge-194/polettix/perl/ch-1.pl
challenge-194/polettix/perl/ch-2.pl
challenge-194/polettix/raku/ch-1.raku
challenge-194/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Blog posts are... on their way!

Add polettix's solution to challenge-194

---

challenge-193/alexander-pankoff/perl/ch-1.pl

Add solution for task 1 of challenge 193

---

challenge-194/jaldhar-h-vyas/blog.txt
challenge-194/jaldhar-h-vyas/perl/ch-1.pl
challenge-194/jaldhar-h-vyas/perl/ch-2.pl
challenge-194/jaldhar-h-vyas/raku/ch-1.raku
challenge-194/jaldhar-h-vyas/raku/ch-2.raku

Challenge 194 by Jaldhar H. Vyas.

---

challenge-195/jeanluc2020/perl/ch-1.pl
challenge-195/jeanluc2020/perl/ch-2.pl

Add jeanluc2020's solution to challenge 195.

---

challenge-195/wlmb/blog.txt
challenge-195/wlmb/perl/ch-1.pl
challenge-195/wlmb/perl/ch-2.pl

Solve PWC195

---

challenge-195/0rir/raku/ch-2.raku

Assigned to %h for up-to-date-ness in balance of statement.

Stale data

---

challenge-195/jaldhar-h-vyas/blog.txt
challenge-195/jaldhar-h-vyas/perl/ch-1.pl
challenge-195/jaldhar-h-vyas/perl/ch-2.pl
challenge-195/jaldhar-h-vyas/raku/ch-1.sh
challenge-195/jaldhar-h-vyas/raku/ch-2.raku

Sorry late again. Also I might miss the next week or three as I'm going to India, to places which most likely don't have good wifi though with the speed things are improving over there these days you never know.

Challenge 195 by Jaldhar H. Vyas.

---

challenge-196/jeanluc2020/blog.txt
challenge-196/jeanluc2020/perl/ch-1.pl
challenge-196/jeanluc2020/perl/ch-2.pl

Add solution for challenge 196.

---

challenge-196/wlmb/blog.txt
challenge-196/wlmb/perl/ch-1.pl
challenge-196/wlmb/perl/ch-2.pl

Solve PWC196

---

challenge-196/jaldhar-h-vyas/blog.txt
challenge-196/jaldhar-h-vyas/perl/ch-1.pl
challenge-196/jaldhar-h-vyas/perl/ch-2.pl
challenge-196/jaldhar-h-vyas/raku/ch-1.raku
challenge-196/jaldhar-h-vyas/raku/ch-2.raku

I'm at the airport in New Delhi.  My connecting flight got delayed so I squeezed this one in.

Challenge 196 by Jaldhar H. Vyas.

---

challenge-196/bruce-gray/raku/ch-1.raku
challenge-196/bruce-gray/raku/ch-2.raku

<singing>Away on vacation, no post for a blog.</singing>
Thanks, manwar!

Add TWC 196 solutions by Bruce Gray (Raku only).

---

challenge-197/jeanluc2020/blog-1.txt
challenge-197/jeanluc2020/blog-2.txt
challenge-197/jeanluc2020/perl/ch-1.pl
challenge-197/jeanluc2020/perl/ch-2.pl

Add solution 197 by Thomas Köhler

---

challenge-197/wlmb/blog.txt
challenge-197/wlmb/perl/ch-1.pl
challenge-197/wlmb/perl/ch-2.pl

Solve PWC197

---

challenge-197/polettix/blog.txt
challenge-197/polettix/blog1.txt
challenge-197/polettix/perl/ch-1.pl
challenge-197/polettix/perl/ch-2.pl
challenge-197/polettix/raku/ch-1.raku
challenge-197/polettix/raku/ch-2.raku

Hi! Thank you so much for your kindness!

Add polettix's solution to challenge-197

---

challenge-197/roger-bell-west/blog.txt

Sorry about the delay putting this into VC.

Blog post for challenge #197

---

challenge-198/jeanluc2020/blog-1.txt
challenge-198/jeanluc2020/blog-2.txt
challenge-198/jeanluc2020/perl/ch-1.pl
challenge-198/jeanluc2020/perl/ch-2.pl

Add solution for challenge 198

---

challenge-198/wlmb/blog.txt
challenge-198/wlmb/perl/ch-1.pl
challenge-198/wlmb/perl/ch-2.pl

Solve PWC198

---

challenge-198/2colours/raku/ch-1.raku
challenge-198/2colours/raku/ch-2.raku

Hello,
I have already followed last week but didn't get to actually complete - this week was so straightforward, though, that I have no excuses.
Happy new year, keep up the good work. :)

New Year's (re)solutions by 2colours

---

challenge-198/robbie-hatley/blog.txt
challenge-198/robbie-hatley/perl/ch-1.pl
challenge-198/robbie-hatley/perl/ch-2.pl

Closed original pull request due to wrong blog URL; resubmitting.

Robbie Hatley's Perl solutions and blog for challenge  #198, with corrected blog URL.

---

challenge-198/polettix/blog.txt
challenge-198/polettix/blog1.txt
challenge-198/polettix/perl/ch-1.pl
challenge-198/polettix/perl/ch-2.pl
challenge-198/polettix/perl/cpanfile
challenge-198/polettix/perl/cpanfile.snapshot
challenge-198/polettix/raku/ch-1.raku
challenge-198/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Thanks for your dedication and hard work!

Add polettix's solution to challenge-198

---

challenge-199/jeanluc2020/blog-1.txt
challenge-199/jeanluc2020/blog-2.txt
challenge-199/jeanluc2020/perl/ch-1.pl
challenge-199/jeanluc2020/perl/ch-2.pl

Add solution 199

---

challenge-199/robbie-hatley/blog.txt
challenge-199/robbie-hatley/perl/ch-1.pl
challenge-199/robbie-hatley/perl/ch-2.pl

Robbie Hatley's Perl solutions and blog for Weekly Challenge #199

---

challenge-199/jaldhar-h-vyas/blog.txt
challenge-199/jaldhar-h-vyas/perl/ch-1.pl
challenge-199/jaldhar-h-vyas/perl/ch-2.pl
challenge-199/jaldhar-h-vyas/raku/ch-1.raku
challenge-199/jaldhar-h-vyas/raku/ch-2.raku

Challenge 199 by Jaldhar H. Vyas.

---

challenge-197/jaldhar-h-vyas/blog.txt
challenge-197/jaldhar-h-vyas/perl/ch-1.pl
challenge-197/jaldhar-h-vyas/perl/ch-2.pl
challenge-197/jaldhar-h-vyas/raku/ch-1.raku
challenge-197/jaldhar-h-vyas/raku/ch-2.raku

This is one of the weeks I missed while I was away.

Challenge 197 by Jaldhar H. Vyas.

---

challenge-198/jaldhar-h-vyas/blog.txt
challenge-198/jaldhar-h-vyas/perl/ch-1.pl
challenge-198/jaldhar-h-vyas/perl/ch-2.pl
challenge-198/jaldhar-h-vyas/raku/ch-1.raku
challenge-198/jaldhar-h-vyas/raku/ch-2.sh

Oh and I forgot this one.  I should be up to date now.

Challenge 198 by Jaldhar H. Vyas.

---

challenge-199/wlmb/perl/ch-1.pl
challenge-200/wlmb/blog.txt
challenge-200/wlmb/perl/ch-1.pl
challenge-200/wlmb/perl/ch-2.pl

Solve PWC200

---

challenge-200/jeanluc2020/blog-1.txt
challenge-200/jeanluc2020/blog-2.txt
challenge-200/jeanluc2020/perl/ch-1.pl
challenge-200/jeanluc2020/perl/ch-2.pl

Add solutions for week 200, including an iterator based one in task 1

---

challenge-199/jo-37/perl/ch-2.pl
challenge-200/jo-37/perl/ch-1.pl
challenge-200/jo-37/perl/ch-2.pl

Reran @drbaggy 's benchmarks with this PDL implementation added.

Solutions to challenge 200

---

challenge-200/polettix/blog.txt
challenge-200/polettix/blog1.txt
challenge-200/polettix/perl/ch-1.pl
challenge-200/polettix/perl/ch-2.pl
challenge-200/polettix/raku/ch-1.raku
challenge-200/polettix/raku/ch-2.raku

Hi! Thank you for all the dedication and for your help!

Add polettix's solution to challenge-200

---

challenge-200/mattneleigh/perl/ch-1.pl
challenge-200/mattneleigh/perl/ch-2.pl

new file:   challenge-200/mattneleigh/perl/ch-2.pl

	new file:   challenge-200/mattneleigh/perl/ch-1.pl

---

challenge-200/tyler-wardhaugh/clojure/README.md
challenge-200/tyler-wardhaugh/clojure/bb.edn
challenge-200/tyler-wardhaugh/clojure/build.clj
challenge-200/tyler-wardhaugh/clojure/deps.edn
challenge-200/tyler-wardhaugh/clojure/src/c200/t1.clj
challenge-200/tyler-wardhaugh/clojure/src/c200/t2.clj
challenge-200/tyler-wardhaugh/clojure/test/c200/t1_test.clj
challenge-200/tyler-wardhaugh/clojure/test/c200/t2_test.clj

Ch200: solve Task 1 in Clojure

---

challenge-200/bruce-gray/raku/ch-1.raku
challenge-200/bruce-gray/raku/ch-2.raku

Thank you for the gentle reminder!
Resuming work on meet-the-champion-2022-11.md today.

Add TWC 200 solutions by Bruce Gray (Raku only).

---

challenge-200/2colours/raku/ch-1.raku

Hello,
Thank you for the tasks, interesting week again.
I was too late with this solution, also I had to realize that if I cannot start with ch-2 the way I'd like to because that would take so much time inventing some ultimate terminal display logic that I would be completely drifting away. :D Also, I used some things in ch-1 that I don't even fully understand why they work... but they seem to work so I hope we can spot the mistakes on the next raku  study group meeting, should there be some.
Cheers :P

Partial solution of week 200 by 2colours

---

challenge-201/wlmb/blog.txt
challenge-201/wlmb/perl/ch-1.pl
challenge-201/wlmb/perl/ch-2.pl

Solve PWC 201

---

challenge-201/2colours/prolog/ch-1.p
challenge-201/2colours/prolog/ch-2.p

Hello,
this time, by the nature of the problems, it really got tempting to try and refresh my Prolog memories. I don't aim for perfection but I was happy to get to a point where I started getting legitimate results - also, performance considerations are always interesting with this language.
I don't know yet if I'm gonna also send Raku solutions this week - for now, please take this humble nostalgic attempt. :)

Prolog solutions for week 201 by 2colours

---

challenge-201/spadacciniweb/go/ch-1.go
challenge-201/spadacciniweb/go/ch-2.go
challenge-201/spadacciniweb/perl/ch-1.pl
challenge-201/spadacciniweb/perl/ch-2.pl

Branch for challenge 201 go

---

challenge-201/roger-bell-west/javascript/ch-1.js
challenge-201/roger-bell-west/javascript/ch-2.js
challenge-201/roger-bell-west/kotlin/ch-1.kt
challenge-201/roger-bell-west/kotlin/ch-2.kt
challenge-201/roger-bell-west/lua/ch-1.lua
challenge-201/roger-bell-west/lua/ch-2.lua
challenge-201/roger-bell-west/perl/ch-1.pl
challenge-201/roger-bell-west/perl/ch-2.pl
challenge-201/roger-bell-west/postscript/ch-1.ps
challenge-201/roger-bell-west/postscript/ch-2.ps
challenge-201/roger-bell-west/python/ch-1.py
challenge-201/roger-bell-west/python/ch-2.py
challenge-201/roger-bell-west/raku/ch-1.p6
challenge-201/roger-bell-west/raku/ch-2.p6
challenge-201/roger-bell-west/ruby/ch-1.rb
challenge-201/roger-bell-west/ruby/ch-2.rb
challenge-201/roger-bell-west/rust/ch-1.rs
challenge-201/roger-bell-west/rust/ch-2.rs
challenge-201/roger-bell-west/tests.yaml

Please ignore previous larger PR with this title / branch name, which I think I've successfully cancelled.

Solutions for challenge no. 201

---

challenge-201/jeanluc2020/blog-1.txt
challenge-201/jeanluc2020/blog-2.txt
challenge-201/jeanluc2020/perl/ch-1.pl
challenge-201/jeanluc2020/perl/ch-2.pl

Add solution for week 201

---

challenge-201/polettix/blog.txt
challenge-201/polettix/blog1.txt
challenge-201/polettix/perl/ch-1.pl
challenge-201/polettix/perl/ch-2.pl
challenge-201/polettix/raku/ch-1.raku
challenge-201/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenges.
Thank you for your constant dedication week after week, much appreciated!

Add polettix's solution to challenge-201

---

challenge-201/jaldhar-h-vyas/blog.txt
challenge-201/jaldhar-h-vyas/perl/ch-1.pl
challenge-201/jaldhar-h-vyas/perl/ch-2.pl
challenge-201/jaldhar-h-vyas/raku/ch-1.raku
challenge-201/jaldhar-h-vyas/raku/ch-2.raku

blog post up in a few minutes.

Challenge 201 by Jaldhar H. Vyas.

---

challenge-201/aut0exec/perl/Task1.pl

Sorry forgot to submit my answer for Challenge 1. Wasn't able to get Challenge 2 figured out in time.

Challenge 201

---

challenge-202/wlmb/blog.txt
challenge-202/wlmb/perl/ch-1.pl
challenge-202/wlmb/perl/ch-2.pl

Solve PWC202

---

challenge-202/e-choroba/erlang/widest_valley.erl
challenge-202/e-choroba/perl/ch-1.pl
challenge-202/e-choroba/perl/ch-2.pl

Add solutions to 202: Consecutive Odds & Widest Valley by E. Choroba

---

challenge-202/jeanluc2020/blog-1.txt
challenge-202/jeanluc2020/blog-2.txt
challenge-202/jeanluc2020/perl/ch-1.pl
challenge-202/jeanluc2020/perl/ch-2.pl

Add solutions for challenge 202

---

challenge-200/jaldhar-h-vyas/blog.txt
challenge-200/jaldhar-h-vyas/perl/ch-1.pl
challenge-200/jaldhar-h-vyas/perl/ch-2.pl
challenge-200/jaldhar-h-vyas/raku/ch-1.raku
challenge-200/jaldhar-h-vyas/raku/ch-2.raku

Oops.  Completely forgot that I had done this one.

Challenge 200 by Jaldhar H. Vyas.

---

challenge-202/polettix/blog.txt
challenge-202/polettix/blog1.txt
challenge-202/polettix/perl/ch-1.pl
challenge-202/polettix/perl/ch-2.pl
challenge-202/polettix/raku/ch-1.raku
challenge-202/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Thanks for everything!

Add polettix's solution to challenge-202

---

challenge-203/wlmb/blog.txt
challenge-203/wlmb/perl/ch-1.pl
challenge-203/wlmb/perl/ch-2.pl

Solve PWC203

---

challenge-203/jeanluc2020/blog-1.txt
challenge-203/jeanluc2020/blog-2.txt
challenge-203/jeanluc2020/perl/ch-1.pl
challenge-203/jeanluc2020/perl/ch-2.pl

Add solution 203

---

challenge-202/spadacciniweb/perl/ch-2.pl
challenge-203/spadacciniweb/bash/ch-2.bash
challenge-203/spadacciniweb/go/ch-1.go
challenge-203/spadacciniweb/go/ch-2.go
challenge-203/spadacciniweb/ksh/ch-2.ksh
challenge-203/spadacciniweb/perl/ch-1.pl
challenge-203/spadacciniweb/perl/ch-2.pl
challenge-203/spadacciniweb/python/ch-1.py
challenge-203/spadacciniweb/python/ch-2.py

PWC 203 - Perl, Python, Go, Bash, Korn shell

---

challenge-203/carlos-oliveira/perl/ch-1.pl
challenge-203/carlos-oliveira/perl/ch-2.pl

Good evening manager of Perl Weekly Challenge. Where do I send a profile picture?

solution to challenge 203

---

challenge-203/shawn-wagner/prolog/ch-1.p
challenge-203/shawn-wagner/racket/ch-2.rkt

Been a while since I've done one of these, so decided to do something different.

Challenge 203.1: Solution in SWI Prolog

---

challenge-203/robbie-hatley/blog.txt
challenge-203/robbie-hatley/perl/ch-1.pl
challenge-203/robbie-hatley/perl/ch-2.pl

#1 was a nice exercise in nested for loops.
#2 was much more complex, but I already had some subs. :-)

Robbie Hatley's Perl solutions for 203

---

challenge-203/polettix/blog.txt
challenge-203/polettix/blog1.txt
challenge-203/polettix/perl/ch-1.pl
challenge-203/polettix/perl/ch-2.pl
challenge-203/polettix/raku/ch-1.raku
challenge-203/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Thanks for everything!

Add polettix's solution to challenge-203

---

challenge-203/barroff/README
challenge-203/barroff/raku/ch-1.raku
challenge-203/barroff/raku/ch-2.raku

Hello,
These are my solutions for challenge 203 using  Raku.
I hope to submit solutions regularly in the future.

feat: add raku solutions for challenge 203

---

challenge-204/wlmb/blog.txt
challenge-204/wlmb/perl/ch-1.pl
challenge-204/wlmb/perl/ch-2.pl

Solve PWC204

---

challenge-204/jeanluc2020/blog-1.txt
challenge-204/jeanluc2020/blog-2.txt
challenge-204/jeanluc2020/perl/ch-1.pl
challenge-204/jeanluc2020/perl/ch-2.pl

Add solution 204

---

challenge-204/matthias-muth/README.md
challenge-204/matthias-muth/perl/ch-1-verbose.pl
challenge-204/matthias-muth/perl/ch-1.pl
challenge-204/matthias-muth/perl/ch-2.pl

First time I participate in the challenge.
Please let me if I am doing anything wrong.

Challenge 204 solutions by Matthias Muth.

---

challenge-204/barroff/raku/ch-1.raku
challenge-204/barroff/raku/ch-2.raku

Hello
here are my solutions for challenge 204 using Raku.

feat: add raku solutions for challenge 204

---

challenge-204/polettix/blog.txt
challenge-204/polettix/blog1.txt
challenge-204/polettix/perl/ch-1.pl
challenge-204/polettix/perl/ch-2.pl
challenge-204/polettix/raku/ch-1.raku
challenge-204/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge, thanks for all!!!

Add polettix's solution to challenge-204

---

challenge-205/wlmb/blog.txt
challenge-205/wlmb/perl/ch-1.pl
challenge-205/wlmb/perl/ch-2.pl

Solve PWC205

---

challenge-205/spadacciniweb/go/ch-1.go
challenge-205/spadacciniweb/go/ch-2.go
challenge-205/spadacciniweb/perl/ch-1.pl
challenge-205/spadacciniweb/perl/ch-2.pl
challenge-205/spadacciniweb/python/ch-1.py
challenge-205/spadacciniweb/python/ch-2.py

PWC 205 - Perl, Python, Go

---

challenge-205/mattneleigh/perl/ch-1.pl
challenge-205/mattneleigh/perl/ch-2.pl

new file:   challenge-205/mattneleigh/perl/ch-2.pl

	new file:   challenge-205/mattneleigh/perl/ch-1.pl

---

challenge-205/polettix/blog.txt
challenge-205/polettix/blog1.txt
challenge-205/polettix/perl/ch-1.pl
challenge-205/polettix/perl/ch-2.pl
challenge-205/polettix/raku/ch-1.raku
challenge-205/polettix/raku/ch-2.raku

Hi! Please find this week's contribution, in time (for a change) 😅

Add polettix's solution to challenge-205

---

challenge-205/shawn-wagner/racket/ch-1.rkt
challenge-205/shawn-wagner/racket/ch-2.rkt

Challenge 205 solutions

---

challenge-205/bruce-gray/blog.txt
challenge-205/bruce-gray/perl/ch-1.pl
challenge-205/bruce-gray/perl/ch-2.pl
challenge-205/bruce-gray/raku/ch-1.raku
challenge-205/bruce-gray/raku/ch-2.raku

@manwar, as the author of the Max XOR problem, you may be interested in my blog post, which details a fast solution when the input array is large.
Also, I am blocked on the interview, trying to resolve. Thanks!

Add TWC 205 blog post and solutions by Bruce Gray (Perl and Raku).

---

challenge-205/barroff/perl/ch-1.pl
challenge-205/barroff/raku/ch-1.raku
challenge-205/barroff/raku/ch-2.raku

Hello
this pull request adds my Perl and Raku solutions for challenge 205.

feat: add solutions for challenge 205 from BarrOff

---

challenge-206/wlmb/blog.txt
challenge-206/wlmb/perl/ch-1.pl
challenge-206/wlmb/perl/ch-2.pl

Solve PWC206

---

challenge-206/2colours/raku/ch-1.raku
challenge-206/2colours/raku/ch-2.raku

Hello,
thank you for the challenges - including the last couple of weeks, I was really cracking my head, waiting for the right solutions to come. :D After a couple of swingy weeks, I felt obliged to make this return, and I needed more reasoning with the second task than I'd like to admit, so the apparently simply solutions are a bit misleading, that was still kind of challenging to convince myself.
Please take these solutions; hopefully I got them right but if not, it will probably be clarified on this week's Raku Study Group online meetup. :)

Weeklies for 206th week by 2colours

---

challenge-206/spadacciniweb/go/ch-1.go
challenge-206/spadacciniweb/perl/ch-1.pl
challenge-206/spadacciniweb/perl/ch-2.pl
challenge-206/spadacciniweb/python/ch-1.py
challenge-206/spadacciniweb/python/ch-2.py

PWC 206 - Perl, Python, Go

---

challenge-206/polettix/blog.txt
challenge-206/polettix/blog1.txt
challenge-206/polettix/perl/ch-1.pl
challenge-206/polettix/perl/ch-2.pl
challenge-206/polettix/raku/ch-1.raku
challenge-206/polettix/raku/ch-2.raku

Hello! Early contribution this week, blog posts are on their way.
Thank you so much for all your dedication!

Add polettix's solution to challenge-206

---

challenge-206/kjetillll/perl/ch-2.pl

...and loop through every possible pairings permutation.
Just need to sort the input numbers and sum up every evenly indexed (0-indexed array) number.

Turns out, with hints from others, we don't need to brute force here

---

challenge-206/mattneleigh/perl/ch-1.pl
challenge-206/mattneleigh/perl/ch-2.pl

new file:   challenge-206/mattneleigh/perl/ch-2.pl

	new file:   challenge-206/mattneleigh/perl/ch-1.pl

---

challenge-206/barroff/blog.txt
challenge-206/barroff/raku/ch-1.raku
challenge-206/barroff/raku/ch-2.raku

Hello,
this pull request adds my solutions for challenge 206

feat: add solutions for challenge 206 from BarrOff

---

challenge-207/wlmb/blog.txt
challenge-207/wlmb/perl/ch-1.pl
challenge-207/wlmb/perl/ch-2.pl

Solve PWC207

---

challenge-207/2colours/raku/ch-1-blead.raku
challenge-207/2colours/raku/ch-1.raku
challenge-207/2colours/raku/ch-2.raku

Hello,
Thank you for the challenges. This week was a bit about experimenting - of course I hope I did things well but now I definitely put more emphasis on the "flow" - also, there is an exotic solution that uses bleeding edge Raku technology - freshly built RakuAST nodes, and thereby constructing a regular expression organically. Perhaps it could be further refined; this is simply based on reverse engineering of the RakuAST frontend.

207th week by 2colours

---

challenge-205/matthias-muth/blog.txt
challenge-206/matthias-muth/blog.txt

Sorry, I forgot to add the blog.txt files in challenges 205 and 206 (you were so kind to create it for me in challenge 204).
I should havedone my RTFM better!
:-)

Add blog.txt for challenges 205 and 206.

---

challenge-206/spadacciniweb/python/ch-1.py
challenge-207/spadacciniweb/go/ch-1.go
challenge-207/spadacciniweb/go/ch-2.go
challenge-207/spadacciniweb/perl/ch-1.pl
challenge-207/spadacciniweb/perl/ch-2.pl
challenge-207/spadacciniweb/python/ch-1.py
challenge-207/spadacciniweb/python/ch-2.py
challenge-207/spadacciniweb/ruby/ch-1.rb
challenge-207/spadacciniweb/ruby/ch-2.rb

PWC-207 - Perl, Python, Ruby, Go

---

challenge-207/mattneleigh/perl/ch-1.pl
challenge-207/mattneleigh/perl/ch-2.pl

new file:   challenge-207/mattneleigh/perl/ch-2.pl

	new file:   challenge-207/mattneleigh/perl/ch-1.pl

---

challenge-207/polettix/blog.txt
challenge-207/polettix/blog1.txt
challenge-207/polettix/perl/ch-1.pl
challenge-207/polettix/perl/ch-2.pl
challenge-207/polettix/raku/ch-1.raku
challenge-207/polettix/raku/ch-2.raku

Hi Mohammad! Please find my contribution for this week's challenge. I hope everything is fine with you and your dear ones :smile:

Add polettix's solution to challenge-207

---

challenge-207/carlos-oliveira/raku/ch-1.raku
challenge-207/carlos-oliveira/raku/ch-2.raku

Good evening. I think my profile picture is broken. It shows only my name. Could you fix it?
Thank you for assembling programmers together.

solution to challenge 207

---

challenge-207/barroff/blog.txt
challenge-207/barroff/raku/ch-1.raku
challenge-207/barroff/raku/ch-2.raku

Hello
This pull request adds my Raku solutions for challenge 207

feat: add solutions for challenge 207 from BarrOff

---

challenge-208/mark-anderson/raku/ch-1.raku
challenge-208/mark-anderson/raku/ch-2.raku

Thanks Mohammad. Hope you're feeling better.

Challenge 208 Solutions (Raku)

---

challenge-208/wlmb/blog.txt
challenge-208/wlmb/perl/ch-1.pl
challenge-208/wlmb/perl/ch-2.pl

Solve PWC208

---

challenge-208/spadacciniweb/go/ch-1.go
challenge-208/spadacciniweb/go/ch-2.go
challenge-208/spadacciniweb/perl/ch-1.pl
challenge-208/spadacciniweb/perl/ch-2.pl
challenge-208/spadacciniweb/python/ch-1.py
challenge-208/spadacciniweb/python/ch-2.py
challenge-208/spadacciniweb/ruby/ch-1.rb
challenge-208/spadacciniweb/ruby/ch-2.rb

PWC-208: Perl, Python, Ruby, Go

---

challenge-208/mattneleigh/perl/ch-1.pl
challenge-208/mattneleigh/perl/ch-2.pl

new file:   challenge-208/mattneleigh/perl/ch-2.pl

	new file:   challenge-208/mattneleigh/perl/ch-1.pl

---

challenge-208/barroff/raku/ch-1.raku
challenge-208/barroff/raku/ch-2.raku

Hello
This pull request adds my Raku solutions for challenge 208.

feat: add solutions for challenge 208 from BarrOff

---

challenge-209/wlmb/blog.txt
challenge-209/wlmb/perl/ch-1.pl
challenge-209/wlmb/perl/ch-2.pl

Solve PWC209

---

challenge-209/polettix/blog.txt
challenge-209/polettix/blog1.txt
challenge-209/polettix/perl/ch-1.pl
challenge-209/polettix/perl/ch-2.pl
challenge-209/polettix/raku/ch-1.raku
challenge-209/polettix/raku/ch-2.raku

Hi! This week the contribution is coming early... Thanks for the dedication and the interesting challenges!

Add polettix's solution to challenge-209

---

challenge-209/robbie-hatley/blog.txt
challenge-209/robbie-hatley/perl/ch-1.pl
challenge-209/robbie-hatley/perl/ch-2.pl

Fun with state machines and arrays of arrays of arrays. :-)

Robbie Hatley's Perl solutions to The Weekly Challenge 209

---

challenge-209/mattneleigh/perl/ch-1.pl
challenge-209/mattneleigh/perl/ch-2.pl

new file:   challenge-209/mattneleigh/perl/ch-2.pl

	new file:   challenge-209/mattneleigh/perl/ch-1.pl

---

challenge-209/barroff/raku/ch-1.raku

Hello
This pull request adds my Raku solution for task one of challenge 209.

feat: add solution for challenge 209-1 from BarrOff

---

challenge-209/polettix/perl/ch-2.pl

Hi! Someone [made me realize](https://github.com/polettix/ETOOBUSY/issues/28) about a bug in my code, here is a correction. Cheers!

Remove bug noted by github/oldtechaa

---

challenge-210/wlmb/blog.txt
challenge-210/wlmb/perl/ch-1.pl
challenge-210/wlmb/perl/ch-2.pl

SOlve PWC210

---

challenge-210/robbie-hatley/blog.txt
challenge-210/robbie-hatley/perl/ch-1.pl
challenge-210/robbie-hatley/perl/ch-2.pl

Fun with 3-part loops and backtracking.

Robbie Hatley's Perl Solutions for The Weekly Challenge 210

---

challenge-210/polettix/blog.txt
challenge-210/polettix/blog1.txt
challenge-210/polettix/perl/ch-1.pl
challenge-210/polettix/perl/ch-2.pl
challenge-210/polettix/raku/ch-1.raku
challenge-210/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Thanks for all and good job!

Add polettix's solution to challenge-210

---

challenge-210/mattneleigh/perl/ch-1.pl
challenge-210/mattneleigh/perl/ch-2.pl

new file:   challenge-210/mattneleigh/perl/ch-2.pl

	new file:   challenge-210/mattneleigh/perl/ch-1.pl

---

challenge-211/wlmb/blog.txt
challenge-211/wlmb/perl/ch-1.pl
challenge-211/wlmb/perl/ch-2.pl

Solve PWC211

---

challenge-211/matthias-muth/README.md
challenge-211/matthias-muth/perl/ch-1.pl
challenge-211/matthias-muth/perl/ch-2.pl

Challenge 211 solutions in Perl by Matthias Muth

---

challenge-211/polettix/blog.txt
challenge-211/polettix/blog1.txt
challenge-211/polettix/perl/ch-1.pl
challenge-211/polettix/perl/ch-2.pl
challenge-211/polettix/raku/ch-1.raku
challenge-211/polettix/raku/ch-2.raku

Hi! Please find my proposed solutions for this week's challenge. I enjoyed them a lot, thanks!

Add polettix's solution to challenge-211

---

challenge-211/barroff/raku/ch-1.raku
challenge-211/barroff/raku/ch-2.raku

Hello
This pull request adds my Raku solutions for challenge 211.

feat: add solutions for challenge 211 from BarrOff

---

challenge-211/avery-adams/perl/ch-1.pl
challenge-211/avery-adams/perl/ch-2.pl

Very last-minute solutions for 211!

211 solutions for Avery Adams

---

challenge-212/wlmb/blog.txt
challenge-212/wlmb/perl/ch-1.pl
challenge-212/wlmb/perl/ch-2.pl

I believe there was a mistake in the statement of task 2, in example 3. I guess the correct answer should be -1 unless the size is changed to 3. Regards.

Solve PWC212

---

challenge-211/spadacciniweb/go/ch-1.go
challenge-211/spadacciniweb/perl/ch-1.pl
challenge-211/spadacciniweb/python/ch-1.py
challenge-211/spadacciniweb/ruby/ch-1.rb
challenge-212/spadacciniweb/go/ch-1.go
challenge-212/spadacciniweb/perl/ch-1.pl
challenge-212/spadacciniweb/python/ch-1.py
challenge-212/spadacciniweb/ruby/ch-1.rb

PWC-212 (and PWC-211 fix)

---

challenge-212/avery-adams/blogs.txt
challenge-212/avery-adams/perl/ch-1.pl
challenge-212/avery-adams/perl/ch-2.pl

Blog posts are included this week in blogs.txt.

Add solutions and blog posts for Avery Adams for 212.

---

challenge-212/mattneleigh/perl/ch-1.pl
challenge-212/mattneleigh/perl/ch-2.pl

new file:   challenge-212/mattneleigh/perl/ch-2.pl

	new file:   challenge-212/mattneleigh/perl/ch-1.pl

---

challenge-212/duncan-c-white/README
challenge-212/duncan-c-white/perl/ch-1.pl
challenge-212/duncan-c-white/perl/ch-2.pl

will add C translations tomorrow

committed my perl solutions to this week's tasks

---

challenge-212/cheok-yin-fung/perl/ch-2.pl

Week 212 Task 2

---

challenge-213/wlmb/blog.txt
challenge-213/wlmb/perl/ch-1.pl
challenge-213/wlmb/perl/ch-2.pl

Solve PWC213

---

challenge-213/luca-ferrari/blog-1.txt
challenge-213/luca-ferrari/blog-2.txt
challenge-213/luca-ferrari/blog-3.txt
challenge-213/luca-ferrari/blog-4.txt
challenge-213/luca-ferrari/blog-5.txt
challenge-213/luca-ferrari/blog-6.txt
challenge-213/luca-ferrari/postgresql/ch-1.plperl
challenge-213/luca-ferrari/postgresql/ch-1.sql
challenge-213/luca-ferrari/postgresql/ch-2.plperl
challenge-213/luca-ferrari/postgresql/ch-2.sql
challenge-213/luca-ferrari/raku/ch-1.p6
challenge-213/luca-ferrari/raku/ch-2.p6

My solutions in Perl, Raku and PostgreSQL.

All tasks done

---

challenge-212/matthias-muth/README.md
challenge-212/matthias-muth/perl/ch-1.pl
challenge-212/matthias-muth/perl/ch-2.pl

Challenge 212 solutions in Perl by Matthias Muth

---

challenge-213/polettix/blog.txt
challenge-213/polettix/blog1.txt
challenge-213/polettix/perl/ch-1.pl
challenge-213/polettix/perl/ch-2.pl
challenge-213/polettix/raku/ch-1.raku
challenge-213/polettix/raku/ch-2.raku

Hi! Thank you so much for last week, I totally missed doing the PR! Here is the contribution for this week.

Add polettix's solution to challenge-213

---

challenge-213/matthias-muth/README.md
challenge-213/matthias-muth/blog.txt
challenge-213/matthias-muth/perl/ch-1.pl
challenge-213/matthias-muth/perl/ch-2.pl

Made it this week!
Including blog post!
:-D

Challenge 213 solutions in Perl by Matthias Muth

---

challenge-213/2colours/raku/ch-1.raku
challenge-213/2colours/raku/ch-2.raku

Hi,
thank you very much for the challenges; it took me some time to return, apparently misunderstood last week's tasks, for example. This time, something usual happened: I hope that the solution is alright but Raku itself caused me some trouble so I won't feel guilty if something went wrong. :P
Please take these quirky solutions nevertheless.

213th week by 2colours

---

challenge-213/avery-adams/blogs.txt
challenge-213/avery-adams/perl/ch-1.pl
challenge-213/avery-adams/perl/ch-2.pl

Here are my solutions for 213, and my blogs.txt is included with my two blog locations.

Week 213 solutions for Avery Adams

---

challenge-213/shimon-ben-avraham/raku/ch-1.raku

Initial submission

---

challenge-212/barroff/raku/ch-1.raku
challenge-212/barroff/raku/ch-2.raku

Hello
This pull request adds my Raku solutions for challenge 212.

feat: add solutions for challenge 212 from BarrOff

---

challenge-213/barroff/gp/ch-1.gp
challenge-213/barroff/raku/ch-1.raku

Hello
This pull request adds my Raku and PARI/GP solutions for task1 of challenge 213.

feat: add solutions for challenge 213 from BarrOff

---

challenge-214/wlmb/blog.txt
challenge-214/wlmb/perl/ch-1.pl
challenge-214/wlmb/perl/ch-2.pl

Solve PWC214

---

challenge-214/robbie-hatley/perl/ch-1.pl

(May add 214-2 and blog later.)

Robbie Hatley's Perl solution to The Weekly Challenge 214-1. 

---

challenge-214/avery-adams/blogs.txt
challenge-214/avery-adams/perl/ch-1.pl

Solution for challenge 1 along with blog links.

Solution for 214 for Avery Adams

---

challenge-214/shimon-ben-avraham/raku/ch-1.raku
challenge-214/shimon-ben-avraham/raku/ch-2.raku

Submission for Challenge 214.1

Branch for challenge 214

---

challenge-214/polettix/blog.txt
challenge-214/polettix/blog1.txt
challenge-214/polettix/perl/ch-1.pl
challenge-214/polettix/perl/ch-2.pl
challenge-214/polettix/raku/ch-1.raku
challenge-214/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Thank you for everything!

Add polettix's solution to challenge-214

---

challenge-214/barroff/raku/ch-1.pl
challenge-214/barroff/raku/ch-1.raku

Hello
This pull request adds my Raku and Perl solutions for task1 of challenge 214.

feat: add solutions for challenge 214 from BarrOff

---

challenge-214/jaldhar-h-vyas/blog.txt
challenge-214/jaldhar-h-vyas/perl/ch-1.pl
challenge-214/jaldhar-h-vyas/perl/ch-2.pl
challenge-214/jaldhar-h-vyas/raku/ch-1.raku
challenge-214/jaldhar-h-vyas/raku/ch-2.raku

blog post not up yet but on its' way shortly.

Challenge 214 by Jaldhar H. Vyas.

---

challenge-215/avery-adams/blogs.txt
challenge-215/avery-adams/perl/ch-1.pl
challenge-215/avery-adams/perl/ch-2.pl

Blogs.txt is included with links to blog posts.

Challenge 215 solutions for Avery Adams

---

challenge-215/polettix/blog.txt
challenge-215/polettix/blog1.txt
challenge-215/polettix/perl/ch-1.pl
challenge-215/polettix/perl/ch-2.pl
challenge-215/polettix/raku/ch-1.raku
challenge-215/polettix/raku/ch-2.raku

Just in time I hope!!! Thank you for evertying, cheers!

Add polettix's solution to challenge-215

---

challenge-215/barroff/perl/ch-1.pl
challenge-215/barroff/perl/ch-2.pl
challenge-215/barroff/raku/ch-1.raku
challenge-215/barroff/raku/ch-2.raku

Hello
This pull request adds my Raku and Perl solutions for the tasks of challenge 215.

feat: add solutions for challenge 215 from BarrOff

---

challenge-216/wlmb/blog.txt
challenge-216/wlmb/perl/ch-1.pl
challenge-216/wlmb/perl/ch-2.pl

Solve PWC216

---

challenge-216/shimon-ben-avraham/raku/ch-1.md
challenge-216/shimon-ben-avraham/raku/ch-1.raku
challenge-216/shimon-ben-avraham/raku/registration-number.raku

Improved the output to match the examples.

Branch 216

---

challenge-216/ribtips/perl/ch-1.pl
challenge-216/ribtips/perl/ch-2.pl

2 perl solutions for challenge 216

Challenge 216 from RibTips

---

challenge-056/jaldhar-h-vyas/blog.txt
challenge-056/jaldhar-h-vyas/perl/ch-1.pl
challenge-056/jaldhar-h-vyas/perl/ch-2.pl
challenge-056/jaldhar-h-vyas/raku/ch-1.p6
challenge-056/jaldhar-h-vyas/raku/ch-2.p6

Challenge 056 by Jaldhar H. Vyas.

---

challenge-216/barroff/raku/ch-1.raku

Hello
This pull request contains my solution for task one of challenge 216.

feat: add solution for challenge 216 from BarrOff

---

challenge-217/wlmb/blog.txt
challenge-217/wlmb/perl/ch-1.pl
challenge-217/wlmb/perl/ch-2.pl

Solve PWC217

---

challenge-216/polettix/perl/ch-2.pl
challenge-216/polettix/raku/ch-2.raku

Hi! E. Choroba kindly provided a test case that exposed a bug in my solution... here's the fixed version. Thanks for everything!

Fix bug detected by E. Choroba

---

challenge-217/aut0exec/perl/challenge_1.pl
challenge-217/aut0exec/perl/challenge_2.pl

Challenge 217

---

challenge-217/robbie-hatley/blog.txt
challenge-217/robbie-hatley/perl/ch-1.pl
challenge-217/robbie-hatley/perl/ch-2.pl

Instead of using a "special sort" approach for #2, I used a "combinatorics" approach. Probably slower, but much simpler.

Robbie Hatley's solutions in Perl for The Weekly Challenge 217

---

challenge-217/polettix/blog.txt
challenge-217/polettix/blog1.txt
challenge-217/polettix/perl/ch-1.pl
challenge-217/polettix/perl/ch-2.pl
challenge-217/polettix/raku/ch-1.raku
challenge-217/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Thank you for all your energy!

Add polettix's solution to challenge-217

---

challenge-215/Week 215/simon-dueck/README
challenge-215/Week 215/simon-dueck/fsharp/ch-1.fsx
challenge-215/Week 215/simon-dueck/fsharp/ch-2.fsx
challenge-216/simon-dueck/README
challenge-216/simon-dueck/fsharp/ch-1.fsx
challenge-217/simon-dueck/README
challenge-217/simon-dueck/fsharp/ch-1.fsx

Added solutions for task 1 and 2 for week 215, task 1 for week 216 and task 1 for week 217

Added solutions by Simon Dueck in F#

---

challenge-217/duncan-c-white/README
challenge-217/duncan-c-white/perl/ch-1.pl
challenge-217/duncan-c-white/perl/ch-2.pl

hacked a non-optimal solution together, will think again and do C translations tomorrow

got stuck on task 2, was tired, couldn't think straight

---

challenge-218/wlmb/blog.txt
challenge-218/wlmb/perl/ch-1.pl
challenge-218/wlmb/perl/ch-2.pl

Solve PWC218

---

challenge-218/matthias-muth/README.md
challenge-218/matthias-muth/blog.txt
challenge-218/matthias-muth/perl/TestExtractor.pm
challenge-218/matthias-muth/perl/ch-1.pl
challenge-218/matthias-muth/perl/ch-2.pl
challenge-218/matthias-muth/perl/challenge-218.txt

... including blog post this week. Phew!

Challenge 218 solutions in Perl by Matthias Muth

---

challenge-218/robbie-hatley/blog.txt
challenge-218/robbie-hatley/perl/ch-1.pl

Only had time to do #1 this week, alas.

Robbie Hatley's solutions to The Weekly Challenge #218.

---

challenge-217/barroff/perl/ch-1.pl
challenge-217/barroff/raku/ch-1.raku
challenge-217/barroff/raku/ch-2.raku

Hello
I missed the deadline for last weeks challenge so now this pull request adds my Perl and Raku solutions for challenge 217.

feat: add solutions for challenge 217 from BarrOff

---

challenge-218/barroff/gp/ch-1.gp
challenge-218/barroff/perl/ch-1.pl
challenge-218/barroff/raku/ch-1.raku
challenge-218/barroff/vlang/ch-1.v
challenge-218/barroff/vlang/ch-1_test.v

Hello
This pull request adds my Perl, Raku, [PARI/GP](https://pari.math.u-bordeaux.fr/) and [vlang](https://vlang.io) solutions for exercise one of challenge 218.

feat: add solutions for challenge 218 from BarrOff

---

challenge-219/polettix/blog.txt
challenge-219/polettix/blog1.txt
challenge-219/polettix/perl/ch-1.pl
challenge-219/polettix/perl/ch-2.pl
challenge-219/polettix/raku/ch-1.raku
challenge-219/polettix/raku/ch-2.raku

Hi! Thank you so much for last week... and for all your hard work.

Add polettix's solution to challenge-219

---

challenge-219/jo-37/octave/ch-2.m
challenge-219/jo-37/perl/ch-1.pl

Again choosing octave for task 2 due to its nice GLPK integration.

Solutions to challenge 219

---

challenge-219/lance-wicks/perl/ch-1.pl
challenge-219/lance-wicks/perl/lib/My/Sorted/Square.pm
challenge-219/lance-wicks/perl/t/01-sorted-squares.t

My thoughts are with you Mohammad and your family.
Lance.

Perl version for Challenge 219wq

---

challenge-219/barroff/perl/ch-1.pl
challenge-219/barroff/raku/ch-1.raku

Hello
This pull request adds my Perl and Raku, solutions for exercise one of challenge 219.

feat: add solutions for challenge 219 from BarrOff

---

challenge-219/matthias-muth/README.md
challenge-219/matthias-muth/blog.txt
challenge-219/matthias-muth/perl/TestExtractor.pm
challenge-219/matthias-muth/perl/ch-1.pl
challenge-219/matthias-muth/perl/ch-2.pl
challenge-219/matthias-muth/perl/challenge-219.txt

Challenge 219 solutions in Perl by Matthias Muth

---

challenge-220/wlmb/blog.txt
challenge-220/wlmb/perl/ch-1.pl
challenge-220/wlmb/perl/ch-2.pl

Solve PWC220

---

challenge-220/polettix/blog.txt
challenge-220/polettix/blog1.txt
challenge-220/polettix/perl/ch-1.pl
challenge-220/polettix/perl/ch-2.pl
challenge-220/polettix/raku/ch-1.raku
challenge-220/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Thank you for everything, as always!

Add polettix's solution to challenge-220

---

challenge-220/barroff/perl/ch-1.pl
challenge-220/barroff/raku/ch-1.raku
challenge-220/barroff/raku/ch-2.raku

Hello
This pull request adds my Perl and Raku solutions for challenge 220.

feat: add solutions for challenge 220 from BarrOff

---

challenge-220/matthias-muth/README.md
challenge-220/matthias-muth/perl/ch-1.pl
challenge-220/matthias-muth/perl/ch-2.pl

Challenge 220 by Matthias Muth: Clarifications and small corrections.

---

challenge-220/e-choroba/perl/ch-2.pl

If we wrap from both sides, we don't have to start from all the elements, a single one is enough.

Optimize 220/2

---

challenge-221/blog.txt
challenge-221/perl/ch-1.pl
challenge-221/perl/ch-2.pl

Regards, hope things get better.

Solve PWC221

---

challenge-221/lance-wicks/blog.txt
challenge-221/lance-wicks/perl/ch-1.pl
challenge-221/lance-wicks/perl/lib/Good/Strings.pm
challenge-221/lance-wicks/perl/t/ch1.t

Hi... thoughts with you and your family Mohammad!

Challenge 1 - Lance

---

challenge-221/polettix/blog.txt
challenge-221/polettix/blog1.txt
challenge-221/polettix/perl/ch-1.pl
challenge-221/polettix/perl/ch-2.pl
challenge-221/polettix/raku/ch-1.raku
challenge-221/polettix/raku/ch-2.raku

Hi! Pleast find my weekly contribution. Cheers!

Add polettix's solution to challenge-221

---

challenge-221/barroff/raku/ch-1.raku
challenge-221/barroff/raku/ch-2.raku

Hello
This pull request adds my Raku solutions for challenge 221.

feat: add solutions for challenge 221 from BarrOff

---

challenge-221/matthias-muth/README.md
challenge-221/matthias-muth/blog.txt
challenge-221/matthias-muth/perl/TestExtractor.pm
challenge-221/matthias-muth/perl/ch-1.pl
challenge-221/matthias-muth/perl/ch-2.pl
challenge-221/matthias-muth/perl/challenge-221.txt

Nice one! :-)
Thank you for the challenge!

Challenge 221 solutions in Perl by Matthias Muth

---

challenge-222/polettix/blog.txt
challenge-222/polettix/blog1.txt
challenge-222/polettix/perl/ch-1.pl
challenge-222/polettix/perl/ch-2.pl
challenge-222/polettix/raku/ch-1.raku
challenge-222/polettix/raku/ch-2.raku

Hi! Here is my contribution for this week's challenge. 222 what a number, uh?!?

Add polettix's solution to challenge-222

---

challenge-222/matthias-muth/README.md
challenge-222/matthias-muth/blog.txt
challenge-222/matthias-muth/perl/TestExtractor.pm
challenge-222/matthias-muth/perl/ch-1.pl
challenge-222/matthias-muth/perl/ch-2.pl
challenge-222/matthias-muth/perl/challenge-222.txt

Thank you for the challenge, and for the 'Champion' honor!

Challenge 222 solutions in Perl by Matthias Muth

---

challenge-222/barroff/perl/ch-1.pl
challenge-222/barroff/perl/ch-2.pl
challenge-222/barroff/raku/ch-1.raku
challenge-222/barroff/raku/ch-2.raku

Hello
This pull request adds my Perl and Raku solutions for challenge 222.

feat: add solutions for challenge 222 from BarrOff

---

challenge-198/e-choroba/perl/ch-2.pl
challenge-223/e-choroba/perl/ch-1.pl
challenge-223/e-choroba/perl/ch-2.pl

In fact, I had a bug in 198/2, its solution was in fact a solution to 223/1.

Solve 223: Count Primes & Box Coins, fix 198/2

---

challenge-223/wlmb/blog.txt
challenge-223/wlmb/perl/ch-1.pl
challenge-223/wlmb/perl/ch-2.pl

Solve PWC223

---

challenge-223/matthias-muth/README.md
challenge-223/matthias-muth/blog.txt
challenge-223/matthias-muth/perl/TestExtractor.pm
challenge-223/matthias-muth/perl/ch-1.pl
challenge-223/matthias-muth/perl/ch-2.pl
challenge-223/matthias-muth/perl/challenge-223.txt

Challenge 223 solutions in Perl by Matthias Muth

---

challenge-223/polettix/blog.txt
challenge-223/polettix/blog1.txt
challenge-223/polettix/perl/ch-1.pl
challenge-223/polettix/perl/ch-2.pl
challenge-223/polettix/raku/ch-1.raku
challenge-223/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge, I hope you're doing fine!

Add polettix's solution to challenge-223

---

challenge-223/barroff/perl/ch-1.pl
challenge-223/barroff/raku/ch-1.raku

Hello
This pull request adds my Perl and Raku solutions for task one of challenge 223.

feat: add solutions for challenge 223 from BarrOff

---

challenge-224/wlmb/blog.txt
challenge-224/wlmb/perl/ch-1.pl
challenge-224/wlmb/perl/ch-2.pl

Solve PWC224

---

challenge-224/matthias-muth/README.md
challenge-224/matthias-muth/blog.txt
challenge-224/matthias-muth/perl/TestExtractor.pm
challenge-224/matthias-muth/perl/ch-1.pl
challenge-224/matthias-muth/perl/ch-2.pl
challenge-224/matthias-muth/perl/challenge-224.txt

Challenge 224 solutions in Perl by Matthias Muth

---

challenge-224/polettix/blog.txt
challenge-224/polettix/blog1.txt
challenge-224/polettix/perl/ch-1.pl
challenge-224/polettix/perl/ch-2.pl
challenge-224/polettix/raku/ch-1.raku
challenge-224/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge. Thank you for everything Mohammad.

Add polettix's solution to challenge-224

---

challenge-224/barroff/awk/ch-1.awk
challenge-224/barroff/perl/ch-1.pl
challenge-224/barroff/raku/ch-1.raku

Hello
This pull request adds my Awk, Perl and Raku solutions for task one of challenge 224.

feat: add solutions for challenge 224 from BarrOff

---

challenge-224/jaldhar-h-vyas/blog.txt
challenge-224/jaldhar-h-vyas/perl/ch-1.pl
challenge-224/jaldhar-h-vyas/perl/ch-2.pl
challenge-224/jaldhar-h-vyas/raku/ch-1.sh
challenge-224/jaldhar-h-vyas/raku/ch-2.raku

Sorry the last one had errors in it.

Challenge 224 by Jaldhar H. Vyas.

---

challenge-225/wlmb/blog.txt
challenge-225/wlmb/perl/ch-1.pl
challenge-225/wlmb/perl/ch-2.pl

Solve PWC 225

---

challenge-222/0rir/raku/ch-1.raku
challenge-222/0rir/raku/ch-2.raku

222 -- Move misplaced files.

---

challenge-225/mattneleigh/perl/ch-1.pl
challenge-225/mattneleigh/perl/ch-2.pl

new file:   challenge-225/mattneleigh/perl/ch-2.pl

	new file:   challenge-225/mattneleigh/perl/ch-1.pl

---

challenge-225/barroff/perl/ch-1.pl
challenge-225/barroff/raku/ch-1.raku

Hello
This pull request adds my Perl and Raku solutions for task one of challenge 225.

feat: add solutions for challenge 225 from BarrOff

---

challenge-225/matthias-muth/README.md
challenge-225/matthias-muth/blog.txt
challenge-225/matthias-muth/perl/TestExtractor.pm
challenge-225/matthias-muth/perl/ch-1.pl
challenge-225/matthias-muth/perl/ch-2.pl
challenge-225/matthias-muth/perl/challenge-225.txt

Challenge 225 solutions in Perl by Matthias Muth

---

challenge-226/mark-anderson/raku/ch-1.raku
challenge-226/mark-anderson/raku/ch-2.raku

Congratulations on your well deserved White Camel Award!!

Challenge 226 Solutions (Raku)

---

challenge-226/wlmb/blog.txt
challenge-226/wlmb/perl/ch-1.pl
challenge-226/wlmb/perl/ch-2.pl

Solve PWC 226

---

challenge-226/adriaandens/perl/ch-1.pl
challenge-226/adriaandens/perl/ch-2.pl

I saw your talk on TPRC 2023 and thought to join the fun :)

A solution for chal 226

---

challenge-226/polettix/blog.txt
challenge-226/polettix/blog1.txt
challenge-226/polettix/perl/ch-1.pl
challenge-226/polettix/perl/ch-2.pl
challenge-226/polettix/raku/ch-1.raku
challenge-226/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week... and my apologies for not opening a pull request the last week 🤦 and my thanks for doing it yourself 🙇

Add polettix's solution to challenge-226

---

challenge-226/mattneleigh/perl/ch-1.pl
challenge-226/mattneleigh/perl/ch-2.pl

new file:   challenge-226/mattneleigh/perl/ch-2.pl

	new file:   challenge-226/mattneleigh/perl/ch-1.pl

---

challenge-226/barroff/julia/ch-1.jl
challenge-226/barroff/julia/ch-2.jl
challenge-226/barroff/perl/ch-1.pl
challenge-226/barroff/perl/ch-2.pl
challenge-226/barroff/raku/ch-1.p6
challenge-226/barroff/raku/ch-2.p6

Hello
This pull request adds my Julia, Perl and Raku solutions for challenge 226.

feat: add solutions for challenge 226 from BarrOff

---

challenge-227/wlmb/blog.txt
challenge-227/wlmb/perl/ch-1.pl
challenge-227/wlmb/perl/ch-2.pl

Solve PWC227

---

challenge-227/andreas-voegele/kotlin/ch-1.kts
challenge-227/andreas-voegele/kotlin/ch-2.kts
challenge-227/andreas-voegele/perl/ch-1.pl
challenge-227/andreas-voegele/perl/ch-2.pl

Congratulations for winning the White Camel award. And thanks a lot for the Learning Perl Exercises coupon.

Challenge 227 by Andreas Vögele

---

challenge-227/polettix/blog.txt
challenge-227/polettix/blog1.txt
challenge-227/polettix/perl/ch-1.pl
challenge-227/polettix/perl/ch-2.pl
challenge-227/polettix/raku/ch-1.raku
challenge-227/polettix/raku/ch-2.raku

Hi! Please find my contribution for this week's challenge, thank you for the hard work and dedication!

Add polettix's solution to challenge-227

---

challenge-226/matthias-muth/README.md
challenge-226/matthias-muth/blog.txt
challenge-226/matthias-muth/perl/TestExtractor.pm
challenge-226/matthias-muth/perl/ch-1.pl
challenge-226/matthias-muth/perl/ch-2.pl
challenge-226/matthias-muth/perl/challenge-226.txt

Sorry I couldn't send my challenge 226 solutions in time!
And congrats for the White Camel Award! It is well deserved!
Thank you for all the challenges and the lot of work you do!
Kind regards,
Matthias

Challenge 226 solutions in Perl by Matthias Muth

---

challenge-227/mattneleigh/perl/ch-1.pl
challenge-227/mattneleigh/perl/ch-2.pl

new file:   challenge-227/mattneleigh/perl/ch-2.pl

	new file:   challenge-227/mattneleigh/perl/ch-1.pl

---

challenge-227/andreas-voegele/kotlin/ch-2.kts
challenge-227/andreas-voegele/perl/ch-2.pl

I've added functions that evaluate strings with Roman numerals.

Evaluate strings

---

challenge-227/matthias-muth/README.md
challenge-227/matthias-muth/blog.txt
challenge-227/matthias-muth/perl/TestExtractor.pm
challenge-227/matthias-muth/perl/ch-1.pl
challenge-227/matthias-muth/perl/ch-2.pl
challenge-227/matthias-muth/perl/challenge-227.txt

Challenge 227 solutions in Perl by Matthias Muth

---

challenge-227/barroff/raku/ch-1.p6

Hello
This pull request adds my Raku solution for task one of challenge 227.

feat: add solution for challenge 227 from BarrOff

---

challenge-228/wlmb/blog.txt
challenge-228/wlmb/perl/ch-1.pl
challenge-228/wlmb/perl/ch-2.pl

Solve PWC228

---

challenge-228/spadacciniweb/perl/ch-1.pl
challenge-228/spadacciniweb/python/ch-1.py

PWC 228 - Perl and Python

---

challenge-221/andreas-voegele/kotlin/ch-2.kts
challenge-223/andreas-voegele/kotlin/ch-1.kts
challenge-224/andreas-voegele/kotlin/ch-2.kts
challenge-225/andreas-voegele/kotlin/ch-1.kts
challenge-228/andreas-voegele/kotlin/ch-1.kts
challenge-228/andreas-voegele/kotlin/ch-2.kts
challenge-228/andreas-voegele/perl/ch-1.pl
challenge-228/andreas-voegele/perl/ch-2.pl

Here are my solutions to challenge 228. There's another commit that updates some of my older solutions, which makes the Kotlin linter happy. Bon voyage to India.

Challenge 228

---

challenge-228/polettix/blog.txt
challenge-228/polettix/blog1.txt
challenge-228/polettix/perl/ch-1.pl
challenge-228/polettix/perl/ch-2.pl
challenge-228/polettix/raku/ch-1.raku
challenge-228/polettix/raku/ch-2.raku

Hello! Please find my contribution to this week's challenge, thank you for everything and keep up with the good work!

Add polettix's solution to challenge-228

---

challenge-228/matthias-muth/perl/ch-2.pl

Sorry!!
I've overseen this...
Thanks!

Challenge 228 small update: Switch perl/ch-2.pl from running benchmarks to running tests.

---

challenge-228/barroff/perl/ch-1.pl
challenge-228/barroff/perl/ch-2.pl
challenge-228/barroff/raku/ch-1.p6
challenge-228/barroff/raku/ch-2.p6

Hello
This pull request adds my Perl and Raku solutions for challenge 228.

feat: add solutions for challenge 228 from BarrOff

---

challenge-229/wlmb/blog.txt
challenge-229/wlmb/perl/ch-1.pl
challenge-229/wlmb/perl/ch-2.pl

Solve PWC229

---

challenge-229/barroff/julia/ch-1.jl
challenge-229/barroff/julia/ch-2.jl
challenge-229/barroff/nim/ch_1.nim
challenge-229/barroff/nim/ch_2.nim
challenge-229/barroff/perl/ch-1.pl
challenge-229/barroff/perl/ch-2.pl
challenge-229/barroff/raku/ch-1.p6
challenge-229/barroff/raku/ch-2.p6

Hello
This pull request adds my Perl, Raku, Julia and Nim solutions for challenge 229.

feat: add solutions for challenge 229 from BarrOff

---

challenge-230/spadacciniweb/perl/ch-1.pl
challenge-230/spadacciniweb/perl/ch-2.pl

ch-1 and ch-2 in Perl

---

challenge-230/wlmb/blog.txt
challenge-230/wlmb/perl/ch-1.pl
challenge-230/wlmb/perl/ch-2.pl

Solve PWC230

---

challenge-230/matthias-muth/README.md
challenge-230/matthias-muth/blog.txt
challenge-230/matthias-muth/perl/TestExtractor.pm
challenge-230/matthias-muth/perl/ch-1.pl
challenge-230/matthias-muth/perl/ch-2.pl
challenge-230/matthias-muth/perl/challenge-230.txt

Challenge 230 Task 1 and 2 solutions in Perl by Matthias Muth

---

challenge-230/barroff/julia/ch-1.jl
challenge-230/barroff/julia/ch-2.jl
challenge-230/barroff/perl/ch-1.pl
challenge-230/barroff/perl/ch-2.pl
challenge-230/barroff/raku/ch-1.p6
challenge-230/barroff/raku/ch-2.p6

Hello
This pull request adds my Perl, Raku and Julia solutions for challenge 230.

feat: add solutions for challenge 230 from BarrOff

---

challenge-229/sgreen/README.md
challenge-230/sgreen/README.md
challenge-230/sgreen/blog.txt
challenge-230/sgreen/perl/ch-1.pl
challenge-230/sgreen/perl/ch-2.pl
challenge-230/sgreen/python/ch-1.py
challenge-230/sgreen/python/ch-2.py

Simon's solution to challenge 230

---

challenge-231/wlmb/blog.txt
challenge-231/wlmb/perl/ch-1.pl
challenge-231/wlmb/perl/ch-2.pl

Solve PWC231

---

challenge-231/andreas-voegele/blog.txt
challenge-231/andreas-voegele/kotlin/ch-1.kts
challenge-231/andreas-voegele/kotlin/ch-2.kts
challenge-231/andreas-voegele/perl/ch-1.pl
challenge-231/andreas-voegele/perl/ch-2.pl

BTW, I don't know whether texts such as https://theweeklychallenge.org/blog/perl-weekly-challenge-231/#TASK2 with "phone" and "sex" in the same sentence are ranked high by search engines 😀 "Gender" might be better and will also make SJWs happy.

Challenge 231 by Andreas Vögele

---

challenge-231/packy-anderson/README.md
challenge-231/packy-anderson/blog.txt
challenge-231/packy-anderson/perl/ch-1.pl
challenge-231/packy-anderson/perl/ch-2.pl
challenge-231/packy-anderson/raku/ch-1.raku
challenge-231/packy-anderson/raku/ch-2.raku

Challenge 231 solutions in Perl and Raku by Packy Anderson, w/ one blog post

Challenge 231 solutions for Packy Anderson

---

challenge-231/spadacciniweb/perl/ch-1.pl
challenge-231/spadacciniweb/perl/ch-2.pl

PWC-231: Perl

---

challenge-231/sgreen/README.md
challenge-231/sgreen/blog.txt
challenge-231/sgreen/perl/ch-1.pl
challenge-231/sgreen/perl/ch-2.pl
challenge-231/sgreen/python/ch-1.py
challenge-231/sgreen/python/ch-2.py

Simon's solution to challenge 231

---

challenge-231/matthias-muth/README.md
challenge-231/matthias-muth/blog.txt
challenge-231/matthias-muth/perl/TestExtractor.pm
challenge-231/matthias-muth/perl/ch-1.pl
challenge-231/matthias-muth/perl/ch-2.pl
challenge-231/matthias-muth/perl/challenge-231.txt

Challenge 231 Task 1 and 2 solutions in Perl by Matthias Muth

---

challenge-231/barroff/julia/ch-1.jl
challenge-231/barroff/julia/ch-2.jl
challenge-231/barroff/nim/ch_1.nim
challenge-231/barroff/nim/ch_2.nim
challenge-231/barroff/perl/ch-1.pl
challenge-231/barroff/perl/ch-2.pl
challenge-231/barroff/raku/ch-1.p6
challenge-231/barroff/raku/ch-2.p6

Hello
This pull request adds my Perl, Raku, Nim and Julia solutions for challenge 231.

feat: add solutions for challenge 231 from BarrOff

---

challenge-233/mark-anderson/raku/ch-1.raku
challenge-233/mark-anderson/raku/ch-2.raku

I was worried about you. Glad you're back and feeling better.

Challenge 233

---

challenge-233/wlmb/blog.txt
challenge-233/wlmb/perl/ch-1.pl
challenge-233/wlmb/perl/ch-2.pl

Regards, hope you recover fully soon

Solve PWC233

---

challenge-233/packy-anderson/README.md
challenge-233/packy-anderson/blog.txt
challenge-233/packy-anderson/perl/ch-1.pl
challenge-233/packy-anderson/perl/ch-2.pl
challenge-233/packy-anderson/python/ch-1.py
challenge-233/packy-anderson/python/ch-2.py
challenge-233/packy-anderson/raku/ch-1.raku
challenge-233/packy-anderson/raku/ch-2.raku

Perl, Raku, and Python solutions with one blog post.

Challenge 233 solutions by Packy Anderson

---

challenge-233/mattneleigh/perl/ch-1.pl
challenge-233/mattneleigh/perl/ch-2.pl

new file:   challenge-233/mattneleigh/perl/ch-2.pl

	new file:   challenge-233/mattneleigh/perl/ch-1.pl

---

challenge-233/spadacciniweb/perl/ch-1.pl
challenge-233/spadacciniweb/perl/ch-2.pl

PWC-233: Perl

---

challenge-233/matthias-muth/README.md
challenge-233/matthias-muth/blog.txt
challenge-233/matthias-muth/perl/TestExtractor.pm
challenge-233/matthias-muth/perl/ch-1.pl
challenge-233/matthias-muth/perl/ch-2.pl
challenge-233/matthias-muth/perl/challenge-233.txt

Best wishes for a full recovery!
Thank you for the challenge!

Challenge 233 Task 1 and 2 solutions in Perl by Matthias Muth

---

challenge-233/barroff/raku/ch-1.raku
challenge-233/barroff/raku/ch-2.raku

Hello
This pull request adds my Raku solutions for challenge 233.

feat: add solutions for challenge 233 from BarrOff

---

challenge-233/2colours/raku/ch-1.raku
challenge-233/2colours/raku/ch-2.raku

Hi,
sorry I kinda skipped out of the weekly challenges but it was really pleasant to hear about it in a Prolog community so I thought, let's show them the power of Raku! I hope I didn't mess it up, though.
Please keep up the good work and also, accept this really banal piece of code I created for this week.
Cheers

Weekly solutions for 2colours (Raku)

---

challenge-234/wlmb/blog.txt
challenge-234/wlmb/perl/ch-1.pl
challenge-234/wlmb/perl/ch-2.pl

solve pwc234

---

challenge-234/jo-37/perl/ch-1.pl
challenge-234/jo-37/perl/ch-2.pl

I'll be on vacation for a few weeks.

Solutions to challenge 234

---

challenge-234/mattneleigh/perl/ch-1.pl
challenge-234/mattneleigh/perl/ch-2.pl

new file:   challenge-234/mattneleigh/perl/ch-2.pl

	new file:   challenge-234/mattneleigh/perl/ch-1.pl

---

challenge-234/matthias-muth/README.md
challenge-234/matthias-muth/blog.txt
challenge-234/matthias-muth/perl/TestExtractor.pm
challenge-234/matthias-muth/perl/ch-1.pl
challenge-234/matthias-muth/perl/ch-2.pl
challenge-234/matthias-muth/perl/challenge-234.txt

Challenge 234 Task 1 and 2 solutions in Perl by Matthias Muth

---

challenge-234/barroff/julia/ch-1.jl
challenge-234/barroff/julia/ch-2.jl
challenge-234/barroff/raku/ch-1.raku
challenge-234/barroff/raku/ch-2.raku

Hello
This pull request adds my Julia and Raku solutions for challenge 234.

feat: add solutions for challenge 234 from BarrOff

---

challenge-234/0rir/raku/ch-2.raku

234 ch-2.raku

---

challenge-234/0rir/raku/ch-1.raku

234 ch-1.raku

---

challenge-234/perlboy1967/perl/ch1.pl
challenge-234/perlboy1967/perl/ch2.pl
challenge-235/perlboy1967/perl/ch1.pl
challenge-235/perlboy1967/perl/ch2.pl

Had forgotten to push to origin before Sunday night

w234 - Task 1 & 2

---

challenge-235/wlmb/blog.txt
challenge-235/wlmb/perl/ch-1.pl
challenge-235/wlmb/perl/ch-2.pl

Solve PWC235

---

challenge-235/packy-anderson/README.md
challenge-235/packy-anderson/java/Ch1.java
challenge-235/packy-anderson/java/Ch2.java
challenge-235/packy-anderson/perl/ch-1.pl
challenge-235/packy-anderson/perl/ch-2.pl
challenge-235/packy-anderson/python/ch-1.py
challenge-235/packy-anderson/python/ch-2.py
challenge-235/packy-anderson/raku/ch-1.raku
challenge-235/packy-anderson/raku/ch-2.raku

* Perl
* Raku
* Python
* Java
One blog entry as well.

Challenge 235 solutions by Packy Anderson

---

challenge-235/mattneleigh/perl/ch-1.pl
challenge-235/mattneleigh/perl/ch-2.pl

new file:   challenge-235/mattneleigh/perl/ch-2.pl

	new file:   challenge-235/mattneleigh/perl/ch-1.pl

---

challenge-235/demerphq/README
challenge-235/demerphq/perl/ch-1.pl
challenge-235/demerphq/perl/ch-2.pl

My first "official" challenge attempt.

Solution to challenge-235 by Yves Orton

---

challenge-235/jo-37/perl/ch-1.pl
challenge-235/jo-37/perl/ch-2.pl

Vacation challenge from Porto, Portugal

Solutions to challenge 235

---

challenge-235/spadacciniweb/perl/ch-2.pl

PWC-235 ch-1.pl

---

challenge-235/barroff/julia/ch-1.jl
challenge-235/barroff/julia/ch-2.jl
challenge-235/barroff/perl/ch-1.pl
challenge-235/barroff/perl/ch-2.pl
challenge-235/barroff/raku/ch-1.p6
challenge-235/barroff/raku/ch-2.p6

Hello
This pull request adds my Julia, Perl and Raku solutions for challenge 235.

feat: add solutions for challenge 235 from BarrOff

---

challenge-235/matthias-muth/README.md
challenge-235/matthias-muth/blog.txt
challenge-235/matthias-muth/perl/TestExtractor.pm
challenge-235/matthias-muth/perl/ch-1.pl
challenge-235/matthias-muth/perl/ch-2.pl
challenge-235/matthias-muth/perl/challenge-235.txt

Challenge 235 Task 1 and 2 solutions in Perl by Matthias Muth

---

challenge-236/wlmb/blog.txt
challenge-236/wlmb/perl/ch-1.pl
challenge-236/wlmb/perl/ch-2.pl

SOlve PWC236

---

challenge-236/demerphq/perl/ch-1.pl
challenge-236/demerphq/perl/ch-2.pl

Exact Change - use a simple algorithm to manage the wallet. The problem description makes it seem like there might be a need to recursively try multiple solutions, but in practice this is not necessary.
Count Loops - I originally implemented this using a destructive approach with a hash, but in my benchmarks this was slow and also non-determinisitc, and making it deterministic would make it slower. Using an array based approach seems like it would be worse, but in practice, with randomly generated input data a pure array approach was faster. *Shrug*

Challenge-236 - "Exact Change" and "Count Loops"

---

challenge-236/jo-37/perl/ch-1.pl
challenge-236/jo-37/perl/ch-2.pl

Vacation challenge from Cascais, Portugal,
@E7-87-83: CY, thanks for Math::Permutation

Solutions to challenge 236

---

challenge-229/polettix/blog.txt
challenge-229/polettix/blog1.txt
challenge-229/polettix/perl/ch-1.pl
challenge-229/polettix/perl/ch-2.pl
challenge-229/polettix/raku/ch-1.raku
challenge-229/polettix/raku/ch-2.raku

Hi! Long time no see, here's my contribution after some time of relax.
I hope everything is fine with you :smile: Thanks for being the rock that you are!

Add polettix's solution to challenge-229

---

challenge-236/mattneleigh/perl/ch-1.pl
challenge-236/mattneleigh/perl/ch-2.pl

new file:   challenge-236/mattneleigh/perl/ch-2.pl

	new file:   challenge-236/mattneleigh/perl/ch-1.pl

---

challenge-236/matthias-muth/README.md
challenge-236/matthias-muth/blog.txt
challenge-236/matthias-muth/perl/TestExtractor.pm
challenge-236/matthias-muth/perl/ch-1.pl
challenge-236/matthias-muth/perl/ch-2.pl
challenge-236/matthias-muth/perl/challenge-236.txt

Challenge 236 Task 1 and 2 solutions in Perl by Matthias Muth

---

challenge-237/wlmb/blog.txt
challenge-237/wlmb/perl/ch-1.pl
challenge-237/wlmb/perl/ch-2.pl

Solve PWC237

---

challenge-237/packy-anderson/README.md
challenge-237/packy-anderson/blog.txt
challenge-237/packy-anderson/java/Ch1.java
challenge-237/packy-anderson/java/Ch2.java
challenge-237/packy-anderson/perl/ch-1.pl
challenge-237/packy-anderson/perl/ch-2.pl
challenge-237/packy-anderson/python/ch-1.py
challenge-237/packy-anderson/python/ch-2.py
challenge-237/packy-anderson/raku/ch-1.raku
challenge-237/packy-anderson/raku/ch-2.raku

Solutions in:
* Perl
* Raku
* Python
* Java
One blog post.

Challenge 237 solutions by Packy Anderson

---

challenge-237/jo-37/perl/ch-1.pl
challenge-237/jo-37/perl/ch-2.pl

Vacation challenge, finally from Lisbon, Portugal

Solutions to challenge 237

---

challenge-237/polettix/blog.txt
challenge-237/polettix/blog1.txt
challenge-237/polettix/perl/ch-1.pl
challenge-237/polettix/perl/ch-2.pl
challenge-237/polettix/raku/ch-1.raku
challenge-237/polettix/raku/ch-2.raku

Hi! Please find my contributions for this week's challenge.
Kudos for the second challenge, it was intriguing and super-fun to address. Thanks.

Add polettix's solution to challenge-237

---

challenge-237/matthias-muth/README.md
challenge-237/matthias-muth/blog.txt
challenge-237/matthias-muth/perl/TestExtractor.pm
challenge-237/matthias-muth/perl/ch-1.pl
challenge-237/matthias-muth/perl/ch-2.pl
challenge-237/matthias-muth/perl/challenge-237.txt

Challenge 237 Task 1 and 2 solutions in Perl by Matthias Muth

---

challenge-237/demerphq/README.md
challenge-237/demerphq/blog.txt
challenge-237/demerphq/js/.gitignore
challenge-237/demerphq/js/ch-1.js
challenge-237/demerphq/js/ch-2.js
challenge-237/demerphq/js/package.json
challenge-237/demerphq/perl/ch-1.pl
challenge-237/demerphq/perl/ch-2.pl

Challenge #237 - Seize The Day and Maximum Greatness

---

challenge-237/barroff/raku/ch-1.p6
challenge-237/barroff/raku/ch-2.p6
challenge-237/barroff/raku/ch_1.nim
challenge-237/barroff/raku/ch_2.nim

Hello
This pull request adds my Nim and Raku solutions for challenge 237.

feat: add solutions for challenge 237 from BarrOff

---

challenge-238/wlmb/blog.txt
challenge-238/wlmb/perl/ch-1.pl
challenge-238/wlmb/perl/ch-2.pl

Solve PWC238

---

challenge-238/packy-anderson/README.md
challenge-238/packy-anderson/blog.txt
challenge-238/packy-anderson/perl/ch-1.pl
challenge-238/packy-anderson/perl/ch-2.pl
challenge-238/packy-anderson/python/ch-1.py
challenge-238/packy-anderson/python/ch-2.py
challenge-238/packy-anderson/raku/ch-1.raku
challenge-238/packy-anderson/raku/ch-2.raku

Solutions in:
* Perl
* Raku
* Python
One blog post!

Challenge 238 solutions by Packy Anderson

---

challenge-238/spazm/python/task_1_running_sum.py
challenge-238/spazm/python/task_2_persistence_sort.py

with pretty modulino unittests

feature: Add TWC 238 python solution by @spazm

---

challenge-238/barroff/perl/ch-1.pl
challenge-238/barroff/raku/ch-1.p6

Hello
This pull request adds my Perl and Raku solutions for task one of challenge 238.

feat: add solutions for challenge 238 from BarrOff

---

challenge-238/matthias-muth/README.md
challenge-238/matthias-muth/blog.txt
challenge-238/matthias-muth/perl/TestExtractor.pm
challenge-238/matthias-muth/perl/ch-1.pl
challenge-238/matthias-muth/perl/ch-2.pl
challenge-238/matthias-muth/perl/challenge-238.txt

Challenge 238 Task 1 and 2 solutions in Perl by Matthias Muth

---

challenge-239/wlmb/blog.txt
challenge-239/wlmb/perl/ch-1.pl
challenge-239/wlmb/perl/ch-2.pl

Solve PWC239

---

challenge-239/matthias-muth/README.md
challenge-239/matthias-muth/blog.txt
challenge-239/matthias-muth/perl/TestExtractor.pm
challenge-239/matthias-muth/perl/ch-1.pl
challenge-239/matthias-muth/perl/ch-2.pl
challenge-239/matthias-muth/perl/challenge-239.txt

Much earlier than usual! Maybe I can start a new tradition for myself...
**Thank you for the challenge!**

Challenge 239 Task 1 and 2 solutions in Perl by Matthias Muth

---

challenge-239/packy-anderson/README.md
challenge-239/packy-anderson/blog.txt
challenge-239/packy-anderson/perl/ch-1.pl
challenge-239/packy-anderson/perl/ch-2.pl
challenge-239/packy-anderson/python/ch-1.py
challenge-239/packy-anderson/python/ch-2.py
challenge-239/packy-anderson/raku/ch-1.raku
challenge-239/packy-anderson/raku/ch-2.raku

* Raku
* Perl
* Python
1 Blog post

Challenge 239 solutions by Packy Anderson

---

challenge-239/mattneleigh/perl/ch-1.pl
challenge-239/mattneleigh/perl/ch-2.pl

new file:   challenge-239/mattneleigh/perl/ch-2.pl

	new file:   challenge-239/mattneleigh/perl/ch-1.pl

---

challenge-239/razetime/README
challenge-239/razetime/prolog/ch-1.pl
challenge-239/razetime/prolog/ch-2.pl
challenge-239/razetime/raku/ch-1.raku
challenge-239/razetime/raku/ch-2.raku

Hi, new contributor here. Hope the format given is ok. Wanna practice a little raku, so figured i would join in.

razetime challenge 239 raku and prolog solutions

---

challenge-239/spadacciniweb/perl/ch-1.pl
challenge-239/spadacciniweb/perl/ch-2.pl

PWC-219 in Perl

---

challenge-239/mattneleigh/perl/ch-2.pl

Punctuation correction in documentation- oops.

	modified:   challenge-239/mattneleigh/perl/ch-2.pl

---

challenge-238/polettix/blog.txt
challenge-238/polettix/blog1.txt
challenge-238/polettix/perl/ch-1.pl
challenge-238/polettix/perl/ch-2.pl
challenge-238/polettix/raku/ch-1.raku
challenge-238/polettix/raku/ch-2.raku

Hi! With almost a week of delay... here's my contribution for challenge 238. Thanks!

Add polettix's solution to challenge-238

---

challenge-239/polettix/blog.txt
challenge-239/polettix/blog1.txt
challenge-239/polettix/perl/ch-1.pl
challenge-239/polettix/perl/ch-2.pl
challenge-239/polettix/raku/ch-1.raku
challenge-239/polettix/raku/ch-2.raku

... and here we come with this week's challenge. Thanks for your dedication!

Add polettix's solution to challenge-239

---

challenge-239/memark/README
challenge-239/memark/uiua/ch-1.ua
challenge-239/memark/uiua/ch-2.ua

First time for me here. Uiua to the rescue!

Add memark's solution to challenge-239

---

challenge-239/barroff/julia/ch-1.jl
challenge-239/barroff/julia/ch-2.jl
challenge-239/barroff/nim/ch_1.nim
challenge-239/barroff/nim/ch_2.nim
challenge-239/barroff/perl/ch-1.pl
challenge-239/barroff/raku/ch-1.p6
challenge-239/barroff/raku/ch-2.p6

Hello
This pull request adds my Julia, Nim, Perl and Raku solutions for challenge 239.

feat: add solutions for challenge 239 from BarrOff

---

challenge-239/augiedb/blog.txt
challenge-239/augiedb/blog1.txt
challenge-239/augiedb/elixir/ch-1.exs
challenge-239/augiedb/js/ch-1.js
challenge-239/augiedb/perl/ch-1.pl
challenge-239/augiedb/python/ch-1.py

Just realized I'm late (time zones!  Argh!), but I'm submitting anyway...

Challenge entry from Augie De Blieck Jr.

---

challenge-240/wlmb/blog.txt
challenge-240/wlmb/perl/ch-1.pl
challenge-240/wlmb/perl/ch-2.pl

Solve PWC240

---

challenge-240/mattneleigh/perl/ch-1.pl
challenge-240/mattneleigh/perl/ch-2.pl

new file:   challenge-240/mattneleigh/perl/ch-2.pl

	new file:   challenge-240/mattneleigh/perl/ch-1.pl

---

challenge-240/mattneleigh/perl/ch-1.pl
challenge-240/mattneleigh/perl/ch-2.pl

modified:   challenge-240/mattneleigh/perl/ch-2.pl
Documentation tweaks

	modified:   challenge-240/mattneleigh/perl/ch-1.pl

---

challenge-240/spadacciniweb/perl/ch-1.pl
challenge-240/spadacciniweb/perl/ch-2.pl

PWC-240 in Perl

---

challenge-240/augiedb/blog.txt
challenge-240/augiedb/perl/ch-1.pl
challenge-240/augiedb/perl/ch-2.pl

Challenge 240 Completed

---

challenge-240/barroff/julia/ch-1.jl
challenge-240/barroff/julia/ch-2.jl
challenge-240/barroff/nim/ch_1.nim
challenge-240/barroff/nim/ch_2.nim
challenge-240/barroff/perl/ch-1.pl
challenge-240/barroff/perl/ch-2.pl
challenge-240/barroff/raku/ch-1.p6
challenge-240/barroff/raku/ch-2.p6

Hello
This pull request adds my Julia, Nim, Perl and Raku solutions for challenge 240.

feat: add solutions for challenge 240 from BarrOff

---

challenge-240/matthias-muth/README.md
challenge-240/matthias-muth/blog.txt
challenge-240/matthias-muth/perl/TestExtractor.pm
challenge-240/matthias-muth/perl/ch-1.pl
challenge-240/matthias-muth/perl/ch-2.pl
challenge-240/matthias-muth/perl/challenge-240.txt

Challenge 240 solutions in Perl by Matthias Muth

---

challenge-241/wlmb/blog.txt
challenge-241/wlmb/perl/ch-1.pl
challenge-241/wlmb/perl/ch-2.pl

Solve PWC241

---

challenge-241/mattneleigh/perl/ch-1.pl
challenge-241/mattneleigh/perl/ch-2.pl

new file:   challenge-241/mattneleigh/perl/ch-2.pl

	new file:   challenge-241/mattneleigh/perl/ch-1.pl

---

challenge-241/lacek96/perl/ch-1.pl

solution for challenge #1

---

challenge-241/matthias-muth/README.md
challenge-241/matthias-muth/perl/TestExtractor.pm
challenge-241/matthias-muth/perl/ch-1.pl
challenge-241/matthias-muth/perl/ch-2.pl
challenge-241/matthias-muth/perl/challenge-241.txt

Challenge 241 Task 1 and 2 solutions in Perl by Matthias Muth

---

challenge-241/matthias-muth/blog.txt

Sorry, I forgot to add 'blog.txt'.
Thank you for still adding it.
:-)

Add blog.txt

---

challenge-242/packy-anderson/README.md
challenge-242/packy-anderson/blog.txt
challenge-242/packy-anderson/perl/ch-1.pl
challenge-242/packy-anderson/perl/ch-2.pl
challenge-242/packy-anderson/python/ch-1.py
challenge-242/packy-anderson/python/ch-2.py
challenge-242/packy-anderson/raku/ch-1.raku
challenge-242/packy-anderson/raku/ch-2.raku

* Raku
* Perl
* Python
1 Blog post

Challenge 242 solutions by Packy Anderson
