- challenge-242/wlmb/blog.txt
- challenge-242/wlmb/perl/ch-1.pl
- challenge-242/wlmb/perl/ch-2.pl
> Solve PWC242

- challenge-242/mattneleigh/perl/ch-1.pl
- challenge-242/mattneleigh/perl/ch-2.pl
new file:   challenge-242/mattneleigh/perl/ch-2.pl
> 	new file:   challenge-242/mattneleigh/perl/ch-1.pl

- challenge-242/e-choroba/perl/ch-1.pl
- challenge-242/e-choroba/perl/ch-2.pl
In Missing Numbers, I added the [] for no missing elements. The added test case shows why I think it's needed.
> Add solutions to 242: Missing Numbers & Flip Matrix by E. Choroba

- challenge-242/packy-anderson/README.md
> Challenge 242 - Packy Anderson

- challenge-242/memark/blog.txt
- challenge-242/memark/uiua/ch-1.ua
- challenge-242/memark/uiua/ch-2.ua
Wrote a blog post about my solutions this time!
> Add 242 solution and blog link

- challenge-242/augiedb/blog.txt
- challenge-242/augiedb/perl/ch-1.pl
Weekly Challenge #242, though only the first task.
> Challenge 242 submission for Challenge 1

- challenge-242/matthias-muth/README.md
- challenge-242/matthias-muth/blog.txt
- challenge-242/matthias-muth/perl/TestExtractor.pm
- challenge-242/matthias-muth/perl/ch-1.pl
- challenge-242/matthias-muth/perl/ch-2.pl
- challenge-242/matthias-muth/perl/challenge-242.txt
> Challenge 242 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-243/wlmb/blog.txt
- challenge-243/wlmb/perl/ch-1.pl
- challenge-243/wlmb/perl/ch-2.pl
> Solve PWC243

- challenge-243/mattneleigh/perl/ch-1.pl
- challenge-243/mattneleigh/perl/ch-2.pl
new file:   challenge-243/mattneleigh/perl/ch-2.pl
> new file:   challenge-243/mattneleigh/perl/ch-1.pl

- challenge-243/spadacciniweb/perl/ch-1.pl
- challenge-243/spadacciniweb/perl/ch-2.pl
> PWC-243 in Perl

- challenge-242/jaldhar-h-vyas/blog.txt
- challenge-242/jaldhar-h-vyas/perl/ch-1.pl
- challenge-242/jaldhar-h-vyas/perl/ch-2.pl
- challenge-242/jaldhar-h-vyas/raku/ch-1.raku
- challenge-242/jaldhar-h-vyas/raku/ch-2.raku
Sorry late because of Diwali and Gujarati New Year.  I hope God grants you and your loved ones peace, proseperity and happiness in the upcoming year.
> Challenge 242 by Jaldhar H. Vyas.

- challenge-243/robbie-hatley/blog.txt
- challenge-243/robbie-hatley/perl/ch-1.pl
- challenge-243/robbie-hatley/perl/ch-2.pl
Two tales of pairs of nested 3-part loops. :-)
> Robbie Hatley's Perl solutions for The Weekly Challenge #243.

- challenge-243/mattneleigh/perl/ch-2.pl
> 	modified:   challenge-243/mattneleigh/perl/ch-2.pl

- challenge-243/packy-anderson/README.md
- challenge-243/packy-anderson/blog.txt
- challenge-243/packy-anderson/perl/ch-1.pl
- challenge-243/packy-anderson/perl/ch-2.pl
- challenge-243/packy-anderson/python/ch-1.py
- challenge-243/packy-anderson/python/ch-2.py
- challenge-243/packy-anderson/raku/ch-1.raku
- challenge-243/packy-anderson/raku/ch-2.raku
* Raku
* Perl
* Python
1 Blog post
> Challenge 243 solutions by Packy Anderson

- challenge-243/barroff/julia/ch-1.jl
- challenge-243/barroff/raku/ch-1.p6
- challenge-243/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia and Raku solutions for challenge 243.
> feat: add solutions for challenge 243 from BarrOff

- challenge-243/matthias-muth/README.md
- challenge-243/matthias-muth/blog.txt
- challenge-243/matthias-muth/perl/TestExtractor.pm
- challenge-243/matthias-muth/perl/ch-1.pl
- challenge-243/matthias-muth/perl/ch-2.pl
- challenge-243/matthias-muth/perl/challenge-243.txt
> Challenge 243 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-244/wlmb/blog.txt
- challenge-244/wlmb/perl/ch-1.pl
- challenge-244/wlmb/perl/ch-2.pl
> Solve PWC244

- challenge-244/mattneleigh/perl/ch-1.pl
- challenge-244/mattneleigh/perl/ch-2.pl
new file:   challenge-244/mattneleigh/perl/ch-2.pl
> 	new file:   challenge-244/mattneleigh/perl/ch-1.pl

- challenge-244/mattneleigh/perl/ch-2.pl
> 	modified:   challenge-244/mattneleigh/perl/ch-2.pl

- challenge-244/nelo-tovar/bash/c.sh
- challenge-244/nelo-tovar/bash/ch-1.sh
- challenge-244/nelo-tovar/bash/ch-2.sh
- challenge-244/nelo-tovar/perl/ch-1.pl
- challenge-244/nelo-tovar/perl/ch-2.pl
> Challenge 244. Add Perl and Bash solutions. By Nelo Tovar.

- challenge-244/robbie-hatley/blog.txt
- challenge-244/robbie-hatley/perl/ch-1.pl
- challenge-244/robbie-hatley/perl/ch-2.pl
- challenge-244/robbie-hatley/perl/ch-2alt.pl
Including both fast and slow variants for task 2.
> Robbie Hatley's Perl solutions to The Weekly Challenge 244.

- challenge-245/wlmb/blog.txt
- challenge-245/wlmb/perl/ch-1.pl
- challenge-245/wlmb/perl/ch-2.pl
> Solve PWC245

- challenge-245/spadacciniweb/perl/ch-1.pl
> PWC-245: Perl ch-1

- challenge-245/pokgopun/go/ch-2.go
- challenge-245/pokgopun/python/ch-2.py
apply the property:"If a + b = c , then a ( mod N ) + b ( mod N ) ≡ c ( mod N )"
> pwc245_task2 - add comments and minor modification

- challenge-245/mattneleigh/perl/ch-1.pl
- challenge-245/mattneleigh/perl/ch-2.pl
new file:   challenge-245/mattneleigh/perl/ch-2.pl
> 	new file:   challenge-245/mattneleigh/perl/ch-1.pl

- challenge-245/nelo-tovar/bash/ch-1.sh
- challenge-245/nelo-tovar/perl/ch-1.pl
- challenge-245/nelo-tovar/perl/ch-2.pl
> Challenge 245. Add Perl and Bash (ch-1) solutions. By Nelo Tovar

- challenge-245/robbie-hatley/perl/ch-1.pl
"Popularities" can now be anything: integers, real numbers, strings, whatever.
> Updated 245-1.

- challenge-245/barroff/julia/ch-1.jl
- challenge-245/barroff/nim/ch_1.nim
- challenge-245/barroff/perl/ch-1.pl
- challenge-245/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia, Perl and Raku solutions for task one of challenge 245.
> feat: add solutions for challenge 245 from BarrOff

- challenge-246/nelo-tovar/bash/ch-1.sh
- challenge-246/nelo-tovar/bash/ch-2.sh
- challenge-246/nelo-tovar/perl/ch-1.pl
- challenge-246/nelo-tovar/perl/ch-2.pl
Adding Perl and Bash solutions
> Adding Perl and Bash solutions. By Nelo Tovar.

- challenge-246/barroff/julia/ch-1.jl
- challenge-246/barroff/nim/ch_1.nims
- challenge-246/barroff/perl/ch-1.pl
- challenge-246/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia, Nim, Perl and Raku solutions for task one of challenge 246.
> feat: add solutions for challenge 246 from BarrOff

- challenge-247/wlmb/blog.txt
- challenge-247/wlmb/perl/ch-1.pl
- challenge-247/wlmb/perl/ch-2.pl
> Solve PWC247

- challenge-247/packy-anderson/README.md
- challenge-247/packy-anderson/blog.txt
- challenge-247/packy-anderson/perl/ch-1.pl
- challenge-247/packy-anderson/perl/ch-2.pl
- challenge-247/packy-anderson/python/ch-1.py
- challenge-247/packy-anderson/python/ch-2.py
- challenge-247/packy-anderson/raku/ch-1.raku
- challenge-247/packy-anderson/raku/ch-2.raku
* Raku
* Perl
* Python
1 Blog post
> Challenge 247 solutions by Packy Anderson

- challenge-247/nelo-tovar/bash/ch-2.sh
- challenge-247/nelo-tovar/perl/ch-1.pl
- challenge-247/nelo-tovar/perl/ch-2.pl
Perl and Bash (ch-2) solutions. By Nelo Tovar
> Challenge 247, Adding Perl and Bash (ch-2) solutions. By Nelo Tovar

- challenge-247/mattneleigh/perl/ch-1.pl
- challenge-247/mattneleigh/perl/ch-2.pl
new file:   challenge-247/mattneleigh/perl/ch-2.pl
> 	new file:   challenge-247/mattneleigh/perl/ch-1.pl

- challenge-247/barroff/julia/ch-2.jl
- challenge-247/barroff/perl/ch-2.pl
- challenge-247/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia, Perl and Raku solutions for task two of challenge 247.
> feat: add solutions for challenge 247 from BarrOff

- challenge-248/wlmb/blog.txt
- challenge-248/wlmb/perl/ch-1.pl
- challenge-248/wlmb/perl/ch-2.pl
> Solve PWC248

- challenge-247/dave-jacoby/blog.txt
- challenge-247/dave-jacoby/perl/ch-1.pl
- challenge-247/dave-jacoby/perl/ch-2.pl
> solved 247

- challenge-248/mattneleigh/perl/ch-1.pl
- challenge-248/mattneleigh/perl/ch-2.pl
new file:   challenge-248/mattneleigh/perl/ch-2.pl
> 	new file:   challenge-248/mattneleigh/perl/ch-1.pl

- challenge-248/packy-anderson/README.md
- challenge-248/packy-anderson/blog.txt
- challenge-248/packy-anderson/perl/ch-1.pl
- challenge-248/packy-anderson/perl/ch-2.pl
- challenge-248/packy-anderson/python/ch-1.py
- challenge-248/packy-anderson/python/ch-2.py
- challenge-248/packy-anderson/raku/ch-1.raku
- challenge-248/packy-anderson/raku/ch-2.raku
* Raku
* Perl
* Python
1 Blog post
> Challenge 248 solutions by Packy Anderson

- challenge-248/nelo-tovar/bash/ch-1.sh
- challenge-248/nelo-tovar/perl/ch-1.pl
- challenge-248/nelo-tovar/perl/ch-2.pl
> Challenge 247, Perl and Bash (ch-1) solutions. By Nelo Tovar

- challenge-248/mattneleigh/perl/ch-1.pl
> 	modified:   challenge-248/mattneleigh/perl/ch-1.pl

- challenge-248/barroff/perl/ch-1.pl
- challenge-248/barroff/raku/ch-1.p6
Hello
This pull request adds my Perl and Raku solutions for task one of challenge 248.
> feat: add solutions for challenge 248 from BarrOff

- challenge-249/wlmb/blog.txt
- challenge-249/wlmb/perl/ch-1.pl
- challenge-249/wlmb/perl/ch-2.pl
> Solve PWC249

- challenge-249/packy-anderson/README.md
- challenge-249/packy-anderson/blog.txt
- challenge-249/packy-anderson/perl/ch-1.pl
- challenge-249/packy-anderson/perl/ch-2.pl
- challenge-249/packy-anderson/python/ch-1.py
- challenge-249/packy-anderson/python/ch-2.py
- challenge-249/packy-anderson/raku/ch-1.raku
- challenge-249/packy-anderson/raku/ch-2.raku
* Raku
* Perl
* Python
1 Blog post
> Challenge 249 solutions by Packy Anderson

- challenge-249/nelo-tovar/bash/ch-1.sh
- challenge-249/nelo-tovar/bash/ch-2.sh
- challenge-249/nelo-tovar/perl/ch-1.pl
- challenge-249/nelo-tovar/perl/ch-2.pl
Perl and Bash Solutions by Nelo Tovar
> Challenge 249. Add Perl and Bash solutions. By Nelo Tovar

- challenge-249/robbie-hatley/blog.txt
- challenge-249/robbie-hatley/perl/ch-1.pl
- challenge-249/robbie-hatley/perl/ch-2.pl
Interesting set of tasks. Turns out, Task 2 has multiple compliant permutations for most strings.
> Robbie Hatley's solutions in Perl for The Weekly Challenge #249.

- challenge-249/sgreen/README.md
- challenge-249/sgreen/perl/ch-1.pl
- challenge-249/sgreen/perl/ch-2.pl
- challenge-249/sgreen/python/ch-1.py
- challenge-249/sgreen/python/ch-2.py
No blog this week. Got struck down with the 'rona :(
> Simon's solution to challenge 249

- challenge-249/mattneleigh/perl/ch-1.pl
- challenge-249/mattneleigh/perl/ch-2.pl
new file:   challenge-249/mattneleigh/perl/ch-2.pl
> 	new file:   challenge-249/mattneleigh/perl/ch-1.pl

- challenge-249/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 249.
> feat: add solution for challenge 249 from BarrOff

- challenge-250/wlmb/blog.txt
- challenge-250/wlmb/perl/ch-1.pl
- challenge-250/wlmb/perl/ch-2.pl
> Solve PWC250

- challenge-250/packy-anderson/README.md
- challenge-250/packy-anderson/blog.txt
- challenge-250/packy-anderson/perl/ch-1.pl
- challenge-250/packy-anderson/perl/ch-2.pl
- challenge-250/packy-anderson/python/ch-1.py
- challenge-250/packy-anderson/python/ch-2.py
- challenge-250/packy-anderson/raku/ch-1.raku
- challenge-250/packy-anderson/raku/ch-2.raku
* Raku
* Perl
* Python
1 Blog post
> Challenge 250 solutions by Packy Anderson

- challenge-250/simon-proctor/raku/ch-1.raku
- challenge-250/simon-proctor/raku/ch-2.raku
Always fun when there's more lines of tests than lines of code.
> New year, back on the challenges

- challenge-250/mattneleigh/perl/ch-1.pl
- challenge-250/mattneleigh/perl/ch-2.pl
new file:   challenge-250/mattneleigh/perl/ch-2.pl
> 	new file:   challenge-250/mattneleigh/perl/ch-1.pl

- challenge-250/nelo-tovar/bash/ch-1.sh
- challenge-250/nelo-tovar/bash/ch-2.sh
- challenge-250/nelo-tovar/perl/ch-1.pl
- challenge-250/nelo-tovar/perl/ch-2.pl
Perl and Bash Solutions by Nelo Tovar
> Adding Perl and Bash solutions. By Nelo Tovar

- challenge-250/barroff/d/ch_1.d
- challenge-250/barroff/d/ch_2.d
- challenge-250/barroff/julia/ch-1.jl
- challenge-250/barroff/julia/ch-2.jl
- challenge-250/barroff/nim/ch_1.nim
- challenge-250/barroff/nim/ch_2.nim
- challenge-250/barroff/perl/ch-1.pl
- challenge-250/barroff/perl/ch-2.pl
- challenge-250/barroff/raku/ch-1.p6
- challenge-250/barroff/raku/ch-2.p6
- challenge-250/barroff/v/ch-1.v
Hello
This pull request adds my D, Julia, Nim, Perl, Raku and V solutions for challenge 250.
> feat: add solutions for challenge 250 from BarrOff

- challenge-250/witawayar/README
- challenge-250/witawayar/cpp/ch-1.cpp
- challenge-250/witawayar/cpp/ch-2.cpp
- challenge-250/witawayar/raku/ch-1.raku
- challenge-250/witawayar/raku/ch-2.raku
hi, thanks for having been doing this and hope the recent thunderstorm's effects are long gone
> Solutions for the 250th challenge

- challenge-251/wlmb/blog.txt
- challenge-251/wlmb/perl/ch-1.pl
- challenge-251/wlmb/perl/ch-2.pl
> SOlve PWC251

- challenge-251/e-choroba/perl/ch-1.pl
- challenge-251/e-choroba/perl/ch-2.pl
Including a nice latex proof :-)
> Solve 251: Concatenation Value & Lucky Numbers by E. Choroba

- challenge-251/nelo-tovar/bash/ch-1.sh
- challenge-251/nelo-tovar/perl/ch-1.pl
- challenge-251/nelo-tovar/perl/ch-2.pl
> Challenge 251, Perl and Bash (ch-1) solutions. By Nelo Tovar

- challenge-251/barroff/perl/ch-1.pl
- challenge-251/barroff/raku/ch-1.p6
Hello
This pull request adds my Perl and Raku solutions for task one of challenge 251.
> feat: add solutions for challenge 251 from BarrOff

- challenge-251/witawayar/cpp/ch-1.cpp
- challenge-251/witawayar/cpp/ch-2.cpp
- challenge-251/witawayar/raku/ch-1.raku
- challenge-251/witawayar/raku/ch-2.raku
> Solutions for the 251st challenge

- challenge-252/mattneleigh/perl/ch-1.pl
- challenge-252/mattneleigh/perl/ch-2.pl
new file:   challenge-252/mattneleigh/perl/ch-2.pl
> new file:   challenge-252/mattneleigh/perl/ch-1.pl

- challenge-252/packy-anderson/README.md
- challenge-252/packy-anderson/blog.txt
- challenge-252/packy-anderson/perl/ch-1.pl
- challenge-252/packy-anderson/perl/ch-2.pl
- challenge-252/packy-anderson/python/ch-1.py
- challenge-252/packy-anderson/python/ch-2.py
- challenge-252/packy-anderson/raku/ch-1.raku
- challenge-252/packy-anderson/raku/ch-2.raku
* Raku
* Perl
* Python
1 Blog post
> Challenge 252 solutions by Packy Anderson

- challenge-252/nelo-tovar/bash/ch-1.sh
- challenge-252/nelo-tovar/bash/ch-2.sh
- challenge-252/nelo-tovar/perl/ch-1.pl
- challenge-252/nelo-tovar/perl/ch-2.pl
> Challenge 252. Add Perl and Bash solutions. By Nelo Tovar

- challenge-252/joaofel/uiua/ch-1.ua
- challenge-252/joaofel/uiua/ch-2.ua
I decided to shake things up and use [Uiua](https://www.uiua.org) (note: Uiua is still in development!)
> Add my solutions

- challenge-252/witawayar/cpp/ch-1.cpp
- challenge-252/witawayar/cpp/ch-2.cpp
- challenge-252/witawayar/raku/ch-1.raku
- challenge-252/witawayar/raku/ch-2.raku
> Solutions for the 252nd challenge

- challenge-252/barroff/julia/ch-1.jl
- challenge-252/barroff/julia/ch-2.jl
- challenge-252/barroff/nim/ch_1.nim
- challenge-252/barroff/nim/ch_2.nim
- challenge-252/barroff/perl/ch-1.pl
- challenge-252/barroff/perl/ch-2.pl
- challenge-252/barroff/raku/ch-1.p6
- challenge-252/barroff/raku/ch-2.p6
- challenge-252/barroff/v/ch-2.v
- challenge-252/barroff/v/ch-2_test.v
Hello
This pull request adds my Julia, Nim, Perl, Raku and V solutions for challenge 252.
> feat: add solutions for challenge 252 from BarrOff

- challenge-253/wlmb/blog.txt
- challenge-253/wlmb/perl/ch-1.pl
- challenge-253/wlmb/perl/ch-2.pl
> Solve PWC253

- challenge-253/packy-anderson/README.md
- challenge-253/packy-anderson/blog.txt
- challenge-253/packy-anderson/perl/ch-1.pl
- challenge-253/packy-anderson/perl/ch-2.pl
- challenge-253/packy-anderson/python/ch-1.py
- challenge-253/packy-anderson/python/ch-2.py
- challenge-253/packy-anderson/raku/ch-1.raku
- challenge-253/packy-anderson/raku/ch-2.raku
* Raku
* Perl
* Python
1 Blog post
> Challenge 253 solutions by Packy Anderson

- challenge-253/spadacciniweb/perl/ch-1.pl
- challenge-253/spadacciniweb/perl/ch-2.pl
> PWC 253 in Perl

- challenge-253/mattneleigh/perl/ch-1.pl
- challenge-253/mattneleigh/perl/ch-2.pl
new file:   challenge-253/mattneleigh/perl/ch-2.pl
> new file:   challenge-253/mattneleigh/perl/ch-1.pl

- challenge-253/mattneleigh/perl/ch-2.pl
> modified:   challenge-253/mattneleigh/perl/ch-2.pl

- challenge-253/nelo-tovar/bash/ch-1.sh
- challenge-253/nelo-tovar/perl/ch-1.pl
- challenge-253/nelo-tovar/perl/ch-2.pl
> Challenge 253. Add Perl and Bash (ch-1) solutions. By Nelo Tovar

- challenge-253/probablyfine/README.md
- challenge-253/probablyfine/uiua/ch-1.ua
- challenge-253/probablyfine/uiua/ch-2.ua
First time contributor, adding my solutions for 253 using [uiua](https://www.uiua.org/).
> Solutions for 253 in uiua

- challenge-253/witawayar/cpp/ch-1.cpp
- challenge-253/witawayar/cpp/ch-2.cpp
- challenge-253/witawayar/raku/ch-1.raku
- challenge-253/witawayar/raku/ch-2.raku
> Solutions for the 253rd challenge

- challenge-253/barroff/julia/ch-1.jl
- challenge-253/barroff/nim/ch_1.nim
- challenge-253/barroff/perl/ch-1.pl
- challenge-253/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia, Nim, Perl and Raku solutions for task one of challenge 253.
> feat: add solutions for challenge 253 from BarrOff

- challenge-254/wlmb/blog.txt
- challenge-254/wlmb/perl/ch-1.pl
- challenge-254/wlmb/perl/ch-2.pl
> Solve PWC254

- challenge-254/dave-jacoby/blog.txt
- challenge-254/dave-jacoby/perl/ch-1.pl
- challenge-254/dave-jacoby/perl/ch-2.pl
Remembered to make a PR this time!
> Blogged 254

- challenge-254/probablyfine/blog.txt
- challenge-254/probablyfine/uiua/ch-1.ua
- challenge-254/probablyfine/uiua/ch-2.ua
My two solutions for this week's challenge, plus a blog post.
> Solutions for 254 in uiua

- challenge-254/mattneleigh/perl/ch-1.pl
- challenge-254/mattneleigh/perl/ch-2.pl
new file:   challenge-254/mattneleigh/perl/ch-2.pl
> new file:   challenge-254/mattneleigh/perl/ch-1.pl

- challenge-254/packy-anderson/README.md
- challenge-254/packy-anderson/blog.txt
- challenge-254/packy-anderson/perl/ch-1.pl
- challenge-254/packy-anderson/perl/ch-2.pl
- challenge-254/packy-anderson/python/ch-1.py
- challenge-254/packy-anderson/python/ch-2.py
- challenge-254/packy-anderson/raku/ch-1.raku
- challenge-254/packy-anderson/raku/ch-2.raku
* Raku
* Perl
* Python
1 Blog post
> Challenge 254 solutions by Packy Anderson

- challenge-254/witawayar/cpp/ch-1.cpp
- challenge-254/witawayar/cpp/ch-2.cpp
- challenge-254/witawayar/raku/ch-1.raku
- challenge-254/witawayar/raku/ch-2.raku
> Solutions for the 254th challenge

- challenge-255/mattneleigh/perl/ch-1.pl
- challenge-255/mattneleigh/perl/ch-2.pl
new file:   challenge-255/mattneleigh/perl/ch-2.pl
> new file:   challenge-255/mattneleigh/perl/ch-1.pl

- challenge-255/wlmb/blog.txt
- challenge-255/wlmb/perl/ch-1.pl
- challenge-255/wlmb/perl/ch-2.pl
> Solve PWC255

- challenge-254/barroff/d/ch_1.d
- challenge-254/barroff/julia/ch-1.jl
- challenge-254/barroff/nim/ch_1.nim
- challenge-254/barroff/perl/ch-1.pl
- challenge-254/barroff/raku/ch-1.p6
- challenge-254/barroff/raku/ch-2.p6
- challenge-254/barroff/v/ch-1.v
- challenge-254/barroff/v/ch-1_test.v
Hello
I totally missed that the deadline was yesterday.
This pull request adds my D, Julia, Nim, Perl, Raku and V solutions for challenge 254.
> feat: add solutions for challenge 254 from BarrOff

- challenge-253/spadacciniweb/perl/ch-2.pl
- challenge-255/spadacciniweb/perl/ch-1.pl
- challenge-255/spadacciniweb/perl/ch-2.pl
> Add PWC 255 and fix PWC 253 (ch-2.pl)

- challenge-255/spadacciniweb/python/ch-1.py
- challenge-255/spadacciniweb/python/ch-2.py
> Add PWC-255 in Python

- challenge-255/probablyfine/uiua/ch-1.ua
- challenge-255/probablyfine/uiua/ch-2.ua
My solutions for this week's challenge
> Solutions for 255 in uiua

- challenge-255/packy-anderson/README.md
- challenge-255/packy-anderson/blog.txt
- challenge-255/packy-anderson/perl/ch-1.pl
- challenge-255/packy-anderson/perl/ch-2.pl
- challenge-255/packy-anderson/python/ch-1.py
- challenge-255/packy-anderson/python/ch-2.py
- challenge-255/packy-anderson/raku/ch-1.raku
- challenge-255/packy-anderson/raku/ch-2.raku
* Raku
* Perl
* Python
1 Blog post
> Challenge 255 solutions by Packy Anderson

- challenge-254/0rir/raku/ch-1.raku
- challenge-255/0rir/raku/ch-1.raku
- challenge-255/0rir/raku/ch-2.raku
> 255  & 254 refactoring

- challenge-255/barroff/julia/ch-1.jl
- challenge-255/barroff/nim/ch_1.nim
- challenge-255/barroff/perl/ch-1.pl
- challenge-255/barroff/raku/ch-1.p6
- challenge-255/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia, Nim, Perl and Raku solutions for challenge 255.
> feat: add solutions for challenge 255 from BarrOff

- challenge-256/wlmb/blog.txt
- challenge-256/wlmb/perl/ch-1.pl
- challenge-256/wlmb/perl/ch-2.pl
> Solve PWC256

- challenge-256/mattneleigh/perl/ch-2.pl
Changed variable name to be more correctly descriptive; minor documentation tweak to match
> modified:   challenge-256/mattneleigh/perl/ch-2.pl

- challenge-256/matthias-muth/README.md
- challenge-256/matthias-muth/blog.txt
- challenge-256/matthias-muth/perl/ch-1.pl
- challenge-256/matthias-muth/perl/ch-2.pl
- challenge-256/matthias-muth/perl/challenge-256.txt
Thank you for all the challenges!
Good to be back!
> Challenge 256 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-250/zapwai/python/ch-1.py
- challenge-250/zapwai/python/ch-2.py
- challenge-251/zapwai/python/ch-1.py
- challenge-251/zapwai/python/ch-2.py
- challenge-252/zapwai/python/ch-1.py
- challenge-252/zapwai/python/ch-2.py
- challenge-253/zapwai/python/ch-1.py
- challenge-253/zapwai/python/ch-2.py
- challenge-254/zapwai/python/ch-1.py
- challenge-254/zapwai/python/ch-2.py
Sometimes I also do challenges from the first 190 weeks, i.e. before I had joined.
Should I upload those very old ones, some time?
> Recent Python scripts

- challenge-256/packy-anderson/README.md
- challenge-256/packy-anderson/blog.txt
- challenge-256/packy-anderson/perl/ch-1.pl
- challenge-256/packy-anderson/perl/ch-2.pl
- challenge-256/packy-anderson/python/ch-1.py
- challenge-256/packy-anderson/python/ch-2.py
- challenge-256/packy-anderson/raku/ch-1.raku
- challenge-256/packy-anderson/raku/ch-2.raku
* Raku
* Perl
* Python
1 Blog post
> Challenge 256 solutions by Packy Anderson

- challenge-256/nelo-tovar/bash/ch-1.sh
- challenge-256/nelo-tovar/bash/ch-2.sh
- challenge-256/nelo-tovar/perl/ch-1.pl
- challenge-256/nelo-tovar/perl/ch-2.pl
> Challenge 256. Add Perl and Bash solutions. By Nelo Tovar.

- challenge-256/barroff/julia/ch-1.jl
- challenge-256/barroff/nim/ch_1.nim
- challenge-256/barroff/perl/ch-1.pl
- challenge-256/barroff/raku/ch-1.p6
- challenge-256/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia, Nim, Perl and Raku solutions for challenge 256.
> feat: add solutions for challenge 256 from BarrOff

- challenge-162/jaldhar-h-vyas/blog.txt
- challenge-162/jaldhar-h-vyas/perl/ch-2.pl
- challenge-162/jaldhar-h-vyas/raku/ch-2.raku
I almost forgot.  This is an old one I only did partially.  I've done the second part and updated the blog entry.
> Challenge 162 part 2 by Jaldhar H. Vyas

- challenge-257/spadacciniweb/go/ch-1.go
- challenge-257/spadacciniweb/perl/ch-1.pl
> Add PWC-257 in Perl ch-1

- challenge-005/archargelod/README
- challenge-005/archargelod/nim/ch_1.nim
- challenge-005/archargelod/nim/ch_2.nim
- challenge-006/archargelod/README
- challenge-006/archargelod/nim/ch_1.nim
- challenge-006/archargelod/nim/ch_2.nim
- challenge-007/archargelod/README
- challenge-007/archargelod/nim/ch_1.nim
- challenge-007/archargelod/nim/ch_2.nim
- challenge-008/archargelod/README
- challenge-008/archargelod/nim/ch_1.nim
- challenge-008/archargelod/nim/ch_2.nim
- challenge-009/archargelod/README
- challenge-009/archargelod/nim/ch_1.nim
- challenge-009/archargelod/nim/ch_2.nim
- challenge-010/archargelod/README
- challenge-010/archargelod/nim/ch_1.nim
- challenge-010/archargelod/nim/ch_2.nim
- challenge-011/archargelod/README
- challenge-011/archargelod/nim/ch_1.nim
- challenge-011/archargelod/nim/ch_2.nim
- challenge-012/archargelod/README
- challenge-012/archargelod/nim/ch_1.nim
- challenge-012/archargelod/nim/ch_2.nim
- challenge-013/archargelod/README
- challenge-013/archargelod/nim/ch_1.nim
- challenge-013/archargelod/nim/ch_2.nim
- challenge-257/archargelod/nim/ch_1.nim
- challenge-257/archargelod/nim/ch_2.nim
Thank you for creating this project. I really enjoy doing these challenges. ❤
> Weeks 5-13, 257 in Nim

- challenge-257/mattneleigh/perl/ch-1.pl
- challenge-257/mattneleigh/perl/ch-2.pl
new file:   challenge-257/mattneleigh/perl/ch-2.pl
> new file:   challenge-257/mattneleigh/perl/ch-1.pl

- challenge-257/barroff/bqn/ch-1.bqn
- challenge-257/barroff/julia/ch-1.jl
- challenge-257/barroff/nim/ch_1.nim
- challenge-257/barroff/perl/ch-1.pl
- challenge-257/barroff/raku/ch-1.p6
Hello
This pull request adds my BQN, Julia, Nim, Perl and Raku solutions for task one of challenge 257.
> feat: add solutions for challenge 257 from BarrOff

- challenge-258/wlmb/blog.txt
- challenge-258/wlmb/perl/ch-1.pl
- challenge-258/wlmb/perl/ch-2.pl
(found a mistake in the problem statement: $ints[3]->$ints[4] in example 1 of task 1)
Regards
> Solve PWC258

- challenge-258/ryan-thompson/README.md
- challenge-258/ryan-thompson/perl/ch-1.pl
- challenge-258/ryan-thompson/perl/ch-2.pl
- challenge-258/ryan-thompson/raku/ch-1.raku
- challenge-258/ryan-thompson/raku/ch-2.raku
> rjt week 258

- challenge-258/mattneleigh/perl/ch-1.pl
- challenge-258/mattneleigh/perl/ch-2.pl
new file:   challenge-258/mattneleigh/perl/ch-2.pl
> new file:   challenge-258/mattneleigh/perl/ch-1.pl

- challenge-258/robbie-hatley/perl/ch-1.pl
- challenge-258/robbie-hatley/perl/ch-2.pl
I'm going "super-terse" this week; my "ch-1.pl" is a 2-liner and my "ch-2.pl" is a 4-liner. :-)
> Robbie Hatley's SHORT solutions in Perl for The Weekly Challenge 258.

- challenge-258/packy-anderson/README.md
- challenge-258/packy-anderson/blog.txt
- challenge-258/packy-anderson/perl/ch-1.pl
- challenge-258/packy-anderson/perl/ch-2.pl
- challenge-258/packy-anderson/python/ch-1.py
- challenge-258/packy-anderson/python/ch-2.py
- challenge-258/packy-anderson/raku/ch-1.raku
- challenge-258/packy-anderson/raku/ch-2.raku
* Raku
* Perl
* Python
1 Blog post
> Challenge 258 solutions by Packy Anderson

- challenge-258/nelo-tovar/bash/ch-1.sh
- challenge-258/nelo-tovar/bash/ch-2.sh
- challenge-258/nelo-tovar/perl/ch-1.pl
- challenge-258/nelo-tovar/perl/ch-2.pl
> Challenge 258. Add Perl and Bash solutions. By Nelo Tovar.

- challenge-258/barroff/blog.txt
- challenge-258/barroff/bqn/ch-1.bqn
- challenge-258/barroff/bqn/ch-2.bqn
- challenge-258/barroff/julia/ch-1.jl
- challenge-258/barroff/julia/ch_2.jl
- challenge-258/barroff/raku/ch-1.p6
- challenge-258/barroff/raku/ch-2.p6
Hello
This pull request adds my BQN, Julia and Raku solutions and blog post for challenge 258.
> feat: add solutions and blog for challenge 258 from BarrOff

- challenge-258/matthias-muth/README.md
- challenge-258/matthias-muth/blog.txt
- challenge-258/matthias-muth/perl/ch-1.pl
- challenge-258/matthias-muth/perl/ch-2.pl
- challenge-258/matthias-muth/perl/challenge-258.txt
> Challenge 258 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-258/ryan-thompson/blog.txt
Whoops! I was wondering why my blog didn't show up in your announcement this week!
> Forgot to commit blog.txt!

- challenge-259/wlmb/blog.txt
- challenge-259/wlmb/perl/ch-1.pl
- challenge-259/wlmb/perl/ch-2.pl
> Solve PWC259

- challenge-259/packy-anderson/README.md
- challenge-259/packy-anderson/blog.txt
- challenge-259/packy-anderson/data/parser-1.txt
- challenge-259/packy-anderson/data/parser-2.txt
- challenge-259/packy-anderson/data/parser-3.txt
- challenge-259/packy-anderson/data/parser-4.txt
- challenge-259/packy-anderson/data/parser-5.txt
- challenge-259/packy-anderson/perl/ch-1.pl
- challenge-259/packy-anderson/python/ch-1.py
- challenge-259/packy-anderson/raku/ch-1.raku
- challenge-259/packy-anderson/raku/ch-2.raku
* Raku - Task 1 & 2
* Perl - Task 1
* Python - Task 1
1 Blog post
> Challenge 259 solutions by Packy Anderson

- challenge-259/ryan-thompson/README.md
- challenge-259/ryan-thompson/blog.txt
- challenge-259/ryan-thompson/perl/ch-1.pl
- challenge-259/ryan-thompson/perl/ch-2.pl
> rjt's week 259 solutions

- challenge-259/nelo-tovar/bash/ch-1.sh
- challenge-259/nelo-tovar/bash/ch-2.pl
- challenge-259/nelo-tovar/bash/ch-2.sh
- challenge-259/nelo-tovar/perl/ch-1.pl
- challenge-259/nelo-tovar/perl/ch-2.pl
> Challenge 259. Add Perl and Bash solutions. By Nelo Tovar.

- challenge-259/barroff/julia/ch-1.jl
- challenge-259/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solutions for task one of challenge 259.
> feat: add solutions for challenge 259 from BarrOff

- challenge-260/wlmb/blog.txt
- challenge-260/wlmb/perl/ch-1.pl
- challenge-260/wlmb/perl/ch-2.pl
> Solve PWC260

- challenge-260/zapwai/c/ch-1.c
- challenge-260/zapwai/c/ch-2.c
- challenge-260/zapwai/javascript/ch-1.js
- challenge-260/zapwai/javascript/ch-2.js
- challenge-260/zapwai/perl/ch-1.pl
- challenge-260/zapwai/perl/ch-2.pl
- challenge-260/zapwai/python/ch-1.py
- challenge-260/zapwai/python/ch-2.py
- challenge-260/zapwai/rust/ch-1.rs
- challenge-260/zapwai/rust/ch-2.rs
Congratulations @manwar on five years of challenges!
> 5 Years of PWC!

- challenge-260/mattneleigh/perl/ch-1.pl
- challenge-260/mattneleigh/perl/ch-2.pl
new file:   challenge-260/mattneleigh/perl/ch-2.pl
> 	new file:   challenge-260/mattneleigh/perl/ch-1.pl

- challenge-260/lubos-kolouch/perl/ch-1.pl
- challenge-260/lubos-kolouch/perl/ch-2.pl
- challenge-260/lubos-kolouch/python/ch-1.py
- challenge-260/lubos-kolouch/python/ch-2.py
- challenge-260/lubos-kolouch/raku/ch-1.raku
- challenge-260/lubos-kolouch/raku/ch-2.raku
> feat(challenge-260/lubos-kolouch/perl,python/): Code and style cleanups for challenge 260

- challenge-260/mark-anderson/raku/ch-2.raku
Jörg Sommrey pointed out a precision issue with example 5. Thanks! 😊
> Jörg Sommrey pointed out a precision issue with example 5

- challenge-260/barroff/blog.txt
- challenge-260/barroff/bqn/ch-1.bqn
- challenge-260/barroff/julia/ch-1.jl
- challenge-260/barroff/raku/ch-1.p6
- challenge-260/barroff/raku/ch-2.p6
Hello
This pull request adds my BQN, Julia and Raku solutions and blog post for challenge 260.
> feat: add solutions and blog for challenge 260 from BarrOff

- challenge-260/matthias-muth/blog.txt
- challenge-260/matthias-muth/perl/README.md
- challenge-260/matthias-muth/perl/ch-1.pl
- challenge-260/matthias-muth/perl/ch-2.pl
- challenge-260/matthias-muth/perl/challenge-260.txt
> Challenge 260 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-261/robbie-hatley/blog.txt
- challenge-261/robbie-hatley/perl/ch-1.pl
- challenge-261/robbie-hatley/perl/ch-2.pl
Watch out for $start = 0 in task 2, that's a real cliff hanger!
> Robbie Hatley's solutions in Perl for The Weekly Challenge #261

- challenge-261/spadacciniweb/elixir/ch-1.exs
- challenge-261/spadacciniweb/elixir/ch-2.exs
- challenge-261/spadacciniweb/go/ch-1.go
- challenge-261/spadacciniweb/go/ch-2.go
- challenge-261/spadacciniweb/perl/ch-1.pl
- challenge-261/spadacciniweb/perl/ch-2.pl
- challenge-261/spadacciniweb/python/ch-1.py
- challenge-261/spadacciniweb/python/ch-2.py
- challenge-261/spadacciniweb/ruby/ch-1.rb
- challenge-261/spadacciniweb/ruby/ch-2.rb
> Add ch-1 and ch-2 in Perl, Elixir, Go, Python, Ruby

- challenge-261/packy-anderson/README.md
- challenge-261/packy-anderson/blog.txt
- challenge-261/packy-anderson/perl/ch-1.pl
- challenge-261/packy-anderson/perl/ch-2.pl
- challenge-261/packy-anderson/python/ch-1.py
- challenge-261/packy-anderson/python/ch-2.py
- challenge-261/packy-anderson/raku/ch-1.raku
- challenge-261/packy-anderson/raku/ch-2.raku
* Raku that looks like Perl
* Perl
* Python that looks like Perl
1 Blog post
> Challenge 261 solutions by Packy Anderson

- challenge-261/nelo-tovar/bash/ch-1.sh
- challenge-261/nelo-tovar/bash/ch-2.sh
- challenge-261/nelo-tovar/perl/ch-1.pl
- challenge-261/nelo-tovar/perl/ch-2.pl
> Challenge 261. Add Perl and Bash solutions. By Nelo Tovar

- challenge-261/mattneleigh/perl/ch-1.pl
- challenge-261/mattneleigh/perl/ch-2.pl
new file:   challenge-261/mattneleigh/perl/ch-2.pl
> new file:   challenge-261/mattneleigh/perl/ch-1.pl

- challenge-261/lance-wicks/perl/lib/EDS.pm
- challenge-261/lance-wicks/perl/t/01-eds.t
Was thinking about you @manwar and how awesome all the effort you put into Perl is. How positive you are for all those who are lucky enough to have contact with you!
So coded up a little solution for this weeks challenge as a little sign of my appreciation!
Kia Kaha my friend!
> Perl solution, happy Ramadan Mohammad

- challenge-261/lance-wicks/roc/main.roc
I've been playing with Roc-lang (because it's a relative of Elm which I like).
So took a stab at this weeks challenge in Roc, which with some help from the Roc community chat I managed to solve it.
> Adding a roc-lang version for week 261

- challenge-261/lubos-kolouch/perl/ch-1.pl
- challenge-261/lubos-kolouch/perl/ch-2.pl
- challenge-261/lubos-kolouch/python/ch-1.py
- challenge-261/lubos-kolouch/python/ch-2.py
> Challenge 261 LK Perl Python

- challenge-261/barroff/bqn/ch-1.bqn
- challenge-261/barroff/bqn/ch-2.bqn
- challenge-261/barroff/julia/ch-1.jl
- challenge-261/barroff/julia/ch-2.jl
- challenge-261/barroff/raku/ch-1.p6
- challenge-261/barroff/raku/ch-2.p6
Hello
This pull request adds my BQN, Julia and Raku solutions for challenge 261.
> feat: add solutions for challenge 261 from BarrOff

- challenge-261/matthias-muth/blog.txt
- challenge-261/matthias-muth/perl/README.md
- challenge-261/matthias-muth/perl/ch-1.pl
- challenge-261/matthias-muth/perl/ch-2.pl
- challenge-261/matthias-muth/perl/challenge-261.txt
> Challenge 261 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-262/wlmb/blog.txt
- challenge-262/wlmb/perl/ch-1.pl
- challenge-262/wlmb/perl/ch-2.pl
> Solve PWC262

- challenge-262/mattneleigh/perl/ch-1.pl
- challenge-262/mattneleigh/perl/ch-2.pl
new file:   challenge-262/mattneleigh/perl/ch-2.pl
> new file:   challenge-262/mattneleigh/perl/ch-1.pl

- challenge-262/packy-anderson/README.md
- challenge-262/packy-anderson/blog.txt
- challenge-262/packy-anderson/perl/ch-1.pl
- challenge-262/packy-anderson/perl/ch-2.pl
- challenge-262/packy-anderson/python/ch-1.py
- challenge-262/packy-anderson/python/ch-2.py
- challenge-262/packy-anderson/raku/ch-1.raku
- challenge-262/packy-anderson/raku/ch-2.raku
* Raku that looks like Perl
* Perl
* Python that looks like Perl
1 Blog post
> Challenge 262 solutions by Packy Anderson

- challenge-262/nelo-tovar/bash/ch-1.sh
- challenge-262/nelo-tovar/bash/ch-2.sh
- challenge-262/nelo-tovar/perl/ch-1.pl
- challenge-262/nelo-tovar/perl/ch-2.pl
> Challenge 262. Add Perl and Bash solutions. By Nelo Tovar.

- challenge-262/lance-wicks/perl/lib/MPN.pm
- challenge-262/lance-wicks/perl/t/mpn.t
- challenge-262/lance-wicks/roc/main.roc
Perl and Roc.
Doing both is really educational.
This week the Roc solution I think is simpler/easier. Last week it was Perl.
> Branch for challenge 262

- challenge-262/lubos-kolouch/perl/ch-1.pl
- challenge-262/lubos-kolouch/perl/ch-2.pl
- challenge-262/lubos-kolouch/python/ch-1.py
- challenge-262/lubos-kolouch/python/ch-2.py
> Challenge 262 LK Perl Python

- challenge-262/barroff/bqn/ch-1.bqn
- challenge-262/barroff/julia/ch-1.jl
- challenge-262/barroff/nim/ch_1.nim
- challenge-262/barroff/perl/ch-1.pl
- challenge-262/barroff/raku/ch-1.p6
- challenge-262/barroff/raku/ch-2.p6
Hello
This pull request adds my BQN, Julia, Nim, Perl and Raku solutions for challenge 262.
> feat: add solutions for challenge 262 from BarrOff

- challenge-263/wlmb/blog.txt
- challenge-263/wlmb/perl/ch-1.pl
- challenge-263/wlmb/perl/ch-2.pl
> Solve PWC263

- challenge-263/mattneleigh/perl/ch-1.pl
- challenge-263/mattneleigh/perl/ch-2.pl
new file:   challenge-263/mattneleigh/perl/ch-2.pl
> new file:   challenge-263/mattneleigh/perl/ch-1.pl

- challenge-263/nelo-tovar/bash/ch-1.sh
- challenge-263/nelo-tovar/perl/ch-1.pl
- challenge-263/nelo-tovar/perl/ch-2.pl
> Challenge 263, Perl and Bash (ch-1) solutions. By Nelo Tovar

- challenge-263/lubos-kolouch/perl/ch-1.pl
- challenge-263/lubos-kolouch/perl/ch-2.pl
- challenge-263/lubos-kolouch/python/ch-1.py
- challenge-263/lubos-kolouch/python/ch-2.py
> Challenge 263 LK Perl Python

- challenge-263/spadacciniweb/go/ch-1.go
- challenge-263/spadacciniweb/perl/ch-1.pl
- challenge-263/spadacciniweb/python/ch-1.py
- challenge-263/spadacciniweb/ruby/ch-1.rb
> Add ch-1 in Perl, Python, Ruby and Go

- challenge-263/matthias-muth/blog.txt
- challenge-263/matthias-muth/perl/README.md
- challenge-263/matthias-muth/perl/ch-1.pl
- challenge-263/matthias-muth/perl/ch-2.pl
- challenge-263/matthias-muth/perl/challenge-263.txt
> Challenge 263 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-263/barroff/bqn/ch-1.bqn
- challenge-263/barroff/julia/ch-1.jl
- challenge-263/barroff/perl/ch-1.pl
- challenge-263/barroff/raku/ch-1.p6
- challenge-263/barroff/raku/ch-2.p6
Hello
This pull request adds my BQN, Julia, Perl and Raku solutions for challenge 263.
> feat: add solutions for challenge 263 from BarrOff

- challenge-264/lubos-kolouch/perl/ch-1.pl
- challenge-264/lubos-kolouch/perl/ch-2.pl
- challenge-264/lubos-kolouch/python/ch-1.py
- challenge-264/lubos-kolouch/python/ch-2.py
> Challenge 264 LK Perl Python

- challenge-264/packy-anderson/README.md
- challenge-264/packy-anderson/blog.txt
- challenge-264/packy-anderson/perl/ch-1.pl
- challenge-264/packy-anderson/perl/ch-2.pl
- challenge-264/packy-anderson/python/ch-1.py
- challenge-264/packy-anderson/python/ch-2.py
- challenge-264/packy-anderson/raku/ch-1.raku
- challenge-264/packy-anderson/raku/ch-2.raku
* Raku that looks like Perl
* Perl
* Python that looks like Perl
1 Blog post
> Challenge 264 solutions by Packy Anderson

- challenge-264/pokgopun/go/ch-1.go
- challenge-264/pokgopun/python/ch-1.py
fix missing out a constraint on ch-1 and add additional test to confirm the fix.
> Pwc264 - Fix Ch-1

- challenge-264/nelo-tovar/bash/ch-1.sh
- challenge-264/nelo-tovar/bash/ch-2.sh
- challenge-264/nelo-tovar/perl/ch-1.pl
- challenge-264/nelo-tovar/perl/ch-2.pl
> Challenge 264. Add Perl and Bash solutions. By Nelo Tovar.

- challenge-264/wlmb/blog.txt
- challenge-264/wlmb/perl/ch-1.pl
- challenge-264/wlmb/perl/ch-2.pl
> Solve PWC264

- challenge-264/barroff/julia/ch-1.jl
- challenge-264/barroff/julia/ch-2.jl
- challenge-264/barroff/raku/ch-1.p6
- challenge-264/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia and Raku solutions for challenge 264.
> feat: add solutions for challenge 264 from BarrOff

- challenge-264/matthias-muth/blog.txt
- challenge-264/matthias-muth/perl/README.md
- challenge-264/matthias-muth/perl/ch-1.pl
- challenge-264/matthias-muth/perl/ch-2.pl
- challenge-264/matthias-muth/perl/challenge-264.txt
> Challenge 264 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-260/mark-anderson/raku/blog-2.md
- challenge-260/mark-anderson/raku/ch-2.raku
Finally adding the FatRat fix. 😵
> FatRat fix

- challenge-265/wlmb/blog.txt
- challenge-265/wlmb/perl/ch-1.pl
- challenge-265/wlmb/perl/ch-2.pl
> Solve PWC265

- challenge-265/packy-anderson/README.md
- challenge-265/packy-anderson/blog.txt
- challenge-265/packy-anderson/perl/ch-1.pl
- challenge-265/packy-anderson/perl/ch-2.pl
- challenge-265/packy-anderson/python/ch-1.py
- challenge-265/packy-anderson/python/ch-2.py
- challenge-265/packy-anderson/raku/ch-1.raku
- challenge-265/packy-anderson/raku/ch-2.raku
* Raku that looks like Perl
* Perl
* Python that looks like Perl
1 Blog post
> Challenge 265 solutions by Packy Anderson

- challenge-265/spadacciniweb/perl/ch-1.pl
- challenge-265/spadacciniweb/perl/ch-2.pl
> Add ch-1 and ch-2 in Perl

- challenge-265/nelo-tovar/bash/ch-1.sh
- challenge-265/nelo-tovar/perl/ch-1.pl
- challenge-265/nelo-tovar/perl/ch-2.pl
> Challenge 265. Add Perl and Bash (ch-1.sh) solutions. By Nelo Tovar.

- challenge-265/lubos-kolouch/perl/ch-1.pl
- challenge-265/lubos-kolouch/perl/ch-2.pl
- challenge-265/lubos-kolouch/python/ch-1.py
- challenge-265/lubos-kolouch/python/ch-2.py
LK solutions in Perl and Python
> Challenge 265 LK Perl Python

- challenge-265/mattneleigh/perl/ch-1.pl
- challenge-265/mattneleigh/perl/ch-2.pl
new file:   challenge-265/mattneleigh/perl/ch-2.pl
> new file:   challenge-265/mattneleigh/perl/ch-1.pl

- challenge-265/barroff/julia/ch-1.jl
- challenge-265/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solutions for task one of challenge 265.
> feat: add solutions for challenge 265 from BarrOff

- challenge-266/wlmb/blog.txt
- challenge-266/wlmb/perl/ch-1.pl
- challenge-266/wlmb/perl/ch-2.pl
> Solve PWC266

- challenge-266/mattneleigh/perl/ch-1.pl
- challenge-266/mattneleigh/perl/ch-2.pl
new file:   challenge-266/mattneleigh/perl/ch-2.pl
> new file:   challenge-266/mattneleigh/perl/ch-1.pl

- challenge-266/barroff/julia/ch-1.jl
- challenge-266/barroff/raku/ch-1.p6
- challenge-266/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia and Raku solutions for task one of challenge 266.
> feat: add solutions for challenge 266 from BarrOff

- challenge-266/matthias-muth/README.md
- challenge-266/matthias-muth/perl/ch-1.pl
- challenge-266/matthias-muth/perl/ch-2.pl
- challenge-266/matthias-muth/perl/challenge-266.txt
Sorry, no blog this time...
Thank you for the Challenge!
> Challenge 266 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-267/wlmb/blog.txt
- challenge-267/wlmb/perl/ch-1.pl
- challenge-267/wlmb/perl/ch-2.pl
> Solve PWC267

- challenge-267/mattneleigh/perl/ch-1.pl
- challenge-267/mattneleigh/perl/ch-2.pl
new file:   challenge-267/mattneleigh/perl/ch-2.pl
> new file:   challenge-267/mattneleigh/perl/ch-1.pl

- challenge-266/packy-anderson/README.md
- challenge-266/packy-anderson/blog.txt
- challenge-266/packy-anderson/perl/ch-1.pl
- challenge-266/packy-anderson/perl/ch-2.pl
- challenge-266/packy-anderson/python/ch-1.py
- challenge-266/packy-anderson/python/ch-2.py
- challenge-266/packy-anderson/raku/ch-1.raku
- challenge-266/packy-anderson/raku/ch-2.raku
- challenge-267/packy-anderson/README.md
- challenge-267/packy-anderson/blog.txt
- challenge-267/packy-anderson/perl/ch-1.pl
- challenge-267/packy-anderson/perl/ch-2.pl
- challenge-267/packy-anderson/python/ch-1.py
- challenge-267/packy-anderson/python/ch-2.py
- challenge-267/packy-anderson/raku/ch-1.raku
- challenge-267/packy-anderson/raku/ch-2.raku
> Challenge 267 solutions by Packy Anderson

- challenge-263/princy-perl/ch-1.pl
- challenge-263/princy-perl/ch-2.pl
tha challenge is done #263 by princy
> Branch for challenge 263

- challenge-263/princy-perl/ch-1.pl
- challenge-263/princy-perl/ch-2.pl
> Princy 263_challenge

- challenge-267/princy_267/task1.perl
i have done task1 and task2 of 276 challenge no. by princy
> the task 1 and task 2 of 267_challenge is completed by princy

- challenge-267/princy_267/task2.perl
added the challenge 267 task2 which states that " Line Counts" 
and the problem statement is : You are given a string, $str, and a 26-items array @widths containing the width of each character from a to z.
Write a script to find out the number of lines and the width of the last line needed to display the given string, assuming you can only fit 100 width units on a line.
> updated the task2 challenge 267

- challenge-267/matthias-muth/README.md
- challenge-267/matthias-muth/blog.txt
- challenge-267/matthias-muth/perl/ch-1.pl
- challenge-267/matthias-muth/perl/ch-2.pl
Thank you for the challenge! :-)
> Challenge 267 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-267/lance-wicks/perl/lib/Product/Sign.pm
- challenge-267/lance-wicks/perl/t/product_sign.t
- challenge-267/lance-wicks/roc/main.roc
> Roc and Perl versions

- challenge-267/nelo-tovar/bash/ch-1.sh
- challenge-267/nelo-tovar/bash/ch-2.sh
- challenge-267/nelo-tovar/perl/ch-1.pl
- challenge-267/nelo-tovar/perl/ch-2.pl
> Challenge 267. Add Perl and Bash solutions. By Nelo Tovar

- challenge-266/2colours/php/ch-1.php
- challenge-266/2colours/php/ch-2.php
- challenge-267/2colours/php/ch-1.php
- challenge-267/2colours/php/ch-2.php
Hi,
long time no see! I had a bit of hiatus but didn't forget how useful these challenges can be to think algorithmically and try out the built-ins of various languages.
These are rather loose, "happy path" implementations in PHP but I enjoyed writing them so I hope they have a place. :)
Cheers.
> PHP solutions for weeks 266 and 267

- challenge-267/barroff/bqn/ch-1.bqn
- challenge-267/barroff/julia/ch-1.jl
- challenge-267/barroff/nim/ch_1.nim
- challenge-267/barroff/perl/ch-1.pl
- challenge-267/barroff/raku/ch-1.p6
Hello
This pull request adds my BQN, Julia, Nim, Perl and Raku solutions for task one of challenge 267.
> feat: add solutions for challenge 267 from BarrOff

- challenge-268/wlmb/blog.txt
- challenge-268/wlmb/perl/ch-1.pl
- challenge-268/wlmb/perl/ch-2.pl
> Solve PWC268

- challenge-267/packy-anderson/elixir/ch-1.exs
- challenge-267/packy-anderson/elixir/ch-1a.exs
- challenge-267/packy-anderson/elixir/ch-2.exs
- challenge-267/packy-anderson/elixir/ch-2a.exs
- challenge-267/packy-anderson/python/ch-1.py
- challenge-267/packy-anderson/raku/ch-1.raku
- challenge-268/packy-anderson/README.md
- challenge-268/packy-anderson/blog.txt
- challenge-268/packy-anderson/perl/ch-1.pl
- challenge-268/packy-anderson/perl/ch-2.pl
- challenge-268/packy-anderson/python/ch-1.py
- challenge-268/packy-anderson/python/ch-2.py
- challenge-268/packy-anderson/raku/ch-1.raku
- challenge-268/packy-anderson/raku/ch-2.raku
* Perl
1 Blog post
Bonus guest solutions to challenge 267 in Elixir.
> Challenge 268 solutions by Packy Anderson

- challenge-268/roger-bell-west/crystal/ch-1.cr
- challenge-268/roger-bell-west/crystal/ch-2.cr
- challenge-268/roger-bell-west/javascript/ch-1.js
- challenge-268/roger-bell-west/javascript/ch-2.js
- challenge-268/roger-bell-west/kotlin/ch-1.kt
- challenge-268/roger-bell-west/kotlin/ch-2.kt
- challenge-268/roger-bell-west/lua/ch-1.lua
- challenge-268/roger-bell-west/lua/ch-2.lua
- challenge-268/roger-bell-west/perl/ch-1.pl
- challenge-268/roger-bell-west/perl/ch-2.pl
- challenge-268/roger-bell-west/postscript/ch-1.ps
- challenge-268/roger-bell-west/postscript/ch-2.ps
- challenge-268/roger-bell-west/python/ch-1.py
- challenge-268/roger-bell-west/python/ch-2.py
- challenge-268/roger-bell-west/raku/ch-1.p6
- challenge-268/roger-bell-west/raku/ch-2.p6
- challenge-268/roger-bell-west/ruby/ch-1.rb
- challenge-268/roger-bell-west/ruby/ch-2.rb
- challenge-268/roger-bell-west/rust/ch-1.rs
- challenge-268/roger-bell-west/rust/ch-2.rs
- challenge-268/roger-bell-west/scala/ch-1.scala
- challenge-268/roger-bell-west/scala/ch-2.scala
- challenge-268/roger-bell-west/tests.json
With an eleventh language. (Yeah, I'm not Abigail, but who is?)
> RogerBW solutions for challenge no. 268

- challenge-268/2colours/groovy/ch-1.groovy
- challenge-268/2colours/groovy/ch-2.groovy
- challenge-268/2colours/php/ch-1.php
- challenge-268/2colours/php/ch-2.php
Hi,
thank you for the challenges. These are very simplistic, optimistic "underthinking" solutions based on the examples, with the additional constraint that non-offset scenarios will output "N/A" for the first task.
Also, from what I can tell, this is the first solution of Groovy. I couldn't find a "groovy" folder or a ".groovy" or ".gsh" file. I found this a bit surprising at first but there are only 6 ".ts" files so maybe I shouldn't be so surprised if there is no Groovy.
> Branch for challenge 268

- challenge-268/asherbhs/apl/ch-1.apl
- challenge-268/asherbhs/apl/ch-2.apl
- challenge-268/asherbhs/bqn/ch-1.bqn
- challenge-268/asherbhs/bqn/ch-2.bqn
- challenge-268/asherbhs/haskell/ch-1.hs
- challenge-268/asherbhs/haskell/ch-2.hs
- challenge-268/asherbhs/hy/ch-1.hy
- challenge-268/asherbhs/hy/ch-2.hy
- challenge-268/asherbhs/j/ch-1.ijs
- challenge-268/asherbhs/j/ch-2.ijs
- challenge-268/asherbhs/nu/ch-1.nu
- challenge-268/asherbhs/nu/ch-2.nu
- challenge-268/asherbhs/raku/ch-1.raku
- challenge-268/asherbhs/raku/ch-2.raku
Solutions in Raku, APL, BQN, J, Haskell, Hy and Nu (new language for me!)
> Challenge 268

- challenge-268/matthias-muth/README.md
- challenge-268/matthias-muth/blog.txt
- challenge-268/matthias-muth/perl/ch-1.pl
- challenge-268/matthias-muth/perl/ch-2.pl
> Challenge 268 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-268/barroff/julia/ch-1.jl
- challenge-268/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solutions for task one of challenge 268.
> feat: add solutions for challenge 268 from BarrOff

- challenge-269/mattneleigh/perl/ch-1.pl
- challenge-269/mattneleigh/perl/ch-2.pl
new file:   challenge-269/mattneleigh/perl/ch-2.pl
> new file:   challenge-269/mattneleigh/perl/ch-1.pl

- challenge-269/nelo-tovar/bash/ch-1.sh
- challenge-269/nelo-tovar/bash/ch-2.sh
- challenge-269/nelo-tovar/perl/ch-1.pl
- challenge-269/nelo-tovar/perl/ch-2.pl
> Challenge 269. Add Perl and Bash solutions. By Nelo Tovar

- challenge-270/wlmb/blog.txt
- challenge-270/wlmb/perl/ch-1.pl
- challenge-270/wlmb/perl/ch-2.pl
Regards. 
Found a small typo in the examples: a 3 should be 4 in
'So the total cost would be (1 x $x) + (3 x $y) => (1 x 2) + (4 x 1) => 6'
> Solve PWC270

- challenge-270/peter-meszaros/perl/ch-2.pl
> challenge-270

- challenge-270/lance-wicks/perl/lib/Special.pm
- challenge-270/lance-wicks/perl/t/ch-1.t
> Perl by Lance

- challenge-270/nelo-tovar/bash/ch-2.sh
- challenge-270/nelo-tovar/perl/ch-1.pl
- challenge-270/nelo-tovar/perl/ch-2.pl
> Challenge 270. Add Perl and Bash(ch-2.sh) solutions. By Nelo Tovar

- challenge-270/robbie-hatley/blog.txt
- challenge-270/robbie-hatley/perl/ch-1.pl
I ran out of time and energy for 270-2, alas.
> Robbie Hatley's Perl solution for The Weekly Challenge #270-1.

- challenge-270/barroff/julia/ch-1.jl
- challenge-270/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solutions for task one of challenge 270.
> feat: add solutions for challenge 270 from BarrOff

- challenge-270/packy-anderson/README.md
- challenge-270/packy-anderson/blog.txt
- challenge-270/packy-anderson/elixir/ch-1.exs
- challenge-270/packy-anderson/elixir/ch-2.exs
- challenge-270/packy-anderson/perl/ch-1.pl
- challenge-270/packy-anderson/perl/ch-2.pl
- challenge-270/packy-anderson/python/ch-1.py
- challenge-270/packy-anderson/python/ch-2.py
- challenge-270/packy-anderson/raku/ch-1.raku
- challenge-270/packy-anderson/raku/ch-2.raku
* Perl
* Elixir that looks like a hybrid between Perl and Elixir
1 Blog post
> Challenge 270 solutions by Packy Anderson

- challenge-270/jo-37/blog1.txt
- challenge-270/jo-37/perl/ch-2a.pl
Fixed an issue after reading @wlmb 's [blog](https://wlmb.github.io/2024/05/20/PWC270/)
> New solution to challenge 270 task 2

- challenge-271/spadacciniweb/perl/ch-1.pl
- challenge-271/spadacciniweb/perl/ch-2.pl
> PWC-271 Add ch-1 and ch-2 in Perl

- challenge-271/atschneid/README.md
- challenge-271/atschneid/haskell/README.md
- challenge-271/atschneid/haskell/ch-1.lhs
- challenge-271/atschneid/haskell/ch-2.lhs
- challenge-271/atschneid/perl/ch-1.pl
- challenge-271/atschneid/perl/ch-2.pl
First time contribution to PWC
> Initial commit of perl and haskell pwc 271 solutions

- challenge-271/nelo-tovar/bash/ch-2.sh
- challenge-271/nelo-tovar/perl/ch-1.pl
- challenge-271/nelo-tovar/perl/ch-2.pl
> Challenge 271. Add Perl and Bash(ch-2.sh) solutions. By Nelo Tovar

- challenge-271/barroff/julia/ch-1.jl
- challenge-271/barroff/julia/ch-2.jl
- challenge-271/barroff/raku/ch-1.p6
- challenge-271/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia and Raku solutions for challenge 271.
> feat: add solutions for challenge 271 from BarrOff

- challenge-271/matthias-muth/README.md
- challenge-271/matthias-muth/blog.txt
- challenge-271/matthias-muth/perl/ch-1.pl
- challenge-271/matthias-muth/perl/ch-2.pl
> Challenge 271 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-272/mattneleigh/perl/ch-1.pl
- challenge-272/mattneleigh/perl/ch-2.pl
new file:   challenge-272/mattneleigh/perl/ch-2.pl
> new file:   challenge-272/mattneleigh/perl/ch-1.pl

- challenge-270/e-choroba/perl/ch-2.pl
The old name was wrongly copied from the previous week.
> Rename and simplify the function in 270/2

- challenge-272/packy-anderson/README.md
- challenge-272/packy-anderson/blog.txt
- challenge-272/packy-anderson/elixir/ch-1.exs
- challenge-272/packy-anderson/elixir/ch-2.exs
- challenge-272/packy-anderson/perl/ch-1.pl
- challenge-272/packy-anderson/perl/ch-2.pl
- challenge-272/packy-anderson/python/ch-1.py
- challenge-272/packy-anderson/python/ch-2.py
- challenge-272/packy-anderson/raku/ch-1.raku
- challenge-272/packy-anderson/raku/ch-2.raku
* Perl
* Elixir that kinda looks like Elixir
1 Blog post
> Challenge 272 solutions by Packy Anderson

- challenge-272/atschneid/README.md
- challenge-272/atschneid/blog.txt
- challenge-272/atschneid/c/ch-1.c
- challenge-272/atschneid/c/ch-2.c
- challenge-272/atschneid/c/makefile
- challenge-272/atschneid/perl/ch-1.pl
- challenge-272/atschneid/perl/ch-2.pl
- challenge-272/atschneid/prolog/ch-1.pro
- challenge-272/atschneid/prolog/ch-2.pro
- challenge-272/atschneid/prolog/makefile
- challenge-272/atschneid/racket/ch-1.rkt
- challenge-272/atschneid/racket/ch-2.rkt
PWC 272 solutions in various languages
Thanks for running this!
> atschneid 272 solutions

- challenge-272/matthias-muth/README.md
- challenge-272/matthias-muth/blog.txt
- challenge-272/matthias-muth/perl/ch-1.pl
- challenge-272/matthias-muth/perl/ch-2.pl
> Challenge 272 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-272/nelo-tovar/bash/ch-1.sh
- challenge-272/nelo-tovar/bash/ch-2.sh
- challenge-272/nelo-tovar/perl/ch-1.pl
- challenge-272/nelo-tovar/perl/ch-2.pl
> Challenge 272. Add Perl and Bash solutions. By Nelo Tovar

- challenge-272/barroff/julia/ch-1.jl
- challenge-272/barroff/julia/ch-2.jl
- challenge-272/barroff/raku/ch-1.p6
- challenge-272/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia and Raku solutions for challenge 272.
> feat: add solutions for challenge 272 from BarrOff

- challenge-273/robbie-hatley/blog.txt
- challenge-273/robbie-hatley/perl/ch-1.pl
- challenge-273/robbie-hatley/perl/ch-2.pl
Fun with regular expressions, in both cases. :-)
> Robbie Hatley's solutions, in Perl, for The Weekly Challenge #273.

- challenge-270/2colours/php/ch-1.php
- challenge-270/2colours/php/ch-2.php
Hi,
Week 270 was very interesting: the first task was good for array-based languages, and the second task was good for math dabblers. To my knowledge, this is the best solution to that problem so far:
- it passes all tests of Mr. Choroba
- it tries to give reasonable values for corner cases (short arrays, negative or zero costs) as well
- it is "formula based" in the sense that after we only need the minimum, the maximum, the length and the sum of the array; everything after that has constant-bound complexity, in the spirit of absolute value (un)equalities. **No loops at all**.
I also think that I have proofs for the formulae I'm using, I can give more insights on the solution if somebody is interested. Hopefully it's easier to explain than come up with it; originally it took me two …
> Solutions for week #270 in PHP

- challenge-273/packy-anderson/README.md
- challenge-273/packy-anderson/blog.txt
- challenge-273/packy-anderson/elixir/ch-1.exs
- challenge-273/packy-anderson/elixir/ch-2.exs
- challenge-273/packy-anderson/perl/ch-1.pl
- challenge-273/packy-anderson/perl/ch-2.pl
- challenge-273/packy-anderson/python/ch-1.py
- challenge-273/packy-anderson/python/ch-2.py
- challenge-273/packy-anderson/raku/ch-1.raku
- challenge-273/packy-anderson/raku/ch-2.raku
* Perl
* Elixir that kinda looks like Elixir
1 Blog post
> Challenge 273 solutions by Packy Anderson

- challenge-273/robbie-hatley/perl/ch-1.pl
> Update to my Perl solution to 273-1, 2024-06-12.

- challenge-273/mattneleigh/perl/ch-1.pl
- challenge-273/mattneleigh/perl/ch-2.pl
new file:   challenge-273/mattneleigh/perl/ch-2.pl
> new file:   challenge-273/mattneleigh/perl/ch-1.pl

- challenge-273/spadacciniweb/go/ch-1.go
- challenge-273/spadacciniweb/go/ch-2.go
> Add ch-1 and ch-2 in Go

- challenge-273/matthias-muth/README.md
- challenge-273/matthias-muth/blog.txt
- challenge-273/matthias-muth/perl/ch-1.pl
- challenge-273/matthias-muth/perl/ch-2.pl
> Challenge 273 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-273/nelo-tovar/bash/ch-1.sh
- challenge-273/nelo-tovar/bash/ch-2.sh
- challenge-273/nelo-tovar/perl/ch-1.pl
- challenge-273/nelo-tovar/perl/ch-2.pl
> Challenge 273. Add Perl and Bash solutions. By Nelo Tovar

- challenge-273/barroff/julia/ch-1.jl
- challenge-273/barroff/julia/ch-2.jl
- challenge-273/barroff/perl/ch-2.pl
- challenge-273/barroff/raku/ch-1.p6
- challenge-273/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia, Perl and Raku solutions for challenge 273.
> feat: add solutions for challenge 273 from BarrOff

- challenge-274/packy-anderson/README.md
- challenge-274/packy-anderson/blog.txt
- challenge-274/packy-anderson/elixir/ch-1.exs
- challenge-274/packy-anderson/elixir/ch-2.exs
- challenge-274/packy-anderson/perl/ch-1.pl
- challenge-274/packy-anderson/perl/ch-2.pl
- challenge-274/packy-anderson/python/ch-1.py
- challenge-274/packy-anderson/python/ch-2.py
- challenge-274/packy-anderson/raku/ch-1.raku
- challenge-274/packy-anderson/raku/ch-2.raku
* Perl
* Elixir for task 1 only
1 Blog post
> Challenge 274 solutions by Packy Anderson

- challenge-274/mattneleigh/perl/ch-1.pl
- challenge-274/mattneleigh/perl/ch-2.pl
new file:   challenge-274/mattneleigh/perl/ch-2.pl
> new file:   challenge-274/mattneleigh/perl/ch-1.pl

- challenge-274/nelo-tovar/bash/ch-1.sh
- challenge-274/nelo-tovar/perl/ch-1.pl
> Challenge 274. Add Perl(ch-1) and Bash(ch-1) solutions. By Nelo Tovar

- challenge-273/sgreen/README.md
- challenge-274/sgreen/README.md
- challenge-274/sgreen/blog.txt
- challenge-274/sgreen/python/ch-1.py
- challenge-274/sgreen/python/ch-2.py
- challenge-274/sgreen/python/test.py
Only Python solutions this week.
> sgreen solutions to challenge 274

- challenge-274/matthias-muth/README.md
- challenge-274/matthias-muth/blog.txt
- challenge-274/matthias-muth/perl/ch-1.pl
- challenge-274/matthias-muth/perl/ch-2.pl
> Challenge 274 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-274/atschneid/README.md
- challenge-274/atschneid/blog.txt
- challenge-274/atschneid/c/ch-1.c
- challenge-274/atschneid/c/ch-2.c
- challenge-274/atschneid/c/makefile
- challenge-274/atschneid/haskell/ch-1.hs
- challenge-274/atschneid/haskell/ch-2.hs
- challenge-274/atschneid/haskell/makefile
- challenge-274/atschneid/haskell/unused-extras.hs
- challenge-274/atschneid/julia/ch-1.jl
- challenge-274/atschneid/julia/ch-2.jl
- challenge-274/atschneid/perl/ch-1.pl
- challenge-274/atschneid/perl/ch-2.pl
> PWC 274 - atschneid

- challenge-274/barroff/julia/ch-1.jl
- challenge-274/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solutions for challenge 274.
> feat: add solutions for challenge 274 from BarrOff

- challenge-275/packy-anderson/README.md
- challenge-275/packy-anderson/blog.txt
- challenge-275/packy-anderson/elixir/ch-1.exs
- challenge-275/packy-anderson/elixir/ch-2.exs
- challenge-275/packy-anderson/perl/ch-1.pl
- challenge-275/packy-anderson/perl/ch-2.pl
- challenge-275/packy-anderson/python/ch-1.py
- challenge-275/packy-anderson/python/ch-2.py
- challenge-275/packy-anderson/raku/ch-1.raku
- challenge-275/packy-anderson/raku/ch-2.raku
> Challenge 275 solutions by Packy Anderson

- challenge-275/mattneleigh/perl/ch-1.pl
- challenge-275/mattneleigh/perl/ch-2.pl
new file:   challenge-275/mattneleigh/perl/ch-2.pl
> new file:   challenge-275/mattneleigh/perl/ch-1.pl

- challenge-275/2colours/prolog/ch-2.p
Hi,
thank you for the new tasks. Not sure if I'll have time to do the other one but I was playing around with Prolog again recently so here we go...
Cheers
> solution #2 task in Prolog

- challenge-275/spadacciniweb/elixir/ch-1.exs
- challenge-275/spadacciniweb/elixir/ch-2.exs
- challenge-275/spadacciniweb/perl/ch-1.pl
- challenge-275/spadacciniweb/perl/ch-2.pl
> Add ch-1 and ch-2 in Perl and Elixir

- challenge-275/nelo-tovar/bash/ch-1.sh
- challenge-275/nelo-tovar/bash/ch-2.sh
- challenge-275/nelo-tovar/perl/ch-1.pl
- challenge-275/nelo-tovar/perl/ch-2.pl
> Challenge 275. Add and Bash solutions. By Nelo Tovar

- challenge-275/matthias-muth/README.md
- challenge-275/matthias-muth/blog.txt
- challenge-275/matthias-muth/perl/ch-1.pl
- challenge-275/matthias-muth/perl/ch-2.pl
> Challenge 275 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-275/barroff/julia/ch-1.jl
- challenge-275/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solutions for task one of challenge 275.
> feat: add solutions for challenge 275 from BarrOff

- challenge-276/mattneleigh/perl/ch-1.pl
- challenge-276/mattneleigh/perl/ch-2.pl
new file:   challenge-276/mattneleigh/perl/ch-2.pl
> new file:   challenge-276/mattneleigh/perl/ch-1.pl

- challenge-276/mgo1977/README
- challenge-276/mgo1977/perl/ch1.pl
- challenge-276/mgo1977/perl/ch2.pl
Hi,
I'm sending my Perl solution,
regards,
Mariano
> mgo1977 - PWC 276

- challenge-276/packy-anderson/README.md
- challenge-276/packy-anderson/blog.txt
- challenge-276/packy-anderson/elixir/ch-1.exs
- challenge-276/packy-anderson/elixir/ch-2.exs
- challenge-276/packy-anderson/perl/ch-1.pl
- challenge-276/packy-anderson/perl/ch-2.pl
- challenge-276/packy-anderson/python/ch-1.py
- challenge-276/packy-anderson/python/ch-2.py
- challenge-276/packy-anderson/raku/ch-1.raku
- challenge-276/packy-anderson/raku/ch-2.raku
> Challenge 276 solutions by Packy Anderson

- challenge-275/2colours/prolog/ch-1.p
- challenge-276/2colours/prolog/ch-1.p
- challenge-276/2colours/prolog/ch-2.p
Hello,
Thank you for the new exercises. I made some solutions using SWI-Prolog, it was educational for me at the very least. Please merge them.
Cheers.
> Add remaining Prolog solutions for week 275 and 276

- challenge-276/atschneid/README.md
- challenge-276/atschneid/blog.txt
- challenge-276/atschneid/c/ch-1.c
- challenge-276/atschneid/c/ch-2.c
- challenge-276/atschneid/c/makefile
- challenge-276/atschneid/perl/ch-1.pl
- challenge-276/atschneid/perl/ch-2.pl
- challenge-276/atschneid/prolog/ch-1.pro
- challenge-276/atschneid/prolog/ch-2.pro
> ATSchneid submission for PWC 276

- challenge-276/barroff/julia/ch-1.jl
- challenge-276/barroff/julia/ch-2.jl
- challenge-276/barroff/raku/ch-1.p6
- challenge-276/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia and Raku solutions for challenge 276.
> feat: add solutions for challenge 276 from BarrOff

- challenge-277/packy-anderson/README.md
- challenge-277/packy-anderson/blog.txt
- challenge-277/packy-anderson/elixir/ch-1.exs
- challenge-277/packy-anderson/elixir/ch-2.exs
- challenge-277/packy-anderson/perl/ch-1.pl
- challenge-277/packy-anderson/perl/ch-2.pl
- challenge-277/packy-anderson/python/ch-1.py
- challenge-277/packy-anderson/python/ch-2.py
- challenge-277/packy-anderson/raku/ch-1.raku
- challenge-277/packy-anderson/raku/ch-2.raku
> Challenge 277 solutions by Packy Anderson

- challenge-277/mattneleigh/perl/ch-1.pl
- challenge-277/mattneleigh/perl/ch-2.pl
new file:   challenge-277/mattneleigh/perl/ch-2.pl
> new file:   challenge-277/mattneleigh/perl/ch-1.pl

- challenge-276/peter-meszaros/perl/ch-1.pl
- challenge-276/peter-meszaros/perl/ch-2.pl
- **challenge-276**
- **challenge-276**
> challenge 276

- challenge-277/mgo1977/perl/ch-1.pl
- challenge-277/mgo1977/perl/ch-2.pl
Hi Mohammad,
How are you doing?
I'm sending my contribution.
Thanks for your hard work!
best regards,
Mariano
> mgo1977 - PWC 277

- challenge-277/2colours/prolog/ch-1.p
- challenge-277/2colours/prolog/ch-2.p
Hi,
thank you for the challenges, I was trying to do them as quickly as possible - well, it wasn't possible as quickly as I wanted. :D But that's more Prolog to blame.
Please merge the solutions and keep up the good work. ^^
> Prolog solutions by 2colours

- challenge-277/nelo-tovar/bash/ch-1.sh
- challenge-277/nelo-tovar/bash/ch-2.sh
- challenge-277/nelo-tovar/perl/ch-1.pl
- challenge-277/nelo-tovar/perl/ch-2.pl
> Challenge 277. Add and Bash solutions. By Nelo Tovar

- challenge-277/matthias-muth/README.md
- challenge-277/matthias-muth/blog.txt
- challenge-277/matthias-muth/perl/ch-1.pl
- challenge-277/matthias-muth/perl/ch-2.pl
> Challenge 277 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-277/atschneid/README.md
- challenge-277/atschneid/blog.txt
- challenge-277/atschneid/c/ch-1.c
- challenge-277/atschneid/c/ch-2.c
- challenge-277/atschneid/c/makefile
- challenge-277/atschneid/erlang/ch_1.erl
- challenge-277/atschneid/erlang/ch_2.erl
- challenge-277/atschneid/perl/ch-1.pl
- challenge-277/atschneid/perl/ch-2.pl
> ATSchneider PWC 277 contribution

- challenge-278/mattneleigh/perl/ch-1.pl
- challenge-278/mattneleigh/perl/ch-2.pl
new file:   challenge-278/mattneleigh/perl/ch-2.pl
> new file:   challenge-278/mattneleigh/perl/ch-1.pl

- challenge-278/wlmb/blog.txt
- challenge-278/wlmb/perl/ch-1.pl
- challenge-278/wlmb/perl/ch-2.pl
> Solve PWC278

- challenge-121/jaldhar-h-vyas/perl/ch-2.pl
- challenge-121/jaldhar-h-vyas/raku/ch-2.raku
This is an old one I hadn't completed the first time.  The blog entry has also been updated though the URL is the same.
> Challenge 121 part 2 by Jaldhar H. Vyas.

- challenge-278/mgo1977/perl/ch-1.pl
- challenge-278/mgo1977/perl/ch-2.pl
Hi Mohammad,
I'm sending you my contribution
best regards,
Mariano
> mgo1977 - PWC 278

- challenge-278/lance-wicks/perl/ch-1.pl
- challenge-278/lance-wicks/perl/lib/String.pm
- challenge-278/lance-wicks/perl/t/ch-1.t
Using sub signatures and not using Moo for a change. :-)
> Perl solution by Lance

- challenge-278/packy-anderson/README.md
- challenge-278/packy-anderson/blog.txt
- challenge-278/packy-anderson/elixir/ch-1.exs
- challenge-278/packy-anderson/elixir/ch-2.exs
- challenge-278/packy-anderson/perl/ch-1.pl
- challenge-278/packy-anderson/perl/ch-2.pl
- challenge-278/packy-anderson/python/ch-1.py
- challenge-278/packy-anderson/python/ch-2.py
- challenge-278/packy-anderson/raku/ch-1.raku
- challenge-278/packy-anderson/raku/ch-2.raku
> Challenge 278 solutions by Packy Anderson

- challenge-278/atschneid/README.md
- challenge-278/atschneid/blog.txt
- challenge-278/atschneid/julia/ch-1.jl
- challenge-278/atschneid/julia/ch-2.jl
- challenge-278/atschneid/perl/ch-1.pl
- challenge-278/atschneid/perl/ch-2.pl
- challenge-278/atschneid/racket/ch-1.rkt
- challenge-278/atschneid/racket/ch-2.rkt
> ATSchneid PWC 278 

- challenge-278/barroff/julia/ch-1.jl
- challenge-278/barroff/julia/ch-2.jl
- challenge-278/barroff/raku/ch-1.p6
- challenge-278/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia and Raku solutions for challenge 278.
> feat: add solutions for challenge 278 from BarrOff

- challenge-279/packy-anderson/README.md
- challenge-279/packy-anderson/blog.txt
- challenge-279/packy-anderson/elixir/ch-1.exs
- challenge-279/packy-anderson/elixir/ch-2.exs
- challenge-279/packy-anderson/perl/ch-1.pl
- challenge-279/packy-anderson/perl/ch-2.pl
- challenge-279/packy-anderson/python/ch-1.py
- challenge-279/packy-anderson/python/ch-2.py
- challenge-279/packy-anderson/raku/ch-1.raku
- challenge-279/packy-anderson/raku/ch-2.raku
> Challenge 279 solutions by Packy Anderson

- challenge-279/mattneleigh/perl/ch-1.pl
- challenge-279/mattneleigh/perl/ch-2.pl
new file:   challenge-279/mattneleigh/perl/ch-2.pl
> new file:   challenge-279/mattneleigh/perl/ch-1.pl

- challenge-279/andrezgz/perl/ch-1.pl
- challenge-279/andrezgz/perl/ch-2.pl
Hi @manwar , I'm back. At least for this week :)
> challenge-279 andrezgz solution

- challenge-279/wlmb/blog.txt
- challenge-279/wlmb/perl/ch-1.pl
- challenge-279/wlmb/perl/ch-2.pl
> Solve PWC 279

- challenge-279/2colours/prolog/ch-1.p
- challenge-279/2colours/prolog/ch-2.p
Hi,
thank you for the challenges. These are fairly banal, better-than-nothing solutions in Prolog - it's funny how complicated certain very simple problems can be stated, right? :D
Anyway, hopefully this can also add to the diversity of the solutions.
Cheers.
> Prolog solutions for week #279

- challenge-279/nelo-tovar/bash/ch-1.sh
- challenge-279/nelo-tovar/bash/ch-2.sh
- challenge-279/nelo-tovar/perl/ch-1.pl
- challenge-279/nelo-tovar/perl/ch-2.pl
> Challenge 279. Add Perl and Bash solutions. By Nelo Tovar

- challenge-279/matthias-muth/README.md
- challenge-279/matthias-muth/blog.txt
- challenge-279/matthias-muth/perl/ch-1.pl
- challenge-279/matthias-muth/perl/ch-2.pl
> Challenge 279 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-279/atschneid/README.md
- challenge-279/atschneid/blog.txt
- challenge-279/atschneid/perl/ch-1.pl
- challenge-279/atschneid/perl/ch-2.pl
- challenge-279/atschneid/rust/ch-1.rs
- challenge-279/atschneid/rust/ch-2.rs
> ATSchneider PWC 279 solutions

- challenge-279/barroff/julia/ch-1.jl
- challenge-279/barroff/julia/ch-2.jl
- challenge-279/barroff/raku/ch-1.p6
- challenge-279/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia and Raku solutions for challenge 279.
> feat: add solutions for challenge 279 from BarrOff

- challenge-279/mark-anderson/raku/ch-1.raku
> Also removed useless brackets.

- challenge-280/e-choroba/perl/ch-1.pl
- challenge-280/e-choroba/perl/ch-2.pl
"Twice Appearance" has two interpretations, show and test solutions for both.
> Solve 280: Twice Appearance & Count Asterisks by E. Choroba

- challenge-280/mattneleigh/perl/ch-1.pl
- challenge-280/mattneleigh/perl/ch-2.pl
new file:   challenge-280/mattneleigh/perl/ch-2.pl
> new file:   challenge-280/mattneleigh/perl/ch-1.pl

- challenge-280/packy-anderson/README.md
- challenge-280/packy-anderson/blog.txt
- challenge-280/packy-anderson/elixir/ch-1.exs
- challenge-280/packy-anderson/elixir/ch-2.exs
- challenge-280/packy-anderson/perl/ch-1.pl
- challenge-280/packy-anderson/perl/ch-2.pl
- challenge-280/packy-anderson/python/ch-1.py
- challenge-280/packy-anderson/python/ch-2.py
- challenge-280/packy-anderson/raku/ch-1.raku
- challenge-280/packy-anderson/raku/ch-2.raku
> Challenge 280 solutions by Packy Anderson

- challenge-280/nelo-tovar/bash/ch-1.sh
- challenge-280/nelo-tovar/perl/ch-1.pl
- challenge-280/nelo-tovar/perl/ch-2.pl
> Challenge 280. Add Perl and Bash (ch-1) solutions. By Nelo Tovar

- challenge-280/roger-bell-west/crystal/ch-1.cr
- challenge-280/roger-bell-west/crystal/ch-2.cr
- challenge-280/roger-bell-west/javascript/ch-1.js
- challenge-280/roger-bell-west/javascript/ch-2.js
- challenge-280/roger-bell-west/kotlin/ch-1.kt
- challenge-280/roger-bell-west/kotlin/ch-2.kt
- challenge-280/roger-bell-west/lua/ch-1.lua
- challenge-280/roger-bell-west/lua/ch-2.lua
- challenge-280/roger-bell-west/perl/ch-1.pl
- challenge-280/roger-bell-west/perl/ch-2.pl
- challenge-280/roger-bell-west/postscript/ch-1.ps
- challenge-280/roger-bell-west/postscript/ch-2.ps
- challenge-280/roger-bell-west/python/ch-1.py
- challenge-280/roger-bell-west/python/ch-2.py
- challenge-280/roger-bell-west/raku/ch-1.p6
- challenge-280/roger-bell-west/raku/ch-2.p6
- challenge-280/roger-bell-west/ruby/ch-1.rb
- challenge-280/roger-bell-west/ruby/ch-2.rb
- challenge-280/roger-bell-west/rust/ch-1.rs
- challenge-280/roger-bell-west/rust/ch-2.rs
- challenge-280/roger-bell-west/scala/ch-1.scala
- challenge-280/roger-bell-west/scala/ch-2.scala
- challenge-280/roger-bell-west/tests.json
Sorry for the delay, looks like git weirdness.
> RogerBW solutions for challenge no. 280

- challenge-280/barroff/julia/ch-1.jl
- challenge-280/barroff/julia/ch-2.jl
- challenge-280/barroff/raku/ch-1.p6
- challenge-280/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia and Raku solutions for challenge 280.
> feat: add solutions for challenge 280 from BarrOff

- challenge-280/matthias-muth/README.md
- challenge-280/matthias-muth/blog.txt
- challenge-280/matthias-muth/perl/ch-1.pl
- challenge-280/matthias-muth/perl/ch-2.pl
> Challenge 280 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-281/mgo1977/perl/ch-1.pl
- challenge-281/mgo1977/perl/ch-2.pl
Hi Mohammad,
I'm sending my solutions
regards,
Mariano
> mgo1977 - PWC 281

- challenge-281/wlmb/blog.txt
- challenge-281/wlmb/perl/ch-1.pl
- challenge-281/wlmb/perl/ch-2.pl
> Solve PWC281

- challenge-281/packy-anderson/elixir/ch-2.exs
- challenge-281/packy-anderson/perl/ch-2.pl
- challenge-281/packy-anderson/python/ch-2.py
- challenge-281/packy-anderson/raku/ch-2.raku
Task 2 in Elixir; remove extraneous newline from Raku/Perl/Python task 2 output.
> Challenge 281 update by Packy Anderson

- challenge-281/robbie-hatley/blog.txt
- challenge-281/robbie-hatley/perl/ch-1.pl
- challenge-281/robbie-hatley/perl/ch-2.pl
Whereas Challenge 281-1 was one of the simplest I've ever worked on, 281-2 was one of the most complex. ("Minimum path" problems are notoriously hard, and some have no closed-form solution.) 
Also, I finally got to put Perl v5.40 to good use in my 281-2 solution, as it uses the new builtin::inf constant.
> Robbie Hatley's solutions, in Perl, for The Weekly Challenge #281.

- challenge-280/santiago-leyva/perl/ch-1.pl
- challenge-280/santiago-leyva/perl/ch-2.pl
late again, but here it is! thanks!
> added perl challenge 280

- challenge-281/nelo-tovar/bash/ch-1.sh
- challenge-281/nelo-tovar/perl/ch-1.pl
> Challenge 281. Add Perl (ch-1) and Bash (ch-1) solutions. By Nelo Tovar

- challenge-278/sgreen/README.md
- challenge-279/sgreen/README.md
- challenge-280/sgreen/README.md
- challenge-281/sgreen/README.md
- challenge-281/sgreen/blog.txt
- challenge-281/sgreen/perl/ch-1.pl
- challenge-281/sgreen/perl/ch-2.pl
- challenge-281/sgreen/python/ch-1.py
- challenge-281/sgreen/python/ch-2.py
- challenge-281/sgreen/python/test.py
> sgreen solutions to challenge 281

- challenge-281/barroff/julia/ch-1.jl
- challenge-281/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solutions for task one of challenge 281.
> feat: add solutions for challenge 281 from BarrOff

- challenge-281/atschneid/README.md
- challenge-281/atschneid/blog.txt
- challenge-281/atschneid/julia/ch-1.jl
- challenge-281/atschneid/julia/ch-2.jl
- challenge-281/atschneid/perl/ch-1.pl
- challenge-281/atschneid/perl/ch-2.pl
- challenge-281/atschneid/racket/ch-1.rkt
- challenge-281/atschneid/racket/ch-2.rkt
Thanks @manwar !
And thanks for the good wishes, AND the Champion announcement - bragging rights at work for me now!
> ATSchneid PWC 281 

- challenge-281/matthias-muth/README.md
- challenge-281/matthias-muth/blog.txt
- challenge-281/matthias-muth/perl/ch-1.pl
- challenge-281/matthias-muth/perl/ch-2.pl
> Challenge 281 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-282/robbie-hatley/blog.txt
- challenge-282/robbie-hatley/perl/ch-1.pl
- challenge-282/robbie-hatley/perl/ch-2.pl
I had fun with "using the m//g operator in scalar context" on both of these.
> Robbie Hatley's solutions, in Perl, for The Weekly Challenge #282

- challenge-282/mgo1977/perl/ch-1.pl
- challenge-282/mgo1977/perl/ch-2.pl
Hi Mohammad,
Sending my solutions,
regards,
Mariano
> mgo1977 - PWC 282

- challenge-282/packy-anderson/README.md
- challenge-282/packy-anderson/blog.txt
- challenge-282/packy-anderson/elixir/ch-1.exs
- challenge-282/packy-anderson/elixir/ch-2.exs
- challenge-282/packy-anderson/perl/ch-1.pl
- challenge-282/packy-anderson/perl/ch-2.pl
- challenge-282/packy-anderson/python/ch-1.py
- challenge-282/packy-anderson/python/ch-2.py
- challenge-282/packy-anderson/raku/ch-1.raku
- challenge-282/packy-anderson/raku/ch-2.raku
> Challenge 282 solutions by Packy Anderson

- challenge-282/robbie-hatley/perl/ch-2.pl
Corrections to comments in Robbie Hatley's solution to PWCC 282-2.
> Corrected pull request (last request got botched somehow).

- challenge-282/nelo-tovar/bash/ch-1.sh
- challenge-282/nelo-tovar/bash/ch-2.sh
- challenge-282/nelo-tovar/perl/ch-1.pl
- challenge-282/nelo-tovar/perl/ch-2.pl
> Challenge 282. Add Perl and Bash solutions. By Nelo Tovar

- challenge-281/santiago-leyva/perl/ch-01.pl
- challenge-281/santiago-leyva/perl/ch-02.pl
Will add the ch-02 later once i crack it! thanks
> Added ch-01 but couldn't finish ch-02 :c

- challenge-282/mattneleigh/perl/ch-1.pl
- challenge-282/mattneleigh/perl/ch-2.pl
new file:   challenge-282/mattneleigh/perl/ch-2.pl
> new file:   challenge-282/mattneleigh/perl/ch-1.pl

- challenge-282/atschneid/README.md
- challenge-282/atschneid/blog.txt
- challenge-282/atschneid/perl/ch-1.pl
- challenge-282/atschneid/perl/ch-2.pl
- challenge-282/atschneid/rust/ch-1.rs
- challenge-282/atschneid/rust/ch-2.rs
> ATSchneid PWC 282 solutions

- challenge-282/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 282.
> feat: Raku solution for task 1 of challenge 282 from BarrOff

- challenge-282/matthias-muth/README.md
- challenge-282/matthias-muth/blog.txt
- challenge-282/matthias-muth/perl/ch-1.pl
- challenge-282/matthias-muth/perl/ch-2.pl
> Challenge 282 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-282/matthias-muth/perl/ch-1.pl
- challenge-282/matthias-muth/perl/ch-2.pl
> Challenge 282 Task 1 and 2 solutions in Perl by Matthias Muth (cosmetic changes)

- challenge-282/matthias-muth/README.md
Seems I gobbled up the README.md file yesterday night while copying things. The version I committed was 'completely uncomplete'!
Thank you for still having considered my 'Power to the Regex' solution 'lovable' in today's Perl Weekly newsletter! :-)
I am glad I found an editor backup of the final version, and here it is.
Thank you for your incredible efforts, and Thank you for the Challenges!
Best regards,
Matthias
> Challenge 282 solutions by Matthias Muth: complete and correct README.md

- challenge-283/packy-anderson/README.md
- challenge-283/packy-anderson/blog.txt
- challenge-283/packy-anderson/elixir/ch-1.exs
- challenge-283/packy-anderson/elixir/ch-2.exs
- challenge-283/packy-anderson/perl/ch-1.pl
- challenge-283/packy-anderson/perl/ch-2.pl
- challenge-283/packy-anderson/python/ch-1.py
- challenge-283/packy-anderson/python/ch-2.py
- challenge-283/packy-anderson/raku/ch-1.raku
- challenge-283/packy-anderson/raku/ch-2.raku
> Challenge 283 solutions by Packy Anderson

- challenge-283/nelo-tovar/bash/ch-1.sh
- challenge-283/nelo-tovar/bash/ch-2.sh
- challenge-283/nelo-tovar/perl/ch-1.pl
- challenge-283/nelo-tovar/perl/ch-2.pl
> Challenge 283. Add Perl and Bash solutions. By Nelo Tovar

- challenge-283/mattneleigh/perl/ch-1.pl
- challenge-283/mattneleigh/perl/ch-2.pl
new file:   challenge-283/mattneleigh/perl/ch-2.pl
> new file:   challenge-283/mattneleigh/perl/ch-1.pl

- challenge-283/barroff/julia/ch-1.jl
- challenge-283/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solutions for task one of challenge 283.
> feat: add solutions for challenge 283 from BarrOff

- challenge-283/sgreen/README.md
- challenge-283/sgreen/blog.txt
- challenge-283/sgreen/perl/ch-1.pl
- challenge-283/sgreen/perl/ch-2.pl
- challenge-283/sgreen/python/ch-1.py
- challenge-283/sgreen/python/ch-2.py
- challenge-283/sgreen/python/test.py
Today's pro tip: After committing the changes before the deadline, make sure you raise a PR too!
> sgreen solutions to challenge 283

- challenge-284/wlmb/blog.txt
- challenge-284/wlmb/perl/ch-1.pl
- challenge-284/wlmb/perl/ch-2.pl
> Solve PWC284

- challenge-284/spadacciniweb/go/ch-1.go
- challenge-284/spadacciniweb/go/ch-2.go
- challenge-284/spadacciniweb/perl/ch-1.pl
- challenge-284/spadacciniweb/perl/ch-2.pl
- challenge-284/spadacciniweb/python/ch-1.py
- challenge-284/spadacciniweb/python/ch-2.py
> Pwc 284 in Perl, Python and Go

- challenge-284/packy-anderson/README.md
- challenge-284/packy-anderson/blog.txt
- challenge-284/packy-anderson/elixir/ch-1.exs
- challenge-284/packy-anderson/elixir/ch-2.exs
- challenge-284/packy-anderson/perl/ch-1.pl
- challenge-284/packy-anderson/perl/ch-2.pl
- challenge-284/packy-anderson/python/ch-1.py
- challenge-284/packy-anderson/python/ch-2.py
- challenge-284/packy-anderson/raku/ch-1.raku
- challenge-284/packy-anderson/raku/ch-2.raku
> Challenge 284 solutions by Packy Anderson

- challenge-284/mattneleigh/perl/ch-1.pl
- challenge-284/mattneleigh/perl/ch-2.pl
new file:   challenge-284/mattneleigh/perl/ch-2.pl
> new file:   challenge-284/mattneleigh/perl/ch-1.pl

- challenge-284/mgo1977/perl/ch-1.pl
- challenge-284/mgo1977/perl/ch-2.pl
Hi Mohammad,
I'm sending you my solutions,
best regards,
Mariano
> go1977 - PWC 284

- challenge-283/andrezgz/perl/ch-1.pl
- challenge-283/andrezgz/perl/ch-2.pl
Hi @manwar, didn't manage to code it in time, but here's my solution to the previous week challenge
> challenge-283 andrezgz solution

- challenge-284/sgreen/README.md
- challenge-284/sgreen/blog.txt
- challenge-284/sgreen/perl/ch-1.pl
- challenge-284/sgreen/perl/ch-2.pl
- challenge-284/sgreen/python/ch-1.py
- challenge-284/sgreen/python/ch-2.py
- challenge-284/sgreen/python/test.py
I remembered to raise the PR this week!
> sgreen solutions to challenge 284

- challenge-284/nelo-tovar/bash/ch-1.sh
- challenge-284/nelo-tovar/bash/ch-2.sh
- challenge-284/nelo-tovar/perl/ch-1.pl
- challenge-284/nelo-tovar/perl/ch-2.pl
> Challenge 284. Add Perl and Bash solutions. By Nelo Tovar

- challenge-284/matthias-muth/README.md
- challenge-284/matthias-muth/blog.txt
- challenge-284/matthias-muth/perl/ch-1.pl
- challenge-284/matthias-muth/perl/ch-2.pl
> Challenge 284 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-284/barroff/julia/ch-1.jl
- challenge-284/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solutions for task one of challenge 284.
> feat: add solutions for challenge 284 from BarrOff

- challenge-284/atschneid/README.md
- challenge-284/atschneid/perl/ch-1.pl
- challenge-284/atschneid/perl/ch-2.pl
- challenge-284/atschneid/rust/ch-1.rs
- challenge-284/atschneid/rust/ch-2.rs
> initial PWC 284 commit

- challenge-285/wlmb/blog.txt
- challenge-285/wlmb/perl/ch-1.pl
- challenge-285/wlmb/perl/ch-2.pl
> Solve PWC 285

- challenge-282/andrezgz/perl/ch-1.pl
- challenge-282/andrezgz/perl/ch-2.pl
Hi @manwar, solving older challeges again!
> challenge-282 andrezgz solution

- challenge-285/packy-anderson/README.md
- challenge-285/packy-anderson/blog.txt
- challenge-285/packy-anderson/elixir/ch-1.exs
- challenge-285/packy-anderson/elixir/ch-2.exs
- challenge-285/packy-anderson/perl/ch-1.pl
- challenge-285/packy-anderson/perl/ch-2.pl
- challenge-285/packy-anderson/python/ch-1.py
- challenge-285/packy-anderson/python/ch-2.py
- challenge-285/packy-anderson/raku/ch-1.raku
- challenge-285/packy-anderson/raku/ch-2.raku
> Challenge 285 solutions by Packy Anderson

- challenge-285/matthias-muth/README.md
- challenge-285/matthias-muth/blog.txt
- challenge-285/matthias-muth/perl/ch-1.pl
- challenge-285/matthias-muth/perl/ch-2.pl
> Challenge 285 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-285/mattneleigh/perl/ch-1.pl
- challenge-285/mattneleigh/perl/ch-2.pl
new file:   challenge-285/mattneleigh/perl/ch-2.pl
> new file:   challenge-285/mattneleigh/perl/ch-1.pl

- challenge-285/robbie-hatley/blog.txt
- challenge-285/robbie-hatley/perl/ch-1.pl
- challenge-285/robbie-hatley/perl/ch-2.pl
Fun with nested for loops. :-)
> Robbie Hatley's Perl solutions for The Weekly Challenge #285.

- challenge-285/torgny-lyon/blog.txt
- challenge-285/torgny-lyon/perl/ch-1.pl
- challenge-285/torgny-lyon/perl/ch-2.pl
> Add solutions for week 285

- challenge-285/nelo-tovar/perl/ch-1.pl
- challenge-285/nelo-tovar/perl/ch-2.pl
> Challenge 285. Add Perl solutions. By Nelo Tovar

- challenge-285/matthias-muth/README.md
- challenge-285/matthias-muth/perl/ch-1.pl
- challenge-285/matthias-muth/perl/ch-2.pl
> Challenge 285 Task 1 and 2 solutions in Perl by Matthias Muth (Update)

- challenge-285/barroff/julia/ch-1.jl
- challenge-285/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solutions for task one of challenge 285.
> feat: add solutions for challenge 285 from BarrOff

- challenge-285/atschneid/README.md
- challenge-285/atschneid/perl/ch-1.pl
- challenge-285/atschneid/perl/ch-2.pl
> ATSchneid PWC 285

- challenge-286/wlmb/blog.txt
- challenge-286/wlmb/perl/ch-1.pl
- challenge-286/wlmb/perl/ch-2.pl
> Solve PWC286

- challenge-286/packy-anderson/README.md
- challenge-286/packy-anderson/blog.txt
- challenge-286/packy-anderson/elixir/ch-1.exs
- challenge-286/packy-anderson/elixir/ch-2.exs
- challenge-286/packy-anderson/perl/ch-1.pl
- challenge-286/packy-anderson/perl/ch-2.pl
- challenge-286/packy-anderson/python/ch-1.py
- challenge-286/packy-anderson/python/ch-2.py
- challenge-286/packy-anderson/raku/ch-1.raku
- challenge-286/packy-anderson/raku/ch-2.raku
> Challenge 286 solutions by Packy Anderson

- challenge-282/andrezgz/perl/ch-1.pl
Hi @manwar, I was reviewing this code, adding more test cases and found it failed under certain ones. So I applied a simple fix to it
> challenge-282-ch-1-fix

- challenge-286/mattneleigh/perl/ch-1.pl
- challenge-286/mattneleigh/perl/ch-2.pl
new file:   challenge-286/mattneleigh/perl/ch-2.pl
> new file:   challenge-286/mattneleigh/perl/ch-1.pl

- challenge-286/mattneleigh/perl/ch-2.pl
> modified:   challenge-286/mattneleigh/perl/ch-2.pl

- challenge-283/santiago-leyva/perl/ch-01.pl
- challenge-283/santiago-leyva/perl/ch-02.pl
- challenge-284/santiago-leyva/perl/ch-01.pl
- challenge-284/santiago-leyva/perl/ch-02.pl
- challenge-285/santiago-leyva/perl/ch-01.pl
- challenge-285/santiago-leyva/perl/ch-02.pl
Perl solutions for challenges #283 / #284/ #285, thanks!
> Late but better than never (added #283/284/285)

- challenge-286/matthias-muth/README.md
- challenge-286/matthias-muth/blog.txt
- challenge-286/matthias-muth/perl/ch-1.pl
- challenge-286/matthias-muth/perl/ch-2.pl
> Challenge 286 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-286/nelo-tovar/perl/ch-1.pl
- challenge-286/nelo-tovar/perl/ch-2.pl
> Challenge 286. Add Perl solutions. By Nelo Tovar

- challenge-286/barroff/julia/ch-1.jl
- challenge-286/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solutions for task one of challenge 286.
> feat: add solutions for challenge 286 from BarrOff

- challenge-286/atschneid/README.md
- challenge-286/atschneid/ch-1.pl
- challenge-286/atschneid/ch-2.pl
> initial PWC 286 commit

- challenge-286/santiago-leyva/perl/ch-01.pl
- challenge-286/santiago-leyva/perl/ch-02.pl
- challenge-287/santiago-leyva/perl/ch-01.pl
- challenge-287/santiago-leyva/perl/ch-02.pl
Both challenges in perl. Thanks!
> Added challenges 286 and 287

- challenge-287/matthias-muth/README.md
- challenge-287/matthias-muth/blog.txt
- challenge-287/matthias-muth/perl/ch-1.pl
- challenge-287/matthias-muth/perl/ch-2.pl
> Challenge 287 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-287/packy-anderson/README.md
- challenge-287/packy-anderson/blog.txt
- challenge-287/packy-anderson/elixir/ch-1.exs
- challenge-287/packy-anderson/elixir/ch-2.exs
- challenge-287/packy-anderson/perl/ch-1.pl
- challenge-287/packy-anderson/perl/ch-2.pl
- challenge-287/packy-anderson/python/ch-1.py
- challenge-287/packy-anderson/python/ch-2.py
- challenge-287/packy-anderson/raku/ch-1.raku
- challenge-287/packy-anderson/raku/ch-2.raku
> Challenge 287 solutions by Packy Anderson

- challenge-287/mattneleigh/perl/ch-1.pl
- challenge-287/mattneleigh/perl/ch-2.pl
new file:   challenge-287/mattneleigh/perl/ch-2.pl
> new file:   challenge-287/mattneleigh/perl/ch-1.pl

- challenge-078/conor-hoekstra/ch-1.bqn
- challenge-078/conor-hoekstra/ch-2.apl
- challenge-078/conor-hoekstra/ch-2.bqn
- challenge-082/conor-hoekstra/ch-1.bqn
- challenge-082/conor-hoekstra/ch-2.bqn
@manwar PS - it looks like there is a small typo somewhere (it says Pytho with no N):
> ✨ Week 78 & 82 in BQN (& 1 APL)

- challenge-287/atschneid/README.md
- challenge-287/atschneid/blog.txt
- challenge-287/atschneid/perl/ch-1.pl
- challenge-287/atschneid/perl/ch-2.pl
Thanks @manwar ! I'm getting it in early (for me!) this week
> ATSchneid PWC 287 solutions

- challenge-287/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 287.
> feat: add solution for challenge 287 from BarrOff

- challenge-287/matthias-muth/README.md
- challenge-287/matthias-muth/perl/ch-1.pl
- challenge-287/matthias-muth/perl/ch-2.pl
> Challenge 287 Task 1 and 2 solutions in Perl by Matthias Muth - Second update

- challenge-287/matthias-muth/perl/ch-2.pl
> Challenge 287 Task 1 and 2 solutions in Perl by Matthias Muth - Silly typo!

- challenge-288/packy-anderson/README.md
- challenge-288/packy-anderson/blog.txt
- challenge-288/packy-anderson/elixir/ch-1.exs
- challenge-288/packy-anderson/perl/ch-1.pl
- challenge-288/packy-anderson/perl/ch-2.pl
- challenge-288/packy-anderson/python/ch-1.py
- challenge-288/packy-anderson/python/ch-2.py
- challenge-288/packy-anderson/raku/ch-1.raku
- challenge-288/packy-anderson/raku/ch-2.raku
* Perl
* Elixir solution for Task 1 (for now)
1 Blog post
> Challenge 288 solutions by Packy Anderson

- challenge-288/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 288.
> feat: add solution for challenge 288 from BarrOff

- challenge-289/packy-anderson/README.md
- challenge-289/packy-anderson/blog.txt
- challenge-289/packy-anderson/elixir/ch-1.exs
- challenge-289/packy-anderson/elixir/ch-2.exs
- challenge-289/packy-anderson/perl/ch-1.pl
- challenge-289/packy-anderson/perl/ch-2.pl
- challenge-289/packy-anderson/python/ch-1.py
- challenge-289/packy-anderson/python/ch-2.py
- challenge-289/packy-anderson/raku/ch-1.raku
- challenge-289/packy-anderson/raku/ch-2.raku
* Perl
* Elixir that's starting to look like Elixir
1 Blog post
> Challenge 289 solutions by Packy Anderson

- challenge-289/mattneleigh/perl/ch-1.pl
- challenge-289/mattneleigh/perl/ch-2.pl
new file:   challenge-289/mattneleigh/perl/ch-2.pl
> new file:   challenge-289/mattneleigh/perl/ch-1.pl

- challenge-289/athanasius/perl/Gettysburg.txt
- challenge-289/athanasius/perl/ch-1.pl
- challenge-289/athanasius/perl/ch-2.pl
- challenge-289/athanasius/raku/Gettysburg.txt
- challenge-289/athanasius/raku/ch-1.raku
- challenge-289/athanasius/raku/ch-2.raku
With example input file "Gettysburg.txt" for Task 2
> Perl & Raku solutions to Tasks 1 & 2 for Week 289

- challenge-289/matthias-muth/README.md
- challenge-289/matthias-muth/blog.txt
- challenge-289/matthias-muth/perl/ch-1.pl
- challenge-289/matthias-muth/perl/ch-2.pl
> Challenge 289 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-289/barroff/julia/ch-1.jl
- challenge-289/barroff/raku/ch-1.p6
- challenge-289/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia and Raku solutions for challenge 289.
> feat: add solutions for challenge 289 from BarrOff

- challenge-289/cheok-yin-fung/perl/ch-1.pl
Missed a few weeks. Need to catch up later...
> Week 289 Task 1

- challenge-289/ryan-thompson/README.md
- challenge-289/ryan-thompson/blog.txt
- challenge-289/ryan-thompson/perl/ch-1.pl
- challenge-289/ryan-thompson/perl/ch-2.pl
rjt's Week 289 solutions and blog
> rjt's Week 289 solutions and blog

- challenge-290/conor-hoekstra/ch-1.bqn
- challenge-290/conor-hoekstra/ch-2.bqn
Looks like the test case int the second problem has a typo
> :sparkles: Week 290 in BQN

- challenge-290/robbie-hatley/blog.txt
- challenge-290/robbie-hatley/perl/ch-1.pl
- challenge-290/robbie-hatley/perl/ch-2.pl
This week, with a touch of Macbeth.  :-) 
Double, double toil and trouble;
Fire burn and caldron bubble.
Fillet of a fenny snake,
In the caldron boil and bake;
Eye of newt and toe of frog,
Wool of bat and tongue of dog,
Adder's fork and blind-worm's sting,
Lizard's leg and howlet's wing,
For a charm of powerful trouble,
Like a hell-broth boil and bubble.
~~William Shakespeare, Macbeth, Act IV, Scene 1.
> Robbie Hatley's solutions, in Perl, for The Weekly Challenge #290.

- challenge-290/ryan-thompson/README.md
- challenge-290/ryan-thompson/blog.txt
- challenge-290/ryan-thompson/perl/ch-1.pl
- challenge-290/ryan-thompson/perl/ch-2.pl
> Week 290 solutions and blog

- challenge-290/packy-anderson/README.md
- challenge-290/packy-anderson/blog.txt
- challenge-290/packy-anderson/elixir/ch-1.exs
- challenge-290/packy-anderson/elixir/ch-2.exs
- challenge-290/packy-anderson/perl/ch-1.pl
- challenge-290/packy-anderson/perl/ch-2.pl
- challenge-290/packy-anderson/python/ch-1.py
- challenge-290/packy-anderson/python/ch-2.py
- challenge-290/packy-anderson/raku/ch-1.raku
- challenge-290/packy-anderson/raku/ch-2.raku
* Perl
* Elixir that's starting to look like Elixir
1 Blog post
> Challenge 290 solutions by Packy Anderson

- challenge-288/santiago-leyva/perl/ch-01.pl
- challenge-288/santiago-leyva/perl/ch-02.pl
- challenge-289/santiago-leyva/perl/ch-01.pl
- challenge-289/santiago-leyva/perl/ch-02.pl
Hello! Just catching up! Thanks! btw, i got the job! Thanks for everything you do Mohammad, cheers!!
> Added challenges 288 and 289

- challenge-290/mattneleigh/perl/ch-1.pl
- challenge-290/mattneleigh/perl/ch-2.pl
new file:   challenge-290/mattneleigh/perl/ch-2.pl
> new file:   challenge-290/mattneleigh/perl/ch-1.pl

- challenge-290/santiago-leyva/perl/ch-01.pl
- challenge-290/santiago-leyva/perl/ch-02.pl
> Added challenges for 290 in perl

- challenge-290/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 290.
> feat: add solution for challenge 290 from BarrOff

- challenge-290/matthias-muth/README.md
- challenge-290/matthias-muth/blog.txt
- challenge-290/matthias-muth/perl/ch-1.pl
- challenge-290/matthias-muth/perl/ch-2.pl
> Challenge 290 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-291/packy-anderson/README.md
- challenge-291/packy-anderson/blog.txt
- challenge-291/packy-anderson/elixir/ch-1.exs
- challenge-291/packy-anderson/elixir/ch-2.exs
- challenge-291/packy-anderson/perl/ch-1.pl
- challenge-291/packy-anderson/perl/ch-2.pl
- challenge-291/packy-anderson/python/ch-1.py
- challenge-291/packy-anderson/python/ch-2.py
- challenge-291/packy-anderson/raku/ch-1.raku
- challenge-291/packy-anderson/raku/ch-2.raku
* Perl
* Elixir that's starting to look like Elixir
1 Blog post
> Challenge 291 solutions by Packy Anderson

- challenge-291/santiago-leyva/perl/ch-01.pl
- challenge-291/santiago-leyva/perl/ch-02.pl
> Added challenge 291 in perl

- challenge-291/mattneleigh/perl/ch-1.pl
- challenge-291/mattneleigh/perl/ch-2.pl
new file:   challenge-291/mattneleigh/perl/ch-2.pl
> new file:   challenge-291/mattneleigh/perl/ch-1.pl

- challenge-291/mattneleigh/perl/ch-2.pl
Fixed documentation formatting issue
> modified:   challenge-291/mattneleigh/perl/ch-2.pl

- challenge-291/barroff/julia/ch-1.jl
- challenge-291/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia and Raku solution for task one of challenge 291.
> feat: add solutions for challenge 291 from BarrOff

- challenge-292/matthias-muth/README.md
- challenge-292/matthias-muth/blog.txt
- challenge-292/matthias-muth/perl/ch-1.pl
- challenge-292/matthias-muth/perl/ch-2.pl
> Challenge 292 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-293/mattneleigh/perl/ch-1.pl
- challenge-293/mattneleigh/perl/ch-2.pl
new file:   challenge-293/mattneleigh/perl/ch-2.pl
> new file:   challenge-293/mattneleigh/perl/ch-1.pl

- challenge-293/mgo1977/perl/ch-1.pl
- challenge-293/mgo1977/perl/ch-2.pl
Hi Mohammad,
I'm sending you my solutions.
best regards,
Mariano
> mgo1977 - PWC 293

- challenge-292/santiago-leyva/perl/ch-01.pl
- challenge-292/santiago-leyva/perl/ch-02.pl
- challenge-293/santiago-leyva/perl/ch-01.pl
- challenge-293/santiago-leyva/perl/ch-02.pl
Added ch-01 and ch-02 for #292 (ch-02 flaky, couldn't finish it) and added for #293 ch-01 and ch-02, thanks!
> Added ch-01 and ch-02 for #292 (ch-02 flaky, couldn't finish it) and added for #293 ch-01 and ch-02, thanks!

- challenge-293/barroff/raku/ch-1.p6
- challenge-293/barroff/raku/ch-2.p6
Hello
This pull request adds my Raku solutions for challenge 293.
> feat: add solutions for challenge 293 from BarrOff

- challenge-294/mattneleigh/perl/ch-1.pl
- challenge-294/mattneleigh/perl/ch-2.pl
new file:   challenge-294/mattneleigh/perl/ch-2.pl
> new file:   challenge-294/mattneleigh/perl/ch-1.pl

- challenge-290/jo-37/blog.txt
- challenge-290/jo-37/perl/ch-1.pl
- challenge-290/jo-37/perl/ch-2.pl
- challenge-291/jo-37/blog.txt
- challenge-291/jo-37/perl/ch-1.pl
- challenge-292/jo-37/blog.txt
- challenge-292/jo-37/perl/ch-1.pl
- challenge-292/jo-37/perl/ch-2.pl
- challenge-293/jo-37/blog.txt
- challenge-293/jo-37/perl/ch-1.pl
- challenge-293/jo-37/perl/ch-2.pl
- challenge-294/jo-37/blog.txt
- challenge-294/jo-37/perl/ch-1.pl
- challenge-294/jo-37/perl/ch-2.pl
> Solutions to challenges 290 - 294

- challenge-294/packy-anderson/README.md
- challenge-294/packy-anderson/blog.txt
- challenge-294/packy-anderson/perl/ch-1.pl
- challenge-294/packy-anderson/python/ch-1.py
- challenge-294/packy-anderson/raku/ch-1.raku
> Challenge 294 solutions by Packy Anderson

- challenge-294/barroff/julia/ch-1.jl
- challenge-294/barroff/nim/ch_1.nim
- challenge-294/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia, Nim and Raku solutions for task one of challenge 294.
> feat: add solutions for challenge 294 from BarrOff

- challenge-294/matthias-muth/README.md
- challenge-294/matthias-muth/blog.txt
- challenge-294/matthias-muth/perl/ch-1.pl
- challenge-294/matthias-muth/perl/ch-2.pl
> Challenge 294 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-294/santiago-leyva/perl/ch-01.pl
- challenge-294/santiago-leyva/perl/ch-02.pl
> Added challenge 294 in perl

- challenge-295/mattneleigh/perl/ch-1.pl
- challenge-295/mattneleigh/perl/ch-2.pl
new file:   challenge-295/mattneleigh/perl/ch-2.pl
> new file:   challenge-295/mattneleigh/perl/ch-1.pl

- challenge-295/matthias-muth/README.md
- challenge-295/matthias-muth/blog.txt
- challenge-295/matthias-muth/perl/ch-1.pl
- challenge-295/matthias-muth/perl/ch-2.pl
> Challenge 295 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-295/barroff/gnat/ch_1/.gitignore
- challenge-295/barroff/gnat/ch_1/alire.toml
- challenge-295/barroff/gnat/ch_1/ch_1.gpr
- challenge-295/barroff/gnat/ch_1/src/ch_1.adb
- challenge-295/barroff/gnat/ch_1/src/word_break.adb
- challenge-295/barroff/gnat/ch_1/src/word_break.ads
- challenge-295/barroff/julia/ch-1.jl
- challenge-295/barroff/nim/ch_1.nim
- challenge-295/barroff/raku/ch-1.p6
Hello
This pull request adds my Ada, Julia, Nim and Raku solutions for task one of challenge 295.
> feat: add solutions for challenge 295 from BarrOff

- challenge-296/mattneleigh/perl/ch-1.pl
- challenge-296/mattneleigh/perl/ch-2.pl
new file:   challenge-296/mattneleigh/perl/ch-2.pl
> new file:   challenge-296/mattneleigh/perl/ch-1.pl

- challenge-296/e-choroba/perl/ch-1.pl
- challenge-296/e-choroba/perl/ch-2.pl
Including the bonus: string DEcompression for 296/1.
> Solve 296: String Compression & Matchstick Square by E. Choroba

- challenge-296/matthias-muth/README.md
- challenge-296/matthias-muth/blog.txt
- challenge-296/matthias-muth/perl/ch-1.pl
- challenge-296/matthias-muth/perl/ch-2.pl
> Challenge 296 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-296/barroff/nim/ch_1.nim
Hello
This pull request adds my Nim solution for task one of challenge 296.
> feat: add solution for challenge 296 from BarrOff

- challenge-296/matthias-muth/perl/ch-2.pl
Corrected a syntax error that I had introduced with my last change and commited without final testing.
Silly me!
> Challenge 296 Task 1 and 2 solutions in Perl by Matthias Muth - Update

- challenge-297/wlmb/blog.txt
- challenge-297/wlmb/perl/ch-1.pl
- challenge-297/wlmb/perl/ch-2.pl
I didn't attempt challenge 1 as I didn't understand, sorry.
> Solve PWC297-2

- challenge-297/mattneleigh/perl/ch-1.pl
- challenge-297/mattneleigh/perl/ch-2.pl
new file:   challenge-297/mattneleigh/perl/ch-2.pl
> new file:   challenge-297/mattneleigh/perl/ch-1.pl

- challenge-297/vxern/README
- challenge-297/vxern/uiua/1.ua
- challenge-297/vxern/uiua/2.ua
These are in the Uiua programming language.
> Add solutions by Dorian 'vxern' Oszczęda.

- challenge-297/dave-jacoby/blog.txt
- challenge-297/dave-jacoby/python/ch-1.py
- challenge-297/dave-jacoby/python/ch-2.py
I Blogged, and I removed libraries in the Python that I wasn't using.
> DAJ 297 2: The Quickening!

- challenge-297/barroff/julia/ch-1.jl
- challenge-297/barroff/nim/ch_1.nim
- challenge-297/barroff/pascal/ch-1.pas
Hello
This pull request adds my Julia, Nim and Pascal solution for task one of challenge 297.
> feat: add solutions for challenge 297 from BarrOff

- challenge-298/mattneleigh/perl/ch-1.pl
- challenge-298/mattneleigh/perl/ch-2.pl
new file:   challenge-298/mattneleigh/perl/ch-2.pl
> new file:   challenge-298/mattneleigh/perl/ch-1.pl

- challenge-298/barroff/julia/ch-2.jl
- challenge-298/barroff/nim/ch_2.nim
- challenge-298/barroff/pascal/ch-2.pas
Hello
This pull request adds my Julia, Nim and Pascal solutions for task two of challenge 298.
> feat: add solutions for challenge 298 from BarrOff

- challenge-298/matthias-muth/README.md
- challenge-298/matthias-muth/blog.txt
- challenge-298/matthias-muth/perl/ch-1.pl
- challenge-298/matthias-muth/perl/ch-2.pl
Thank you for the challenge!
(And for accepting my late arrival...)
> Challenge 298 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-298/wlmb/blog.txt
- challenge-298/wlmb/perl/ch-1.pl
- challenge-298/wlmb/perl/ch-2.pl
> Solve PWC 298

- challenge-298/santiago-leyva/perl/ch-01.pl
- challenge-298/santiago-leyva/perl/ch-02.pl
Bit late but never late than never.
> Added perl ch-01 and ch-02

- challenge-298/mattneleigh/perl/ch-1.pl
Clarity enhancements- changed name of variable and edited comments.
> modified:   challenge-298/mattneleigh/perl/ch-1.pl

- challenge-299/matthias-muth/README.md
- challenge-299/matthias-muth/perl/ch-1.pl
- challenge-299/matthias-muth/perl/ch-2.pl
Sorry, no blog this week. I hope to write it later.
**Thank you for the Challenge!***
> Challenge 299 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-300/sgreen/README.md
- challenge-300/sgreen/blog.txt
- challenge-300/sgreen/perl/ch-1.pl
- challenge-300/sgreen/perl/ch-2.pl
- challenge-300/sgreen/python/ch-1.py
- challenge-300/sgreen/python/ch-2.py
- challenge-300/sgreen/python/test.py
Thank you Mohammad for the effort you put in each week for us.
> sgreen solutions to challenge 300

- challenge-300/barroff/julia/ch-1.jl
- challenge-300/barroff/nim/ch_1.nim
- challenge-300/barroff/raku/ch-1.p6
Hello
This pull request adds my Julia, Nim and Raku solutions for task one of challenge 300.
> feat: add solutions for challenge 300 from BarrOff

- challenge-301/e-choroba/perl/ch-1.pl
- challenge-301/e-choroba/perl/ch-2.pl
> Solve 301: Largest Number & Hamming Distance by E. Choroba

- challenge-301/ryan-thompson/README.md
- challenge-301/ryan-thompson/blog.txt
- challenge-301/ryan-thompson/c/ch-2.c
- challenge-301/ryan-thompson/perl/ch-1.pl
- challenge-301/ryan-thompson/perl/ch-2.pl
- challenge-301/ryan-thompson/perl/t/ch-1.t
- challenge-301/ryan-thompson/perl/t/ch-2.t
> rjt's week 301 solutions and blog

- challenge-301/mahnkong/README
- challenge-301/mahnkong/perl/ch-1.pl
- challenge-301/mahnkong/perl/ch-2.pl
Added my Solutions for Task 1 and Task 2 of Challenge 301
> Challenge-301

- challenge-301/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 301.
> feat: add solution for challenge 301 from BarrOff

- challenge-302/wlmb/blog.txt
- challenge-302/wlmb/perl/ch-1.pl
- challenge-302/wlmb/perl/ch-2.pl
> Solve PWC302

- challenge-301/santiago-leyva/perl/ch-01.pl
- challenge-301/santiago-leyva/perl/ch-02.pl
> added challenge 301 in perl

- challenge-302/robbie-hatley/perl/ch-1.pl
- challenge-302/robbie-hatley/perl/ch-2.pl
> Improvements to Robbie Hatley's Perl solutions for PWCC 302.

- challenge-301/jo-37/blog.txt
- challenge-301/jo-37/perl/ch-1.pl
- challenge-301/jo-37/perl/ch-2.pl
- challenge-302/jo-37/blog.txt
- challenge-302/jo-37/perl/ch-1.pl
- challenge-302/jo-37/perl/ch-2.pl
> Solutions to challenges 301 and 302

- challenge-302/matthias-muth/README.md
- challenge-302/matthias-muth/perl/ch-1.pl
- challenge-302/matthias-muth/perl/ch-2.pl
Sorry, no blog post again this week (even though I think my ch-2.pl one line solution would be interesting enough to write about).
Happy new year! :-)
And thank you for the Challenges!
> Challenge 302 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-302/barroff/julia/ch-2.jl
- challenge-302/barroff/nim/ch_2.nim
- challenge-302/barroff/pascal/ch2.lpi
- challenge-302/barroff/pascal/ch2.lpr
- challenge-302/barroff/pascal/ch2.lps
- challenge-302/barroff/raku/ch-1.p6
- challenge-302/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia, Nim, Pascal and Raku solutions for challenge 302.
> feat: add solutions for challenge 302 from BarrOff

- challenge-303/wlmb/blog.txt
- challenge-303/wlmb/perl/ch-1.pl
- challenge-303/wlmb/perl/ch-2.pl
> Solve PWC303

- challenge-302/mahnkong/perl/ch-1.pl
Fixed ch-1.pl based on a hint from @jo-37 (https://github.com/manwar/perlweeklychallenge-club/pull/11384#issuecomment-2573281919)
> Fixed 1st solution of challenge-302 after getting hint from 'jo-37'

- challenge-299/jo-37/blog1.txt
- challenge-299/jo-37/perl/ch-2a.pl
Improved solution that can handle larger grids.
Thanks @choroba for your solution and the permission to use it as benchmark and @moocow-the-bovine for your support on `PDL::CCS`. Here is the source for moocow-the-bovine/PDL-CCS#14!
See [blog](https://github.sommrey.de/the-bears-den/2025/01/09/ch-299.html) for details.
> New solution to challenge 299 task 2

- challenge-303/matthias-muth/README.md
- challenge-303/matthias-muth/perl/ch-1.pl
- challenge-303/matthias-muth/perl/ch-2.pl
Again no time for a blog this week. Next week I hope!
**Thank you for the Challenge**
> Challenge 303 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-303/barroff/raku/ch-1.p6
Hello
Fell asleep yesterday and missed the deadline ^^.
This pull request adds my Raku solution for task one of challenge 303.
> feat: add solution for challenge 303 from BarrOff

- challenge-303/2colours/prolog/ch-1.p
- challenge-303/2colours/prolog/ch-2.p
Hello,
thank you for the challenges, quite funny to play around with Prolog to solve them. One can always learn something new from them, that much is certain haha.
I'm a bit late but please take these solutions for last week's challenges.
Cheers.
> Prolog solutions for week #303

- challenge-304/wlmb/blog.txt
- challenge-304/wlmb/perl/ch-1.pl
- challenge-304/wlmb/perl/ch-2.pl
> Solve PWC304

- challenge-304/mahnkong/perl/ch-1.pl
- challenge-304/mahnkong/perl/ch-2.pl
Coding perl every week (again after a very long time) feels good. :)
> Challenge 304

- challenge-304/barroff/julia/ch-1.jl
- challenge-304/barroff/julia/ch-2.jl
- challenge-304/barroff/nim/ch_1.nim
- challenge-304/barroff/nim/ch_2.nim
- challenge-304/barroff/pascal/ch1.lpi
- challenge-304/barroff/pascal/ch1.lpr
- challenge-304/barroff/pascal/ch1.lps
- challenge-304/barroff/raku/ch-1.p6
- challenge-304/barroff/raku/ch-2.p6
Hello
This pull request adds my Julia, Nim, Pascal and Raku solutions for challenge 304.
> feat: add solutions for challenge 304 from BarrOff

- challenge-302/santiago-leyva/perl/ch-01.pl
- challenge-302/santiago-leyva/perl/ch-02.pl
- challenge-303/santiago-leyva/perl/ch-01.pl
- challenge-303/santiago-leyva/perl/ch-02.pl
Sorry about the delay, thanks :)
> Added perl challenges for 302

- challenge-304/matthias-muth/README.md
- challenge-304/matthias-muth/blog.txt
- challenge-304/matthias-muth/perl/ch-1.pl
- challenge-304/matthias-muth/perl/ch-2.pl
> Challenge 304 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-304/matthias-muth/perl/ch-1.pl
> Challenge 304 Task 1 and 2 solutions in Perl by Matthias Muth - Update

- challenge-305/japhy/README
- challenge-305/japhy/perl/ch-1.pl
- challenge-305/japhy/perl/ch-2.pl
I went for a golf-ish approach, though I haven't gone to extremes.
> Jeffrey "japhy" Pinyan's Perl solutions to weekly challenge 305

- challenge-305/matthias-muth/README.md
- challenge-305/matthias-muth/perl/ch-1.pl
- challenge-305/matthias-muth/perl/ch-2.pl
Sorry, didn't manage to create a blog post this week.
**Thank you for the Challenge!**
> Challenge 305 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-305/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 305.
> feat: add solution for challenge 305 from BarrOff

- challenge-306/wlmb/blog.txt
- challenge-306/wlmb/perl/ch-1.pl
- challenge-306/wlmb/perl/ch-2.pl
> Solve PWC306

- challenge-306/2colours/prolog/ch-1.p
- challenge-306/2colours/prolog/ch-2.p
Hello,
thank you for the challenges. They aren't complicated but they taught me to stay humble with getting the control flow right, even made me prefer CLP/FD over a plain ISO Prolog solution.
Please take the solutions.
Cheers
> Branch for challenge 306

- challenge-306/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 306.
> feat: add solution for challenge 306 from BarrOff

- challenge-306/matthias-muth/README.md
Thank you for the Challenge!
But this week, I really messed it up... my bad!
Hope it will be better next week.
> Challenge 306 *no* solutions in Perl by Matthias Muth this week

- challenge-306/jaldhar-h-vyas/blog.txt
- challenge-306/jaldhar-h-vyas/perl/ch-1.pl
- challenge-306/jaldhar-h-vyas/perl/ch-2.pl
- challenge-306/jaldhar-h-vyas/raku/ch-1.raku
- challenge-306/jaldhar-h-vyas/raku/ch-2.raku
> Challenge 306 by Jaldhar H. Vyas.

- challenge-307/matthias-muth/README.md
- challenge-307/matthias-muth/blog.txt
- challenge-307/matthias-muth/perl/ch-1.pl
- challenge-307/matthias-muth/perl/ch-2.pl
Thank you for the challenge!
Happy to have made it this week!
> Challenge 307 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-307/barroff/julia/ch-1.jl
- challenge-307/barroff/julia/ch-2.jl
- challenge-307/barroff/nim/ch_1.nim
- challenge-307/barroff/raku/ch-1.p6
- challenge-307/barroff/raku/ch-2.p6
Hello
Fell asleep before creating the PR yesterday ^^.
This pull request adds my Julia, Nim and Raku solutions for challenge 307.
> feat: add solutions for challenge 307 from BarrOff

- challenge-308/robbie-hatley/blog.txt
- challenge-308/robbie-hatley/perl/ch-1.pl
- challenge-308/robbie-hatley/perl/ch-2.pl
Ok, that's better! I deleted and re-created my branch "rh308" so now the pull request only contains 1 commit, which is correct!
> Robbie Hatley's solutions, in Perl, for The Weekly Challenge #308.

- challenge-308/matthias-muth/README.md
- challenge-308/matthias-muth/blog.txt
- challenge-308/matthias-muth/perl/ch-1.pl
- challenge-308/matthias-muth/perl/ch-2.pl
> Challenge 308 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-309/mgo1977/java/Ch1.java
- challenge-309/mgo1977/java/Ch2.java
- challenge-309/mgo1977/perl/ch-1.pl
- challenge-309/mgo1977/perl/ch-2.pl
Hi Mohammad,
I'm sending you my contribution
regards,
Mariano
> mgo1977 - PWC 309

- challenge-309/2colours/prolog/ch-12.p
Hi,
thank you for the tasks, this really is just a simplistic Prolog solution because I felt like doing it. It's easy to push something interesting in some "alien" language always. :)
Cheers
> Week #309 Prolog solutions added

- challenge-309/matthias-muth/README.md
- challenge-309/matthias-muth/blog.txt
- challenge-309/matthias-muth/perl/ch-1.pl
- challenge-309/matthias-muth/perl/ch-2.pl
> Challenge 309 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-308/barroff/raku/ch-1.p6
Hello
Missed creating the PR last week ^^.
This pull request adds my Raku solution for task one of challenge 308.
> feat: add solution for challenge 308 from BarrOff

- challenge-309/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 309.
> feat: add solution for challenge 309 from BarrOff

- challenge-310/lubos-kolouch/perl/ch-1.pl
- challenge-310/lubos-kolouch/perl/ch-2.pl
- challenge-310/lubos-kolouch/python/ch-1.py
- challenge-310/lubos-kolouch/python/ch-2.py
- Implemented arrays intersection function in Perl and Python
- Created sort odd/even indices function in Perl and Python
- Added comprehensive unit tests for both solutions
> LK Perl and Python solutions for Challenge 310

- challenge-310/matthias-muth/README.md
- challenge-310/matthias-muth/blog.txt
- challenge-310/matthias-muth/perl/ch-1.pl
- challenge-310/matthias-muth/perl/ch-2.pl
> Challenge 310 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-310/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 310.
> feat: add solution for challenge 310 from BarrOff

- challenge-311/matthias-muth/README.md
- challenge-311/matthias-muth/blog.txt
- challenge-311/matthias-muth/perl/ch-1.pl
- challenge-311/matthias-muth/perl/ch-2.pl
Thank you for the Challenge!
Kind regards!
> Challenge 311 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-311/barroff/raku/ch-1.p6
Hello
Fell asleep yesterday evening before submitting my solution ^^
This pull request adds my Raku solution for task one of challenge 311.
> feat: add solution for challenge 311 from BarrOff

- challenge-311/sgreen/README.md
- challenge-311/sgreen/blog.txt
- challenge-311/sgreen/python/ch-1.py
- challenge-311/sgreen/python/ch-2.py
- challenge-311/sgreen/python/test.py
- challenge-312/sgreen/README.md
- challenge-312/sgreen/blog.txt
- challenge-312/sgreen/perl/ch-1.pl
- challenge-312/sgreen/perl/ch-2.pl
- challenge-312/sgreen/python/ch-1.py
- challenge-312/sgreen/python/ch-2.py
- challenge-312/sgreen/python/test.py
> sgreen solutions to challenge 311 and 312

- challenge-312/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 312.
> feat: add solution for challenge 312 from BarrOff

- challenge-313/pjscott/README
- challenge-313/pjscott/perl/ch-1.pl
Just the one. Thanks for the good work!
> Branch 313

- challenge-313/arne-sommer/blog.txt
- challenge-313/arne-sommer/raku/broken-keys
- challenge-313/arne-sommer/raku/ch-1.raku
- challenge-313/arne-sommer/raku/ch-2.raku
- challenge-313/arne-sommer/raku/reverse-letters
I have one correction to https://theweeklychallenge.org/blog/perl-weekly-challenge-313/
My blog, in the section "Blogs with Creative Title", is indeed very creatively titled. It is not the correct article.
> Arne Sommer

- challenge-312/mahnkong/perl/ch-1.pl
- challenge-312/mahnkong/perl/ch-2.pl
- challenge-313/mahnkong/perl/ch-1.pl
- challenge-313/mahnkong/perl/ch-2.pl
> Challenges 312 and 313

- challenge-313/matthias-muth/README.md
- challenge-313/matthias-muth/blog.txt
- challenge-313/matthias-muth/perl/ch-1.pl
- challenge-313/matthias-muth/perl/ch-2.pl
> Challenge 313 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-313/barroff/raku/ch-2.p6
Hello
This pull request adds my Raku solution for task two of challenge 313.
> feat: add solution for challenge 313 from BarrOff

- challenge-313/2colours/prolog/solution.prolog
Hi,
thank you for the tasks; I just noticed these solutions have been around for a while. :D
Please merge them, and take care ^^
> Week #313 (Prolog) solution added

- challenge-314/ashwin-shenoy/README.md
- challenge-314/ashwin-shenoy/dart/ch-1.dart
- challenge-314/ashwin-shenoy/dart/ch-2.dart
- challenge-314/ashwin-shenoy/python/ch-1.py
- challenge-314/ashwin-shenoy/python/ch-2.py
This PR adds my solution for challenge 314 in Python & Dart.
> [Challenge 314] Adds solution for Python & Dart.

- challenge-314/deadmarshal/perl/ch-1.pl
- challenge-314/deadmarshal/perl/ch-2.pl
I forgot to add in the perl solutions in the last PR.
> TWC314 perl

- challenge-314/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 314.
> feat: add solution for challenge 314 from BarrOff

- challenge-314/matthias-muth/README.md
- challenge-314/matthias-muth/blog.txt
- challenge-314/matthias-muth/perl/ch-1.pl
- challenge-314/matthias-muth/perl/ch-2.pl
> Challenge 314 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-315/ashwin-shenoy/dart/ch-1.dart
- challenge-315/ashwin-shenoy/dart/ch-2.dart
- challenge-315/ashwin-shenoy/python/ch-1.py
- challenge-315/ashwin-shenoy/python/ch-2.py
This PR adds my solution for challenge 315 in Python & Dart.
> [Challenge 315] Adds solution for Python & Dart.

- challenge-315/matthias-muth/README.md
- challenge-315/matthias-muth/blog.txt
- challenge-315/matthias-muth/perl/ch-1.pl
- challenge-315/matthias-muth/perl/ch-2.pl
> Challenge 315 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-315/2colours/prolog/ch-1.p
- challenge-315/2colours/prolog/ch-2.p
Hi,
thank you for the challenges; here comes a much improvised Prolog solution just for fun. Please merge it.
Take care
> Weekly challenges #315 for 2colours (Prolog)

- challenge-315/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 315.
> feat: add solution for challenge 315 from BarrOff

- challenge-316/jo-37/blog.txt
- challenge-316/jo-37/perl/ch-1.pl
- challenge-316/jo-37/perl/ch-2.pl
Terse blog. Gardening takes precedence over the Weekly Challenge these days.
> Solutions to challenge 316

- challenge-316/packy-anderson/README.md
- challenge-316/packy-anderson/blog.txt
- challenge-316/packy-anderson/elixir/ch-1.exs
- challenge-316/packy-anderson/elixir/ch-2.exs
- challenge-316/packy-anderson/perl/ch-1.pl
- challenge-316/packy-anderson/perl/ch-2.pl
- challenge-316/packy-anderson/python/ch-1.py
- challenge-316/packy-anderson/python/ch-2.py
- challenge-316/packy-anderson/raku/ch-1.raku
- challenge-316/packy-anderson/raku/ch-2.raku
> Challenge 316 solutions by Packy Anderson

- challenge-316/matthias-muth/README.md
- challenge-316/matthias-muth/blog.txt
- challenge-316/matthias-muth/perl/ch-1.pl
- challenge-316/matthias-muth/perl/ch-2.pl
> Challenge 316 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-315/jaldhar-h-vyas/blog.txt
- challenge-315/jaldhar-h-vyas/perl/ch-1.pl
- challenge-315/jaldhar-h-vyas/perl/ch-2.pl
- challenge-315/jaldhar-h-vyas/raku/ch-1.raku
- challenge-315/jaldhar-h-vyas/raku/ch-2.raku
Took a short holiday but I'm back.
> Challenge 315 by Jaldhar H. Vyas.

- challenge-316/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 316.
I find it quite funny that I miss a deadline just after being mentioned in this weeks announcement.
My weekend was really intense and I just fell asleep yesterday before submitting, but here it is ^^·
> feat: add solution for challenge 316 from BarrOff

- challenge-317/robbie-hatley/blog.txt
- challenge-317/robbie-hatley/perl/ch-1.pl
- challenge-317/robbie-hatley/perl/ch-2.pl
Today's theme: "Friendly Acronyms".
> Robbie Hatley's solutions, in Perl, for The Weekly Challenge #317.

- challenge-314/jaldhar-h-vyas/blog.txt
- challenge-314/jaldhar-h-vyas/perl/ch-1.pl
- challenge-314/jaldhar-h-vyas/perl/ch-2.pl
- challenge-314/jaldhar-h-vyas/raku/ch-1.raku
- challenge-314/jaldhar-h-vyas/raku/ch-2.raku
Oops forgot this one.  I should be all caught up now.
> Challenge 314 by Jaldhar H. Vyas.

- challenge-317/matthias-muth/README.md
- challenge-317/matthias-muth/blog.txt
- challenge-317/matthias-muth/perl/ch-1.pl
- challenge-317/matthias-muth/perl/ch-2.pl
> Challenge 317 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-317/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 317.
> feat: add solution for challenge 317 from BarrOff

- challenge-317/steven-wilson/perl/ch-1.pl
- challenge-317/steven-wilson/python/ch-1.py
- challenge-317/steven-wilson/python/ch-2.py
sorry I forgot to commit these last week.
> add solutions week 317 in python and perl

- challenge-318/packy-anderson/README.md
- challenge-318/packy-anderson/blog.txt
- challenge-318/packy-anderson/elixir/ch-1.exs
- challenge-318/packy-anderson/elixir/ch-2.exs
- challenge-318/packy-anderson/perl/ch-1.pl
- challenge-318/packy-anderson/perl/ch-2.pl
- challenge-318/packy-anderson/python/ch-1.py
- challenge-318/packy-anderson/python/ch-2.py
- challenge-318/packy-anderson/raku/ch-1.raku
- challenge-318/packy-anderson/raku/ch-2.raku
> Challenge 318 solutions by Packy Anderson

- challenge-318/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 318.
> feat: add solution for challenge 318 from BarrOff

- challenge-318/matthias-muth/README.md
- challenge-318/matthias-muth/blog.txt
- challenge-318/matthias-muth/perl/ch-1.pl
- challenge-318/matthias-muth/perl/ch-2.pl
> Challenge 318 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-305/santiago-leyva/perl/ch-01.pl
- challenge-305/santiago-leyva/perl/ch-02.pl
Will start to catch up!
Added challenge 305, thanks!
> Added perl challenge for 305

- challenge-319/packy-anderson/README.md
- challenge-319/packy-anderson/blog.txt
- challenge-319/packy-anderson/elixir/ch-1.exs
- challenge-319/packy-anderson/elixir/ch-2.exs
- challenge-319/packy-anderson/perl/ch-1.pl
- challenge-319/packy-anderson/perl/ch-2.pl
- challenge-319/packy-anderson/python/ch-1.py
- challenge-319/packy-anderson/python/ch-2.py
- challenge-319/packy-anderson/raku/ch-1.raku
- challenge-319/packy-anderson/raku/ch-2.raku
> Challenge 319 solutions by Packy Anderson

- challenge-319/matthias-muth/README.md
- challenge-319/matthias-muth/blog.txt
- challenge-319/matthias-muth/perl/ch-1.pl
- challenge-319/matthias-muth/perl/ch-2.pl
> Challenge 319 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-319/barroff/raku/ch-1.p6
- challenge-319/barroff/raku/ch-2.p6
Hello
This pull request adds my Raku solutions for challenge 319.
> feat: add solutions for challenge 319 from BarrOff

- challenge-320/packy-anderson/README.md
- challenge-320/packy-anderson/blog.txt
- challenge-320/packy-anderson/elixir/ch-1.exs
- challenge-320/packy-anderson/elixir/ch-2.exs
- challenge-320/packy-anderson/perl/ch-1.pl
- challenge-320/packy-anderson/perl/ch-2.pl
- challenge-320/packy-anderson/python/ch-1.py
- challenge-320/packy-anderson/python/ch-2.py
- challenge-320/packy-anderson/raku/ch-1.raku
- challenge-320/packy-anderson/raku/ch-2.raku
> Challenge 320 solutions by Packy Anderson

- challenge-320/barroff/bqn/ch-1.bqn
- challenge-320/barroff/bqn/ch-2.bqn
- challenge-320/barroff/raku/ch-1.p6
- challenge-320/barroff/raku/ch-2.p6
Hello
This pull request adds my BQN and Raku solutions for challenge 320.
> feat: add solutions for challenge 320 from BarrOff

- challenge-320/matthias-muth/README.md
- challenge-320/matthias-muth/blog.txt
- challenge-320/matthias-muth/perl/ch-1.pl
- challenge-320/matthias-muth/perl/ch-2.pl
> Challenge 320 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-321/packy-anderson/README.md
- challenge-321/packy-anderson/blog.txt
- challenge-321/packy-anderson/elixir/ch-1.exs
- challenge-321/packy-anderson/elixir/ch-2.exs
- challenge-321/packy-anderson/perl/ch-1.pl
- challenge-321/packy-anderson/perl/ch-2.pl
- challenge-321/packy-anderson/python/ch-1.py
- challenge-321/packy-anderson/python/ch-2.py
- challenge-321/packy-anderson/raku/ch-1.raku
- challenge-321/packy-anderson/raku/ch-2.raku
> Challenge 321 solutions by Packy Anderson

- challenge-321/barroff/raku/ch-1.p6
- challenge-321/barroff/raku/ch-2.p6
Hello
This pull request adds my Raku solutions for challenge 321.
> feat: add solutions for challenge 321 from BarrOff

- challenge-321/matthias-muth/README.md
- challenge-321/matthias-muth/blog.txt
- challenge-321/matthias-muth/perl/ch-1.pl
- challenge-321/matthias-muth/perl/ch-2.pl
> Challenge 321 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-321/matthias-muth/README.md
- challenge-321/matthias-muth/perl/ch-2.pl
I found that my Task 2 solution was not completely correct.
I updated the code in perl/ch-2.pl and the blog in README.md.
Kind regards,
Matthias
> Challenge 321 Task 1 and 2 solutions in Perl by Matthias Muth - Update

- challenge-322/packy-anderson/README.md
- challenge-322/packy-anderson/blog.txt
- challenge-322/packy-anderson/elixir/ch-1.exs
- challenge-322/packy-anderson/elixir/ch-2.exs
- challenge-322/packy-anderson/perl/ch-1.pl
- challenge-322/packy-anderson/perl/ch-2.pl
- challenge-322/packy-anderson/python/ch-1.py
- challenge-322/packy-anderson/python/ch-2.py
- challenge-322/packy-anderson/raku/ch-1.raku
- challenge-322/packy-anderson/raku/ch-2.raku
> Challenge 322 solutions by Packy Anderson

- challenge-321/memark/uiua/ch-1.ua
- challenge-321/memark/uiua/ch-2.ua
- challenge-322/memark/uiua/ch-1.ua
- challenge-322/memark/uiua/ch-2.ua
Add Uiua solutions for 321, 322
> Add Uiua solutions for 321, 322

- challenge-322/matthias-muth/README.md
- challenge-322/matthias-muth/blog.txt
- challenge-322/matthias-muth/perl/ch-1.pl
- challenge-322/matthias-muth/perl/ch-2.pl
> Challenge 322 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-323/packy-anderson/README.md
- challenge-323/packy-anderson/blog.txt
- challenge-323/packy-anderson/elixir/ch-1.exs
- challenge-323/packy-anderson/elixir/ch-2.exs
- challenge-323/packy-anderson/perl/ch-1.pl
- challenge-323/packy-anderson/perl/ch-2.pl
- challenge-323/packy-anderson/python/ch-1.py
- challenge-323/packy-anderson/python/ch-2.py
- challenge-323/packy-anderson/raku/ch-1.raku
- challenge-323/packy-anderson/raku/ch-2.raku
> Challenge 323 solutions by Packy Anderson

- challenge-323/matthias-muth/README.md
- challenge-323/matthias-muth/blog.txt
- challenge-323/matthias-muth/perl/ch-1.pl
- challenge-323/matthias-muth/perl/ch-2.pl
> Challenge 323 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-324/packy-anderson/README.md
- challenge-324/packy-anderson/blog.txt
- challenge-324/packy-anderson/elixir/ch-1.exs
- challenge-324/packy-anderson/elixir/ch-2.exs
- challenge-324/packy-anderson/perl/ch-1.pl
- challenge-324/packy-anderson/perl/ch-2.pl
- challenge-324/packy-anderson/python/ch-1.py
- challenge-324/packy-anderson/python/ch-2.py
- challenge-324/packy-anderson/raku/ch-1.raku
- challenge-324/packy-anderson/raku/ch-2.raku
> Challenge 324 solutions by Packy Anderson

- challenge-009/jaldhar-h-vyas/blog.txt
- challenge-010/jaldhar-h-vyas/blog.txt
- challenge-011/jaldhar-h-vyas/blog.txt
- challenge-012/jaldhar-h-vyas/blog.txt
I noticed that there were four really old challenges for which I had provided solutions but not blogs so here they are
> Blogs for Old Challenges 

- challenge-324/dave-jacoby/blog.txt
- challenge-324/dave-jacoby/perl/ch-1.pl
- challenge-324/dave-jacoby/perl/ch-2.pl
> DAJ 324 blogged

- challenge-325/packy-anderson/README.md
- challenge-325/packy-anderson/blog.txt
- challenge-325/packy-anderson/elixir/ch-1.exs
- challenge-325/packy-anderson/elixir/ch-2.exs
- challenge-325/packy-anderson/perl/ch-1.pl
- challenge-325/packy-anderson/perl/ch-2.pl
- challenge-325/packy-anderson/python/ch-1.py
- challenge-325/packy-anderson/python/ch-2.py
- challenge-325/packy-anderson/raku/ch-1.raku
- challenge-325/packy-anderson/raku/ch-2.raku
> Challenge 325 solutions by Packy Anderson

- challenge-325/matthias-muth/README.md
- challenge-325/matthias-muth/blog.txt
- challenge-325/matthias-muth/perl/ch-1.pl
- challenge-325/matthias-muth/perl/ch-2.pl
> Challenge 325 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-326/wlmb/blog.txt
- challenge-326/wlmb/perl/ch-1.pl
- challenge-326/wlmb/perl/ch-2.pl
> Solve PWC326

- challenge-326/simon-proctor/README
- challenge-326/simon-proctor/raku/ch-1.raku
- challenge-326/simon-proctor/raku/ch-2.raku
I'm BACK!!!
With a blog! https://khanate.co.uk/weekly/326.html
> Weekly Challenge 326

- challenge-326/matthias-muth/README.md
- challenge-326/matthias-muth/blog.txt
- challenge-326/matthias-muth/perl/ch-1.pl
- challenge-326/matthias-muth/perl/ch-2.pl
> Challenge 326 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-326/walt-mankowski/README.md
- challenge-326/walt-mankowski/c/Makefile
- challenge-326/walt-mankowski/c/ch-1.c
- challenge-326/walt-mankowski/c/ch-2.c
I added C solutions to my solutions for challenge 326.
> Branch for challenge 326a

- challenge-325/barroff/raku/ch-1.p6
- challenge-326/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solutions for task one of challenges 325 and 326.
> feat: add solution for challenge 325 from BarrOff

- challenge-327/walt-mankowski/README.md
- challenge-327/walt-mankowski/perl/ch-1.pl
- challenge-327/walt-mankowski/perl/ch-2.pl
- challenge-327/walt-mankowski/python/ch-1.py
- challenge-327/walt-mankowski/python/ch-2.py
Here's my code for challenge 327. I did it in Perl and Python again this week.
> Branch for challenge 327

- challenge-328/packy-anderson/README.md
- challenge-328/packy-anderson/blog.txt
- challenge-328/packy-anderson/elixir/ch-1.exs
- challenge-328/packy-anderson/elixir/ch-2.exs
- challenge-328/packy-anderson/perl/ch-1.pl
- challenge-328/packy-anderson/perl/ch-2.pl
- challenge-328/packy-anderson/python/ch-1.py
- challenge-328/packy-anderson/python/ch-2.py
- challenge-328/packy-anderson/raku/ch-1.raku
- challenge-328/packy-anderson/raku/ch-2.raku
> Challenge 328 solutions by Packy Anderson

- challenge-328/matthias-muth/README.md
- challenge-328/matthias-muth/blog.txt
- challenge-328/matthias-muth/perl/ch-1.pl
- challenge-328/matthias-muth/perl/ch-2.pl
> Challenge 328 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-329/jo-37/blog.txt
- challenge-329/jo-37/perl/ch-1.pl
- challenge-329/jo-37/perl/ch-2.pl
Almost forgot to submit my solutions.
> Solutions to challenge 329

- challenge-329/matthias-muth/README.md
- challenge-329/matthias-muth/blog.txt
- challenge-329/matthias-muth/perl/ch-1.pl
- challenge-329/matthias-muth/perl/ch-2.pl
> Challenge 329 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-330/simon-proctor/raku/ch-1.raku
- challenge-330/simon-proctor/raku/ch-2.raku
I added in some tests for the case where the digit is at the start of the string. 
From my reading of the task it should still be deleted. 
(And then while writing this comment I realised I'd overcomplicated it)
> Challenge accepted

- challenge-330/arne-sommer/blog.txt
- challenge-330/arne-sommer/raku/ch-1.raku
- challenge-330/arne-sommer/raku/ch-2.raku
- challenge-330/arne-sommer/raku/clear-digits
- challenge-330/arne-sommer/raku/title-capital
The first week with a new 100% automated git script, and things did not work 100% the first time....
> week 330 Arne Sommer

- challenge-330/matthias-muth/README.md
- challenge-330/matthias-muth/blog.txt
- challenge-330/matthias-muth/perl/ch-1.pl
- challenge-330/matthias-muth/perl/ch-2.pl
> Challenge 330 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-330/packy-anderson/README.md
- challenge-330/packy-anderson/blog.txt
- challenge-330/packy-anderson/elixir/ch-1.exs
- challenge-330/packy-anderson/elixir/ch-2.exs
- challenge-330/packy-anderson/perl/ch-1.pl
- challenge-330/packy-anderson/perl/ch-2.pl
- challenge-330/packy-anderson/python/ch-1.py
- challenge-330/packy-anderson/python/ch-2.py
- challenge-330/packy-anderson/raku/ch-1.raku
- challenge-330/packy-anderson/raku/ch-2.raku
* Perl
* Elixir that's starting to look more like Elixir
1 blog post
> Challenge 330 solutions by Packy Anderson

- challenge-330/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 330.
> feat: add solution for challenge 330 from BarrOff

- challenge-331/simon-proctor/raku/ch-1.raku
- challenge-331/simon-proctor/raku/ch-2.raku
I hope you have a nice and relaxing time off.
> Challenge 331

- challenge-093/jaldhar-h-vyas/blog.txt
- challenge-093/jaldhar-h-vyas/perl/ch-1.pl
- challenge-093/jaldhar-h-vyas/perl/ch-2.pl
- challenge-093/jaldhar-h-vyas/raku/ch-1.raku
- challenge-093/jaldhar-h-vyas/raku/ch-2.raku
> Challenge 93 by Jaldhar H. Vyas.

- challenge-331/peter-meszaros/perl/ch-2.pl
- challenge-331/peter-meszaros/tcl/ch-2.tcl
> challange-331

- challenge-331/jo-37/blog.txt
- challenge-331/jo-37/perl/ch-1.pl
- challenge-331/jo-37/perl/ch-2.pl
> Solutions to challenge 331

- challenge-331/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 331.
> feat: add solution for challenge 331 from BarrOff

- challenge-331/matthias-muth/README.md
- challenge-331/matthias-muth/blog.txt
- challenge-331/matthias-muth/perl/ch-1.pl
- challenge-331/matthias-muth/perl/ch-2.pl
> Challenge 331 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-332/simon-proctor/raku/ch-1.raku
- challenge-332/simon-proctor/raku/ch-2.raku
> Challenge 332

- challenge-332/barroff/raku/ch-1.p6
- challenge-332/barroff/raku/ch-2.p6
Hello
This pull request adds my Raku solutions for challenge 332.
> feat: add solutions for challenge 332 from BarrOff

- challenge-333/packy-anderson/README.md
- challenge-333/packy-anderson/blog.txt
- challenge-333/packy-anderson/elixir/ch-1.exs
- challenge-333/packy-anderson/elixir/ch-2.exs
- challenge-333/packy-anderson/perl/ch-1.pl
- challenge-333/packy-anderson/perl/ch-2.pl
- challenge-333/packy-anderson/python/ch-1.py
- challenge-333/packy-anderson/python/ch-2.py
- challenge-333/packy-anderson/raku/ch-1.raku
- challenge-333/packy-anderson/raku/ch-2.raku
* Perl
* Elixir that's starting to look more like Elixir
1 blog post
> Challenge 333 solutions by Packy Anderson

- challenge-332/mahnkong/perl/ch-1.pl
- challenge-332/mahnkong/perl/ch-2.pl
- challenge-333/mahnkong/perl/ch-1.pl
- challenge-333/mahnkong/perl/ch-2.pl
> Challenges 332 and 333

- challenge-333/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 333.
> feat: add solution for challenge 333 from BarrOff

- challenge-334/packy-anderson/README.md
- challenge-334/packy-anderson/blog.txt
- challenge-334/packy-anderson/elixir/ch-1.exs
- challenge-334/packy-anderson/elixir/ch-2.exs
- challenge-334/packy-anderson/perl/ch-1.pl
- challenge-334/packy-anderson/perl/ch-2.pl
- challenge-334/packy-anderson/python/ch-1.py
- challenge-334/packy-anderson/python/ch-2.py
- challenge-334/packy-anderson/raku/ch-1.raku
- challenge-334/packy-anderson/raku/ch-2.raku
* Perl
* Elixir that's starting to look more like Elixir
1 blog post
> Challenge 334 solutions by Packy Anderson

- challenge-334/matthias-muth/README.md
- challenge-334/matthias-muth/blog.txt
- challenge-334/matthias-muth/perl/ch-1.pl
- challenge-334/matthias-muth/perl/ch-2.pl
> Challenge 334 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-334/mattneleigh/perl/ch-1.pl
- challenge-334/mattneleigh/perl/ch-2.pl
new file:   challenge-334/mattneleigh/perl/ch-2.pl
> new file:   challenge-334/mattneleigh/perl/ch-1.pl

- challenge-335/packy-anderson/README.md
- challenge-335/packy-anderson/blog.txt
- challenge-335/packy-anderson/elixir/ch-1.exs
- challenge-335/packy-anderson/elixir/ch-2.exs
- challenge-335/packy-anderson/perl/ch-1.pl
- challenge-335/packy-anderson/perl/ch-2.pl
- challenge-335/packy-anderson/python/ch-1.py
- challenge-335/packy-anderson/python/ch-2.py
- challenge-335/packy-anderson/raku/ch-1.raku
- challenge-335/packy-anderson/raku/ch-2.raku
* Perl
* Elixir that I think looks like Elixir
1 blog post
> Challenge 335 solutions by Packy Anderson

- challenge-335/mattneleigh/perl/ch-1.pl
- challenge-335/mattneleigh/perl/ch-2.pl
new file:   challenge-335/mattneleigh/perl/ch-2.pl
> new file:   challenge-335/mattneleigh/perl/ch-1.pl

- challenge-336/packy-anderson/README.md
- challenge-336/packy-anderson/blog.txt
- challenge-336/packy-anderson/elixir/ch-1.exs
- challenge-336/packy-anderson/elixir/ch-2.exs
- challenge-336/packy-anderson/perl/ch-1.pl
- challenge-336/packy-anderson/perl/ch-2.pl
- challenge-336/packy-anderson/python/ch-1.py
- challenge-336/packy-anderson/python/ch-2.py
- challenge-336/packy-anderson/raku/ch-1.raku
- challenge-336/packy-anderson/raku/ch-2.raku
* Perl
* Elixir that is starting to look like Elixir
1 blog post
> Challenge 336 solutions by Packy Anderson

- challenge-336/mattneleigh/perl/ch-1.pl
- challenge-336/mattneleigh/perl/ch-2.pl
new file:   challenge-336/mattneleigh/perl/ch-2.pl
> new file:   challenge-336/mattneleigh/perl/ch-1.pl

- challenge-335/barroff/raku/ch-1.p6
- challenge-336/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenges 335 and 336.
> add solutions for challenges 335/336

- challenge-336/matthias-muth/README.md
- challenge-336/matthias-muth/blog.txt
- challenge-336/matthias-muth/perl/ch-1.pl
- challenge-336/matthias-muth/perl/ch-2.pl
> Challenge 336 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-337/matthias-muth/README.md
- challenge-337/matthias-muth/blog.txt
- challenge-337/matthias-muth/perl/ch-1.pl
- challenge-337/matthias-muth/perl/ch-2.pl
> Challenge 337 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-337/jo-37/perl/ch-2.pl
Spied on other solutions to find out that mine was incomplete. This is called _cheating_.
> Fix solution to task 2

- challenge-338/packy-anderson/README.md
- challenge-338/packy-anderson/blog.txt
- challenge-338/packy-anderson/elixir/ch-1.exs
- challenge-338/packy-anderson/elixir/ch-2.exs
- challenge-338/packy-anderson/perl/ch-1.pl
- challenge-338/packy-anderson/perl/ch-2.pl
- challenge-338/packy-anderson/python/ch-1.py
- challenge-338/packy-anderson/python/ch-2.py
- challenge-338/packy-anderson/raku/ch-1.raku
- challenge-338/packy-anderson/raku/ch-2.raku
* Raku that is finally Raku-ish
* Perl
* Python that kinda looks like Raku
* Elixir that is starting to look like Elixir
1 blog post
> Challenge 338 solutions by Packy Anderson

- challenge-338/barroff/raku/ch-1.p6
- challenge-338/barroff/raku/ch-2.p6
Hello
This pull request adds my Raku solutions for challenge 338.
> feat: add solutions for challenge 338 from BarrOff

- challenge-339/wlmb/blog.txt
- challenge-339/wlmb/perl/ch-1.pl
- challenge-339/wlmb/perl/ch-2.pl
> Solve PWC339

- challenge-339/packy-anderson/README.md
- challenge-339/packy-anderson/blog.txt
- challenge-339/packy-anderson/elixir/ch-1.exs
- challenge-339/packy-anderson/elixir/ch-2.exs
- challenge-339/packy-anderson/perl/ch-1.pl
- challenge-339/packy-anderson/perl/ch-2.pl
- challenge-339/packy-anderson/python/ch-1.py
- challenge-339/packy-anderson/python/ch-2.py
- challenge-339/packy-anderson/raku/ch-1.raku
- challenge-339/packy-anderson/raku/ch-2.raku
* Raku that is finally Raku-ish
* Perl
* Python that kinda looks like Raku
* Elixir that is starting to look like Elixir
1 blog post
> Challenge 339 solutions by Packy Anderson

- challenge-337/e-choroba/perl/ch-1.pl
- challenge-337/e-choroba/perl/ch-2.pl
Forgotten commit from a few weeks ago.
> Solve 337: Smaller Than Current & Odd Matrix by E. Choroba

- challenge-340/spadacciniweb/go/ch-2.go
> PWC 340: add ch-2 in Go

- challenge-340/spadacciniweb/elixir/ch-2.exs
> PWC 340: add ch-2 in Elixir

- challenge-340/matthias-muth/README.md
- challenge-340/matthias-muth/blog.txt
- challenge-340/matthias-muth/perl/ch-1.pl
- challenge-340/matthias-muth/perl/ch-2.pl
> Challenge 340 Task 1 and 2 solutions in Perl by Matthias Muth

- challenge-340/barroff/raku/ch-1.p6
Hello
This pull request adds my Raku solution for task one of challenge 340.
> feat: add solution for challenge 340 from BarrOff

- challenge-341/spadacciniweb/elixir/ch-2.exs
> Add ch-2 in Elixir
